### ISSUE TITLE
Release? Dev builds?

### ISSUE THREAD

**Issue by thermatk** [microg/android_packages_apps_GmsCore#10]
Good evening!
Now that you have implemented a lot of APIs and taking into consideration that it's not always truly easy to rebuild this app from source(https://github.com/microg/android_packages_apps_GmsCore/issues/9), is it possible for you to publish test builds here(in releases) or on FDroid?
Thank you!

**Comment by mar-v-in** [comment]
I am sure that releases on F-Droid will happen some day in the future. I also plan to automatically do "nightly" builds.

Sadly I'm currently rather busy so don't expect anything before the next month from my side.

**Comment by SWW13** [comment]
FYI: http://android.brn.li/apps/GmsCore/Latest/

**Comment by jeekajoo** [comment]
@SWW13 nice, thanks. do you have any information about how we can install it?
should it be put in /system/priv-app/ ? thanks

**Comment by SWW13** [comment]
@jeekajoo put it in `/system/app`, but you most likely need a ROM with patched framework/base see #11.

If your device is supported by CM 12.1 I could possibly build my ROM with GmsCore builtin for your device, you can reach me on freenode.

**Comment by jeekajoo** [comment]
@SWW13 I'm using omnirom 4.4.4 so I might be good (https://gerrit.omnirom.org/#/c/8672/) ?

**Comment by mar-v-in** [comment]
@jeekajoo yes omni 4.4 has builtin support :+1:

**Comment by jeekajoo** [comment]
I tried without success. I did this:
```
su
mount -o remount,rw /system
cp /sdcard/play-services-core-release-unsigned.apk  /system/app/
chmod 644 /system/app/play-services-core-release-unsigned.apk
mount -o remount,ro /system
reboot
```
so I have 3 questions:
* is it supposed to work with my device: Nexus5 (codename = hammerhead) ?
* is it supposed to work with omnirom 4.4.4 (20141111) ?
* should I rename the apk to some specific name?

Thanks

**Comment by mar-v-in** [comment]
What do you mean by "without success"? Does GmsCore show up in Settings->Apps->System?

It is not strictly necessary to install to /system/*app. You can try to install GmsCore as a normal application, which should work on most systems as well. If you do so it will also generate useful error output on logcat.

Your system should be supported and the apk name does not matter

**Comment by jeekajoo** [comment]
* installation in userland: `Installation error code: -103` because package is unsigned I guess.
* installation through commandline: I can't find the application.

```
root@hammerhead:/ # pm list packages | grep -i gms                             
1|root@hammerhead:/ #

root@hammerhead:/ # pm list packages | grep -i google                      
package:com.google.android.apps.authenticator2
package:com.google.zxing.client.android
package:com.google.android.apps.translate

```

**Comment by mar-v-in** [comment]
Grab and install the -debug.apk from the builds by @SWW13

**Comment by jeekajoo** [comment]
and it works, thanks @mar-v-in and @SWW13 :+1:

**Comment by julienschmidt** [comment]
Just to confirm: If I have GmsCore installed, I have to use "µg UnifiedNlp for devices with GAPPS"?
The apk for "without GAPPS" devices tries to install itself as an update to GmsCore.

**Comment by SWW13** [comment]
GmsCore (µg) contains UnifiedNlp so you only need GmsCore.

**Comment by jeekajoo** [comment]
for those who use omnirom, it is normal if UnifiedNIp interface backends are not showing.
read this: http://forum.xda-developers.com/showpost.php?p=61510899&postcount=1060
thanks again @mar-v-in :+1:

**Comment by julienschmidt** [comment]
I see the GsfProxy question came up again in the XDA thread. Also mar-v-in just updated the project.
@SWW13 any chance you can add an automated build for https://github.com/microg/android_packages_apps_GsfProxy? It might be a good idea to preinstall it in BRNmod :wink:

**Comment by mar-v-in** [comment]
:gift: https://github.com/microg/android_packages_apps_GsfProxy/releases/tag/v0.0.1

Currently preparing for the first "alpha-grade" release.

**Comment by julienschmidt** [comment]
... or GitHub releases. Perfect, thanks :+1:

**Comment by SWW13** [comment]
@julienschmidt Here you go: http://files.brnmod.rocks/apps/GsfProxy/Latest/ (maybe still interesting for testing commits)

**Comment by moosd** [comment]
I don't like the idea of having to recompile the entire OS just to be able to insert a fake signature patch. Nor do I like the idea of needing to rely on Xposed.

...So I wrote a python script to inject the necessary smali into framework.jar. It pulls the framework.jar off the device, patches it and pushes it back, so it should work on any ROM. Perhaps this might help other people?

I've put it here - https://github.com/moosd/Needle - tested on Linux.

It doesn't do anything all that complicated so I could make it into a root-requiring app if people want so you don't need a computer with adb installed to do it?

**Comment by mar-v-in** [comment]
@moosd 
> so it should work on any ROM.

I just had a short look into your patcher and noticed it is based on the line number. This means it will cause problems when using it on ROMs that have a slightly different original source code resuling in different line numbers.

Nonetheless I like the idea of a patcher :+1: (even though it would be a lot better if cm/roms would just ship a compatible patch...)

**Comment by moosd** [comment]
I do agree it would be better if roms would integrate this, but I can understand why they don't (it defeats the purpose of having a signature!)

I've just updated the code for performing the injection to actually find the one line to replace in the disassembly, should be theoretically more portable :)

**Comment by nagalun** [comment]
@moosd
Hey!
I took part of your patch and some other files to make a flashable zip for needle:
Python 3.5
baksmali-dvk.jar and smali-dvk.jar from @mar-v-in
Your fillinsig.smali and a modified patch.py.
It depends on the 'zip' binary in /system/xbin, because I was too lazy to include it.
I'm wondering if I have to do something so it's ok with me uploading this?

**Comment by mar-v-in** [comment]
@nagalun this will work on pre 5.0 only, right?

**Comment by nagalun** [comment]
@mar-v-in
I tried on CM13 and it worked, so I'm not sure on what systems it will work and won't,

**Comment by mar-v-in** [comment]
Interesting. Can you upload it somewhere (or just dirty put the files into a github repo)? 
My Experience with ART is that you can't easily run java code from recovery (which was possible with dalvik), but maybe this changed with 6.0 or some recoveries, so additional investigation might be a good thing.
I'd like to make this dynamic permission agnostic (the old patch is not) like on OmniROM if possible.

I'll also close this issue as this discussion is a bit off topic and the initial request is now addressed by the wiki page https://github.com/microg/android_packages_apps_GmsCore/wiki/Downloads

**Comment by nagalun** [comment]
@mar-v-in
Sorry for the delay, I was on mobile:
https://github.com/nagalun/needle-zip
