### ISSUE TITLE
Update Wiki (Signature Spoofing in OmniRom MM)

### ISSUE THREAD

**Issue by hansWURSCHT10000** [microg/android_packages_apps_GmsCore#101]
At the moment this is written in the Wiki:

>The following ROMs have out-of-box support for signature spoofing. 
>**This feature has to be enabled at the bottom of the developer settings first.**
>
>- OmniROM

The bold written does not apply to Omni 6 Marshmallow.
Please update to this:
http://forum.xda-developers.com/showpost.php?p=65350074&postcount=487

*(...and those:
http://forum.xda-developers.com/showpost.php?p=65353888&postcount=488
http://forum.xda-developers.com/showpost.php?p=65362468&postcount=491 )*

**Comment by ibleedbinari** [comment]
Wiki updated. If it looks good, you can close the issue. Thanks!

**Comment by hansWURSCHT10000** [comment]
Perfect thanks :)
