### ISSUE TITLE
Can't sign into chrome for sync

### ISSUE THREAD

**Issue by pudup** [microg/android_packages_apps_GmsCore#1019]
Just switched to microg.
Other google apps I use like Drive and Youtube work fine with microg and sync my account however it fails with Chrome

Chrome detects the account just fine but does nothing when I click the "Yes I'm in" button for syncing.

**Comment by AzimsTech** [comment]
I have similar issue. How you managed to fix yours? @pudup

**Comment by pudup** [comment]
@AzimsTech by switching to Firefox :P
