### ISSUE TITLE
Slack notifications does not work with MicroG 

### ISSUE THREAD

**Issue by tobiasBora** [microg/android_packages_apps_GmsCore#1027]
Hello,

I'm trying to enable slack notifications, however, it does not work. When I troubleshot in slack, it passes the steps "Slack settings", "Play services", and "Device settings", but fails at step "Token registration".

I've just installed GmsCore, 0.2.10.19420 from FDroid, FakeFapps version 2.0, and the XPosed module FakeGapps to fake the signature (I also have the module XPrivacy if it matters) on a LineageOS rom.

When I go to MicroG parameters, I didn't added an account, but I registered the terminal, and enabled Google Cloud Messaging. In the auto-verification tab: says that basically the system supports the signature spoofing, that all packets are installed, that all autorisations are granted.that battery optimisation is ignored (I just didn't installed any localization backend because I don't need that).

On the main page, I can see "Google Cloud Messaging: enabled/0 app registered", and when I click, it's enabled but the current status is disconnected.

Any idea what I did wrong?

Thanks!

**Comment by p4t44** [comment]
enable Google device registration and sign through microG Settings. Restart and then it should work.

**Comment by tobiasBora** [comment]
Hum indeed if I sign in using microG, I can go a bit further (the app appear in the list), and after a reboot, everything rocks! Thanks a lot, keep the good job!

**Comment by kousu** [comment]
I just had the same problem, found this thread, signed in to a Google Account through microG Settings, rebooted, and I received this notification immediately:

![slack-notif-microG](https://user-images.githubusercontent.com/987487/127930694-3bf51054-6460-4590-a664-7f84c5549579.jpeg)

That's pretty obnoxious of Slack. I assume microG is censoring that account from Slack? If so, why does it need to have it at all to function? Boo Slack.
