### ISSUE TITLE
Micro G causes error message in AFWall

### ISSUE THREAD

**Issue by jw243** [microg/android_packages_apps_GmsCore#103]
I noticed an odd behaviour when micro G is combined with AFWall. If com.google.android.gsf (version 0.1.0) is installed, but the two check boxes "activate device check-in" and "activate google cloud messaging" are left unchecked in micro G settings (version 0.2.1), then there will be the following error message in AFWall (version 2.2.1) after booting the device: "error applying firewall rules". This error message does not appear, if the two check boxes are ticked or if com.google.android.gsf is not installed. 

Does com.google.android.gsf have to be installed, anyway? I was surprised that the app is described as " legacy support" in F-droid. In addition, the two check boxes can be chosen whether com.google.android.gsf is installed or not. For now, I have decided to leave it uninstalled.

I would really like to thank you for all the effort you put into this project. I really appreciate this app.

**Comment by mar-v-in** [comment]
gsf is used for c2dm (cloud to device massaging), the predecessor of gcm (google cloud messaging). If you disable gcm in microG settings, gsf will be useless

However, there is no reason why installing gsf results in problems with AFWall. Did you file a bug report against AFWall?

**Comment by jw243** [comment]
Well, it's not the installation of gsf itself causing the error message. The error message appears only if gsf is installed but the two check boxes are left unchecked. Once they are checked, everything seems to be fine.

I have just discovered that I get the same error message upon installation of NetworkLocation.apg (version 1.6.2) instead of gsmcore. Since there aren't any relevant tick boxes in this app, only deletion of the app solves the problem.

So you think I should file the bug with AFWall?

**Comment by mar-v-in** [comment]
Yes, this has nothing to do with GmsCore or UnifiedNlp. If AFWall fails due to any state inside GmsCore or UnifiedNlp it is definitely AFWall that is broken.
