### ISSUE TITLE
K9mail don't sync anymore

### ISSUE THREAD

**Issue by tobiasBora** [microg/android_packages_apps_GmsCore#1032]
Hello,

First thanks a lot for this tool. I now have all notifications for more applications: Slack, Mattermost... But there is a very annoying issue: I lose the notifications for new email!

More precisely, before I had some push notifications when I received a new email, on all my addresses (gmail, but also work...). Since the installation of MicroG, K9mail does not receive any email if I don't manually synchronize. I tried to check, and the "synchro" button in the notification bar is on (before it used to uncheck automatically for no reasons, but now it seems to stay "on"). In the verification of MicroG, all cases are checked except the one in the section of UnifiedNlp.

Any idea what's going wrong?

**Comment by chris42** [comment]
Are you sure this has to do something with microg? I am unaware, that k9mail uses any push notifications, but previously used imap push. Which is completely different and I know there were some problems with it in k9mail. Probably worth checking the issue tracker over there.

Please also note, that the push notifications are something different than the system notifications. Push notifications are a communication mean for messengers etc., while your system notifications are just the note popup in your screen and can be triggered by several means (push notifications normally are just presented with a system notification, as it makes sense)

**Comment by tobiasBora** [comment]
Thanks for your answer. So indeed you're right, I meant imap push. But I'm pretty sure that this issue started when I installed microG. I was using the same version of K9mail, same configuration... for maybe a year, and the day I installed microG it started to cause some troubles... I updated to get the latest version today, but the problem seem to still be present. I was thinking that it may be linked with MicroG, because K9mail seems to be linked with the "synchronisation" option in the notification bar  I have with LineageOs (when I uncheck/check again K9mail suddently receives the messages), and I was thinking that maybe MicroG does some strange thing with this system setting...

If not, I'll try to ask to K9mail devs to see if they have some ideas...

**Comment by chris42** [comment]
I am not sure what the LineageOS synchronization option is, so can't say anything about that.

For me imap push with k9mail stopped working some time ago and only timed synchronization was working (e.g. every 15min). Notifications on new mails were always reliable though (Then of course only every 15min).
k9mail had issues with their imap push and battery optimization. You can check if disabling it helps, but I would check the imap push issues over at k9mail for other infos.

**Comment by tobiasBora** [comment]
Ok, so now everything works again. Basically, I think that you need to reinstall app after installing microg (it's what I needed to do for app that uses notifications, but apparently it's also usefull for k9mail), but the thing is that the new version 5.7 have disabled push imap because they are working on a complete rewrite, so when I reinstalled the newer version... well notification was disabled. But in FDroid's repo, you can find version 5.6, that has notification! So after uninstall+reinstall, everything works!

Sorry to bother you, thanks for your help!
