### ISSUE TITLE
gmail login error "This account already exists on your device."

### ISSUE THREAD

**Issue by Techwolf** [microg/android_packages_apps_GmsCore#1035]
Installed gmail v2020.03.01.300951155.release.62129274

A "New in Gmail" screen presented. Press "GOT IT".

Press "Add an email address".

Press "Google"

Press "Sign In" at the microG Services Core screen.

"Just a sec..."

Enter email and press next.

Get the following error: "This account already exists on your device."

**Comment by abampalexnder** [comment]
I have got solution for google after 3 weeks brain storming and spent all day and night time to resolve the issue

any one need solution can contact on wire @abampalxender

**Comment by Techwolf** [comment]
I fixed it by installing Android 10 and system-MinMicroG-Standard-2.7-20200727053128.zip.
