### ISSUE TITLE
Messaging app and microg appears to be a problem

### ISSUE THREAD

**Issue by dln949** [microg/android_packages_apps_GmsCore#1044]
I have a Samsung Galaxy Tab S2 tablet.  I have no experience with microg.  I wanted to be able to use this tablet with a minimum of involvement with Google.  So, I installed LineageOS for microg, using file lineage-16.0-20200409-microG-gts210vewifi.  Everything seems to work fine.  I have only one problem.  

I use this messaging app, Pulse SMS ( https://messenger.klinkerapps.com/overview/ ).  The problem is when I try to set this app up on my tablet, it keeps cycling me into the question of whether I want to use the tablet as my primary device in my Pulse SMS account (I do not it to be the primary device).  

I do not have this problem with this app on my “regular” android device, nor on a device on which I have LineageOS with OpenGapps.  

I really don’t know what I’m doing, I am very new to all this – I’m still confused about what the heck a Gapp even is, what is a safetynet, what core GMS means, etc. - so at this stage I suspect that the problem has something to do with how Pulse SMS works with – or doesn’t work with – microg.  

My first problem is this:  I am not sure where I should be going for help with this.  Is this github page the correct place to discuss this issue?  When I go to https://github.com/microg , there are many (mysterious to me) repositories, I don’t know which one I should be posting in to ask for help.  

Which github page – or other page or forum – should I be going to in order to seek assistance?

**Comment by chris42** [comment]
This is the place to ask for help, but probably we will need some information. :-) 
I assume you know that the app is using push notifications? Not that we are checking for something that is not used. You can normally see in the logs if it trying to do something with gms or firebase.

Then a test with the push notification tester would be great, to have a view if it generally is working. If not, check the [helpful information on messaging](https://github.com/microg/android_packages_apps_GmsCore/wiki/Helpful-Information)
After we established that push notifications are working in general and there is still trouble with the app, we will need to check more logs.

And finally, expectation management: microg right now is not very feature complete, hence a lot of the google api is missing.
It might be that your app uses something that is not implemented and hence might not work.

**Comment by dln949** [comment]
@chris42 , thanks for the reply.  

I do not know if the app is using "push notifications'.  How do I determine that?  

I read the "helpful information on messaging" page.  There it talks about the "Push Notification Tester" app, but it requires "Latest Google Play App and Play Services installed Google Account set up in Google Play", which I do not have because I have installed microg instead.  So, I'm not seeing how that app will help.  Am I misunderstanding things?   

The second bullet point on that pages says this:  "You can add an account through the system settings. Some applications might ask you to do so, if you don't."  But....  I don't  know what account they are talking about, nor how I would add such an account.  

It also talks about whether my device "registers" with something called "Firebase Cloud Messaging", don't know what that is, nor how to know if my device registered.  

I'm wondering - Is microg only to be used by expert programming people, and ordinary people like me should avoid it for now?  I ask because of all the questions I'm posing, I'm thinking maybe microg isn't intended for use by a regular guy.

**Comment by chris42** [comment]
It definitely will need some time to get used to and some steep learning curve. It is not a install and forget thing. You will need to set things up and tinker with it. This is due to the status of microg, but mainly because you try to degoogle. To do that properly a lot of learning and a lot of changes on how you use your phone is needed.

So the question is less if this is for you, the question is more, if you want to learn it and use it?

**Comment by dln949** [comment]
Hmmm....  Good question, fair question.  I don't know the answer, I guess I first need to see how deep the rabbit hole is before I can answer your question for sure.  (Can you recommend a reputable online source a novice can read to learn the basics one needs to know to manage microg?)  I'll try for now.  

In the meantime....  For my original problem, how might I start tracking down what the problem might be?  You originally suggested this as a first step: "You can normally see in the logs if it trying to do something with gms or firebase."  Where does a person find these logs?

**Comment by chris42** [comment]
Phew, so if we are starting at square one, it is probably best to check what you installed on the phone.
Did you install anything like play store, opengapps, basically anything that is related directly to google?
If not, how did you install PulseSMS?
This is important to know as microg replaces the google components on your phone. If you then install google stuff you might mess it up a bit.

**Comment by dln949** [comment]
I did not install play store, opengapps, or anything like that.  

I wiped every partition, formatted the entire drive, and installed LineageOS for microg.  

I installed Pulse SMS from the APK Pure store.

**Comment by chris42** [comment]
Ok, that probably is already good. So next would be to know if microg is installed correctly.
Can you open the microg app or go via Settings -> System -> Extended into the microg settings.
There you find the self check for microg. It should have green checkmarks everywhere. Sometimes some are missing on the bottom for unifiednlp, but that would be a different topic.

If everything is green, make sure, that you activate in the same app the google cloud messaging.
After that you should be able to use push notifications. To test it you can download the push notification tester app. You will not need a google account to use it. Install it and test if you get success.
After the first test you should see the app as registered and probably a message counter in the microg settings app under google cloud messaging. If not, or the test is not working, try the checkin code from the [helpful information](https://github.com/microg/android_packages_apps_GmsCore/wiki/Helpful-Information) and repeat the test.

**Comment by dln949** [comment]
Thank you again for your help and patience.  

I did the above, I got to the step where I installed the push notification tester.  It stopped at "step 1", it had one red X on the registration item.  (Don't know what that is telling me.)  

Wasn't sure what to do at that step.  So, I went to the "helpful information" page, and I did the last step to manually register the device using the adb commands, and then reran the push notification tester, but ended up with the exact same result.  

Incidentally, when I ran the adb command (both via sudo and trying again by becoming root user in Ubuntu) found on the "helpful information" page, I got these two error messages, again I don't know what they are telling me:  

Security exception: Permission Denial: not allowed to send broadcast android.provider.Telephony.SECRET_CODE from pid=22462, uid=2000

java.lang.SecurityException: Permission Denial: not allowed to send broadcast android.provider.Telephony.SECRET_CODE from pid=22462, uid=2000

**Comment by chris42** [comment]
Hmm... I can't tell anything about the adb stuff. I always used the phone dial pad and then it worked.

**Comment by dln949** [comment]
Unfortunately this tablet doesn't have phone functionality.

**Comment by chris42** [comment]
ah, sorry forgot that. I think you need to have adb run as root to be able to get the command working. Not on the calling computer, but on the tablet. Hence try to get a shell with adb shell and then su before the command.
For that of cause you need to have the device rooted. I don't know how lineage is doing that. If it is rooted already or what needs to be done. I always used magisk to root my phones.

**Comment by dln949** [comment]
Ok, I ran adb root, and then ran the adb commands on the "helpful information" page, it ran, produced no errors.  

In an earlier response you wrote this:  "After the first test you should see the app as registered and probably a message counter in the microg settings app under google cloud messaging. If not, or the test is not working, try the checkin code from the helpful information and repeat the test."  When you said I should see "the app" as registered, did you mean the "Push Notification Tester" app?  I do not see that app as registered.  Also, I do not see a "message counter" under "Google Cloud Messaging".  Finally, when running the "Push Notification Tester" app again, I still get stuck at step 1 with a red "X" for "Register for Push Notifications".  

One other question:  Under "microG Settings", under "Account" I have not set up a Google account.  Am I supposed to do that?

**Comment by chris42** [comment]
Yes, the the app notification tester should show up there. If everything is working all apps, that use push notifications should be there.
I know that the notification tester works, hence that is the first step to have the registration working. It is quite a diva and I had to run the checkin command multiple times and uninstall/install the tester again.

No, you do not need that google account, if you only want to use push notifications.

**Comment by dln949** [comment]
How long should I attempt this before I conclude there is something wrong?  

I've run the checkin command, and uninstalled and reinstalled the tester app about 20 times over a five or six hour period.  Still, the tester app does not appear as registered, and when I run the tester app it still gets stuck at step #1 with a red "X" for "Register for Push Notifications".  

Don't know what the next step should be.

**Comment by chris42** [comment]
:-) That should definitely be enough.
So we need to do some logging. As you already use adb to send the checkin command. You should be able to log.
the command to see realtime log is "adb logcat", or if you need sudo on your host "sudo adb logcat". This will put the logs in the shell.
If you want to save them do "adb logcat > log.txt". You can logcat after the checkin command, or run it in two different terminals.

**Comment by dln949** [comment]
I have attached the log.txt file here.  
[log.txt](https://github.com/microg/android_packages_apps_GmsCore/files/4489633/log.txt)

**Comment by dln949** [comment]
I stumbled across the problem.  

In the microg settings, under "Google Cloud Messaging", it was set to ask before allowing an app to register for push notifications.  Don't know how that got set that way, I guess I must have done that.  When I reversed that setting, all appears to work fine now.

**Comment by WookedWare** [comment]
I had tried to get Pulse SMS to work with MicroG before and had no success. Found this page and turned on "google Cloud Messaging" and it worked no problem. Thank you.
