### ISSUE TITLE
 Slack notifications does not work with MicroG

### ISSUE THREAD

**Issue by Lutty76** [microg/android_packages_apps_GmsCore#1068]
Slack notification doesn't work on my device, I have la test GMS core and set up config as explain in this issue : https://github.com/microg/android_packages_apps_GmsCore/issues/1027

![Screenshot_20200608-091506_microG_Services_Core](https://user-images.githubusercontent.com/9408013/84002889-718dcc80-a969-11ea-96ea-aabbe422e8e7.png)
![Screenshot_20200608-091519_Slack](https://user-images.githubusercontent.com/9408013/84002896-75215380-a969-11ea-8e7d-af86afedd17c.png)

Some more information : 
ROM : https://lineage.microg.org/ (build : 27/03/2020)
Device : One Plus 3

I have missed a thing ?

Thanks

**Comment by mar-v-in** [comment]
This is fixed due to merging #1069 in 5146559f89cdaaa05e7e6a5f2bb41988a4e4677b

**Comment by luken-dev** [comment]
While we wait for an update, you can manually roll back to Slack version 30010363 using AuroraStore, register with GCM (using notification troubleshooting), and then update Slack to latest.
