### ISSUE TITLE
A possible resource leak in AskPushPermission

### ISSUE THREAD

**Issue by AICT20** [microg/android_packages_apps_GmsCore#1071]
I am now doing some analysis works. I find in AskPushPermission, 
 
onCreate(Bundle savedInstanceState) {
...
        if (database.getApp(packageName) != null) {
            finish();
            return;
        }
...
}

Here 'finish()' method may be invoked in the 'onCreate' method, and from Android Development Documents, it may 'case onDestroy() will be immediately called'. Method 'onStop' will be skipped so that a database leak occurs, doesn't it?
I also find that many other repositories choose to release resources just after finish(), it is a good idea, isn't it?

**Comment by mar-v-in** [comment]
This should be fixed as of 895c74d095348e028b726587cb7b1761f8d1d9bf by moving the closing to `onDestroy()`
