### ISSUE TITLE
Keep Microg version as high as google play services

### ISSUE THREAD

**Issue by UltraBlackLinux** [microg/android_packages_apps_GmsCore#1074]
Hello,
so first of all I realy like your application and its a great replacement for the google play services. Ive got a problem now: In germany a corona app recently got published, now the problem is it requires the newest google play store version (surely it does - what a damn scam lol).
So could you make microg fake the "google services" version? I need use that corona app.
Thank you for response!

**Comment by chris42** [comment]
Fixing the version would not help you, as the required API is not implemented.
Overall automatically raising the version has been discussed before and won't work.

Regarding Corona see #1057 

If you "need" to use the app right now you should remove microg for now and use regular google service framework.

**Comment by UltraBlackLinux** [comment]
ah ok.
"If you "need" to use the app right now you should remove microg for now and use regular google service framework." uuh, no. xD
thank you for the response!
