### ISSUE TITLE
GCM does not work with marshmallow's battery optimizations

### ISSUE THREAD

**Issue by jeekajoo** [microg/android_packages_apps_GmsCore#108]
When using battery saver, GCM does not work.
As soon as I tell Android not to optimize `microG Services Core`, GCM works again.
![optim](https://lut.im/2JW6srynl2/wA9DGJaXBdhPIXOh)

Rom: Omnirom
Android: 6.0.1

Thanks

**Comment by art1fa** [comment]
Battery optimization has to be disabled for mircoG services to work properly. This is the same for the original Google Play Services. See @mar-v-in 's post in #31

**Comment by jeekajoo** [comment]
I was not sure it was documented, but it is: https://github.com/microg/android_packages_apps_GmsCore/wiki/Installation
Closing. Thanks.
