### ISSUE TITLE
[Feature request] replace liblatinime.so to support swype keyboards

### ISSUE THREAD

**Issue by Christian-Git01** [microg/android_packages_apps_GmsCore#1080]
In order to use AOSP keyboard with gesture typing the blob liblatinime.so is necessary. Could this be replaced by an alternative in microg? Would be awesome if swyping could work out of the box when using microg.

**Comment by chris42** [comment]
I would guess, as the blob is proprietary, it wouldn't be legal to bundle it with microg. An alternative setup would probably need full rework of such library and as far as I know there are no open libraries available to include?

**Comment by Christian-Git01** [comment]
I guess that you are right.

**Comment by Christian-Git01** [comment]
Duplicate of #460
