### ISSUE TITLE
Gradle Build Instructions don't work anymore

### ISSUE THREAD

**Issue by tlambertz** [microg/android_packages_apps_GmsCore#1091]
Since 895c74d095348e028b726587cb7b1761f8d1d9bf removed the .gitmodules file, the build instructions at https://github.com/microg/android_packages_apps_GmsCore/wiki/Building are invalid.

After running
```
git clone https://github.com/microg/android_packages_apps_GmsCore.git
cd android_packages_apps_GmsCore/
git submodule update --recursive --init
```
git complains
```
fatal: No url found for submodule path 'extern/RemoteDroidGuard' in .gitmodules
```
Adding the .gitmodules file back as it was fixes this.

However, the build still does not succeed, this time while running gradle:
```
Could not execute [class org.jetbrains.kotlin.gradle.plugin.statistics.DefaultKotlinBuildStatsService.buildFinished]

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':play-services-core'.
> kotlin.KotlinNullPointerException (no error message)
```

A checkout of tag v0.2.10.19420 builds great however.

**Comment by M4G13** [comment]
You don't need to do anything with git submodules any more, Gradle does it for you.
Just add a local.properties file and run ./gradlew build. (I had memory issues too but allocating more with JAVA_OPTS env var fixed it.)

**Comment by drrossum** [comment]
The build succeeds for me when I add this line to the gradle.properties file:
---
org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError
---

**Comment by TheLastGimbus** [comment]
Uummmm...
@drrossum 
So I added this in the wiki in the script: https://github.com/microg/android_packages_apps_GmsCore/wiki/Building
> `echo "org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError" >> gradle.properties`
I thought there was going to be some "Fork->edit on my fork->PR" while editing the wiki, but turns out it is directly saved

Anyway, this should help :)

**Comment by tlambertz** [comment]
I can confirm it is building with the updated instructions.

I have modified them further to mention `local.propterties` not only in the second bash script and have removed any mention of submodules.

**Comment by CNugteren** [comment]
FYI, I came across the same error:
```
 FAILURE: Build failed with an exception.
 
 * What went wrong:
 A problem occurred configuring project ':play-services-core'.
 > kotlin.KotlinNullPointerException (no error message)
```
And solved it not only by adding those JAVA settings to `gradle.properties` as mentioned here and on the Wiki, but I also had to do the following, which is mentioned further down in the bash script build instructions:
```
echo "sdk.dir=$ANDROID_SDK_HOME" > local.properties
echo "sdk-location=$ANDROID_SDK_HOME" >> local.properties
```
