### ISSUE TITLE
Patch android_frameworks_base

### ISSUE THREAD

**Issue by thermatk** [microg/android_packages_apps_GmsCore#11]
So, it seems to be the only thing preventing the debug builds from being recognized by apps as true GMS is the fake signature patch.
Will try to integrate it into some ROMs, hope others share their success too.

**Comment by mar-v-in** [comment]
Mainly, yes. OmniROM 4.4 includes the patch and for 5.1 it's in their [Gerrit](https://gerrit.omnirom.org/#/c/13136/), but I am not aware of any 5.* ROM that already included it.

**Comment by thermatk** [comment]
I have patched and self-built cm 12.1, moved the built with assembleDebug file to /system/priv-app and I have tested that the signature got replaced with the fake one as I could see with the https://f-droid.org/repository/browse/?fdfilter=application&fdid=com.majeur.applicationsinfo . 
Yet, no apps from Google got tricked, they all ask me to install the Google Play Services. I have tested oldest 2.0 and newest Hangouts and YouTube. 
Or they never should be tricked and check something else not yet implemented?

**Comment by thermatk** [comment]
Update:
I have read logcat and found out that all the Google's apps are saying "Google Play Store is missing", so I have installed BlankStore for it just to be there. And it worked!
Youtube working great, Hangouts is stuck in endless "Signing in"

**Comment by mar-v-in** [comment]
Hangouts requires contact sync which is not there yet.

**Comment by thermatk** [comment]
Logcat suggests it's a problem with GCM:

D/GmsHttpFormClient( 2665): -- Response --
D/GmsHttpFormClient( 2665): Error=PHONE_REGISTRATION_ERROR
D/GmsGcmRegisterSvc( 2665): register[res]: Intent { act=com.google.android.c2dm.intent.REGISTRATION pkg=com.google.android.talk (has extras) }
I/Babel   (12703): Creating RTCS
I/Babel   (12703): Destroying RTCS
W/Babel   (12703): Error registering for GCM
W/Babel   (12703): java.io.IOException: SERVICE_NOT_AVAILABLE
W/Babel   (12703): 	at dfu.a(Unknown Source)
W/Babel   (12703): 	at cbz.a(SourceFile:305)
W/Babel   (12703): 	at cbz.doInBackground(SourceFile:298)
W/Babel   (12703): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/Babel   (12703): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/Babel   (12703): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/Babel   (12703): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/Babel   (12703): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/Babel   (12703): 	at java.lang.Thread.run(Thread.java:818)
I/Babel   (12703): Setting up account:Redacted-18 clean: false fromBackground: false
I/Babel   (12703): Account is good, register account directly for Redacted-18
I/Babel   (12703): Account registration pending Gcm:Redacted-18

**Comment by mar-v-in** [comment]
I guess i should write some tutorial on how to setup things like gcm and accounts. Will come soon

**Comment by thermatk** [comment]
I have found the tricky secret codes in the source and used them both, now Hangouts is really stuck with the contacts :)
It's truly great what you are doing here

**Comment by cobalt232** [comment]
I just did some testing with the debug build that SWW13 provided and it looks like the Android GSF ID is not generated or it it's a least not written into gservices.db. Maybe you can look into this.

BTW: I can't get this to build. Are you planning to provide an Android Studio project?

**Comment by mar-v-in** [comment]
OmniROM 5.1 accepted the patch in their latest nightlies.
