### ISSUE TITLE
Bitcoin donation

### ISSUE THREAD

**Issue by bigjesusmordino** [microg/android_packages_apps_GmsCore#1114]
Hi mar-v-in

Thanks for devoting your time to microg, it's amazing to see it's possible to use android without google. Is it possible to support this project with bitcoin? 

Feel free to pm me bitcoin address to donate if such donation can't be public for one reason or another.

**Comment by mar-v-in** [comment]
Please write a mail to `donate at microg.org` for cryptocurrency or SEPA donation details.
