### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by Psk-Ita** [microg/android_packages_apps_GmsCore#1117]
Ciao @mar-v-in 
I am new using microG, and I don't know if I made something usefull or not, anyway i prepared a module to install microG, with Playstore, Contact and Caledar Sync.
now I did it for my personal use, but I am seeing also other uaers like mixing services as I did (even if this were not the initial idea of microG)
shall I publish my module on your xda post?

if you want give a look at it, "https://androidfilehost.com/?w=files&flid=315751"

I think it could help others newby on first approach to microG, what do you think?

looking forward hearing from you.

Regards,
Pasquale

**Comment by mar-v-in** [comment]
I haven't reviewed your module, but feel free to share any work in the XDA developers thread.

**Comment by Psk-Ita** [comment]
Thank you


On 5 ago 2020 at 16:02, Marvin W <notifications@github.com> wrote:

Closed #1117
<https://github.com/microg/android_packages_apps_GmsCore/issues/1117>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/microg/android_packages_apps_GmsCore/issues/1117#event-3624825274>,
or unsubscribe
