### ISSUE TITLE
[Design] Disable animation

### ISSUE THREAD

**Issue by black-cerberon** [microg/android_packages_apps_GmsCore#1119]
Please disable animation in app. It's showing when all animation in system are disabled.

**Comment by mar-v-in** [comment]
What animation are you referring to? Fragment transitions?

**Comment by black-cerberon** [comment]
> Fragment transitions?
Yes
> Also which Android version are you using?
Android 9

**Comment by black-cerberon** [comment]
@mar-v-in animation still show in location modules activity

**Comment by mar-v-in** [comment]
Yes, this will be solved with next alpha release of UnifiedNlp
