### ISSUE TITLE
Sygic-App Problem with LocationProvider

### ISSUE THREAD

**Issue by Catfriend1** [microg/android_packages_apps_GmsCore#112]
Hello,

Sygic App does take a very long time to get a precise GPS location and updates it like stuttering. When I am indoor, it does never get a valid location and shows "inaccurate or no GPS" location error.
I'm on cm 13 nightly 2016-03-05 (A6.0.1) with licensed Sygic and MicroG GMS dated 2016-03-24.

On Catlog, I found some strange errors when recording a log and opening sygic:

> 03-31 13:03:06.338 E/Finsky  (10544): [1] com.google.android.finsky.utils.da.a(3106): No permission to get location. java.lang.SecurityException: "fused" location provider requires ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission.

> Then, there was an Error line telling me that "com.android.vending" misses permission "android.permission.WRITE_SETTINGS". 

=> pm grant com.android.vending android.permission.WRITE_SETTINGS did not solve the problem. pm can't do that.

I checked, that Google Play Store has location rights granted and they already were there. Revoked and reactivated the location rights for Play Store and Sygic. => No solution found.
Tried to set "GPS location" to "Device only" and no solution.

Whats wrong here? When I open Google Maps or Ingress, I get a very precise location immediately (outside and inside). I am using Apple WiFi, Local GSM Backend, Local Wifi Backend with filled/online databases. Ticking them on or off does not change anything regarding sygic.

**Comment by Catfriend1** [comment]
According to catlog I successfully got a location while running sygic in high accuracy location mode. But the App still complains about Bad vor inaccurate GPS. cm privacy off and location granted.


4-08 17:27:14.117 V/NlpLocationBackendFuser(27125): location=Location[network X,Y acc=907 et=+2d19h59m11s668ms {Bundle[{noGPSLocation=Location[network X,Y acc=907 et=+2d19h59m11s668ms], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService, OTHER_BACKEND_RESULTS=[Location[network X,Y acc=16 et=+2d19h52m3s938ms {Bundle[{noGPSLocation=Location[network
X,Y
acc=16 et=+2d19h52m3s938ms], AVERAGED_OF=11, SERVICE_BACKEND_PROVIDER=wifi, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.wifi_backend/.backend.BackendService_}]}]]}]}]

**Comment by n76** [comment]
It looks like only the local GSM and local WiFi/WLAN backends are giving (or have given) locations. Does this app complain about locations if a different backend is used? (Maybe try the Apple backend or the Mozilla backends by themselves.)

In this case it looks like the off line GSM location provider is showing 907 meters error and the local WiFi backend last reported a position over two days ago. I can imagine that an app looking for a good position might not like nearly a 1km error.

May not be much to help the GSM backend depending on your phone and what mobile/cell towers are in your area. But the local WiFi backend can learn your WLAN/WiFi APs if you run a GPS using app while walking around outside where you have a view to the sky and then might be able to give you a position while inside.

**Comment by Catfriend1** [comment]
Thanks for your detailed explanation. I got the problem solved by upgrading LocalWifiBackend to the newest release version from F-Droid. Temporarily I upgraded and activated newest release of AppleWifiBackend. Now Sygic gets location very fast (2-3 seconds).

**Comment by ghost** [comment]
please delete issue
