### ISSUE TITLE
disable battery optimization via API

### ISSUE THREAD

**Issue by Diapolo** [microg/android_packages_apps_GmsCore#113]
AFAIK it should be somehow possible to deactivate battery optimization for the microG Services Core via an API, IMHO this should be considered an improvement for future releases.

Could `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` be the keyword here? I'm no Android coder at all ;).

See for an example: https://github.com/JavaJens/TextSecure/issues/72#issuecomment-170034359
##

**Comment by Nutomic** [comment]
The battery optimization should definitely be handled better. 

I think it would also make sense to add an item for battery optimization to the "self-check" screen, using the [isIgnoringBatteryOptimizations()](https://developer.android.com/reference/android/os/PowerManager.html#isIgnoringBatteryOptimizations(java.lang.String)) function (on Android 6+).

**Comment by ale5000-git** [comment]
Shouldn't this be closed?

**Comment by Nutomic** [comment]
Should be, but Github didn't understand the commit message right.
