### ISSUE TITLE
Unnable to integrate in AOSP-based ROM (Lineage 17.1)

### ISSUE THREAD

**Issue by chilliger** [microg/android_packages_apps_GmsCore#1134]
When I try to integrate microG into the ROM like it is described [here](https://github.com/microg/android_packages_apps_GmsCore/wiki/Building#integrate-gmscore-in-aosp-based-rom) I get the follwoing error when building:
```
FAILED: 
packages/apps/FakeStore/Android.mk:29: error: writing to readonly directory: "packages/apps/FakeStore/fake-store/build/outputs/apk/fake-store-release-unsigned.apk"
13:38:05 ckati failed with: exit status 1
```

**Comment by mar-v-in** [comment]
I removed/replaced the entry in the wiki. This is no longer supported.
