### ISSUE TITLE
Can't login to google account

### ISSUE THREAD

**Issue by FerryAr** [microg/android_packages_apps_GmsCore#1137]
Device : Samsung Galaxy Young 2
OS : Android 4.4.2
Status : Stock ROM Rooted with Magisk v20.3
MicroG services core version : 0.2.11.202414 installed via NanoDroid Module

Logcat :
`W/GmsAuthLoginBrowser( 1295): onException
W/GmsAuthLoginBrowser( 1295): java.lang.SecurityException: caller uid 10135 is different than the authenticator's uid
W/GmsAuthLoginBrowser( 1295):   at android.os.Parcel.readException(Parcel.java:1472)
W/GmsAuthLoginBrowser( 1295):   at android.os.Parcel.readException(Parcel.java:1426)
W/GmsAuthLoginBrowser( 1295):   at android.accounts.IAccountManager$Stub$Proxy.addAccountExplicitly(IAccountManager.java:719)
W/GmsAuthLoginBrowser( 1295):   at android.accounts.AccountManager.addAccountExplicitly(AccountManager.java:617)
W/GmsAuthLoginBrowser( 1295):   at org.microg.gms.auth.login.LoginActivity$2.onResponse(LoginActivity.java:287)
W/GmsAuthLoginBrowser( 1295):   at org.microg.gms.auth.login.LoginActivity$2.onResponse(LoginActivity.java:283)
W/GmsAuthLoginBrowser( 1295):   at org.microg.gms.common.HttpFormClient$1.run(HttpFormClient.java:198)
W/GmsAuthLoginBrowser( 1295):   at java.lang.Thread.run(Thread.java:841)`

**Comment by FerryAr** [comment]
Disabling google account manager is solving the issue.
Closing

**Comment by MarceloZapatta** [comment]
@FerryAr how do you disabled google account manager?

**Comment by FerryAr** [comment]
@MarceloZapatta 
Like this?, not sure for newer android
![gam](https://ibb.co/jb14mNC)
