### ISSUE TITLE
Whatsapp can't load map

### ISSUE THREAD

**Issue by feduss** [microg/android_packages_apps_GmsCore#1155]
The error is:

`loading style failed a valid access token parameter is required when using a mapbox service`

I have 0.2.11.2099991 service core version

**Comment by Romern** [comment]
If you are building from source, you need to include your mapbox access key as ``mapbox.key=pk.ey**************`` in your ``local.properties`` file.

**Comment by feduss** [comment]
Thanks! So, the dev of my rom didn't do it :/
