### ISSUE TITLE
Exposure Notification (Corona) Scanner Implementation

### ISSUE THREAD

**Issue by tommes0815** [microg/android_packages_apps_GmsCore#1158]
**ROM**:
lineage-14.1 unofficial build - Android 7.1.2

**GmsCore**:
dirty build, commit d641ca7e7e9a147f65120c5cb40216c11744b702

**device**:
Sony Z5 compact (E5823)

**Corona app:**
CWA 1.3.0.37

Hi, I am having some issues running the EN API. First I noticed that after running EN for a while the preferences app did not show any collected IDs. So I debugged a bit. My device seems to scan for 30mins and then stops. It only continues scanning after disabling and re-enabling EN or rebooting (basically after the `ScannerService` is restarted). I added some debug output printing `seenAdvertisements` to the callback function [onScanResult](https://github.com/microg/android_packages_apps_GmsCore/blob/fd6d915f0ad1b4b35e17e0b5d844c6fc4a5efcf8/play-services-nearby-core/src/main/kotlin/org/microg/gms/nearby/exposurenotification/ScannerService.kt#L69). I see those debug prints for 30min and then stopping. They only restart after restarting the `ScannerService`.

Since nobody else noticed while testing, it might be a problem with my device/bluetooth chip. Nonetheless, it might be worth finding the issue or changing the implementation in case it affects other people. Since there is no error message it might go unnoticed and basically breaking the EN scanning functionality.

While searching for the reason of the bug I also had a look on the Google implementation / description. Please correct me if I am wrong, but I think your current implementation constantly / all the time scans for other devices? The EN system, at least as envisioned from Google/Apple, should actually only scan for a couple of seconds in an interval of a couple of minutes (when the device is woken or every 5min). Do you have a reason for the continues scanning other than to have a quick first release? I guess it is also not very battery friendly (ok, there is a "battery optimization" item on your todo list). Probably my problem would also be solved with a system, which scans only every now and then (where the ScannerService is restarted).

**Comment by rudestorm** [comment]
Not sure about this, but I thought this is part of the battery optimization process mentioned [here](https://github.com/microg/android_packages_apps_GmsCore/issues/1057#issuecomment-668276901)

**Comment by mar-v-in** [comment]
- I agree that scanning continuously is not optimal and that will certainly be optimized later on, however I also don't see a big battery impact on my device at least.
- Do you have "battery optimizations" ignored for microG Services Core according to Self-Check?
- When you are connected with adb shell, you can run `dumpsys activity service com.google.android.gms/org.microg.gms.nearby.exposurenotification.ScannerService` to let it print when it was started and when the last advertisement was recorded.

**Comment by tommes0815** [comment]
- In general, do you mind PRs for this feature or EN? I am not really a Android developer and never used kotlin. But if I am bored in the next couple of weeks, I might give it a try.
- No, all self checks are ticked
- I did not know this dump feature (as I said, I am not a Android developer), its nice :). I was already wondering for what the `dump` function is for :D

time 9:36
`SERVICE com.google.android.gms/org.microg.gms.nearby.exposurenotification.ScannerService 51a0247 pid=3207
  Client:
    Started: true
    Since Mon Sep 07 09:35:19 GMT+02:00 2020
    Seen advertisements: 23
    Last advertisement: Mon Sep 07 09:36:39 GMT+02:00 2020`
time 10:02
`SERVICE com.google.android.gms/org.microg.gms.nearby.exposurenotification.ScannerService 51a0247 pid=3207
  Client:
    Started: true
    Since Mon Sep 07 09:35:19 GMT+02:00 2020
    Seen advertisements: 340
    Last advertisement: Mon Sep 07 10:02:44 GMT+02:00 2020`
time 10:10
`SERVICE com.google.android.gms/org.microg.gms.nearby.exposurenotification.ScannerService 51a0247 pid=3207
  Client:
    Started: true
    Since Mon Sep 07 09:35:19 GMT+02:00 2020
    Seen advertisements: 379
    Last advertisement: Mon Sep 07 10:05:19 GMT+02:00 2020`

tine 10:48
`SERVICE com.google.android.gms/org.microg.gms.nearby.exposurenotification.ScannerService 51a0247 pid=3207
  Client:
    Started: true
    Since Mon Sep 07 09:35:19 GMT+02:00 2020
    Seen advertisements: 379
    Last advertisement: Mon Sep 07 10:05:19 GMT+02:00 2020`

I also attached `adb logcat *:S ExposureNotification:D` (which also shows an other problem I have, CWA has a problem checking keys and shows an timeout error, but I will use the similar open issue for this)

[2020-09-07_logcat_en-1.log](https://github.com/microg/android_packages_apps_GmsCore/files/5182055/2020-09-07_logcat_en-1.log)

**Comment by mar-v-in** [comment]
Can you test with 4663d61007060f7f42b8d91920571b1969a79b55?

**Comment by tommes0815** [comment]
I started testing it today in the morning (~3 hours ago) and until now it runs without any problem. I will close the issue if it continues running until tomorrow morning. Thank you for the quick fix

**Comment by tommes0815** [comment]
All looks well after a day, thanks again for fixing it and your work on EN in general :+1:
