### ISSUE TITLE
Waze does not get EXTENDED_ACCESS permission

### ISSUE THREAD

**Issue by bilbonotry** [microg/android_packages_apps_GmsCore#116]
This issue seems a bit like #86 to me.
Waze force-closes since v4 at launch on Android 6. I could not test on a setup with Gapps.

[logcat](http://pastebin.com/Z4aucBnc)

Thank you.

**Comment by mar-v-in** [comment]
Right before the part of the logcat you uploaded should be a line tagged with "GmsPeopleSvcImpl", can you report that line?

**Comment by bilbonotry** [comment]
No, unfortunately there is not.
Here is another logcat extract covering two different FC's and the logs between them : http://pastebin.com/azSrVcpn

**Comment by bilbonotry** [comment]
I tested in a ROM with Gapps and Waze works.

**Comment by mar-v-in** [comment]
This should be fixed in Version 0.2.2-3

**Comment by bilbonotry** [comment]
Great, thank you for your really quick fix !

**Comment by bilbonotry** [comment]
I updated microg and can confirm the issue is fixed. Thank you very much again !
