### ISSUE TITLE
Bluetooth has to be enabled for Corona Warn App

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [microg/android_packages_apps_GmsCore#1169]
To use the German Corona Warn App with microg, you have to enable bluetooth. This does enable the whole bluetooth stack including visibility of your device - not only the BLE variant used for exposure notification.
In my opinon, this is a problem regarding power consumption - and privacy, too, because on Android 9 Lineage for microg, there is no option for disabeling visibility if bluetooth is on.

Because AFAIK this problems are fixed in stock Android versions with Google services, it would be great to only use and enable BLE for EN with microg, too.

Or do I miss a already existing setting that could fix the problem?

**Comment by mar-v-in** [comment]
Even with Google services, Bluetooth needs to be enabled on Android to use Exposure Notifications. This is also noted in the CWA FAQ: https://www.coronawarn.app/de/faq/#bluetooth_off

However, on Android, devices are only visible while you are in the system settings "Bluetooth" or "Connected devices" section. Your device becomes invisible as soon as you are not in this section of the system settings, i.e. during normal usage or while the screen is off.
