### ISSUE TITLE
Status screen for GCM

### ISSUE THREAD

**Issue by mar-v-in** [microg/android_packages_apps_GmsCore#117]
As requested in #104

**Comment by Diapolo** [comment]
That'd be a very nice and helpful addition, looking forward to it :).

**Comment by zoff99** [comment]
can you enhance this status screen, with a debug option, to really display all incoming GCM messages including to full data? this would be very helpful to debug stuff

**Comment by mar-v-in** [comment]
Implemented via #175 

@zoff99 incoming messages are printed to logcat, you can grep it from there including some time (usually only hours) backlog.
