### ISSUE TITLE
Add ability to view the number of currently visible exposure notification IDs

### ISSUE THREAD

**Issue by ljl-covid** [microg/android_packages_apps_GmsCore#1170]
This is a feature request mostly inspired by the [UUID 0xFD6F Scanner](https://github.com/marq24/UUID0xFD6FTracer/) app. That app, which is named so generically in order to be allowed in the Google Play store, and yet ironically [it was removed anyway](https://github.com/marq24/UUID0xFD6FTracer/blob/master/GOOGLEPLAYSTORE.md), simply tells you the number of exposure notification IDs visible at any given time, with logic (since "at any given time" has a degree of arbitrariness for anything that's broadcast periodically) that is described in German [in this issue](https://github.com/marq24/UUID0xFD6FTracer/issues/1#issuecomment-652256496).

MicroG already provides the number of IDs seen in the past hour, but for me, it's also interesting to see, like, I'm at a busy traffic junction, or I'm in a particular store, how many devices are broadcasting *at that moment*? Also, since [I have myself an issue with the app sometimes incorrectly reporting 0](https://github.com/marq24/UUID0xFD6FTracer/issues/9#issuecomment-691180912), I would find it of particular interest to have the exact same logic in MicroG in order to compare directly. However, if you think a different logic would make more sense, that's fine, as obviously it doesn't make sense to demand identical behavior jus for the sake of it.

The author of the app also offers [a solution with logging](https://github.com/marq24/UUID0xFD6FTracer/blob/master/LOGGING_de.md) (German again), but it's not open source, and besides, this one acts more like microG already does, by counting the number of IDs seen in total (which has the issue that IDs keep changing, so the number is less meaningful than one would think), instead of the ones currently visible. But anyway, all kinds of logging of what's been seen could be interesting, and while I understand providing detailed graphs or even maps might be considered outside of the scope of microG, I was thinking that maybe just providing an option to export the database in a sensible format, with timestamps, would be useful to enable such things separately.

**Comment by chris42** [comment]
Isn't something like that completely against the philosophy of microg, which tries to reduce data gathering as much as possible?

**Comment by ljl-covid** [comment]
@chris42 why would *showing* the user something that is already *gathered* anyway entail any data gathering? What do you even mean by "gathering" here? I felt pretty sure microG wasn't against *me* gathering data on my device.

**Comment by chris42** [comment]
Sorry for not putting that correct: Exposing this information or make it available to use out of context. Data protection is 2-ways, so if I want to reduce my data footprint, I would of course do the same for other peoples data. So having a function, that gives the opportunity to log all IDs and use them out of context would hurt that?!

**Comment by ljl-covid** [comment]
The protocol is designed to be anonymous. If you don't believe it really is, then you shouldn't use it to protect your privacy. On the other hand, relying on an open source project providing that anonymity for you by refraining from showing collected data to the user is *extremely* bad security practice, so your reasoning is essentially very flawed.

Practical example: since installing microG entails having /system access, that means that if I *really* want to, I can just get the database from my recovery file manager anyway, no matter what protections are put against it.

Anyway, luckily I don't believe either of us decides what the philosophy of microG is, so I propose waiting for developers to review this proposed feature.

**Comment by chris42** [comment]
Thank you for lecturing me in this weird way. Your are correct, we do not decide this, hence I wrote my opinion and asked. It is up to Marvin to see if it fits microg and if he wants to put effort in it.

**Comment by ljl-covid** [comment]
Yeah, you totally did nothing as bad as me lecturing you by alleging that I was proposing something against the "philosophy" of the project just by asking for a simple extension of the feature that is already present showing you the graph of IDs you have encountered. Give me a break.

**Comment by chris42** [comment]
You figure, that this is an open space, in which what you post can be questioned and criticised? If you cannot cope with that, you should probably get in contact with the developers in a more private manner.

**Comment by mar-v-in** [comment]
I do agree that such functionality could be useful. However there are two main reasons I don't think it makes sense to have it in microG.

- It's not in any way necessary for the usage of microG and can be implemented outside of microG without any issue.
- Live data is not available inside microG. We only scan every 3 minutes and will probably change this to 5 minutes at some point. While this is very close to live, it could confuse users to not see a live number increase as soon as they jump in a full tram or whatever.

If you need data for.debugging purposes, you can either use external apps or use dumpsys to gather insights from the service.

**Comment by ljl-covid** [comment]
Okay, that makes sense. But please don't make the checking interval too sparse... some (most?) of these apps are already being way overly cautious with what counts as a "contact", both in terms of distance, which is inevitably guesstimated using signal strength, and time, which I believe needs to be at least 15 minutes, at least here. 15 minutes is a pretty long time, considering the distance criteria has been shown to result in two people kissing not counting as less than 2m apart simply because they had their phones in their back pockets... if to that, you add a check only every 5 minutes, even the 15 minute threshold becomes harder to actually meet.

If you're just uncomfortable to leave it at something that isn't what Google uses, please consider making it user-configurable: I really don't care if I waste a little more battery in exchange for better likelihood of catching contacts.

**Comment by mar-v-in** [comment]
I do agree that sparse scanning is going to lower the sensitivity of the whole approach.

However the original Google implementation only checks every 5 minutes, which is why many apps using it decided to only consider those that have 5, 10 or more minutes of contact, as the provided data accuracy is just not high enough if you want to reach a certain specificity

**Comment by ljl-covid** [comment]
FWIW, I've had the chance to look at a non-microG phone, and it does provide some kind of export (although I didn't check what data exactly would be exported):

![Screenshot_20200915-204915_Google_Play_Services](https://user-images.githubusercontent.com/62215844/93277508-487ba400-f7c2-11ea-941b-0630e3dabeb6.jpg)

So while I agree it's not necessary to use microG, the Google implementation actually seems to provide it to some extent. To be honest I'm more just reporting this simply because I'm surprised to find it.
