### ISSUE TITLE
Upgrading to LineageOS for microG 17.1

### ISSUE THREAD

**Issue by Foxite** [microg/android_packages_apps_GmsCore#1172]
I know this isn't the right repo for this issue, but I wasn't able to find the repo for the LineageOS fork. Please point me in the right direction for it (or transfer the issue). 

I noticed LineageOS for microG 17.1 recently became available for my device (kuntao - currently on 16.0). I want to upgrade but I'm not sure what the procedure is.

The website has a section on upgrading from 15.1 to 16.0. Is going from 16.0 to 17.1 any different? I have updated microG 2 days ago, do I need to do anything special to ensure that there will be no problems? (Because the microG version I currently have is more recent than the LineageOS build, upgrading to that version means I will downgrade microG.)

**Comment by Nanolx** [comment]
AFAIK you can dirty flash LOS 17 over LOS16, still I'd advise to make a backup (I don't use LOS, but AICP and made a clean flash when switching from P to Q anyways).

> Because the microG version I currently have is more recent than the LineageOS build, upgrading to that version means I will downgrade microG.

Not on a dirty flash. The update you installed resides in /data/app, the older version from LOS resides in /system/priv-app. Android gives updates a higher priority over lower system apps, so it won't downgrade.

**Comment by Foxite** [comment]
I've dirty flashed LOS 17 shortly after your message and I have not had any issues with microG since.
