### ISSUE TITLE
Exposure Notifications don't ask for ACCESS_FINE_LOCATION permission

### ISSUE THREAD

**Issue by jplitza** [microg/android_packages_apps_GmsCore#1178]
I set up Corona Warn App with microG Exposure Notifications on my LineageOS 17.1. No error messages or any indication of it not working: CWA is happy, and so is the microG settings page.

<details>
<summary>microG self-check screenshot</summary>

![Screenshot_20200915-141035_microG_Services_Core](https://user-images.githubusercontent.com/3628012/93209312-3b2cce00-f75e-11ea-98a3-46887f0afba9.png)
</details>

However, no IDs of other phones are recorded: The settings page always displays "0 IDs in den letzten 60 Minuten" ("0 IDs in the last 60 minutes"), and the graph on the detailed page also displays no collected IDs (in a rather funny way), and has the "Delete all" button disabled.

<details>
<summary>microG collected IDs graph</summary>

![Eh8EzVlWkAE4auh](https://user-images.githubusercontent.com/3628012/93207116-c3a96f80-f75a-11ea-9e64-59d60cfb2a2b.png)
</details>

The [UUID 0xFD6F Scanner app](https://f-droid.org/de/packages/com.emacberry.uuid0xfd6fscan/), on the other hand, detects foreign phones just fine. So my hardware seems to be working.

logcat just gives the following, repeating every few minutes:
```
09-15 13:53:12.145 22887 22887 D ExposureNotification: Starting scanner for service 0000fd6f-0000-1000-8000-00805f9b34fb
09-15 13:53:12.147 22887 22887 D BluetoothAdapter: isLeEnabled(): ON
09-15 13:53:12.151  1338  1486 I bt_stack: [INFO:gatt_api.cc(946)] GATT_Register 42831303-0186-f783-cc36-ccb66d16ab7a
09-15 13:53:12.151  1338  1486 I bt_stack: [INFO:gatt_api.cc(966)] allocated gatt_if=6
09-15 13:53:12.152 22887 15198 D BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=6 mScannerId=0
09-15 13:53:12.155  1338  1594 E BluetoothUtils: Permission denial: Need ACCESS_FINE_LOCATION permission to get scan results
09-15 13:53:12.254 22887 22887 D ExposureNotification: RPI: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX, Version: 0x40, TX Power: -18, AEM: 0x290a2198, Timeout: 180000ms
09-15 13:53:12.258 22887 22887 D BluetoothAdapter: isLeEnabled(): ON
09-15 13:53:12.260 22887 22887 D BluetoothAdapter: isLeEnabled(): ON
09-15 13:53:12.263  1338  1594 D BluetoothAdapterService: getAdapterService() - returning com.android.bluetooth.btservice.AdapterService@7606849
09-15 13:53:12.266  1459  1461 E WCNSS_FILTER: do_read: read returned 0, err = Success, read bytes: 0, expected: 0
```

Where `XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX` is (according to the microG settings) my current RPI. The problem probably lies here:
```
09-15 13:53:12.155  1338  1594 E BluetoothUtils: Permission denial: Need ACCESS_FINE_LOCATION permission to get scan results
```
but according to the self-check page, I granted the location permission to microG!?

**Comment by jplitza** [comment]
Indeed executing `pm grant com.google.android.gms android.permission.ACCESS_FINE_LOCATION` in a root adb, I got rid of the "Permission denial" message and started collecting RPIs. Strange, that microG never asked for that permission, and doesn't include it in its self-check.

**Comment by mar-v-in** [comment]
Thanks for pointing this out. Good catch. Just for others who see this issue: You should be able to grant the permission also from system settings user interface by removing and then re-granting the location permission (which will grant both coarse and fine location access).

**Comment by ljl-covid** [comment]
@mar-v-in that doesn't work for me (if I understand what you're saying correctly) because on trying to remove it, I get

> microG Services Core is a provider of location services for this device. Location access can be modified from locaion settings.

and Location permission remains enabled after this dialog.

**Comment by mar-v-in** [comment]
@ljl-covid can you check the log if there is any error message when enabling EN (I guess you can just disable and re-enable EN logging in the Immuni app)? If the permission is the issue, there should be logs pointing this out.

I improved both advertising and scanning code further since the 0.2.12 release and also included a bit more useful logging. So if the issue persists, I can provide you a build with these changes (or you build it yourself).

**Comment by ljl-covid** [comment]
@mar-v-in you may probably ignore my complaint, because I realized that particular phone was stuck on 0.2.11. Sorry, I've got a few phones running this, for my family... F-Droid doesn't make it any easier, but I think they've now pushed a fix for the incorrect pinning of microG.

If I see this happen again with 0.2.12 I'll let you know.
