### ISSUE TITLE
VTMGo app crashes on startup

### ISSUE THREAD

**Issue by goffioul** [microg/android_packages_apps_GmsCore#1186]
I'm testing integration of MicroG within Android-x86, currently being ported to Android 11. A summary of me setup is as follows:
- signature spoofing is integrated into the build (fyi, Android 11 patch can be found in [1])
- android-x86 running in qemu with virgl, in live mode (aka /data is tmpfs, no data persistence between run)
- install GmsCore v0.2.12.203315
- install com.google.android.gsf-8.apk
- install com.android.vending-16.apk
- launch MicroG settings, go to Self Check, enable everything
- adb shell am start -n com.android.vending/.GrantFakeSignaturePermissionActivity, grant permission
- go back to MicroG settings -> Self Check, verify all check boxes are ticked
- install VTMGo [2]
- launch VTMGo app => crash; logcat output can be found in [1]

[1] https://drive.google.com/drive/folders/1wZ0ZSh-m7jLpWUSwcP9MtvgeHvFzbgjN?usp=sharing
[2] https://apkpure.com/vtm-go/be.vmma.vtm.zenderapp

**Comment by mar-v-in** [comment]
Probably fixed through dbcf70f99ec36e68a886efef5f4552fe0e0d7e7e

**Comment by goffioul** [comment]
Confirmed, app runs fine now. Thanks.
