### ISSUE TITLE
whishlist: make hearbeat interval input box in setting

### ISSUE THREAD

**Issue by zoff99** [microg/android_packages_apps_GmsCore#119]
i am running with hearbeat interval of 10 minutes. and it works fine. so i think everybody needs really different values.

can you make a settings input field so every user can configure the best value for use?

#47

**Comment by mar-v-in** [comment]
What do you mean? There already is an input box in settings to configure heartbeat interval.

**Comment by zoff99** [comment]
sorry my bad. was using old version
