### ISSUE TITLE
unavailable shared library com.google.android.maps

### ISSUE THREAD

**Issue by SWW13** [microg/android_packages_apps_GmsCore#12]
Is the 'com.google.android.maps' included? If so, how can I debug the Problem?

Tested on customized CM12.1 build with signature patch.
I used 'Öffi' (http://oeffi.schildbach.de/download.html) for testing.

```
D/PackageManager(  607): Renaming /data/app/vmdl1666102432.tmp to /data/app/de.schildbach.oeffi-1
E/installd(  202): Couldn't opendir /data/data/de.schildbach.oeffi: No such file or directory
W/PackageManager(  607): Package couldn't be installed in /data/app/de.schildbach.oeffi-1
W/PackageManager(  607): com.android.server.pm.PackageManagerException: Package de.schildbach.oeffi requires unavailable shared library com.google.android.maps; failing!
W/PackageManager(  607): 	at com.android.server.pm.PackageManagerService.updateSharedLibrariesLPw(PackageManagerService.java:5390)
W/PackageManager(  607): 	at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:5741)
W/PackageManager(  607): 	at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:5482)
W/PackageManager(  607): 	at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:10940)
W/PackageManager(  607): 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:11485)
W/PackageManager(  607): 	at com.android.server.pm.PackageManagerService.access$2500(PackageManagerService.java:271)
W/PackageManager(  607): 	at com.android.server.pm.PackageManagerService$5.run(PackageManagerService.java:9384)
W/PackageManager(  607): 	at android.os.Handler.handleCallback(Handler.java:739)
W/PackageManager(  607): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/PackageManager(  607): 	at android.os.Looper.loop(Looper.java:135)
W/PackageManager(  607): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/PackageManager(  607): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
D/fdroid.AppDetails( 5175): Getting application details for de.schildbach.oeffi
E/fdroid.AppDetails( 5175): Installer aborted with errorCode: 2
```

**Comment by mar-v-in** [comment]
Use https://github.com/microg/android_frameworks_mapsv1 or https://github.com/mar-v-in/MapsAPI for apps using legacy maps. MapsAPI is older, but more stable and easier to build and also comes precompiled as a flashable zip.

**Comment by drtrigon** [comment]
Is there another, probably simpler way to install and setup this (e.g. using an apk)? I now how to do but I really don't like messing around with recovery images or adb.

**Comment by ale5000-git** [comment]
@drtrigon
It isn't an app, it is a library; so there isn't an apk and there isn't any other way to install it other than place the file in the proper folder.
PS: My [microG unofficial installer](https://github.com/micro5k/microg-unofficial-installer) (an OTA zip) automatically setup GmsCore, Maps API and other microG components.

**Comment by drtrigon** [comment]
@ale5000-git: Can it also be done using e.g. Ghost Commander? Or by converting from user to system app by e.g. Link2SD?

**Comment by ale5000-git** [comment]
You can't convert it since it is NOT an app but you can place the ".jar" file manually in the right place if you have root.

**Comment by drtrigon** [comment]
Would it be possible to make a (dummy) app that does install this library into the system? E.g. "mapsapiv1 installer"? I guess it would need root.

**Comment by ale5000-git** [comment]
@drtrigon
It should be easy to put it on the system if you have adb (with adb root enabled), but it probably still require a restart of Android (I'm not 100% sure).
