### ISSUE TITLE
Remove Blitzortung Lightning Monitor from problem apps

### ISSUE THREAD

**Issue by YigYag** [microg/android_packages_apps_GmsCore#1204]
The app has used OSM for a while so it works perfectly fine with microG.

**Comment by ljl-covid** [comment]
Yes, it's in F-Droid too. I don't know what the "problem apps" list is actually, but just confirming it works fine, at least the F-Droid version.

**Comment by YigYag** [comment]
@ljl-covid The list is part of the wiki 
https://github.com/microg/android_packages_apps_GmsCore/wiki/Problem-Apps

**Comment by YigYag** [comment]
I was not aware it was publicly editable. I have now removed the app myself from the list so I will close this issue.
