### ISSUE TITLE
Exposure Notification in Nearby framework not working on HTC One A9

### ISSUE THREAD

**Issue by herionhonig** [microg/android_packages_apps_GmsCore#1216]
German 'Corona-Warn-App' don't work. 
Device: HTC One A9, LineageOS 14.1, Android 7.1.2, microG Services Core 0.2.12.203315
The One A9 uses Bluetooth 4.1 and should support BT LE.

In the microG-Settings the Exposure Notifications are listet but are reported as off. The message is "To enable Exposure Notifications, open any app supporting it." See picture 'ExposureNotification01.png'. Enabling it manually is not possible.

In the Corona-Warn-App the error message is "Your Corona-Warn-App is correctly installed, but the COVID-19 exposure notifications service is not available...". See picture 'ExposureNotification02.png' and 'ExposureNotification03.png'

In the logcat's in pictures 'logcat01.png' and 'logcat02.png' you can find the corresponding error messages.

![ExposureNotification01](https://user-images.githubusercontent.com/65958163/95558466-90cf6000-0a16-11eb-95b9-420ab813e740.png)
![ExposureNotification02](https://user-images.githubusercontent.com/65958163/95558472-9167f680-0a16-11eb-8d23-0fa705885900.png)
![ExposureNotification03](https://user-images.githubusercontent.com/65958163/95558474-92992380-0a16-11eb-86d5-d0755b8c0f9b.png)
![logcat01](https://user-images.githubusercontent.com/65958163/95558480-93ca5080-0a16-11eb-8df9-361b89b9e6c4.png)
![logcat02](https://user-images.githubusercontent.com/65958163/95558482-9462e700-0a16-11eb-9092-f573e4d581bc.png)

**Comment by mar-v-in** [comment]
What does the Self-Check in microG Settings say?

**Comment by spaetz** [comment]
Same issue with a LineageOS 17.1 device here. This is the (German) self check...
![Screenshot_20201009-193024_microG_Services_Core](https://user-images.githubusercontent.com/63132/95613984-11697d00-0a66-11eb-8f03-2519c1ef4f34.png)

**Comment by spaetz** [comment]
All the rest looking good in the self check too
