### ISSUE TITLE
Unreasonable disk usage (?)

### ISSUE THREAD

**Issue by trashcan55** [microg/android_packages_apps_GmsCore#1217]
Probably related to exposure notifications functionality.

Since I have installed the latest Version with contact-tracing support and using it with the german [corona-warn-app](https://github.com/corona-warn-app/cwa-app-android), microg uses enormous amounts of space for user data, until my internal disk space runs full and the corona-app (and other apps) stop functioning. 

6 days ago I had to wipe all of the userdata of microg, but it has since then accumulated again to 3.5GB of internal disk space.

is this intended behaviour?

**Comment by trashcan55** [comment]
so sorry, must have overseen this issue was already filed >_>

**Comment by beatstick** [comment]
Sorry, I cannot find the related issue. I do have the same problem on Android 7.1 as well. Maybe on Android 10, too, I have to check, the disk is just a lot bigger, so it will be noticed later...

**Comment by trashcan55** [comment]
#1190 is the related issue
