### ISSUE TITLE
Checkin service does not start on boot

### ISSUE THREAD

**Issue by goffioul** [microg/android_packages_apps_GmsCore#1220]
I'm trying to integrate MicroG (GmsCore-v0.2.12.203315.apk) in an Android 9 build of android-x86, and have both checkin and gcm services started automatically on boot, including on first boot. To enable services, my build contains the following `/system/etc/microg.xml` file:
```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="checkin_enable_service" value="true" />
    <boolean name="gcm_enable_mcs_service" value="true" />
</map>
```

On initial boot, I can see GCM service started (on BOOT_COMPLETED broadcast), but it bails out as there's no checkin. Checkin service does not start, even when Wi-Fi connection is established (the build automatically connects to a specified AP). From what I can see, even though service `org.microg.gms.checkin.TriggerReceiver` registers a receiver for `android.net.conn.CONNECTIVITY_CHANGE` in the manifest, it's never triggered, because the APK targets API >= 24 (API 29 as of this writing). As stated in doc for ConnectivityManager, an app cannot receive that broadcast through manifest since Android N.

**Comment by goffioul** [comment]
For the record, I've successfully used the following patch:
```
diff --git a/play-services-core/src/main/AndroidManifest.xml b/play-services-core/src/main/AndroidManifest.xml
index 9c50217..8e9d432 100644
--- a/play-services-core/src/main/AndroidManifest.xml
+++ b/play-services-core/src/main/AndroidManifest.xml
@@ -195,6 +195,7 @@
 
         <receiver android:name="org.microg.gms.checkin.TriggerReceiver">
             <intent-filter>
+                <action android:name="android.intent.action.BOOT_COMPLETED" />
                 <action android:name="android.server.checkin.CHECKIN" />
                 <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
             </intent-filter>
diff --git a/play-services-core/src/main/java/org/microg/gms/checkin/TriggerReceiver.java b/play-services-core/src/main/java/org/microg/gms/checkin/TriggerReceiver.java
index 123d76d..5cc6c8b 100644
--- a/play-services-core/src/main/java/org/microg/gms/checkin/TriggerReceiver.java
+++ b/play-services-core/src/main/java/org/microg/gms/checkin/TriggerReceiver.java
@@ -18,8 +18,10 @@ package org.microg.gms.checkin;
 
 import android.content.Context;
 import android.content.Intent;
+import android.content.IntentFilter;
 import android.net.ConnectivityManager;
 import android.net.NetworkInfo;
+import android.os.Build;
 import android.preference.PreferenceManager;
 import android.util.Log;
 
@@ -32,6 +34,16 @@ import static org.microg.gms.checkin.CheckinService.EXTRA_FORCE_CHECKIN;
 public class TriggerReceiver extends WakefulBroadcastReceiver {
     private static final String TAG = "GmsCheckinTrigger";
     private static final long REGULAR_CHECKIN_INTERVAL = 12 * 60 * 60 * 1000; // 12 hours
+    private static boolean registered = false;
+
+    private synchronized static void register(Context context) {
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N && !registered) {
+            Log.d(TAG, "Registering receiver for " + ConnectivityManager.CONNECTIVITY_ACTION);
+            IntentFilter intentFilter = new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION);
+            context.getApplicationContext().registerReceiver(new TriggerReceiver(), intentFilter);
+            registered = true;
+        }
+    }
 
     @Override
     public void onReceive(Context context, Intent intent) {
@@ -39,9 +51,16 @@ public class TriggerReceiver extends WakefulBroadcastReceiver {
             boolean force = "android.provider.Telephony.SECRET_CODE".equals(intent.getAction());
             ConnectivityManager cm = (ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE);
 
+            Log.d(TAG, "Processing " + intent);
+
+            if (Intent.ACTION_BOOT_COMPLETED.equals(intent.getAction())) {
+                register(context);
+            }
+
             if (CheckinPrefs.get(context).isEnabled() || force) {
                 if (ConnectivityManager.CONNECTIVITY_ACTION.equals(intent.getAction()) &&
                         LastCheckinInfo.read(context).lastCheckin > System.currentTimeMillis() - REGULAR_CHECKIN_INTERVAL) {
+                    Log.d(TAG, "Ignoring " + intent + ": too early, " + LastCheckinInfo.read(context).lastCheckin);
                     return;
                 }
 
@@ -50,6 +69,8 @@ public class TriggerReceiver extends WakefulBroadcastReceiver {
                     Intent subIntent = new Intent(context, CheckinService.class);
                     subIntent.putExtra(EXTRA_FORCE_CHECKIN, force);
                     startWakefulService(new ForegroundServiceContext(context), subIntent);
+                } else {
+                    Log.d(TAG, "Ignoring " + intent + ": no network, " + networkInfo);
                 }
             } else {
                 Log.d(TAG, "Ignoring " + intent + ": checkin is disabled");
```

**Comment by mar-v-in** [comment]
e20a6c3a3cfda186edbc6a4c9ac525509dbe3809 fixes device checkin with newer Android versions.

**Comment by goffioul** [comment]
> It's also not possible to register for CONNECTIVITY_ACTION from within the BOOT_COMPLETED receiver.
Do you have a reference that forbids that? That's why my suggested patch does and it works fine for me.

> I don't see why you need to register a device at the earliest option after boot.
I need the service running automatically without user intervention. It can be at boot or shortly after (e.g. when connectivity becomes available), but it must be running.

> It should be enough to register the device before the first app registers for push notifications, no?
This is not happening for me. After boot, I install skype and sign-in. That does not trigger the checkin service. And the skype account cannot be called from another device.

**Comment by mar-v-in** [comment]
> Do you have a reference that forbids that? That's why my suggested patch does and it works fine for me.

The documentation of [`registerReceiver()`](https://developer.android.com/reference/android/content/Context#registerReceiver(android.content.BroadcastReceiver,%20android.content.IntentFilter)) has a note:
> this method cannot be called from a BroadcastReceiver component; that is, from a BroadcastReceiver that is declared in an application's manifest.

It might have worked in your case if the BroadcardReceiver component was still valid at the time the connection came online - as broadcast receiver components are active for about 10 seconds.

> After boot, I install skype and sign-in. That does not trigger the checkin service.

OK, so that is a real issue here :)

**Comment by goffioul** [comment]
> It might have worked in your case if the BroadcardReceiver component was still valid at the time the connection came online - as broadcast receiver components are active for about 10 seconds.

Thanks for the pointer. Not sure it made a difference, but I used the application context to register the receiver. I understand that Android throws `ReceiverCallNotAllowedException` in cases where you're not supposed to register a receiver, but that obviously didn't occur in my case.

In any case, I'm all in favor for a register-on-demand solution, if that's how it's supposed to work.

**Comment by goffioul** [comment]
> > After boot, I install skype and sign-in. That does not trigger the checkin service.

> OK, so that is a real issue here :)

Should I open a separate issue for this?

**Comment by mar-v-in** [comment]
I'm already working on this ;)

**Comment by goffioul** [comment]
For my own information, do you have an ETA for a fix/solution?

**Comment by mar-v-in** [comment]
Have you tried with latest release? It already has code to try a checkin before gcm registration

**Comment by goffioul** [comment]
My bad. I wasn't monitoring the git commits, and as there was no update to this issue report, I missed the fix. I can confirm that this commit solves my problem: https://github.com/microg/android_packages_apps_GmsCore/commit/26f2e859b8d424f20f42f3c2ec3736817f39b6e2

Starting registration on-demand, the first time an app attempts to register, fits in my use-case. Thanks.
