### ISSUE TITLE
INearbyExposureNotificationService.aidl looks wrong

### ISSUE THREAD

**Issue by mame82** [microg/android_packages_apps_GmsCore#1221]
Hi, I don't use microg myself, but did some reversing work on GMS EN Binder interface.

https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-nearby-api/src/main/aidl/com/google/android/gms/nearby/exposurenotification/internal/INearbyExposureNotificationService.aidl

In the file above some methods are missing, also I wonder why the transaction codes start from 0 (instead of 1).

I have attached a screenshot from my code for comparison (for code 14 and 19, the 'Params' suffix has to be removed).

Hope this helps, cheers MaMe82

![Screenshot_20201009-175343_Samsung Internet](https://user-images.githubusercontent.com/13119970/95606489-b1b9a480-0a5a-11eb-9bda-ab504f6c13a4.jpg)

**Comment by mar-v-in** [comment]
The interface file you are referring to is in AIDL format. The first valid transaction code for user commands in binder transactions is `1` ([see `FIRST_CALL_TRANSACTION`](https://developer.android.com/reference/android/os/IBinder#FIRST_CALL_TRANSACTION)). The number in AIDL specifies the **offset** from `FIRST_CALL_TRANSACTION`, thus `0` in AIDL means `1` in the binder interface.

AIDL interfaces do not need to include all methods. It's completely fine if some of them are missing as long as the associated transaction number matches. The reason why some methods show up in your reverse engineered list and not in microG's AIDL, is probably that these methods are not exposed in the gms client library but only used internally within Google apps (e.g. the `resetAllData` is called by a menu option in Google Settings, but cannot be invoked by apps using EN API). In microG we don't expose internal functions in public AIDL interfaces, so there is no need to reproduce them.

With regards to the name: AIDL interfaces do not include any method names, but instead only use transaction call codes. As such it doesn't matter at all how we name the method, it still stays completely compatible as long as we associate the same semantic meaning with a transaction call code. As the method names are typically obfuscated in the published gms binaries, it's actually very common for those names to mismatch as they are only "guessed" either from the client function call involved or by their meaning.

**Comment by mame82** [comment]
Thank you for clarifying the relevant aspects on AIDL.

In fact I was totally unaware that the numbering describes the offset from IBinder.FIRST_CALL, instead of the transaction code used in BINDER_WRITE_READ IOCTLs (I am aiming at the latter in my project).

This also helps me to sort out some past issues I ran into, when manually interpreting publicly available AIDL files, to conclude for corresponding transaction codes.

Thx for shedding some light, gonna close this
