### ISSUE TITLE
CoronaWarn App fails to download IDs

### ISSUE THREAD

**Issue by ou-li** [microg/android_packages_apps_GmsCore#1227]
since updating LineageOS to 17.1 (12 Oct 2020) 
microG Services Core  0.2.12.203315
CoronaWarn App version 1.3.1

Checking for updates for a couple of minutes then fails...

![Screenshot_20201014-123702_Corona-Warn](https://user-images.githubusercontent.com/7612981/95978159-15a4ea00-0e1a-11eb-9831-a7869ccf9527.png)
![Screenshot_20201014-120340_Corona-Warn](https://user-images.githubusercontent.com/7612981/95978199-22c1d900-0e1a-11eb-9f4b-2fb8e6c08f39.png)

Collection of IDs working fine though:
![Screenshot_20201014-125933_microG_Services_Core](https://user-images.githubusercontent.com/7612981/95980269-33c01980-0e1d-11eb-8b58-9a6c081b60f7.png)

**Comment by gxtu** [comment]
Could this just be a problem with the servers? I noticed the same problem today, but haven't updated the app or LineageOS for microG since it last worked.

**Comment by ou-li** [comment]
Thanks for the suggestion @gxtu . I have tried restarting the app a couple of times as you suggested and also restarted the phone. This brings up new errors (timeout, job cancelled). Will tray again tomorrow and report back here.
![Screenshot_20201014-194541_Corona-Warn](https://user-images.githubusercontent.com/7612981/96026285-984b9a80-0e56-11eb-907a-9fa5b2b1c038.png)
![Screenshot_20201014-194546_Corona-Warn](https://user-images.githubusercontent.com/7612981/96026281-971a6d80-0e56-11eb-89fc-747f2621f295.png)
![Screenshot_20201014-194202_Corona-Warn](https://user-images.githubusercontent.com/7612981/96026289-997cc780-0e56-11eb-9de9-b4fdf50b8601.png)

**Comment by jounathaen** [comment]
I had a very similar issue since now a week and the latest "beta"-release linked in #1190 seems to fix it. (Now I cannot look what the error message for me was, so I can't 100% confirm if it was the same error). Let's see if the error comes back.

**Comment by ou-li** [comment]
Thank you @jounathaen ! That was it. 
Installing mar-v-in's updated core-en.apk, switchin gEsposure notification off and back on, 
CWA working fine now.
