### ISSUE TITLE
play store crashes after system reinstall

### ISSUE THREAD

**Issue by herrdeh** [microg/android_packages_apps_GmsCore#123]
In my first setup play store worked fine.
After a clean install of SlimKat, play store crashes often, and reliably when trying to download an app or an update. A logcat (open play store twice - crashed twice - tried to download the update of "GPS status" (com.eclipsim.gpsstatus2) - play store crashed again) is attached.

PlayStore_v6.4.12.C-all.apk, GmsCore v0.22
(tried com.android.vending-5.6.8-80360800-minAPI9.apk, which was working in the old setup - but it didn't work either)

[play2.txt](https://github.com/microg/android_packages_apps_GmsCore/files/227603/play2.txt)

**Comment by Catfriend1** [comment]
is it installed in system/priv-app?

**Comment by herrdeh** [comment]
No,  neither.

**Comment by herrdeh** [comment]
When I try to launch my paid app "windfinder", it will return the message "license check failed - There was an error when checking your pro version status. Check app status in google play. Download an update" (words translated from German).

Hope, this may provide additional information about the problem.
[windfinder.txt](https://github.com/microg/android_packages_apps_GmsCore/files/231351/windfinder.txt)


Logcat attached.

**Comment by mar-v-in** [comment]
> Permission Denial: Accessing service ComponentInfo{com.android.vending/com.google.android.finsky.services.LicensingService} from pid=13549, uid=10093 requires com.android.vending.CHECK_LICENSE

@herrdeh Did you install Play Store *after* installing Windfinder? If so, try reinstalling Windfinder.

**Comment by mar-v-in** [comment]
Also note that you are required to install Play Store to `/system/priv-app` (e.g. with system-app mover), it does not work if installed the usual way (blame Google)

**Comment by herrdeh** [comment]
Allright. I moved the apk to /system/private-app, and everything is nice again. Downloads are working, windfinder as well. 

Great!
And thanks!
