### ISSUE TITLE
Corona Warn App requires an Play Service Update on latest microG

### ISSUE THREAD

**Issue by Varbin** [microg/android_packages_apps_GmsCore#1232]
With the new app version of the  German Corona-Warn-App released today (1.5.0.47), it wants an update of the Google Play services and refuses to run otherwise.

**Update:** I was sucessfully able to enable exposure notification (_but the warning persists_) by entering the app and clickin on enable and immediatly leave (so microG at least continues to collect ids), but it sometimes disables itself. There are also sometimes communication errors, similar to #1171 (did not happen on older versions).

Software versions:
Lineage 17.1-20201016-microG-river
microG Services Core 0.2.12.203315

**Comment by mar-v-in** [comment]
Works again with v0.2.13.203915
