### ISSUE TITLE
Empty currently broadcasted ID

### ISSUE THREAD

**Issue by donpatrice** [microg/android_packages_apps_GmsCore#1233]
In exposure notifications the field "Currently broadcasted ID" is empty. Two days ago I could see the the ID there.

Any ideas what the problem could be? I am wondering if there actually is an ID so the exposure notifications is propperly working.

Thanks a lot for your effort.

**Comment by mar-v-in** [comment]
If you just installed the microG update 0.2.13, it might be that the database upgrade is still in process in the background and the UI is waiting for this to complete. Do you still see this issue?

**Comment by donpatrice** [comment]
I updated to 0.2.13.203915 around three hours before and still have this issue. Also before updating I had this issue. I don't know what happend when it stopped showing me the currently broadcasted ID. Thanks again!

**Comment by donpatrice** [comment]
Also the data only has a size of 432 KB. I don't know if that is normal after two days.

**Comment by mar-v-in** [comment]
If no currently broadcasted ID is listed, you are most likely not broadcasting. Maybe you accidentally disabled bluetooth?
Only scanning and matching have any significant impact on the database size. For scanning, you can easily see if it's working in the "Collected IDs" section.

**Comment by donpatrice** [comment]
Ok, scanning seems to work, because the number of collected IDs growths.
Bluethoot is enabled, I double checked. Also I reactivated exposure notifications, but still no currently broadcasted ID.
I also tried to reboot, without success.

**Comment by mar-v-in** [comment]
What device are you using? Some devices are not fully BLE compliant and thus do not support broadcasting IDs. I know that this issue affects the Fairphone 2 or at least some version of it.

**Comment by donpatrice** [comment]
Yes I use a Fairphone 2. The strange thing is that I saw this currently broadcasted ID before. Then suddenly it stopped showing.

**Comment by donpatrice** [comment]
Could reinstalling microg be an option? Loosing two days of ID, could be acceptable. ;)

**Comment by donpatrice** [comment]
For matching I also need my IDs, so I am wondering if my ID is only not broadcasted or not generated at all.

**Comment by mar-v-in** [comment]
Early test versions with EN support generated new broadcasting keys without any need. These keys would be used to generate and display IDs for the rest of the day, so this might be why it showed up for you. Since a016feba35c05ce482b67e01b51b93ef1d39ef70 we only generate keys when they're used for broadcasting IDs.

You don't need to generate or broadcast IDs for matching or exposure risk computation, so you can still use the system to get informed about exposures, but you won't be able notify others in case of a positive diagnosis.

**Comment by donpatrice** [comment]
Thanks for the explanation!
