### ISSUE TITLE
Corona Warn-App 1.5.0.47: "Google Play-Dienste aktualisieren"

### ISSUE THREAD

**Issue by hubbty** [microg/android_packages_apps_GmsCore#1235]
Die Corona Warn-App in der Version 1.5.0.47 ist mit microG Services Core 0.2.12.203315 nicht mehr zufrieden. Beim ersten Start der App kommt die Meldung:
```
Google Play-Dienste aktualisieren
Corona-Warn wird nur ausgeführt, wenn du die Google Play-Dienste aktualisierst
```

Ich betone übrigens, dass ich niemanden im RKI, bei SAP oder der Telekom persönlich kenne. Woher die sich die Freiheit nehmen, mich zu duzen, ist mir schleierhaft.  Mir kommt bei diesen dreisten Vertraulichkeiten jedenfalls immer die Assoziation an die Nazis, die auch schon geschrieben haben "Kaufe nicht bei Juden".

![Screenshot_20201019-192945_Corona-Warn](https://user-images.githubusercontent.com/59095639/96493254-0b815200-1245-11eb-917e-8813577d9739.png)

**Comment by chris42** [comment]
#1232 - Please search before posting an issue
