### ISSUE TITLE
Corona-Warn won't run unless you update Google Play services

### ISSUE THREAD

**Issue by jnnkB** [microg/android_packages_apps_GmsCore#1236]
Today I unfortunately updated the Corona-Warn App. Since than I get this "Corona-Warn won't run unless you update Google Play services" Notification. When I open the App I get the following alert:

![alert](https://user-images.githubusercontent.com/29376715/96494799-1fc64e80-1247-11eb-835e-36b695d82747.jpeg)

Thanks for your awesome work!

**Comment by chris42** [comment]
#1232 and #1235 - Please search before posting an issue

**Comment by jnnkB** [comment]
I'm sorry. I just filtered with  label:"🦠 Exposure Notifications"
