### ISSUE TITLE
Why should I use microg?

### ISSUE THREAD

**Issue by castor-troy** [microg/android_packages_apps_GmsCore#124]
I don't know where to post this, but I have few questions about Microg project and the location stuff that comes along with it.

I am using CyanogenMod Marshmallow with no gapps. I don't use a google account. Honestly, there are not many apps that I use which require google play. So, Im guessing microg is not required for me. But I am trying to understand what advantages does one get using it instead of Google play services.

1. Does microg connect to google servers?

2. If I use mozilla or apple backend location stuff with microg, does google know about my location? I mostly use running based apps like runtastic which might give maps if i use microg location stuff.

3. What are the advantages that I get in using microg. 

Please note that I dont use google account on my Android. Thanks.

**Comment by julienschmidt** [comment]
> Does microg connect to google servers?

Only if you activate Google Could Messaging (GCM), Google's push service. All data is anonymized (device id etc)

> If I use mozilla or apple backend location stuff with microg, does google know about my location? I mostly use running based apps like runtastic which might give maps if i use microg location stuff.

Other apps might leak that info, but mircog does not. You can also use local backends (e.g. https://f-droid.org/repository/browse/?fdid=org.fitchfamily.android.gsmlocation ) which don't require any internet connections at all

> What are the advantages that I get in using microg.

Privacy, your battery might last longer and offline location service

**Comment by castor-troy** [comment]
> Google Could Messaging (GCM), Google's push service
Could you tell me a bit about these. Are these part of microg or the third-party apps? And are you saying that even if I use those, the data is anonymized?

**Comment by herrdeh** [comment]
And I found that google services slow down my phone awfully. MicroG doesn't.

**Comment by Catfriend1** [comment]
It does not autoupdate silently without users consent.

**Comment by mar-v-in** [comment]
Question answered, closing here.

**Comment by art1fa** [comment]
I am currently updating the wiki to make also these kind of questions more clear ;)

**Comment by mar-v-in** [comment]
Great, thank you!
