### ISSUE TITLE
NHS England Exposure Notifications not registering

### ISSUE THREAD

**Issue by Cadair** [microg/android_packages_apps_GmsCore#1246]
I am running the latest microG from fdroid on cRdroid on a oneplus 5. When I install the NHS england contact tracing app it doesn't give me a popup asking to enable exposure notifications or anything, it just immediately says my device is not supported.

I looked in logcat to see if anything obvious was showing up and I couldn't see anything. This might be the same as #1242 but I can't be sure.

**Comment by mar-v-in** [comment]
Are you using latest microG version 0.2.13?
Did you check if everything is fine according to microG Self-Check?

**Comment by Cadair** [comment]
Self-check was missing the fake store and that fixed it. Sorry for the noise.
