### ISSUE TITLE
EN in Nougat: no Currently broadcasted ID

### ISSUE THREAD

**Issue by kurt-by** [microg/android_packages_apps_GmsCore#1249]
**Describe the bug**
One plus one "bacon" with /e/ nougat and CoronaWarnApp no ID displayed (no ID sent?)

Same device Lineage.microg.org android 10 works as expected.

**To Reproduce**
1. Go to microg settings Exposure Notification
2. 
3. 

**Expected behavior**
ID shown

**Screenshots**

**System**
Android Version: 7
Custom ROM: /e/

**Additional context**
GMS core updated with nanodroid microG to 0.2.13

**Comment by Konradrundfunk** [comment]
I got an error when using the Corona Warn App but the implementation in Micro G is working but the Corona Warn App is not able to calculate the current risk. 

System:
Android 9
Corona Warn App 1.5
Micro G 0.2.12.203315

**Comment by Tentos** [comment]
I can confirm this behaviour on my Fairphone 2 (ROM: Android 7 AOSP).

**Comment by ArchangeGabriel** [comment]
@Tentos Fairphone 2 cannot broadcast (it does not support BLE).

@kurt-by Apparently that’s the same for the OnePlus One, I’ve just checked the spec and it does not seem to support BLE either.

**Comment by Tentos** [comment]
@ArchangeGabriel You are correct; to be precise, the FP2 supports BLE, but not the Peripheral Mode, which is needed to send IDs. However, it can still receive IDs. [There is a corresponding thread in German](https://forum.fairphone.com/t/corona-warn-app-zum-herunterladen/62003/76) in the FP forum.

Thank you for pointing out the problem!

**Comment by kurt-by** [comment]
This is no microG bug. Confirmed with beacon scope app. GalaxyS5 klte with lineage4microG 17.1 and CWA is sending beacons. LineageOS 14.1 with GApps and CWA is not sending beacons. No error messages.

**Comment by ArchangeGabriel** [comment]
@Tentos OK, then indeed it is available for LineageOS, I asked a friend to check and here is the screenshot in case you’re interested:
![fp2](https://user-images.githubusercontent.com/490531/97902214-afdfba00-1d56-11eb-9172-7b88adfe51e6.png)
