### ISSUE TITLE
[de.rki.coronawarnapp] UnsupportedApiCallException nearby_exposure_notification_get_version

### ISSUE THREAD

**Issue by sebastianwagner** [microg/android_packages_apps_GmsCore#1250]
**Affected app**
Name: Corona-Warn
Package id: `de.rki.coronawarnapp.48`

**Describe the bug**
Exposure Notification `UnsupportedApiCallException`: `nearby_exposure_notification_get_version`

Error Dialog states "Missing feature" (screenshot [1])

error only happened once, different, repeated errors afterwards:
app is still collecting ids but could not update due to mentioned different error.
(see 4th screenshot [4])

since de.rki.coronawarn `1.5.0.48`
seems to try to access unimplemented method
didn't happen with earlier `1.3.1.38` version

**To Reproduce**
1. Install coronawarn app old build 38, use it(works like a charm)
2. update to version build 48
3. on first launch error occurs, once

**Expected behavior**
Exposure API mocks expected methods calls :)

**Screenshots**
[1] ![error_dialog_20201023-URSACHE9002_Corona-Warn_crop,scale](https://user-images.githubusercontent.com/1701745/97115607-e040ac00-16f7-11eb-9edf-b0200f56f93b.png)

[2] ![traceback_20201023-get_version_Corona-Warn_crop,scale](https://user-images.githubusercontent.com/1701745/97115626-fbabb700-16f7-11eb-87a4-b0df9bd8e318.png)

[3] 
![selfcheck_20201017_microG_Services_Core_croped,scaled](https://user-images.githubusercontent.com/1701745/97115650-12eaa480-16f8-11eb-821b-d5ba6fa83139.png)

[4] 
![cwa_repeated_crash_20201023_Corona-Warn_crop,scaled](https://user-images.githubusercontent.com/1701745/97115653-18e08580-16f8-11eb-9a8a-d803d0ee3de4.png)

**System**
Android Version: 10 QQ3A.200805.001
Custom ROM: microG LineageOS build for lake 17.1 `eng.root.20201015.063715` dev-keys

**microG**
microG Core version: `0.1.2.12.203315`
microG Self-Check results: All ticked, except System battery optimization
(see 3rd screenshot [3])

**Comment by kurt-by** [comment]
Update GMS core to 0.2.13

**Comment by sebastianwagner** [comment]
I updated the preinstalled _UnifiedNlp (no GAPPS)_ via FDroid to the next Version available: `0.2.13.203915` rendering _microG Services Core_ to that version as well.
Corona-Warn app now seems to work without new exceptions.
Thank you for pointing this out.
