### ISSUE TITLE
Corona Warn App doesn't work after update to 1.6

### ISSUE THREAD

**Issue by meisteredermeistereder-the-second** [microg/android_packages_apps_GmsCore#1267]
Affected App:
Corona Warn App

After I updated the German Corona Warn App to 1.6.0.1060008 it doesn't work anymore. My microG version is 0.2.13 from f-droid.
I get the following error:
![Screenshot_20201112-075301_Corona-Warn](https://user-images.githubusercontent.com/36160804/98909193-c78b1100-24c1-11eb-9ff4-bdb1f29a74f2.png)

![Screenshot_20201112-075316_Corona-Warn](https://user-images.githubusercontent.com/36160804/98909160-bc37e580-24c1-11eb-8849-139a9fff3486.png)

![Screenshot_20201112-075324_Corona-Warn](https://user-images.githubusercontent.com/36160804/98909121-acb89c80-24c1-11eb-93c0-f89afa437011.png)

**Comment by meisteredermeistereder-the-second** [comment]
The original error message I get in the app:

![Screenshot_20201112-083810_Corona-Warn](https://user-images.githubusercontent.com/36160804/98909722-7cbdc900-24c2-11eb-8ae5-0aca61d98cf5.png)

**Comment by lbort** [comment]
Is this due to the same reason the swiss covid app stopped to work recently? There is a new "exposure window" API in the google framework, that is not ported yet to microG, and the swiss app started using that on 28.10.2020. See #1258

**Comment by meisteredermeistereder-the-second** [comment]
It turned out that an update of my ROM (a problem with signature spoofing) was the cause for the problem.
So I close this bug report.
