### ISSUE TITLE
https cert not working with f-droid repo

### ISSUE THREAD

**Issue by zoff99** [microg/android_packages_apps_GmsCore#128]
the repo "https://microg.org/fdroid/repo/" does not work with f-droid client 0.97 (on lollipop)
i get this error now and can't update anymore

> 05-08 09:45:48.434: E/UpdateService(3566): Caused by: java.io.IOException: A problem occurred while establishing an SSL connection. If this problem persists, AND you have a very old device, you could try using http instead of https for the repo URL.javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:322)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.okhttp.Connection.connect(Connection.java:155)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:199)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
05-08 09:45:48.434: E/UpdateService(3566): 	at org.fdroid.fdroid.net.HttpDownloader.getInputStream(HttpDownloader.java:60)
05-08 09:45:48.434: E/UpdateService(3566): 	at org.fdroid.fdroid.net.Downloader.downloadFromStream(Downloader.java:106)
05-08 09:45:48.434: E/UpdateService(3566): 	at org.fdroid.fdroid.net.HttpDownloader.doDownload(HttpDownloader.java:120)
05-08 09:45:48.434: E/UpdateService(3566): 	at org.fdroid.fdroid.net.HttpDownloader.download(HttpDownloader.java:78)
05-08 09:45:48.434: E/UpdateService(3566): 	at org.fdroid.fdroid.net.Downloader.downloadUninterrupted(Downloader.java:94)
05-08 09:45:48.434: E/UpdateService(3566): 	at org.fdroid.fdroid.RepoUpdater.downloadIndex(RepoUpdater.java:100)
05-08 09:45:48.434: E/UpdateService(3566): 	at org.fdroid.fdroid.RepoUpdater.update(RepoUpdater.java:128)
05-08 09:45:48.434: E/UpdateService(3566): 	at org.fdroid.fdroid.UpdateService.onHandleIntent(UpdateService.java:387)
05-08 09:45:48.434: E/UpdateService(3566): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
05-08 09:45:48.434: E/UpdateService(3566): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-08 09:45:48.434: E/UpdateService(3566): 	at android.os.Looper.loop(Looper.java:135)
05-08 09:45:48.434: E/UpdateService(3566): 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-08 09:45:48.434: E/UpdateService(3566): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:114)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:550)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
05-08 09:45:48.434: E/UpdateService(3566): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
05-08 09:45:48.434: E/UpdateService(3566): 	... 21 more
05-08 09:45:48.434: E/UpdateService(3566): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-08 09:45:48.434: E/UpdateService(3566): 	... 27 more
05-08 09:45:48.434: E/UpdateService(3566): 	at org.fdroid.fdroid.net.HttpDownloader.download(HttpDownloader.java:81)
05-08 09:45:48.434: E/UpdateService(3566): 	at org.fdroid.fdroid.net.Downloader.downloadUninterrupted(Downloader.java:94)
05-08 09:45:48.434: E/UpdateService(3566): 	at org.fdroid.fdroid.RepoUpdater.downloadIndex(RepoUpdater.java:100)
05-08 09:45:48.434: E/UpdateService(3566): 	... 6 more

without "https" (normal http) i get this error:

> 05-08 09:49:21.059: E/UpdateService(3566): Error updating repository http://microg.org/fdroid/repo
05-08 09:49:21.059: E/UpdateService(3566): org.fdroid.fdroid.RepoUpdater$UpdateException: Error parsing index for repo http://microg.org/fdroid/repo
05-08 09:49:21.059: E/UpdateService(3566): 	at org.fdroid.fdroid.RepoUpdater.processDownloadedFile(RepoUpdater.java:183)
05-08 09:49:21.059: E/UpdateService(3566): 	at org.fdroid.fdroid.RepoUpdater.update(RepoUpdater.java:134)
05-08 09:49:21.059: E/UpdateService(3566): 	at org.fdroid.fdroid.UpdateService.onHandleIntent(UpdateService.java:387)
05-08 09:49:21.059: E/UpdateService(3566): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
05-08 09:49:21.059: E/UpdateService(3566): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-08 09:49:21.059: E/UpdateService(3566): 	at android.os.Looper.loop(Looper.java:135)
05-08 09:49:21.059: E/UpdateService(3566): 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-08 09:49:21.059: E/UpdateService(3566): Caused by: java.util.zip.ZipException: Not a zip archive
05-08 09:49:21.059: E/UpdateService(3566): 	at java.util.zip.ZipFile.readCentralDir(ZipFile.java:385)
05-08 09:49:21.059: E/UpdateService(3566): 	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
05-08 09:49:21.059: E/UpdateService(3566): 	at java.util.jar.JarFile.<init>(JarFile.java:199)
05-08 09:49:21.059: E/UpdateService(3566): 	at java.util.jar.JarFile.<init>(JarFile.java:182)
05-08 09:49:21.059: E/UpdateService(3566): 	at org.fdroid.fdroid.RepoUpdater.processDownloadedFile(RepoUpdater.java:151)
05-08 09:49:21.059: E/UpdateService(3566): 	... 6 more

is there a solution??

**Comment by Catfriend1** [comment]
Do you use a transparent proxy ?
Are your root certificates ok ? (should be by default)
Did you try updating to F-Droid 0.99 ?

**Comment by zoff99** [comment]
i dont use anything. its google gcm --> google servers.
why do you ask?
something changed in the code of microg software. i would like to find out where and when

**Comment by zoff99** [comment]
i can't
starting with f-droid 0.98 on they totally broke everything.
updating takes over 13 minutes on my highend phone (before on same phone 30 seconds)

also my broswer gives the same problem with the certificate

**Comment by n76** [comment]
My laptop browser shows a valid certificate (expiration 19Sept2016 issued by COMODO) for f-droid.org. I wonder why your browser is showing that as a problem. FWIW, my F-Droid has updated itself to v0.100-alpha6 from 3May2016 and the last GmsCore it installed was 0.2.2-5-g6bf59b2 from 18Apr2016.

**Comment by zoff99** [comment]
there is no issue with f-droid.org but with microg.org
i could update a few days ago, just now the cert error is happening

**Comment by n76** [comment]
My laptop browser shows a valid certificate for that too: Issued by "Let's Encrypt Authority" expires 4 August 2016.

**Comment by zoff99** [comment]
ok its works now. without me chaning anything! :-)
so i guess it must have been the activation date of the certificate
