### ISSUE TITLE
unable to Connect to gcm config Start?

### ISSUE THREAD

**Issue by Catfriend1** [microg/android_packages_apps_GmsCore#130]
05-11 19:44:19.840 E/GmsClient(5818): unable to connect to service: com.google.android.gms.config.START

i am getting this error but do not have any hinter what is causing it. maybe its my New Installation of Google keyboard App?!

**Comment by Catfriend1** [comment]
I dont have any problems at the moment. Can be closed.

**Comment by ghost** [comment]
please delete issue
