### ISSUE TITLE
Problem installing GMScore from f-droid

### ISSUE THREAD

**Issue by Catfriend1** [microg/android_packages_apps_GmsCore#131]
I cant manage to Install the fdroid Version od gmscore. i have currently gmscore build by Sww13 Nr. 5 installed and need to upgrade to repo build Nr. 9.
i did also try to uninstall first but no luck.
unknown error in cm 13 with xposed and sigfake setup ok.
Trier pm Install and got error invalid_Uri in APK install.
any help on this?

**Comment by n76** [comment]
Is the old version by Sww13 installed in /system/app (I've seen some ZIP install files that put it there). If so you will probably have to remount /system as rw and then manually remove the old APK either using a root file explorer or the shell before you can install any version from the F-Droid repository.

**Comment by Catfriend1** [comment]
Checked with Root Explorer. it is only installed in data/App. when uninstalled from there , icon in launcher disappears.

**Comment by Catfriend1** [comment]
http://stackoverflow.com/questions/13617440/installation-failed-due-to-invalid-uri-installs-only-in-debug-mode

i tried this:
- setting permissions on data/local does not help.
- renaming APK file - no Solution

do microg fdroid and sww release share the same Signature so upgrading without uninstall is possible?

**Comment by n76** [comment]
Sounds like they may have different signing keys. . . Fortunately there are really only a couple of settings in GmsCore itself so removing it then doing a fresh install from F-Droid is not too painful.

The settings in any plug-in backend are saved in the data area for the backend and are not affected by replacing GmsCore itself. OTOH, if that ZIP installed any backends, those probably have the same issue about not being able to be updated through F-Droid.

**Comment by mar-v-in** [comment]
Check if the app appears in Settings->Apps at the bottom-most as "uninstalled". This can happen if the system is a multi-user system (not necessarily requiring multiple users). You can open app details from this screen and from overflow menu do "uninstall for all users" or sth like that.

**Comment by Catfriend1** [comment]
I noticed when gmscore got uninstalled that after reinstalling sww13 s build i had to reenter my Google account. after that all apps using c2dm crashed suddenly after Boot screen vor Main menu. made then titanium backup of the faulty ones, uninstalled each, reinstalled through titanium and they worked again. so from the work factor its ok.
my cm Rom does not support multi user on Samsung i9100. i dont See what Marvin described. the App is completely gone after uninstall of gms Core. 
is it a Problem when i uninstall only sww gmscore and keep gsfcore from sww ? do i need to use both from either fdroid or sww?

**Comment by Catfriend1** [comment]
by the way i checked my download folder. each gmscore release got me 3 files from sww. debug release and unaligned apk. i can only Install the gmscore-debug.apk version of him without error. can you provide a debug build in fdroid?

**Comment by n76** [comment]
Sounds like installing the build from sww is more trouble than it is worth. Any reason you aren't just installing them from the project's official repository via F-Droid to begin with?

**Comment by Catfriend1** [comment]
I'd like to do so but it did never work out because of the Uri invalid error when trying to Install the apk. even copying it to data App so it should be installed on reboot with apps being optimized did not work.  i have no leftovers of the old Installation thats crazy... !? should xposed be turned on with sig fake or off during Install?

**Comment by Catfriend1** [comment]
i habe now removed all sww stuff wiped dalvik, Tried but failed , Turned SIG fake off, reboot, retried.
i can Install gsfproxy from fdroid, but gmscore still throws error

05-15 10:21:48.361 D/InstallAppProgress(7503): Installation error code: -7

**Comment by Catfriend1** [comment]
I found a solution:

First, I uninstalled GMS Core Debug Build by SWW13 regularly and left XPosed FakeSig turned on as it was before.
Then I ran the following commands:

> This detects most leftovers that do not uninstall cleanly:
find / | grep -Fi "com.google.android.gms" 2> /dev/null

rm -rf "/data/app/com.google.android.gms-2"
rm -rf "/data/app-lib/com.google.android.gms-1"
rm -rf "/storage/<EXTSDCARD_UUID>/Android/data/com.google.android.gms"
rm -f "/data/system/theme/icons/com.google.android.gms_7f030000_240.png"
rm -f "/data/system/theme/icons/com.google.android.gms_7f030001_240.png"
pm uninstall com.google.android.gms
adb install com.google.android.gms-0.2.2-9_8492250.apk

**Comment by Catfriend1** [comment]
Ohhh shit. Did a reboot because microg gms self check said, it is needed for the system to register with unifiednlp provider. --> got a bootloop.

What now?

**Comment by Catfriend1** [comment]
hmm redid everything from last backup now reboot is fine.

**Comment by ghost** [comment]
please delete issue
