### ISSUE TITLE
can't get spoofing to work

### ISSUE THREAD

**Issue by uuafj** [microg/android_packages_apps_GmsCore#132]
I've tried to enable signature spoofing on CyanogenMod using Needle.

Running patch.py on Linux (Debian) using "python3 patch.py" returned the following:

*** Device detected! proceeding...
*** Working dir: /tmp/tmpi_qbrdss
*** Rooting adbd...
remount succeeded
*** Pulling framework from device...
220 KB/s (309 bytes in 0.001s)
*** Disassembling framework...
I: Using Apktool 2.0.2 on framework.jar
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
*** Done. Now this won't hurt a bit...
Traceback (most recent call last):
File "patch.py", line 47, in
f = open(to_patch, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'framework.jar.out/smali/android/content/pm/PackageParser.smali'

What am I doing wrong? Am I missing a package perhaps?

**Comment by julienschmidt** [comment]
Wrong repository. All issues related to 'Needle' belong here: https://github.com/moosd/Needle/issues

**Comment by ale5000-git** [comment]
@uuafj: Just in case you haven't already found the solution, my patcher shouldn't have this problem => https://github.com/ale5000-git/tingle
