### ISSUE TITLE
Cant open Play Store 6.5.8-d-all

### ISSUE THREAD

**Issue by Catfriend1** [microg/android_packages_apps_GmsCore#134]
going back to 6.4.12-c-all which worked last.

since the New Version play store stays grey window when i try to open it.

anyone having this issue too?

**Comment by Catfriend1** [comment]
05-17 18:04:44.079 E/GMPM    (25743): GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.

05-17 18:02:34.001 E/GCMRegistrar(24986): internal error: retry receiver class not set yet

**Comment by Catfriend1** [comment]
Restoring old play store helped. its opening.
Could microg as a prerequisite of play store aid in blocking it from updating ?

**Comment by mar-v-in** [comment]
1. No, microG can not prohibit Play Store from updating.
2. The cited error message should not cause the described problem.
3. Did you try (at latest version): clear play store data, dial *#*#CHECKIN#*#*, open play store.

**Comment by ibleedbinari** [comment]
The Play Store began working for me again just after clearing data and no downgrade

**Comment by Catfriend1** [comment]
ok ill.update it and then freeze its autoupdate. dont need that every day Any other Google shit breaks itself.

Here is some tasker Boot script:

<TaskerData sr="" dvi="1" tv="4.8u4m">
	<Task sr="task101">
		<cdate>1463636452463</cdate>
		<edate>1463639399284</edate>
		<id>101</id>
		<nme>Setup-Services</nme>
		<pri>100</pri>
		<Action sr="act1" ve="7">
			<code>123</code>
			<se>false</se>
			<Str sr="arg0" ve="3">pm disable com.android.vending/com.google.android.finsky.services.DailyHygiene</Str>
			<Int sr="arg1" val="0"/>
			<Int sr="arg2" val="1"/>
			<Str sr="arg3" ve="3"/>
			<Str sr="arg4" ve="3"/>
			<Str sr="arg5" ve="3"/>
		</Action>
		<Action sr="act2" ve="7">
			<code>123</code>
			<se>false</se>
			<Str sr="arg0" ve="3">pm disable com.android.vending/com.google.android.finsky.autoupdate.ReschedulerUsingAlarmManager\$CheckWifiAndAutoUpdate</Str>
			<Int sr="arg1" val="0"/>
			<Int sr="arg2" val="1"/>
			<Str sr="arg3" ve="3"/>
			<Str sr="arg4" ve="3"/>
			<Str sr="arg5" ve="3"/>
		</Action>
		<Action sr="act3" ve="7">
			<code>123</code>
			<se>false</se>
			<Str sr="arg0" ve="3">pm disable com.android.vending/com.google.android.finsky.autoupdate.ReschedulerUsingBroadcast\$AutoUpdateRecheckForBroadcast</Str>
			<Int sr="arg1" val="0"/>
			<Int sr="arg2" val="1"/>
			<Str sr="arg3" ve="3"/>
			<Str sr="arg4" ve="3"/>
			<Str sr="arg5" ve="3"/>
		</Action>
		<Action sr="act4" ve="7">
			<code>123</code>
			<se>false</se>
			<Str sr="arg0" ve="3">pm disable com.android.vending/com.google.android.finsky.autoupdate.ReschedulerUsingJobScheduler\$CheckPreconditionsAndAutoUpdateJobService</Str>
			<Int sr="arg1" val="0"/>
			<Int sr="arg2" val="1"/>
			<Str sr="arg3" ve="3"/>
			<Str sr="arg4" ve="3"/>
			<Str sr="arg5" ve="3"/>
		</Action>
		<Img sr="icn" ve="2">
			<nme>hd_aaa_ext_android</nme>
		</Img>
	</Task>
</TaskerData>

**Comment by ghost** [comment]
please delete issue
