### ISSUE TITLE
Request: Update Play Services Version to Latest

### ISSUE THREAD

**Issue by JERW86** [microg/android_packages_apps_GmsCore#138]
@mar-v-in will you please update play services version to the latest? I get this message when trying to use BubbleUPnP.  Thank you.

![update play services to 9 0 1](https://cloud.githubusercontent.com/assets/16406776/15693679/30305de6-2765-11e6-8d73-7e9a83fb0f5a.png)

**Comment by Kraphut** [comment]
Hi, Play Services effectively seems to be outdated.
I use S3 LTE (i9305) and OS CM 11 patched with Needle and mapsv1. GmsCore.apk, GsfProxy.apk FakeStore.apk, MozillaNlp.apk and NominatimNlp.apk was installed.

This is from logcat :
`W/GooglePlayServicesUtil( 8760): Google Play services out of date. Require 9080000 but found 8492252`

**Comment by Catfriend1** [comment]
I am not having any troube but must tell that i did not update bubble to 2.7+.
Are fake sigs right under self check?

**Comment by mar-v-in** [comment]
Should be fixed in 0.2.3-1+

**Comment by uberspot** [comment]
I've started getting these sort of notificatioms as well recently. Does the version need updating again?

**Comment by ale5000-git** [comment]
@uberspot: Probably it is just that you haven't the latest [version](https://microg.org/download.html) (currently 0.2.4-**30**, note the 30).
