### ISSUE TITLE
android-matrix-console / vector-android loosing connection to GCM

### ISSUE THREAD

**Issue by DatGizmo** [microg/android_packages_apps_GmsCore#139]
Setup:

Android 5.1 (CM12.1)
GSMCore 0.2.3.

The vector app (which is based on the matrix-console), seems to loose the connection to the GCM after it has been woken up by a receiving message.

Steps:
1. Vector app closed and EventStreamingService stopped.
2. Receiving notification in matrix, which wakes the vector app.
3. The app starts the EventStreamingService, which then takes over to check for new messages.

I also reported the issue at the vector-android repo (https://github.com/vector-im/vector-android/issues/167).

If I can provide you with some more detailed debug info. I'll gladly do so, but I might need some guidance, because I've not yet done this.

**Comment by mar-v-in** [comment]
What is EventStreamingService? I don't see it vector-android source code and it's definitely not present in GmsCore.

**Comment by DatGizmo** [comment]
It's the service started by the vector app.
Afaik the vector app is based on the https://github.com/matrix-org/matrix-android-console.

And I think you are looking for this?
https://github.com/matrix-org/matrix-android-console/blob/fe72c0bd4bcee9845490b7e0bc26d2a512e62105/console/src/main/java/org/matrix/console/services/EventStreamService.java

**Comment by mar-v-in** [comment]
according to source code, vector app should be based on matrix-android-sdk, not matrix-android-console (which itself is based on matrix-android-sdk as well).

**Comment by DatGizmo** [comment]
Sorry mixed it up.
You're right, vector and matrix-console are based on the matrix-android-sdk.

**Comment by DatGizmo** [comment]
The issue got fixed by the vector-android guys. 
So this one can be closed.
