### ISSUE TITLE
Notification "microG Services Framework Proxy" has stopped."

### ISSUE THREAD

**Issue by 74cmonty** [microg/android_packages_apps_GmsCore#142]
Hello!

I get regularely a notification window with this message:
"microG Services Framework Proxy" has stopped."

Question:
How can I start troubleshooting this notification by means of identifying the trigger of it?

THX
![screenshot_2016-06-12-10-49-22](https://cloud.githubusercontent.com/assets/12523591/16005751/376ee74a-3169-11e6-822f-e58a926844d8.png)

**Comment by Catfriend1** [comment]
Please use the catlog App - filter errors - open App after crash immediately and post the last 5 pages.

**Comment by 74cmonty** [comment]
Hello!

I have started Catlog w/o any filters but collected the attached file.
In this file I have identified this info:
06-15 01:51:30.099 W/ActivityManager(  929): Scheduling restart of crashed service com.google.android.gsf/org.microg.gms.gcm.PushRegisterProxy in 1000ms

However, I cannot identify what is causing this.

Could you please assist?

THX
[2016-06-15-00-06-28.txt](https://github.com/microg/android_packages_apps_GmsCore/files/315602/2016-06-15-00-06-28.txt)

**Comment by 74cmonty** [comment]
Update:
I think I've identified the relevant lines in the log documenting the error:
`06-15 01:51:28.236 W/ActivityManager(  929): Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=9789, uid=10062 requires com.google.android.c2dm.permission.RECEIVE
06-15 01:51:28.237 E/AndroidRuntime( 9789): FATAL EXCEPTION: IntentService[GsfGcmRegisterProxy]
06-15 01:51:28.237 E/AndroidRuntime( 9789): Process: com.google.android.gsf, PID: 9789
06-15 01:51:28.237 E/AndroidRuntime( 9789): java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
06-15 01:51:28.237 E/AndroidRuntime( 9789): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1747)
06-15 01:51:28.237 E/AndroidRuntime( 9789): 	at android.app.ContextImpl.startService(ContextImpl.java:1724)
06-15 01:51:28.237 E/AndroidRuntime( 9789): 	at android.content.ContextWrapper.startService(ContextWrapper.java:522)
06-15 01:51:28.237 E/AndroidRuntime( 9789): 	at org.microg.gms.gcm.PushRegisterProxy.onHandleIntent(PushRegisterProxy.java:32)
06-15 01:51:28.237 E/AndroidRuntime( 9789): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
06-15 01:51:28.237 E/AndroidRuntime( 9789): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-15 01:51:28.237 E/AndroidRuntime( 9789): 	at android.os.Looper.loop(Looper.java:135)
06-15 01:51:28.237 E/AndroidRuntime( 9789): 	at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by mar-v-in** [comment]
Try if reinstalling microg Services Framework Proxy fixes it.

**Comment by 74cmonty** [comment]
I have executed the following steps:
1. Remove package "microG Services Framework Proxy" v0.1.0
2. Reboot
3. Installation of "microG Services Framework Proxy" from F-Droid
4. Validating that all restrictions for "microG Services Framework Proxy" in XPrivacy are off
5. Validating "migcroG Settings" - Self-Check -> no errors reported

As for now the error message is not displayed anymore.
I'll keep this issue updated when observing the device for next 48h or close the issue accordingly.

**Comment by Catfriend1** [comment]
Hat this some time before. The order of installing components should be:
Microg gms (provides c2dm service and adds permission to system)
Microg gsf proxy (Docks to the provided c2dm Perm)
Play store (Docks to microg gms and provides licensing services and Permission)
Apps requiring Google lvl must be installed after play store. Or Perm BIND will not exist ... Crash!
If you uninstall one part hosting permission , i did habe to reinstall dependent parts in order few weeks ago. Also appplies to Googles apps.

**Comment by jeekajoo** [comment]
It looks like uninstalling/reinstalling 'framework proxy' did the trick for me. Thanks.
