### ISSUE TITLE
Core Messaging enhancement

### ISSUE THREAD

**Issue by n76** [microg/android_packages_apps_GmsCore#145]
There does not seem to be a way to find which apps are using core messaging nor to use a permission like facility to selectively deny core messaging to specific apps.

For example, I need/want core messaging enabled so that Signal will work. But I don't want to allow other apps to use it.

Could a display of which apps are registered for GCM with enable/disable check boxes be implemented?

**Comment by zoff99** [comment]
wow +1 for that feature

**Comment by JERW86** [comment]
+1

**Comment by Catfriend1** [comment]
+1

**Comment by mar-v-in** [comment]
Will be implemented together with #117

**Comment by ale5000-git** [comment]
Shouldn't this be closed?

**Comment by mar-v-in** [comment]
We don't have this feature all done yet (you can not block apps from registering for push notifications), but I have it locally and will push it soon
