### ISSUE TITLE
Gmail with GmsCore ?

### ISSUE THREAD

**Issue by breversa** [microg/android_packages_apps_GmsCore#146]
Has anyone managed to make Gmail work with GmsCore ?

I can download and install the app ; upon launch, I'm asked about my email and password, but then get stuck on a waiting screen, before being sent back to the email input screen.

**Comment by georgedorn** [comment]
Similar problem.  Here's logcat from when it gives up (it stalls at 'Your device is contacting Google to save information to your account' but the title of the card changes to 'Sorry').  There's some other noise in this log but I'm not entirely sure what's related and what isn't.

> 07-13 23:32:31.252  1696  1732 I Gmail   : getAccountsCursor
07-13 23:32:31.263   679   687 W CursorWrapperInner: Cursor finalized without prior close()
07-13 23:32:31.263  1283  1283 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
07-13 23:32:31.278   679  1352 I Telecom : PhoneAccountRegistrar: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, [e0184adedf913b076626646d3f52c3b49c39ad6d], UserHandle{0}(addr: tel:********** -> tel:)(icon: Icon(typ=BITMAP size=29x36) -> Icon(typ=BITMAP size=29x36))(subAddr: tel:********** -> tel:)]
07-13 23:32:31.282  1689  1689 W System  : ClassLoader referenced unknown path: /data/app/org.fdroid.fdroid-1/lib/arm
07-13 23:32:31.298   679  1352 I Telecom : : Sending phone-account registered intent as user
07-13 23:32:31.303  1283  1283 I Telephony: AccountEntry: Registered phoneAccount: [[ ] PhoneAccount: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, [e0184adedf913b076626646d3f52c3b49c39ad6d], UserHandle{0} Capabilities: 54 Schemes: tel voicemail ] with handle: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, [e0184adedf913b076626646d3f52c3b49c39ad6d], UserHandle{0}
07-13 23:32:31.303  1283  1283 I Telephony: PstnIncomingCallNotifier: Registering: Handler (com.android.internal.telephony.gsm.GSMPhone) {3b68ded}
07-13 23:32:31.314  1696  1733 D ActivityThread: Loading provider com.google.android.gmail.provider;com.android.mail.notifier;com.google.android.gm.email.provider;com.google.android.gm.email.notifier: com.android.email.provider.EmailProvider
07-13 23:32:31.346   841   841 D PhoneStatusBar: disable: < EXPAND ICONS alerts SYSTEM_INFO BACK HOME RECENT clock SEARCH quick_settings >
07-13 23:32:31.379   679  1323 W Telecom : : No account found for the calling user
07-13 23:32:31.396  1283  1283 V ConfigResourceUtil: resourceName = config_spn_display_control resourceId = 2130837514resourceValue = false
07-13 23:32:31.449   679   891 V KeyguardServiceDelegate: **** SHOWN CALLED ****
07-13 23:32:31.458   679   708 D GpsLocationProvider: received SIM change, new known MCC/MNC: []
07-13 23:32:31.485  1283  1283 I Telephony: PstnIncomingCallNotifier: Unregistering: Handler (com.android.internal.telephony.gsm.GSMPhone) {3b68ded}
07-13 23:32:31.492  1283  1283 W Telephony: TelecomAccountRegistry: Failed to get primary stack id
07-13 23:32:31.495   679  1236 V KeyguardServiceDelegate: **** SHOWN CALLED ****
07-13 23:32:31.503  1283  1283 E PhoneInterfaceManager: [PhoneIntfMgr] getIccId: No UICC
07-13 23:32:31.511   679   800 D WifiService: New client listening to asynchronous messages
07-13 23:32:31.543   679   696 I Telecom : PhoneAccountRegistrar: [ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, [e0184adedf913b076626646d3f52c3b49c39ad6d], UserHandle{0}(icon: Icon(typ=BITMAP size=29x36) -> Icon(typ=BITMAP size=29x36))]
07-13 23:32:31.573   679   696 I Telecom : : Sending phone-account registered intent as user
07-13 23:32:31.584  1283  1283 I Telephony: AccountEntry: Registered phoneAccount: [[ ] PhoneAccount: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, [e0184adedf913b076626646d3f52c3b49c39ad6d], UserHandle{0} Capabilities: 54 Schemes: tel voicemail ] with handle: ComponentInfo{com.android.phone/com.android.services.telephony.TelephonyConnectionService}, [e0184adedf913b076626646d3f52c3b49c39ad6d], UserHandle{0}
07-13 23:32:31.584  1283  1283 I Telephony: PstnIncomingCallNotifier: Registering: Handler (com.android.internal.telephony.gsm.GSMPhone) {3b68ded}
07-13 23:32:31.604   679  1398 W Telecom : : No account found for the calling user
07-13 23:32:31.638  1239  1253 D GmsServicesProvider: query caller=com.google.android.gm name=gmail-memory-monitoring-app value=null
07-13 23:32:31.642  1239  1276 D GmsServicesProvider: query caller=com.google.android.gm name=gmail_analytics_sampling_rate value=null
07-13 23:32:31.668   878   878 D MediaScannerReceiver: action: android.intent.action.MEDIA_MOUNTED path: /storage/9016-4EF8
07-13 23:32:31.696   841   854 I art     : Background sticky concurrent mark sweep GC freed 33839(2MB) AllocSpace objects, 0(0B) LOS objects, 17% free, 11MB/13MB, paused 14.130ms total 64.397ms
07-13 23:32:31.697  1696  1696 W GAV2    : Thread[main,5,main]: Need to call initialize() and be in fallback mode to start dispatch.
07-13 23:32:31.706  1283  1283 D CarrierConfigLoader: update config for phoneId: 0 simState: LOADED
07-13 23:32:31.707  1283  1283 D CarrierServiceBindHelper: update binding for phoneId: 0 simState: LOADED
07-13 23:32:31.740  1283  1283 D CarrierConfigLoader: mHandler: 7 phoneId: 0
07-13 23:32:31.763  1283  1283 D CarrierConfigLoader: Loaded config from XML. package=com.android.carrierconfig phoneId=0
07-13 23:32:31.780  1283  1283 D CarrierServiceBindHelper: mHandler: 0
07-13 23:32:31.780  1283  1283 D CarrierServiceBindHelper: Binding to phoneId: 0
07-13 23:32:31.783  1283  1283 D CarrierServiceBindHelper: No carrier app for: 0
07-13 23:32:31.783  1283  1283 D CarrierConfigLoader: mHandler: 5 phoneId: 0
07-13 23:32:31.871  1239  1253 D GmsServicesProvider: query caller=com.google.android.gm name=gmail-dogfood-promo-build-flavor-override value=null
07-13 23:32:31.957   679   708 D GpsLocationProvider: received SIM change, new known MCC/MNC: []
07-13 23:32:31.983  1696  1696 I Gmail   : Account list changed
07-13 23:32:31.983   679   679 I Telecom : PhoneAccountRegistrar: SimCallManager queried, returning: null
07-13 23:32:31.992   679   800 D WifiService: New client listening to asynchronous messages
07-13 23:32:32.001  1696  1732 I Gmail   : getAccountsCursor
07-13 23:32:32.022  1696  1759 I Gmail   : No Email application installed
07-13 23:32:32.022  1696  1759 I EmailMigration: No data to migrate
07-13 23:32:32.027  1387  1445 I ContactDirectoryManager: deleted 0 stale rows which don't have any relevant directory
07-13 23:32:32.038  1696  1759 W EmailMigration: No Exchange migration, not the right Email provider version
07-13 23:32:32.075  1696  1757 I Gmail   : Initiated Service map for: [gPop3, gLegacyImap, gEas, gmail]
07-13 23:32:32.161   891   891 W Binder_3: type=1400 audit(0.0:34): avc: denied { ioctl } for path="socket:[15610]" dev="sockfs" ino=15610 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
07-13 23:32:32.161   891   891 W Binder_3: type=1400 audit(0.0:35): avc: denied { ioctl } for path="socket:[15610]" dev="sockfs" ino=15610 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
07-13 23:32:32.205  1387  1445 I ContactDirectoryManager: Discovered 0 contact directories in 2717ms
07-13 23:32:32.206   878   878 D MediaScannerReceiver: action: android.intent.action.MEDIA_MOUNTED path: /storage/emulated/0
07-13 23:32:32.247  1696  1696 I Exchange: EasService.onCreate
07-13 23:32:32.248  1669  1764 D ActivityThread: Loading provider com.android.email.provider;com.android.email.notifier: com.android.email.provider.EmailProvider
07-13 23:32:32.284   679  1206 I ActivityManager: Start proc 1771:org.mariotaku.twidere/u0a91 for broadcast org.mariotaku.twidere/.receiver.PowerStateReceiver
07-13 23:32:32.285   679  1238 W ActivityManager: Unable to start service Intent { cmp=com.google.android.gm.exchange/com.android.exchange.service.EasService } U=0: not found
07-13 23:32:32.288  1696  1696 I Exchange: EasService.onCreate stoppedOldService=false
07-13 23:32:32.325   841   841 W KeyguardUpdateMonitor: invalid subId in handleSimStateChange()
07-13 23:32:32.328  1696  1696 I Exchange: needResyncCalendar: true, hasCalendarPermission: false, needResyncContacts: true, hasContactsPermission: false
07-13 23:32:32.332   841   841 W KeyguardUpdateMonitor: invalid subId in handleServiceStateChange()
07-13 23:32:32.332   841   841 I Choreographer: Skipped 113 frames!  The application may be doing too much work on its main thread.
07-13 23:32:32.343  1283  1283 D MccTable: updateMccMncConfiguration mccmnc='310120' fromServiceState=false
07-13 23:32:32.351  1283  1283 D MccTable: updateMccMncConfiguration defaultMccMnc=
07-13 23:32:32.351  1283  1283 D MccTable: updateMccMncConfiguration: mcc=310, mnc=120
07-13 23:32:32.351  1283  1283 D MccTable: updateMccMncConfiguration updateConfig config={1.0 310mcc120mnc ?locale ?layoutDir ?swdp ?wdp ?hdp ?density ?lsize ?long ?orien ?uimode ?night ?touch ?keyb/?/? ?nav/? themeResource=null}
07-13 23:32:32.419  1696  1757 I Exchange: RestartPingTask
07-13 23:32:32.445   255   668 E QC-time-services: Daemon:tod_update_ind_cb: Got Update from modem msg_id 46
07-13 23:32:32.445   255   668 E QC-time-services: Daemon:tod_update_ind_cb: Got Update from modem msg_id 39
07-13 23:32:32.445   255   669 D QC-time-services: Daemon:read_offset: Sending read request for offset 8
07-13 23:32:32.446   255   669 E QC-time-services: Daemon:read_offset: Error in reading full time ignoring update rc=0 resp=3 
07-13 23:32:32.617  1696  1696 I Gmail   : Database deleted: No account for db [internal.<snip>@gmail.com.db]
07-13 23:32:32.674  1689  1777 W ACRA    : org.fdroid.fdroid reports will be sent by email (if accepted by user).
07-13 23:32:32.680  1534  1575 E ELEVEN  : calling refresh!
07-13 23:32:32.729  1696  1696 I Gmail   : Database deleted: No account for db [mailstore.<snip>@gmail.com.db]
07-13 23:32:32.765   679  1238 D AlarmManagerService: Setting time of day to sec=1468474352

**Comment by georgedorn** [comment]
I've also tried rebooting the device in the theory that a previous signon (for Ingress) caused the issue.

I tried some older versions of GMail, and this one eventually worked:
http://www.oldversion.com/android/download/com-google-android-gm-5-0-1566562-5000670

I am investigating whether having logged in successfully with that one I can now upgrade to a more recent version - when I opened 5.0, my account was already visible.

**Comment by georgedorn** [comment]
Note that in 5.4, I saw the odd behavior where my account showed up on the 'Add an email address' screen after a few seconds of waiting.  I had logged in successfully with 5.0 and during the binary search installed working and non-working versions, but all of them took a while to find the successfully-logged-in from prior attempts.

**Comment by mar-v-in** [comment]
If you have problems with logging in on Android 6.0, it might be because of missing contacts permission. I was able to run GMail 6.6 fine.
1. Create a Google account from system settings -> accounts (if not already done).
2. Install GMail
3. On Android 6.0: Open App settings and grant contacts and Google Mail permission (under additional permissions) to GMail
4. Open GMail and skip the intro if necassary. Do not add any account
5. Open system settings -> accounts -> Google -> your google account and check if there is a GMail present. Disable (if enabled) and enable it. It should take a short time to sync mails and then display current time as "last synced".
6. If there are new mails in you GMail account there should already be
7. Open GMail app again. If it is still on the "add account" screen, touch the "continue to gmail" (or sth like that) button at the bottom.
8. You should see your GMail.

**Comment by georgedorn** [comment]
> 5. Open system settings -> accounts -> Google -> your google account and check if there is a GMail present. Disable (if enabled) and enable it. It should take a short time to sync mails and then display current time as "last synced".

I have a Google account and a Google Play Account showing up in the account settings (also a Signal account).  There's no GMail account, nor a way to disable/enable anything either in the Accounts menu nor the Google account screen.  It does show the current time as last synced when I forcefully sync.

> 7. Open GMail app again. If it is still on the "add account" screen, touch the "continue to gmail" (or sth like that) button at the bottom.

At this stage, with GMail 6.0 (really, 5.5 or above), the GMail account does not show up on the "add account" screen and it refuses to move past the screen without adding one.  Re-re-re-adding the gmail account yields the error log above.

**Comment by EleutheriusBliss** [comment]
Mine works ok. Did not login from the app, just installed it, set the right permissions, opened it, then rebooted. It picked up Microg-Google account on its own. International S5, android 6.0.1.

**Comment by Lanchon** [comment]
i followed the instructions, but didn't work. when i enabled sync on Gmail, sync failed and said "there is a problem with sync" or something of the sort.

to fix the issue you need to enable "Trust Google for app permissions" in google account's sign-in and security.

**Comment by lbdroid** [comment]
Isn't it contrary to the objective here to intentionally run google-branded software when you don't have to? You can configure your gmail account for IMAP+SMTP and use *any* IMAP client, like k9mail.

**Comment by georgedorn** [comment]
No, the objective is to avoid running Google Play Services, not all Google
software.  The latter may be the objective of some users, but there are a
lot of Google apps.  A year ago, would you have suggested that Ingress
users should avoid playing the game because Niantic was under the Google
umbrella?

**Comment by lbdroid** [comment]
What's the point? Either you trust Google, or you don't.
If you do, then you can run google services and gmail.
If you don't, then you can run neither.

**Comment by mar-v-in** [comment]
@lbdroid there are numerous reasons to use microG besides not trusting Google. Please keep this discussion of the issue, as it's not related.

**Comment by breversa** [comment]
@mar-v-in :
You 2016-07-14 solution did the trick for Lineage for MicroG 14.1/Android 7.1.2 as well.

Thanks a lot ! I can close this issue now. :-)

**Comment by breversa** [comment]
The above solution stopped working for a time, but as of microG Services Core 0.2.7.17455-65-mapbox, it works again. Thanks for the continuous support !! :+1:
