### ISSUE TITLE
CopperheadOS compatibility status

### ISSUE THREAD

**Issue by markkuit** [microg/android_packages_apps_GmsCore#155]
Hello,

I'm on my way to try microg, but I got a few questions first. I start by saying I'm gonna try it on CopperheadOS. I've read it's quite easy to install it with the provided APK, has anyone had any experience with microg+copperheados already? Will I be able to use Google Maps application or is there any as-similar-as-possible alternative (in terms of reliability and efficiency)? Are social apps (e.g. Facebook, Whatsapp, Signal, ...) gonna work? and finally, I've got an LG G Watch R W110. Judging by what I could see in the wiki, there's no support whatsoever for Android Wear yet. Is it correct?

If there's something major you also feel like I should know before diving into this please let me know.
Thank you very much!

**Comment by mar-v-in** [comment]
AFAIK, CopperheadOS does not include support for [signature spoofing](https://github.com/microg/android_packages_apps_GmsCore/wiki/Signature-Spoofing) out of the box for security reasons.

For app support, there should not be any differences between Copperhead OS and other custom ROMs, so I expect all the apps you mentioned to be running. There are some apps not working, if you encounter problems, please report a bug here.

Android Wear support is not yet supported. There is experimental support to communicate with an Android Wear emulator, but no bluetooth support yet.
