### ISSUE TITLE
Crash on isLocationAvailable

### ISSUE THREAD

**Issue by dos1** [microg/android_packages_apps_GmsCore#159]
Pokemon Go 0.31.0 crashes on MicroG's GmsCore (0.2.4):

```
07-30 21:11:39.790  6854  7043 E AndroidRuntime: FATAL EXCEPTION: ContextService
07-30 21:11:39.790  6854  7043 E AndroidRuntime: Process: com.nianticlabs.pokemongo, PID: 6854
07-30 21:11:39.790  6854  7043 E AndroidRuntime: java.lang.Error: FATAL EXCEPTION [ContextService]
07-30 21:11:39.790  6854  7043 E AndroidRuntime: Unity version     : 5.3.5f1
07-30 21:11:39.790  6854  7043 E AndroidRuntime: Device model      : samsung GT-I9300
07-30 21:11:39.790  6854  7043 E AndroidRuntime: 
07-30 21:11:39.790  6854  7043 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.gms.location.LocationAvailability.isLocationAvailable()' on a null object reference
07-30 21:11:39.790  6854  7043 E AndroidRuntime:        at com.nianticlabs.nia.location.FusedLocationProvider$4.onLocationResult(FusedLocationProvider.java:221)
07-30 21:11:39.790  6854  7043 E AndroidRuntime:        at com.google.android.gms.location.internal.zzk$zza$1.handleMessage(Unknown Source)
07-30 21:11:39.790  6854  7043 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-30 21:11:39.790  6854  7043 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
07-30 21:11:39.790  6854  7043 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)
07-30 21:11:39.793  3015  3566 W ActivityManager:   Force finishing activity com.nianticlabs.pokemongo/com.unity3d.player.UnityPlayerNativeActivity
```

**Comment by 0x47** [comment]
I second that. Here are the docs for [isLocationAvailable()](https://developers.google.com/android/reference/com/google/android/gms/location/LocationAvailability.html#isLocationAvailable()).

There are a few more interesting lines before that log excerpt above:

    07-31 01:22:24.926 13794 13808 V NlpLocationProvider: onSetRequest: ProviderRequest[ON interval=+1s0ms] by WorkSource{10109 com.google.android.gms}
    07-31 01:22:24.926 13794 13808 V NlpLocationProvider: using autoUpdate=true autoTime=2500
    07-31 01:22:25.472 13794 13794 D GmsLocProviderReal: uh-ok: last location for network is null!
    07-31 01:22:25.473 13794 13794 D GmsLocRequestHelper: sending Location: Location[gps [...] {Bundle[mParcelledData.dataSize=40]}]
    07-31 01:22:25.482 13794 14356 D GmsLocManagerSvcImpl: iglms34: com.nianticlabs.pokemongo
    07-31 01:22:25.484  2442  3374 E AndroidRuntime: FATAL EXCEPTION: ContextService
    ...

This shows [`1iglms34()`](https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/location/GoogleLocationManagerServiceImpl.java#L249) being called which indeed does simply return `null`.

**Comment by mar-v-in** [comment]
Should be fixed by 47a61d6, please update to preview release 0.2.4-3+

**Comment by Roxxor91** [comment]
I can confirm it to be fixed! Thank you very much!

**Comment by dos1** [comment]
I can confirm that it works now, thanks!
