### ISSUE TITLE
The microg.org site is down

### ISSUE THREAD

**Issue by maxellnormalbias** [microg/android_packages_apps_GmsCore#162]
I don't really know where else to post this, so, sorry if it doesn't belong here. I recently wiped my phone and tried to go gapps-less. Yesterday, the site was working fine. When I tried to upgrade to the latest version of microG services core from the fdroid repo, it said "connection refused". When I tried downloading directly from the website, Chromium also gave me a "connection refused" error. What's going on?

**Comment by ale5000-git** [comment]
Today it works again.

**Comment by maxellnormalbias** [comment]
Thanks man.
