### ISSUE TITLE
Pokemon Go 0.31.0 location doesn't work

### ISSUE THREAD

**Issue by lucalateralus** [microg/android_packages_apps_GmsCore#165]
On cellular data: "GPS signal not found"
On Wifi: With location disabled, game loads but "GPS signal not found". App crashes when location turned on in phone settings.

Previous versions of Pokemon Go worked fine but now the update is enforced.

**Comment by FoxP** [comment]
Same issue for me with latest stable and unstable releases with CyanogenMod 13 (Android 6.0.1) on a Redmi Note 3 Pro Prime (Kenzo) phone.

**Comment by zoff99** [comment]
could it be that the version 0.31.0 does in general only work with GPS turned on?
have you tried that version on a phone with real google play services?

**Comment by FoxP** [comment]
I forgot to say that v0.31.0 also crashes with "GPS only" activated. No only with "High accuracy" mode.

**Comment by mar-v-in** [comment]
Are you on 0.2.4 or 0.2.4-3? See #159

**Comment by lucalateralus** [comment]
^yes... Updating to latest preview release worked. Thanks and sorry, this was a duplicate of #159
(I didn't realise that the latest versions weren't in Fdroid while https://microg.org was also down)

**Comment by FoxP** [comment]
Oops... Fixed by updating to latest preview. Latest versions should be in Fdroid for more visibility.
IMO you can close this issue.
