### ISSUE TITLE
Maps API not working?

### ISSUE THREAD

**Issue by ArchangeGabriel** [microg/android_packages_apps_GmsCore#169]
Hi there,

I’m using GmsCore and can’t get apps usings Maps API to work. UnifiedNlp works perfectly, with all box checked, but any apps requiring Maps API (like Sensorly, OpenSignal, Pokémon GO…) do not work correctly (message about missing Google Play Services — except for Pokémon Go — and no map shown).

Not sure if I missed something in configuration or whether this is a real bug. I’m using CM13 on a OPO, with Xposed module for signature faking. GMS is up-to-date (0.2.4-6).

Thanks a lot for your help.
##

**Comment by ale5000-git** [comment]
It is possible that the Xposed module do not work correctly on your ROM.
Try to reinstall Xposed and the Xposed module.
Or alternatively try patching the framework.jar.

**Comment by ArchangeGabriel** [comment]
Tried reinstalling Xposed and the module, for no result. Also upgraded CM13.0 to latest SNAPSHOT from y-day, reinstalled Xposed and the module, for no result.

Patching the framework.jar using Needle isn’t an option for me, don’t want to root my device. Or where you referring to another method?

**Comment by ArchangeGabriel** [comment]
Seems to work now after installing BlankStore (not quite sure about that, but this is the only thing I can see that could have changed something). However overlay from OpenSignal and Sensorly do not work, and I’ve encountered several issue (crash, constant zooming-out, glitches). But I suppose this is expected at this point of development.

At least Pokémon Go is working now. :p

**Comment by ale5000-git** [comment]
Note: GmsCore contains a copy of UnifiedNlp, so if you have installed GmsCore you shouldn't also install a separate UnifiedNlp.
Note 2: GmsCore contains Maps API v2, some apps need Maps API v1 that can be found here: https://github.com/microg/android_frameworks_mapsv1

To patch framework.jar root is needed (maybe with a custom recovery it may works without root but I have never tried).

Some apps require also the presence of the PlayStore (or another app that emulate it like BlankStore).

Does all self checks of GmsCore pass?

**Comment by ArchangeGabriel** [comment]
I was talking of GmsCore’s UnifiedNlp indeed, it’s not even possible to install both AFAIK.

I’m not sure whether you’ve understood my issues, but this is the current status:

1. At first, apps using Maps API v2 weren’t working correctly (no map shown, error message about Play Services — but no crash).

2. After installing BlankStore, and even without configuring it, things started to work correctly. I understand now (and from the wiki) that the presence of any app faking PlayStore signature is needed, although this is awkward, but it definitively made things work.

3. At this point, almost of self-check of microG are checked, except for GSF (not installed, so that’s OK), and permissions 3/4 (I’ve tried with them enabled, but it didn’t changed anything regarding current issues, so disabled them again). Previously, “store” one wasn’t checked obviously.

4. While PokémonGo works OK, Sensorly and OpenSignal are crashing often (especially on zoom out) and there map overlays (signal strength/coverage) don’t work, also they are not able to display my position. Though, I don’t know how to help you sort this out. Also, PokémonGo maps are definitively GMaps one, not OSM or anything else, is that expected? Is PokémonGo even using Maps API in fact? I’m wondering if the issue I had with it was just “PlayStore” related or if that was really needed through Maps API somehow.

5. At least one app that used to work before install microG doesn’t work anymore (crash on login), this one: https://play.google.com/store/apps/details?id=fr.cnaf.mobile.moncompte. This is not very important since this app is quite limited in its functionalities vs their website, but I suppose this is still worth fixing anyway. However, I suppose you don’t have any account at the french CAF, so debugging might be hard… Please tell me if there is anything I can do.

So, overall, for my current usage, microG works quite well and Maps API v2 seems to be working, but there are some things that need enhancement or fixing. ;)

**Comment by ArchangeGabriel** [comment]
@mar-v-in Do you want me to open new separated issues for 4 and 5 and close this one?

**Comment by ale5000-git** [comment]
Try to download the latest preview version [here](https://microg.org/download.html), currently 0.2.4-20.

**Comment by mar-v-in** [comment]
Regarding Pokemon Go: No they don't use the Android Maps API, the Android Maps API does not support theming (only select from some basic styles like terrain or satellite). Regarding the other things: I might have a look on it before the 0.2.5 release, but no guarantees. The map rendering code is mostly from the [vtm library](https://github.com/mapsforge/vtm) and I am not very used to GL stuff.

**Comment by ArchangeGabriel** [comment]
5. was solved by reinstalling apparently.

I’ve opened https://github.com/microg/android_packages_apps_GmsCore/issues/238 for the remaining related issues.
