### ISSUE TITLE
Request: Use Magisk for Signature Spoofing & Gapps Removal?

### ISSUE THREAD

**Issue by JERW86** [microg/android_packages_apps_GmsCore#170]
Hi @mar-v-in - I came across a project called Magisk and I thought it could be used with microG. I am not a dev and I do not understand computer or Android code. I just wanted to share an idea I had after coming across this project. I hope it will be considered and someone with more experience might implement this idea.

Magisk by @topjohnwu [link here](http://forum.xda-developers.com/android/software/mod-magisk-v1-universal-systemless-t3432382) is a a mod utility that allows the system partition to be altered without touching it or, in some cases, removing real files and replacing them with dummy files, to fool google and manufacturers into thinking the system hasn't been touched.  Devs create individual mods to modify the system how they wish.

 I am hoping that this method can be used by creating two mods to help setup microG. The mods could be 
1. inject signature spoofing for MicroG via a flashable zip in custom recovery.

**Potential Advantages**
-Easier and more seamless implementation by using TWRP/CWM
-No xposed required
-No computer required
1. Flashable zip to replace official Gapps base and Apps in system (with an option to keep the original Google Play Store) with dummy files. 

**Potential Advantages**
-Easier way to remove/replace gapps to customize and control what apps are used. The zip could remove/replace all Gapps with the possible exception of Google Play Store. Than the user could reinstall whatever Google apps they wanted as user apps.
microG users might be able to accept and successfully flash OTA updates while still using microG because system remains "untouched".
-If the OTA update overrides signature spoofing and flashes Gapps again, the mods could be reinstated by flashing magisk, magisk comatable su, signature spoofing, and Gapps removal/replacement zips directly after the ota. This might be accomplished by reflashing TWRP or using Chainfire's Flashfire app (which would hopefully make the process automatic!) 

Making these Magisk mods might make installing microG even simpler. What do you think?
##

**Comment by ArchangeGabriel** [comment]
Now that Magisk is required to pass SafetyNet when using Xposed for signature spoofing, I would very much like a Magisk version of signature spoofing (I’m using Xposed only for that, so could then get ride of it). :)

**Comment by mar-v-in** [comment]
As far as I understand, Magisk allows to dynamically add or replace files in /system. It is not a replacement for Xposed and has a completely different focus. That's why one of the core features  of Magisk (beside root) is to add Xposed.

**Comment by ArchangeGabriel** [comment]
@mar-v-in Yes, but I was wondering if signature spoofing could be done as a Magisk Module directly instead of relying on Xposed (for instance Needle is not far from this FWIU).

**Comment by mar-v-in** [comment]
Yes, if Needle/Tingle would be working perfectly when run in recovery, it would be possible to put it inside a Magisk module. But then it would also be possible to use it directly so you would need neither Magisk nor Xposed.

**Comment by ale5000-git** [comment]
Tingle now works perfectly also inside Android (with QPython, without pc), and possibly in the future also as flashable package only.
I will support all configurations but it may take from half hour to 4 hours depending of the phone performance.

**Comment by JERW86** [comment]
@ale5000-git I don't have Magisk on my device right now. I am waiting for Magisk v7 to come out before I try Magisk on my AT&T SGS3 with CM13. If you create a Magisk module for signature spoofing, I will test it. Just let me know.

**Comment by ale5000-git** [comment]
@JERW86: I don't have Magisk, mine was only an idea.

**Comment by JERW86** [comment]
@ale5000-git: ok nice to know it might be possible.

**Comment by JERW86** [comment]
This seems to have been achieved as mentioned in #284 including signature spoofing using Magisk. Therefore,  I am closing this issue.

**Comment by Nanolx** [comment]
@JERW86 not actually. My patcher makes use of `dexpatcher` and the `haystack` patches and uses your ROM's very own `dalvikvm` to patch the framework.

My patcher then knows three installation paths:
* NanoMod Magisk Module (full)
* NanoMod Magisk Module (microG)
* ROM (directly into /system/framework)

The patcher itself does not make use of Magisk, so anyone can use that patcher, regardless of Magisk. (It's just part of my NanoMod project and NanoMod is a Magisk Module)

**Comment by JERW86** [comment]
@Nanolx oh, OK. I'm sorry for the incorrect assumption. Thank you for the explaination and correction.
