### ISSUE TITLE
Some apps crashing or not getting push notifications

### ISSUE THREAD

**Issue by bytemybits** [microg/android_packages_apps_GmsCore#171]
I'm re-installing CM13 with no GAPPS and I'm discovering some problems with apps I usually use from Google Play (which I know is expected). Unfortunately it seems to be that app developer's simply use Google Play services without serious thought if they needed it at all.

Currently I detected 3 affected apps:
Signal
- pops up warning stating that it needs Google Play services to work properly
- blocks from activating the app, rendering it useless

ProtonMail
- pops up warning stating that it needs Google Play services to work properly every time the app is restarted
- doesn't receive push notifications

Revolut
- pops up warning stating that it needs Google Play services to work properly every time the app is restarted
- app hangs and crashes when clicking on _Top Up_

If there is any relevant info that I could post here to help with this issue, please tell me so. Thanks!

**Comment by bytemybits** [comment]
I was able to extract the Manifest for Revolut and ProtonMail, here's the references I found for Google Services:

**Revolut**
```
<action android:name="com.google.android.c2dm.intent.RECEIVE"/>

<meta-data android:name="com.google.android.gms.analytics.globalConfigResource" android:resource="@xml/analytics"/>

<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
```

**ProtonMail**
```
<action android:name="com.google.android.c2dm.intent.RECEIVE"/>

<action android:name="com.google.android.gms.iid.InstanceID"/>

<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>

<provider android:authorities="ch.protonmail.android.google_measurement_service" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementContentProvider"/>

<action android:name="com.google.android.gms.measurement.UPLOAD"/>

<service android:enabled="true" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementService"/>
```

**Comment by bytemybits** [comment]
Funny enough, I got Revolut _Top Up_ to work, just need to be connected to a WiFi network as it seems. Doesn't work every time, but some parts of the app only work if connected through WiFi while the others through Cellular connection. Strange as this doesn't seem to make sense...

**Comment by RMcNeely** [comment]
Surprised Signal and ProtonMail have GMS dependancies. Looks like they're both working on making it  to F-droid but haven't arrived yet. I know its not really an answer but something else that may work soon.
(Signal)[https://fdroid.eutopia.cz/]
(ProtonMail)[https://f-droid.org/forums/topic/protonmail/]

**Comment by bytemybits** [comment]
ProtonMail is planning on open-sourcing their mobile apps (both iOS and Android) but have no planned date for that. As for the F-Droid store I'm guessing they don't even have it on their roadmap, at least from the response they sent me and given the fact that they depend on Google Services.
As for Signal I think they'll never publish to the F-Droid, because they prefer to have the security the Play Store provides and using it as the only mean to get and publish the app. An example of that is the Silence fork that exists in both Play Store and F-Droid, but Signal only exists in the Play Store.

**Comment by metaphorex** [comment]
Hello, I've been using Signal and ProtonMail on CM13 with microG without issues for a long time, it's kind of surprising that you've been experiencing issues.

**Comment by bytemybits** [comment]
@metaphorex What versions of both apps are you running? Does the Google Play Services pop up appear to you as well? What are the settings for your microG app? Maybe I'm missing something...

**Comment by metaphorex** [comment]
@bytemybits I'm running 1.4.1 version of ProtonMail and 3.17.0 of Signal which are the newest I believe. I'm also running version 0.2.4-7 of microG GmsCore. In microG settings I've enabled device checkin and Google Cloud Messaging, I've also allowed all permissions except location. I don't think that version of microG or any of the apps matte, because I've been using all of them for quite a long time now and I've never had any issues nor popups at all, while I've had with some other apps.

**Comment by ArchangeGabriel** [comment]
@bytemybits Are all microG self-check boxes ticked? Do you have BlankStore or FakeStore installed?

**Comment by bytemybits** [comment]
@ArchangeGabriel I have Device Check-in and Cloud messaging enabled (I'm getting push notifications in slack and WhatsApp for example) and for the Self-check I have everything checked except:
- Play Store (Phonesky)
- System supports location provider
- Network-based location enabled
All these three puzzle me as I did install FakeStore and have location services working (tested it with Google Maps). Also I'm running version 0.2.4-7 of microG GmsCore.

**Comment by NormalRa** [comment]
IIRC FakeStore (Phonesky) is required for Play Services to be recognized.

I found that the the **Spoof package signature** permission has to be granted manually for the FakeStore package via _Settings_ > _Apps_ > _(wrench icon)_ > _App permissions_ > _Spoof package signature_

**Comment by bytemybits** [comment]
@NormalRa I do have FakeStore installed but I don't see _Spoof package signature_ listed in the App permissions. As CM doesn't natively support Signature Spoofing I installed Needle as per instructions in the [Wiki] (https://github.com/microg/android_packages_apps_GmsCore/wiki/Signature-Spoofing) page.
Do I still need the [Xposed Framework] (http://forum.xda-developers.com/showthread.php?t=3034811)?

**Comment by mar-v-in** [comment]
@bytemybits is the problematic point in Installed pacakges "Play Store (Phonesky) installed" or "Play Store (Phonesky) has correct signature"?

**Comment by bytemybits** [comment]
@mar-v-in The first one, the second doesn't even exist (guessing because the first one ins't active). So that means I do have to install Xposed right?

**Comment by mar-v-in** [comment]
No, this is not related to signature spoofing then. The system does not see the FakeStore package installed. Try uninstalling and reinstalling it.

**Comment by NormalRa** [comment]
@bytemybits Apologies, I should have mentioned that the procedure is valid only for cm-13 built with the signature spoofing patch applied.

**Comment by bytemybits** [comment]
@mar-v-in that did the trick! The setting is active in microG and I no longer have the issues I described. Revolut still crashes when doing _Top Up_ but at this point I think it's an app bug, not an issue with microG.
Thank you all very much!
