### ISSUE TITLE
F-Droid repo packages category

### ISSUE THREAD

**Issue by licaon-kter** [microg/android_packages_apps_GmsCore#178]
Now it's setup as "None", can it be changed to "System" maybe?

Reference: https://gitlab.com/fdroid/fdroidclient/merge_requests/388

**Comment by Nutomic** [comment]
Where's the Github repo for the F-Droid repository? This should be a single line change, but I can't find the proper place for it (it doesn't seem to be in the [microg.org](https://github.com/microg/microg.org) repo).

**Comment by mar-v-in** [comment]
@Nutomic the f-droid repo mostly consists of apk binaries and a few very small config file. I don't want to put the binaries in a git repo (that's not what git is built for) and I did not invest time to set up a git repo for the three config files.

Issue is fixed.
