### ISSUE TITLE
Wrong operator tag in Play Store

### ISSUE THREAD

**Issue by EleutheriusBliss** [microg/android_packages_apps_GmsCore#180]
Great project! Most all that matters to me works.
- Official Play Store works, didn't need install Blank Store
- YouTube official app works beautifully
- Google search app works, voice and all
- Contacts and calendar sync works ok
- Gmail official app works ok

And of course, location and push notifications work ok for all apps. Version 0.2.4-8.

All of this on Samsung S5, int. version, dual sim, stock android 6.0.1.
BUT: I suddenly became an O2 client :-) as per Play Store, which I'm not supposed to be...
Store proposes to "Install on: O2 Sm-G900fd" (as a consequence, or maybe not, remote install doesn't function, but that's no problem to me). What gives?

P.s. oh, I see. MaR-V-iN, the developer, is precisely an O2 client. Well, I hope he can find the time to remove the O2 tag from the settings.
##

**Comment by tomasz1986** [comment]
Are you sure that remote installation does not work?

My devices are also displayed as "O2" but I can still remotely install applications without any problems. I am using the stable version of micrGo which is 0.2.4 for now.

**Comment by EleutheriusBliss** [comment]
Yep, I'm sure, I just made an attempt. I'm using the official Play Store ver. 6.9.15, part of the OpenGapps pico pack, and MicroG 0.2.4-8 beta, as I already wrote.

**Comment by tomasz1986** [comment]
I am microG 0.2.4 (stable) and Play Store 7.0.12.H (from APKMirror) and remote installation works for me. Have you granted all the permissions the Play Store app?

**Comment by mar-v-in** [comment]
realizable through #90, closing this separate issue
