### ISSUE TITLE
Unable to activate Xposed microG module

### ISSUE THREAD

**Issue by DarwinWattersonRU** [microg/android_packages_apps_GmsCore#185]
Xposed module just dont appears in modules checklist.
Sony Xperia Z2, stock firmware with manually-removed gapps.

**Comment by tomasz1986** [comment]
What do you mean by "Xposed microG module"?

MicroG itself is not an Xposed module. Are you perhaps looking for the [FakeGApps ](http://repo.xposed.info/module/com.thermatk.android.xf.fakegapps) module (which may or not be required depending on the ROM used)?

**Comment by ale5000-git** [comment]
@DarwinWattersonRU: Have you read?

**Comment by DarwinWattersonRU** [comment]
@ale5000-git
Sorry, didnt visit github for a long time.
I forget that i need an extension for xposed installer, so, sorry.
