### ISSUE TITLE
Stay stalled at "Sorry..."

### ISSUE THREAD

**Issue by Alysko** [microg/android_packages_apps_GmsCore#191]
Hi,
I create a Google account, enter it, but after this, it stay on "Sorry... Your device is contacting Google to save information to your account. This can take a couple of minutes".

**Comment by tomasz1986** [comment]
You have not written anything what exactly you have installed at the moment but I had this problem when the Play Store apk was installed as a user app. I could log in only after moving it to the /system/priv-app folder.
