### ISSUE TITLE
How disable "persmission to location network based"

### ISSUE THREAD

**Issue by kdipp** [microg/android_packages_apps_GmsCore#194]
Hi! In microG settings in persmissions granted i have made a mistake. I have checked the above option ""persmission to location network based" and now i can't disable it anymore! How can i disable it back again please!

**Comment by Nutomic** [comment]
You can remove permissions in the system settings.

**Comment by mar-v-in** [comment]
Apps can't request the system to de-grant a permission, you have to do it manually in system settings.
