### ISSUE TITLE
Provide Flashable Zip [$50]

### ISSUE THREAD

**Issue by Nutomic** [microg/android_packages_apps_GmsCore#196]
There should be a flashable zip for microg, that works in the same way as gapps zips. This would make it easier to install all of microg in one step. 

The zip could also include F-Droid with the microg repo preconfigured, and grant all required permissions to microg automatically.

The zip could then be offered for download on opengapps.org (see https://github.com/opengapps/opengapps/issues/215).

Edit: Someone posted a zip [here](https://xiaomi.eu/community/threads/guide-set-up-microg-on-bugers-cm12-1.31843/), but I can't find any source code for it.
##

**Comment by ale5000-git** [comment]
I have done something but currently is only for old Android versions: http://forum.xda-developers.com/android/development/microg-unofficial-installer-t3432360

**Comment by seanrand** [comment]
@ale5000-git FYI, last I heard, installing microG to /system isn't officially supported/recommended. https://github.com/microg/android_packages_apps_GmsCore/issues/97#issuecomment-190618393

**Comment by ale5000-git** [comment]
@seanrand: In my thread there is a message that say that isn't supported by the author, by I test it personally and it works for the ones that want to do it (my installer automatically extract the native libraries when flashed, so it don't have this problem).
When I will be able to get a real phone with Android 5 I will add support for it also.

**Comment by Nutomic** [comment]
@ale5000-git How do you create the zip? Do you have a script to generate it? If so, you should put it on Github, so that others can easily contribute to it, and adjust it for their own needs.

**Comment by ale5000-git** [comment]
@Nutomic: To extract, just extract (it is a real zip).
To create I use this: http://forum.xda-developers.com/showthread.php?t=3427157

**Comment by Nutomic** [comment]
I just put a 50$ bounty on this issue: https://www.bountysource.com/issues/38000858-provide-flashable-zip

**Comment by ale5000-git** [comment]
I have some plans to add support for new Android versions in my flashable zip, but I'm not sure when yet.

**Comment by ale5000-git** [comment]
I have added support for newer Android versions in my flashable zip.

Here: [microG unofficial installer](https://forum.xda-developers.com/showthread.php?t=3432360)

**Comment by ale5000-git** [comment]
@Nutomic

I have added support for newer Android versions in my flashable zip.

Here: [microG unofficial installer](https://forum.xda-developers.com/showthread.php?t=3432360)

**Comment by Nutomic** [comment]
Great! However, the main thing I want to see is official support for zips directly from microg.

**Comment by okias** [comment]
When you have this nice ZIP, which I testing right now.

Would be nice to have signature spoofing integrated in ZIP.

Good work!

**Comment by ale5000-git** [comment]
@okias: I plan to do something for signature spoofing but currently is not feasible because it can take 3 hours on slow phones, first I must find a way to optimize it.

**Comment by Poomex** [comment]
I actually wouldn't mind waiting 3 hours, as long as signature spoofing works (I really need Signal).

**Comment by JERW86** [comment]
This seems to have been achieved as mentioned in #284 including signature spoofing using Magisk. It is not officially supported by this project.

**Comment by Nanolx** [comment]
@JERW86 it's also achived by @ale5000-git as a non-magisk flashable zip.

@ale5000-git you may checkout my framework-patcher over at Nanolx/NanoMod if you're interested (it's independent of Magisk and can install the services.jar in either my Magisk Module or directly to /system, so it's suitable for your zip, too)

**Comment by alterechtschreibung** [comment]
I created flashable zip files for the MicroG GMS Core Project for Android / LineageOS Details and download: https://github.com/alterechtschreibung/MicroGFlashableZip 

For the signature spoofing I included the NanoMod framework-patcher, thus we don't need Magisk.

**Comment by Nutomic** [comment]
Thank you :)

**Comment by mar-v-in** [comment]
@alterechtschreibung can you add instructions for building the zip files to your repo (or ideally, a fully-working build script). I also think it would be a lot better to publish the binary releases via GitHubs releases feature instead of commiting them in the git (git is not suited for large binary files). This way you should also be able to upload larger files (up to 2GB).

**Comment by Roboe** [comment]
@mar-v-in I did a clean and open source flashable ZIP with flavours and OTA survival that installs only microG/UnifiedNlp apps. The build script get APKs from official microG and F-Droid repos: https://github.com/WeAreFairphone/flashable-zip_microG

**Comment by ArchangeGabriel** [comment]
@Roboe Signature spoofing is the hard part, you don’t need a flashable zip if you don’t need signature spoofing, because the distro that have enabled location providers outside system apps are the same that allow spoofing.

**Comment by Roboe** [comment]
I'm fine tingle-patching each update. UnfiedNlp doesn't need sig-spoof, btw. Anyway, I'll look at NanoMod for patching in-device in the future, but feel free to PR it if you have the time. Build script is documented, :)

**Comment by Nanolx** [comment]
@Roboe nanomod-patcher creates the file /system/.nanomod-patcher after patching, so you can check upon this file whether patching is required or not (additionally to whether it's required at all).

**Comment by ale5000-git** [comment]
I published mine on GitHub: https://github.com/micro5k/microg-unofficial-installer

My plans for the future are:
- Add automatic build script (DONE)
- Add support for config file read during flash (MOSTLY DONE)
- Add support for "live" options (DONE)
- Add option to choose between PlayStore and FakeStore (DONE)
- Create a separate flashable zip for alternative market apps
- Create a separate flashable zip for signature spoofing

@Nanolx: I will look at it but I'm quite busy.

**Comment by rugk** [comment]
IMHO these ZIPs should get official and be adopted by the microg team and published on the official website. Having thousand different microg installers does not help anyone.

Unless this is done, this issue is not closed IMHO. So @Nutomic maybe reopen it? And it would be nice to get a statement from the maintainers…

**Comment by mar-v-in** [comment]
Just for the record, I will only consider a zip to be the "official" one (linked from the website), if it fulfills some criteria:
- Fully open-source - Apache or GPL licensed (or similar)
- Easy to build (script which takes apks as parameters is a good idea)
- build process should not include binaries, always build everything from source.
- compatible with arm an x86
- Does not include routines to include proprietary Google apk (play store)

**Comment by rugk** [comment]
Actually I do not even want to give it any APK. Why? Just publish the ZIP, which has all binary stuff etc. included (of course, built from this repo and open-source).
And when there is a new release they should just publish a new ZIP again. The apk is also only a binary-package more or less.

**Comment by ale5000-git** [comment]
@mar-v-in: Many phones may have broken busybox or no busybox at all, so I include a precompiled one from [here](https://forum.xda-developers.com/showthread.php?t=3348543); compiling it from sources during the process may be long and complicate and it mat take more time than anything else.

**Comment by mar-v-in** [comment]
@rugk you need to include apk in the zip, that's just how Android works. While it might be convenient sometimes to directly build and include the apk, sometimes it's also useful to "override" this and use a specific apk. So ideally we go for both: fully-automated "just build the latest release" and semi-automated "I know what I do and I want this specific file" mode

@ale5000-git I think it's fine to include a binary as lo g as there is an option to still build it from source. I'd like the "official" build to be reproducible and source-built only, but a convenience option to reduce compile time is certainly possible.

**Comment by ale5000-git** [comment]
I have added a build script but currently it only include the "fast" build.
I will include the full build in the future.

**Comment by coconox** [comment]
hanks @ale5000-git for your work ! It was a hard work to install microG on Pure Nexus Rom, until a discover your flashable zip ! Thanks a lot, worked like a charm !
