### ISSUE TITLE
Native Google Play Store

### ISSUE THREAD

**Issue by Teyro** [microg/android_packages_apps_GmsCore#199]
Hi there,

I have read that it is possible to use the GooglePlay Store (Version 6.4.XXX) with microG ...And for somebody it seems to work ;) Many posts said that worked ;) So i want to try that at my test Phone for Myself but it stops after Login to the Google Account... It said sorry that shoudnt happen and after restart of the playstore i can enter account details again....

What i did:

Downloaded the Playstore from ApkMirror, Installed it and moved to System Apps with Titanium
Added Google Account....

Looping to Welcome Screen ;)

What should is do?

**Comment by ale5000-git** [comment]
Play Store should be in /system/priv-app (not /system/app).
Check it.

**Comment by Teyro** [comment]
Check ;) Worked.... THX
