### ISSUE TITLE
Missing EXTENDED_ACCESS permission: add Google Trips app signature

### ISSUE THREAD

**Issue by papjul** [microg/android_packages_apps_GmsCore#203]
Hi,

Can you add Google Trips signature to KNOWN_GOOGLE_SIGNATURES in https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/common/PackageUtils.java and try if Google Trips work?

Thanks,

**Comment by papjul** [comment]
Can I help somehow?
I thought it would be easy to implement…

**Comment by licaon-kter** [comment]
Seeing this too in Google Cardboard Camera:
* 1.0.0.120917439 works ok, no Skip/Update Services dialogue is shown
* 1.0.0.132734800 crash on start, disabling FakeGApps w/ reboot makes the app offer the Skip/Update Services dialogue, but it works after that
* 1.0.0.133061787 crash on start disabling FakeGApps w/ reboot makes the app offer the Skip/Update Services dialogue, but it works after that


logcat: https://gist.github.com/licaon-kter/452e381a897bd5d52e46b76af7fc2218

**Comment by haidahaha** [comment]
I am having exact same problem. Any news?

**Comment by papjul** [comment]
If some of you know how to get the SHA1 signature of related Google apps, we can make a pull request.
However, I have no use anymore for this project so this is no longer installed on my phone, if you want to try it.
I regret that the maintainer totally ignored this issue, it didn't seem to be very long to fix…

**Comment by ale5000-git** [comment]
I don't think it ignore it.
It may be just busy with other things.

**Comment by haidahaha** [comment]
@papjul can you explain more how to do it? I obtained the SHA1 of Google Trip apk.

**Comment by papjul** [comment]
Click on the Pencil icon on the top right: https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/common/PackageUtils.java
Add Google Trips SHA-1 to the list of private static final String[] KNOWN_GOOGLE_SIGNATURES. Add a comment /* Google Trips */ like for other applications. This should be a pretty straightforward task, but ask if you're stuck.
Then make a pull request to the original repo of mar-v-in ;)

**Comment by haidahaha** [comment]
Thanks! Done https://github.com/microg/android_packages_apps_GmsCore/pull/375

**Comment by ale5000-git** [comment]
This should be fixed.

**Comment by haidahaha** [comment]
@ale5000-git do you know when or where is a new preview release with this fix available? I thought it was nightly built but it looked like I was wrong.

**Comment by ale5000-git** [comment]
The code was merged but there isn't a new build yet, probably he wait to add other fixes before releasing a new build.

**Comment by mar-v-in** [comment]
Build is uploaded to website / F-Droid now.

**Comment by haidahaha** [comment]
@mar-v-in thanks for updating. Why did it take so long to publish a new version? Wouldn't it be better to have a nightly build or something?
