### ISSUE TITLE
Unzip error with microG Services Core 0.2.4-20

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#204]
While extracting microG Services Core 0.2.4-20 with unzip you get "unzip: invalid zip magic 00000597".
Probably it isn't a problem but it is a thing to verify.

**Comment by mar-v-in** [comment]
I am not receiving this message when trying to unzip the file on my system, can you check that you don't have a broken download (sha1: 5e4a0513eed1ea6fd401d16c9e6b7d73d292c507)

**Comment by ale5000-git** [comment]
Retried with 0.2.4-22  (sha1: 5f88935aebb904f0ccbca9e3a80509b85f1d314c).
Command: busybox unzip com.google.android.gms-9685081.apk *.dex
Output:
> Archive:  com.google.android.gms-9685081.apk
>   inflating: classes.dex
> unzip: invalid zip magic 00000597

**Comment by mar-v-in** [comment]
Indeed, busybox unzip is showing this for me as well. The latest builds are done using the new version of the Android SDK build tools, which use zip version 2.4 (older used zip version 2.0). However 2.4 is backwards compatible to 2.0, so this should not make a difference. Not sure why busybox unzip is complaining here, but as far as I can tell, it should still correctly extract the file.

**Comment by ale5000-git** [comment]
So, it may be a bug in Android SDK build tools, in zip or in BusyBox.
I will try to report where it belong, if someone have more info please tell me.

**Comment by ale5000-git** [comment]
Ref: https://github.com/rmyorston/busybox-w32/issues/67
