### ISSUE TITLE
Twitter crashes / waiting at the launch screen

### ISSUE THREAD

**Issue by alanpoulain** [microg/android_packages_apps_GmsCore#208]
I have the same issue as #134 since Twitter 6.7.0 (6.7.0 is working and I was hoping for the bug to be fixed).
I am now on Twitter 6.17.0.
Logcat:
```
GMPM GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services. Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
```
And then:
```
dalvikvm Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.twitter.android.initialization.AppStyleInitializer.a
```
Am I the only one?

**Comment by mar-v-in** [comment]
Can you provide a logcat from the crash? I do not see any obvious problems with Twitter and as in #134 the messages do not indicate there is a microG related problem.

**Comment by alanpoulain** [comment]
I was blocking Crashlytics using XPrivacy, that's why Twitter crashed. But now Twitter keeps waiting at the launch screen.
I don't know if it is related to microG, Xposed or XPrivacy (sorry if it is the latter).
Here is the logcat:
`I/ActivityManager(  910): Start proc com.twitter.android for activity com.twitter.android/.StartActivity: pid=5297 uid=10251 gids={50251, 3003, 1028, 1015, 1006}
I/FixedAndroidHandler( 5297): logging to file is not enabled
W/XPrivacy( 5297): Hooking package=com.twitter.android
D/ActivityThread( 5297): handleBindApplication:com.twitter.android
D/ActivityThread( 5297): setTargetHeapUtilization:0.75
D/ActivityThread( 5297): setTargetHeapMinFree:2097152
I/MultiDex( 5297): VM with version 1.6.0 does not have multidex support
I/MultiDex( 5297): install
I/MultiDex( 5297): MultiDexExtractor.load(/data/app/com.twitter.android-2.apk, false)
I/MultiDex( 5297): loading existing secondary dex files
I/MultiDex( 5297): load found 2 secondary dex files
I/MultiDex( 5297): install done
I/dalvikvm( 5297): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.n.zzi
W/dalvikvm( 5297): VFY: unable to resolve virtual method 2450: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
D/dalvikvm( 5297): VFY: replacing opcode 0x6e at 0x000b
I/GMPM    ( 5297): App measurement is starting up, version: 8487
I/GMPM    ( 5297): To enable debug logging run: adb shell setprop log.tag.GMPM VERBOSE
E/GMPM    ( 5297): GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
E/GMPM    ( 5297): Scheduler not set. Not logging error/warn.
E/GMPM    ( 5297): Uploading is not possible. App measurement disabled
I/dalvikvm( 5297): Could not find method android.app.Activity.setTaskDescription, referenced from method com.twitter.android.initialization.AppStyleInitializer.a
W/dalvikvm( 5297): VFY: unable to resolve virtual method 389: Landroid/app/Activity;.setTaskDescription (Landroid/app/ActivityManager$TaskDescription;)V
D/dalvikvm( 5297): VFY: replacing opcode 0x6e at 0x000b
E/dalvikvm( 5297): Could not find class 'android.app.ActivityManager$TaskDescription', referenced from method com.twitter.android.initialization.AppStyleInitializer.a
W/dalvikvm( 5297): VFY: unable to resolve new-instance 132 (Landroid/app/ActivityManager$TaskDescription;) in Lcom/twitter/android/initialization/AppStyleInitializer;
D/dalvikvm( 5297): VFY: replacing opcode 0x22 at 0x0038
I/dalvikvm( 5297): Could not find method android.app.ActivityManager$TaskDescription.getPrimaryColor, referenced from method com.twitter.android.initialization.AppStyleInitializer.a
W/dalvikvm( 5297): VFY: unable to resolve virtual method 395: Landroid/app/ActivityManager$TaskDescription;.getPrimaryColor ()I
D/dalvikvm( 5297): VFY: replacing opcode 0x6e at 0x0008
D/dalvikvm( 5297): DexOpt: unable to opt direct call 0x018a at 0x3a in Lcom/twitter/android/initialization/AppStyleInitializer;.a
I/dalvikvm( 5297): Could not find method android.accounts.AccountManager.removeAccountExplicitly, referenced from method com.twitter.app.common.account.d.a
W/dalvikvm( 5297): VFY: unable to resolve virtual method 1849: Landroid/accounts/AccountManager;.removeAccountExplicitly (Landroid/accounts/Account;)Z
D/dalvikvm( 5297): VFY: replacing opcode 0x6e at 0x002a
D/dalvikvm( 5297): Trying to load lib /data/app-lib/com.twitter.android-2/libcrashlytics.so 0x42c8aa28
D/dalvikvm( 5297): Added shared lib /data/app-lib/com.twitter.android-2/libcrashlytics.so 0x42c8aa28
D/libcrashlytics( 5297): Initializing libcrashlytics version 1.1.3
D/libcrashlytics( 5297): Attempting to load unwinder...
D/libcrashlytics( 5297): Done; using libcorkscrew
D/libcrashlytics( 5297): Attempting to register signal handler...
D/libcrashlytics( 5297): Signal handler registered.
D/libcrashlytics( 5297): Initializing native crash handling successful.
I/CrashlyticsCore( 5297): Initializing Crashlytics 2.3.11.142
I/dalvikvm( 5297): Could not find method android.app.Notification$Builder.setLocalOnly, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zza
W/dalvikvm( 5297): VFY: unable to resolve virtual method 2129: Landroid/app/Notification$Builder;.setLocalOnly (Z)Landroid/app/Notification$Builder;
D/dalvikvm( 5297): VFY: replacing opcode 0x6e at 0x00cb
I/Xposed  (  910): FakeGApps: returning fake signature to com.twitter.android
I/Xposed  (  910): FakeGApps: returning fake signature to com.twitter.android
I/Xposed  (  910): FakeGApps: returning fake signature to com.twitter.android
I/Xposed  (  910): FakeGApps: returning fake signature to com.twitter.android
I/Xposed  (  910): FakeGApps: returning fake signature to com.twitter.android
W/dalvikvm( 5297): VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
I/dalvikvm( 5297): Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
W/dalvikvm( 5297): VFY: unable to resolve interface method 20432: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
D/dalvikvm( 5297): VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm( 5297): Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
W/dalvikvm( 5297): VFY: unable to resolve interface method 20436: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
D/dalvikvm( 5297): VFY: replacing opcode 0x72 at 0x0002
I/Timeline( 5297): Timeline: Activity_launch_request id:com.twitter.android time:11724919
I/ActivityManager(  910): START u0 {cmp=com.twitter.android/.DispatchActivity (has extras)} from pid 5297
I/Xposed  (  910): FakeGApps: returning fake signature to com.twitter.android
I/Xposed  (  910): FakeGApps: returning fake signature to com.twitter.android
I/Xposed  (  910): FakeGApps: returning fake signature to com.twitter.android
I/dalvikvm( 5297): Could not find method android.app.Activity.requestPermissions, referenced from method com.twitter.android.km.a
W/dalvikvm( 5297): VFY: unable to resolve virtual method 1980: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
D/dalvikvm( 5297): VFY: replacing opcode 0x6e at 0x0014
I/dalvikvm( 5297): Could not find method android.app.Activity.shouldShowRequestPermissionRationale, referenced from method com.twitter.android.km.a
W/dalvikvm( 5297): VFY: unable to resolve virtual method 1993: Landroid/app/Activity;.shouldShowRequestPermissionRationale (Ljava/lang/String;)Z
D/dalvikvm( 5297): VFY: replacing opcode 0x6e at 0x000e
I/dalvikvm( 5297): Could not find method android.content.Context.checkSelfPermission, referenced from method com.twitter.android.km.a
W/dalvikvm( 5297): VFY: unable to resolve virtual method 2269: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
D/dalvikvm( 5297): VFY: replacing opcode 0x6e at 0x000f
I/dalvikvm( 5297): Could not find method android.content.Context.checkSelfPermission, referenced from method com.twitter.android.km.c
W/dalvikvm( 5297): VFY: unable to resolve virtual method 2269: Landroid/content/Context;.checkSelfPermission (Ljava/lang/String;)I
D/dalvikvm( 5297): VFY: replacing opcode 0x6e at 0x0015
I/dalvikvm( 5297): Could not find method android.view.Window.setStatusBarColor, referenced from method com.twitter.android.pk.a
W/dalvikvm( 5297): VFY: unable to resolve virtual method 20455: Landroid/view/Window;.setStatusBarColor (I)V
D/dalvikvm( 5297): VFY: replacing opcode 0x6e at 0x001a
I/dalvikvm( 5297): Could not find method android.support.design.widget.FloatingActionButton.setAccessibilityTraversalBefore, referenced from method com.twitter.app.common.base.TwitterFragmentActivity.a
W/dalvikvm( 5297): VFY: unable to resolve virtual method 4695: Landroid/support/design/widget/FloatingActionButton;.setAccessibilityTraversalBefore (I)V
D/dalvikvm( 5297): VFY: replacing opcode 0x6e at 0x0042
I/Timeline( 5297): Timeline: Activity_launch_request id:com.twitter.android time:11725012
I/ActivityManager(  910): START u0 {flg=0x4000000 cmp=com.twitter.android/com.twitter.app.main.MainActivity} from pid 5297
D/AndroidRuntime( 5297): Shutting down VM
W/dalvikvm( 5297): threadid=1: thread exiting with uncaught exception (group=0x4165edb8)
D/audio_hw_primary(  231): out_standby: enter: stream (0xb8320cc8) usecase(1: low-latency-playback)
I/listen_hal_loader(  231): audio_extn_listen_update_stream_status(): uc_id 1 of type 0 for Event 2, with Raise=0
D/hardware_info(  231): hw_info_append_hw_type : device_name = speaker
I/listen_hal_loader(  231): audio_extn_listen_update_device_status(): device 0x2 of type 0 for Event 0, with Raise=0
D/GmsGcmMcsSvc( 1378): Heartbeat initiated, reason: Intent { act=org.microg.gms.gcm.mcs.HEARTBEAT flg=0x4 cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }
D/GmsGcmMcsSvc( 1378): Scheduling heartbeat in 60 seconds...
D/GmsGcmMcsOutput( 1378): Outgoing message: HeartbeatPing{last_stream_id_received=203}
D/GmsGcmMcsInput( 1378): Incoming message: HeartbeatAck{last_stream_id_received=199}
W/ActivityManager(  910): Launch timeout has expired, giving up wake lock!`

I have an OPO with CM 11 (Android 4.4.4), Xposed 2.6.1, XPrivacy 3.6.19 and microG 0.2.4-22.

**Comment by mar-v-in** [comment]
@alanpoulain there is nothing suspicious in the log and it does work for me. So yeah, it might be related to XPrivacy. I'll keep this issue open in case someone else reports the same problem.

**Comment by Torvin** [comment]
I don't have XPrivacy. I have CM13 and run FakeGapps through XPosed. Twitter used to crashed for me too, in Exif decoder, but I didn't save the logcat and it doesn't crash anymore.

What crashes every time though is Shazam. Should I post logcat here? Or create a separate issue?

**Comment by alanpoulain** [comment]
OK I have resolved the issue: I was blocking getRunningAppProcesses in XPrivacy and Twitter seems to not like it.
Sorry to have bothered you, you can close this issue. Maybe @Torvin should create another issue.

**Comment by mar-v-in** [comment]
@Torvin yes, please create a seperate issue for that. Closing here.

**Comment by Torvin** [comment]
@mar-v-in done: https://github.com/microg/android_packages_apps_GmsCore/issues/213
