### ISSUE TITLE
Add an option to allow / disallow / ask for a remote installation

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#212]
It would be nice to have an option to auto-allow / auto-disallow / ask for a remote installation when I go on the Play Store site and I choose install on an app's page.

**Comment by mar-v-in** [comment]
Remote installations are managed through Play Store (the Play Store app or in case you use BlankStore/FakeStore, it would be the responsibility of those), not Play Services / GmsCore. You could add this issue to the Phonesky repo, but certainly it won't be fixed soon as Phonesky is not even usable right now :)

**Comment by ale5000-git** [comment]
I was hoping it was in play services, well nevermind.
