### ISSUE TITLE
is Signature Spoofer same as Disabling Signature check?

### ISSUE THREAD

**Issue by evildog1** [microg/android_packages_apps_GmsCore#215]
Lucky Patcher app have 3 options to patch signature. is it the same as Signature Spoofer?
I don't want to install Xposed or install Python just to path my device.

![image](https://cloud.githubusercontent.com/assets/8687585/19211961/cfc0d4e6-8d48-11e6-903a-f780493f582b.png)

**Comment by Lanchon** [comment]
no it is not. but you could make microg work if you rebuild the microg apps with google's signatures (which will obviously not pass checking in unpatched androids). Lucky Patcher is closed source AFAIK, don't use it. look for XInstaller for similar mods and more.

**Comment by evildog1** [comment]
close
