### ISSUE TITLE
Problem installing New app

### ISSUE THREAD

**Issue by Catfriend1** [microg/android_packages_apps_GmsCore#217]
Device: lg-g4 h815 Android 6.0 cm13 dated nightly 16-09-05
Microg up to date 4.22
Fakegapps up2date with xposed.
Everything is Wirkung including playnstore gcm ....
But i cannot Install lovoo chat from gplay store.

Heres logcat extract:
10-13 22:50:49.418 E/Finsky  (26912): [1]  google.android.finsky.installer.ad.onReceive(3633): Error -507 while installing net.lovoo.android: INSTALL_FAILED_MISSING_SHARED_LIBRARY: Package couldn't be installed in /data/app/net.lovoo.android-1: Package net.lovoo.android requires unavailable shared library com.google.android.maps; failing!

I do have a Wirkung gmaps Installation.

**Comment by ale5000-git** [comment]
It has nothing to do with GmsCore, you need this: https://github.com/microg/android_frameworks_mapsv1

**Comment by Catfriend1** [comment]
Ok ill try

**Comment by Catfriend1** [comment]
Thanks it worked installing maps 1.

**Comment by ghost** [comment]
please delete issue
