### ISSUE TITLE
[Q] about sig spoofing patches

### ISSUE THREAD

**Issue by Lanchon** [microg/android_packages_apps_GmsCore#218]
hi,

intro: i made a dex "reengineering" framework called dexpatcher that modifies dalvik executable files directly without disassembling and reassembling them. the changes to be done are defined exclusively by Java source code (not dalvik bytecode) that is semantically extended with annotations. during application, the patches are checked for validity against the code to be patched, with plenty of diagnostics generated if required. the application of patches is a "lightweight" operation that can be done on memory-constraint devices. (eg: patching MM's framework.jar on a single core ARM takes 7 minutes, vs <2 minutes on quad-core ARM, vs 6 seconds on a quad-core i7.)

context: i made a couple of patches for microG signature spoofing. the advantage compared to needle/tingle (besides being much clearer about the changes made, giving stronger warranties regarding correct functioning if the patch applies, and ability to run on constrained devices) is that the patches can do more complex stuff, like adding UI to control the spoofing (as in Omni 5.x or better).

now the Q:
- ive seen that you originally patched PackageParser.generatePackageInfo().
- later you switched to patching PackageManagerService.generatePackageInfo(), which is a specific client of PackageParser.

this means that, potentially, the first patch-style can provide more "functionality" than the second. for example: maybe the second style can only lie to apps that query the system about signatures; while the first style could -on top of that- also lie to the OS itself and permit stuff like "upgrading" a "genuine" app with a fake-signature variant from a different origin without erasing its data, participating in signature-based private data sharing between genuine and faked apps, etc.

so my question is: are you aware of any performance difference between these patching styles? is there a reason to prefer one over the other? or a reason to support both styles?

and i'll take the opportunity to thank you for microG. i think it's the single most important FLOSS project being done on android by far. and although i think android is beyond the point of no return an the FLOSS community should just discard it and move to a different linux distro, microg is the only true hope remaining for android IMO.

my wish is to see android dead and replaced by really free software. but whatever comes next will have to run android apps, and your project also holds the key to that so it is doubly important.

thanks so much!

**Comment by mar-v-in** [comment]
Both approaches can not be used to lie to the OS because both are not used in the installation process: Although the PackageParser is used, the patch modifies the signature when the PackageParser creates a `PackageInfo` object. This is only used for the public API, the internal class is `PackageParser.Package`.

The reason to switch to the `PackageManagerService` in later versions is that runtime permissions are not available in the `PackageParser`, which works directly on the package file, whereas `PackageManagerService` knows about runtime permissions.

**Comment by Lanchon** [comment]
thanks! yes, i've seen that. but in the 5.1 patch you only use `PackageParser.Package.requestedPermissions` and still switched to patching `PackageManagerService`:
https://gerrit.omnirom.org/#/c/14898/1/services/core/java/com/android/server/pm/PackageManagerService.java
so it looks like before 6.0 runtime permissions there's no **implementation** reason to choose one over the other.

but setting aside implementation issues, are you aware of any performance difference between these patching styles? is there something that patching the parser does, that patching the service does not?

**Comment by mar-v-in** [comment]
For the OmniROM patch (that has an entry in system settings UI), it was required to read settings. The `PackageParser` has no reference to an Android `Context` implementation, which is necessary to access system settings, this is why the move to `PackageManagerService`.

I don't think there are relevant performance differences between those two when patching from source or at runtime. However when you patch the binary you are probably a few times faster when doing it for `PackageManagerService` as it resides in `services.jar/.odex` instead of `framework.jar/boot.oat`, which is a lot smaller.

**Comment by xyyx** [comment]
Hi all. I tried to use microG with Nougat - https://github.com/nitrogen-project/android_frameworks_base/commit/2700d7f2230f4c306be97ed2d088f5a16d334d3d

But I don't have working fake signatures( http://imgur.com/a/JVV7S

**Comment by danielegobbetti** [comment]
@xyyx I am using the original patch for M (the one in this repo) on my AOSP build of N and it works well.

**Comment by xyyx** [comment]
It's based on original but use switch) Maybe this switch is root cause

**Comment by ale5000-git** [comment]
@xyyx: Have you enabled the option in the developer settings?

**Comment by xyyx** [comment]
Yes. I used it not in Develop Settings. In my menu) I'll check it again.

**Comment by ale5000-git** [comment]
There are many patch so I'm not sure but check everything just in case.
There may be an option in developer settings and also a signature spoofing permission to grant.

**Comment by xyyx** [comment]
Ok, guys. I don't check it in permission. http://imgur.com/a/wOuAV
All good now)

**Comment by Lanchon** [comment]
hi @mar-v-in,

ok, i've had some time to do a write-up and publish the sig spoof patches; they are here:
https://github.com/Lanchon/haystack

thanks again!

**Comment by Lanchon** [comment]
and another thing that you may want to link is this:
https://github.com/Lanchon/sigspoof-checker

in contrast to microG, this app can be installed to test sigspoof even if the phone has google crap installed.
