### ISSUE TITLE
com.google.android.gms.ads.identifier.service.START missing

### ISSUE THREAD

**Issue by n76** [microg/android_packages_apps_GmsCore#22]
In playing around with play-services-core-debug.apk some more, there are some apps complaining that play services are not installed. The Meetup app is one and it has an okay button after the message. If pressed, the app crashes. Looks like there are two things here. One a missing api for something that looks like an ad service (maybe should be added to play-services-core) and something that might be a Meetup app issue or an unexpected null pointer from play-services-core:

    W/ActivityManager( 1256): Unable to start service Intent { act=com.google.android.gms.ads.identifier.service.START pkg=com.google.android.gms } U=0: not found
    E/AndroidRuntime( 3351): FATAL EXCEPTION: main
    E/AndroidRuntime( 3351): Process: com.meetup, PID: 3351
    E/AndroidRuntime( 3351): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.migrateExtraStreamToClipData()' on a null object reference
    E/AndroidRuntime( 3351): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1494)
    E/AndroidRuntime( 3351): 	at android.app.Activity.startActivityForResult(Activity.java:3745)
    E/AndroidRuntime( 3351): 	at android.app.Activity.startActivityForResult(Activity.java:3706)
    E/AndroidRuntime( 3351): 	at android.app.Activity.startActivity(Activity.java:4016)
    E/AndroidRuntime( 3351): 	at android.app.Activity.startActivity(Activity.java:3984)
    E/AndroidRuntime( 3351): 	at com.google.android.gms.dynamic.zza$5.onClick(Unknown Source)
    E/AndroidRuntime( 3351): 	at android.view.View.performClick(View.java:4780)
    E/AndroidRuntime( 3351): 	at android.view.View$PerformClick.run(View.java:19866)
    E/AndroidRuntime( 3351): 	at android.os.Handler.handleCallback(Handler.java:739)
    E/AndroidRuntime( 3351): 	at android.os.Handler.dispatchMessage(Handler.java:95)
    E/AndroidRuntime( 3351): 	at android.os.Looper.loop(Looper.java:135)
    E/AndroidRuntime( 3351): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
    E/AndroidRuntime( 3351): 	at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime( 3351): 	at java.lang.reflect.Method.invoke(Method.java:372)
    E/AndroidRuntime( 3351): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
    E/AndroidRuntime( 3351): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    W/ActivityManager( 1256):   Force finishing activity 1 com.meetup/.activity.Bootstrap

**Comment by mar-v-in** [comment]
Can you please provide more details about how you use the Meetup app? I ran it without problems using version 2.7.7 and login with my e-mail address (not using Google sign in)

**Comment by n76** [comment]
I too use my non-google email to log in, and the app generally functions. But on first start I get a message saying my phone does not support Play Services along with a "okay" button. If that button is pressed the app crashes.

With respect to function, I am able to browse new meetup events, RSVP for them (having them added to my calendar), send and receive messages and to upload photos. So all the functionality I need is there, just this annoying little message that if acknowledged crashes the app.

I have also noticed in my logcat:

    W/GooglePlayServicesUtil(24113): Google Play Store signature invalid.
    E/GooglePlayServicesUtil(24113): Google Play services is invalid. Cannot recover.

Which leads me to think I have installed something wrong. I have installed BlankStore and it appears to be running fine in that I can browse apps, install apps, update apps, etc.

**Comment by mar-v-in** [comment]
Which version of BlankStore are you using? Are you using the system patch or the Xposed module?

**Comment by n76** [comment]
"Android Market" (com.android.vending) is showing as 0.7.2 in my App Info.

I do not have Xposed installed. I have read of a "system patch" but have not seen what it is or how to do it.

**Comment by mar-v-in** [comment]
https://github.com/microg/android_packages_apps_GmsCore/blob/master/android_frameworks_base%2BFAKE_PACKAGE_SIGNATURE.patch
This is the system patch. Either this or an Xposed module is required to properly run GmsCore. This is due to the signature check inside play services that needs to be bypassed and unfortunately there is no way to come around this.

If you're able and willing to run OmniROM 4.4, it already contains the system patch. There are some other custom ROMs that include the patch, but none of the big players.

**Comment by n76** [comment]
Hmmm. Can I just compile and insert a new PackageParser or do I need to build the whole ROM?

I am running the ZMoD Android 5.1.1 as found at http://forum.xda-developers.com/galaxy-nexus/development/rom-cyanogenmod-12-beta-builds-t3060319

Quite frankly my limited experience with Xposed was not pleasant. If I do go that way again, which specific Xposed module would I need?

**Comment by bonanza123** [comment]
You need this Xposed module: https://github.com/thermatk/FakeGApps/releases

**Comment by n76** [comment]
Hmmm. Xposed seems not to be compatible with 5.1 (yet). I've put a comment on the XDA thread for the ROM I am using asking for the patch to be installed.

For my edification, is there an explanation of what the signature issue is? And with that explanation, I guess this issue can be closed as with an unpatched 5.1 ROM I am not running a system that can be supported at the moment.

**Comment by bonanza123** [comment]
Try this http://forum.xda-developers.com/xposed/super-alpha-posted-permission-xposed-t3072979 for android 5.1 (its working fine)

**Comment by n76** [comment]
Thank you bonanza123 for that. I will mull this over. . . I haven't been able to find a recovery for my Galaxy Nexus (maguro) that supports both f2fs and encryption properly (running a special build of TWRP). Net result is I am a bit leery of doing things that look like they rely on putting flashable ZIPs into /data and then expecting recovery to find them. It looks like I can sideload them for initial install but after that?

**Comment by bonanza123** [comment]
what do you mean with initial install? you flash the zip once and the modules are then installed from android itself (I also have a maguro and troubles finding proper kernels and recoveries ;-) ).

**Comment by n76** [comment]
Okay, bit the bullet and installed the Xposed frame work and module posted. Reinstalled play-services-core-debug.apk and thing appear to be working now. I fired up three apps that had complained from time to time about missing Play Services and they are not complaining now (Meetup, Skype and one for a hotel chain). I also installed the current version of YouTube using Blankstore and it runs too.

Only issue now is that the phone boots slower and acts a bit weird (flashing several screens quickly) when getting to the point where it wants the encryption PIN. I hope I can get the ROM developer to add the patch so I can drop Xposed.

**Comment by bonanza123** [comment]
For Xposed it usually advised to stay to AOSP as close as possible or using some major ROMs like cyanogen. This is because each ROM may have undertaken some special system changes such as framework specific modifications that may lead to unexpected behaviour with Xposed. (Btw, as you seem to be new to Xposed, have a look at this here: http://forum.xda-developers.com/xposed/modules/xprivacy-ultimate-android-privacy-app-t2320783 maybe you will like it)

**Comment by n76** [comment]
When I used CM11 I tried Xposed specifically to try Xprivacy. I was perhaps over zealous on restricting permissions and I got into a condition were I couldn't even make calls. The ROM I am using is released by the official maintainer of CM for Maguro and is probably closer to AOSP that CM is. Until I installed Xposed it was remarkably snappy. Now it is feeling about like CM11 was.
