### ISSUE TITLE
microg.org is down

### ISSUE THREAD

**Issue by myroad94** [microg/android_packages_apps_GmsCore#221]
Multiple ping from my computer or online ping site shows that microg.org is down for days. So we are stuck with the old versions because we cannot use fdroid repo.

**Comment by mar-v-in** [comment]
Fixed. Sorry for the outage.

**Comment by ale5000-git** [comment]
@mar-v-in: The site is offline again.

**Comment by mar-v-in** [comment]
See microg/microg.org#6
