### ISSUE TITLE
Android 7.1 (AICP 12.1) crash on CheckBoxPreference

### ISSUE THREAD

**Issue by Nanolx** [microg/android_packages_apps_GmsCore#224]
I just installed microG on AICP 12.1 on lux (Moto X Play). Everything is fine and dandy, except that

Settings > Accounts > Google

is crashing. logcat:

`11-14 22:03:10.451  5314  5332 D Index   : Indexing locale 'de_DE' took 8 millis
11-14 22:03:10.466  5314  5332 D Index   : Indexing locale 'de_DE' took 8 millis
11-14 22:03:10.499  5314  5332 W TileUtils: Found com.android.systemui.tuner.TunerActivity for intent Intent { act=com.android.settings.action.EXTRA_SETTINGS } missing metadata 
11-14 22:03:10.511  5314  5332 D Index   : Deleting data for locale 'de_DE' took 6 millis
11-14 22:03:10.517  5314  5332 D Index   : Indexing locale 'de_DE' took 6 millis
11-14 22:03:10.528  5314  5314 E RecyclerView: No adapter attached; skipping layout
11-14 22:03:10.590  1484  1558 I ActivityManager: Displayed com.android.settings/.Settings$AccountSettingsActivity: +284ms
11-14 22:03:10.625  5314  5329 D OpenGLRenderer: endAllActiveAnimators on 0x97af7700 (RippleDrawable) with handle 0x993b5820
11-14 22:03:10.973  1484  1503 I WindowManager: Destroying surface Surface(name=com.android.settings/com.android.settings.Settings) called by com.android.server.wm.WindowStateAnimator.destroySurface:2033 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:884 com.android.server.wm.WindowState.destroyOrSaveSurface:2095 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3047 com.android.server.wm.WindowManagerService.relayoutWindow:2913 com.android.server.wm.Session.relayout:215 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:136 
11-14 22:03:11.300  1484  2338 I ActivityManager: START u0 {act=android.intent.action.MAIN cmp=com.android.settings/.SubSettings (has extras)} from uid 1000 on display 0
11-14 22:03:11.378  5314  5314 D SubSettings: Launching fragment com.android.settings.accounts.ManageAccountsSettings
11-14 22:03:11.430  5314  5328 D Index   : Indexing locale 'de_DE' took 8 millis
11-14 22:03:11.444  5314  5314 D AndroidRuntime: Shutting down VM
11-14 22:03:11.446  5314  5314 E AndroidRuntime: FATAL EXCEPTION: main
11-14 22:03:11.446  5314  5314 E AndroidRuntime: Process: com.android.settings, PID: 5314
11-14 22:03:11.446  5314  5314 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.android.settings/com.android.settings.SubSettings}: android.view.InflateException: Binary XML file line #19: Error inflating class (not found)CheckBoxPreference
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3403)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3443)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2716)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6088)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class (not found)CheckBoxPreference
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.support.v7.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:301)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:359)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.support.v7.preference.PreferenceInflater.rInflate(PreferenceInflater.java:361)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.support.v7.preference.PreferenceInflater.inflate(PreferenceInflater.java:167)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.support.v7.preference.PreferenceInflater.inflate(PreferenceInflater.java:117)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.support.v7.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:122)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at com.android.settings.accounts.AccountPreferenceBase.addPreferencesForType(AccountPreferenceBase.java:162)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at com.android.settings.accounts.ManageAccountsSettings.addPreferencesForType(ManageAccountsSettings.java)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at com.android.settings.accounts.ManageAccountsSettings.addAuthenticatorSettings(ManageAccountsSettings.java:410)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at com.android.settings.accounts.ManageAccountsSettings.showAccountsIfNeeded(ManageAccountsSettings.java:402)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at com.android.settings.accounts.ManageAccountsSettings.onResume(ManageAccountsSettings.java:112)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.Fragment.performResume(Fragment.java:2399)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1032)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2049)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.FragmentController.dispatchResume(FragmentController.java:198)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6804)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3380)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	... 10 more
11-14 22:03:11.446  5314  5314 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.preference.CheckBoxPreference" on path: DexPathList[[],nativeLibraryDirectories=[/system/priv-app/TeleService/lib/arm, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.support.v7.preference.PreferenceInflater.createItem(PreferenceInflater.java:233)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.support.v7.preference.PreferenceInflater.onCreateItem(PreferenceInflater.java:281)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	at android.support.v7.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:290)
11-14 22:03:11.446  5314  5314 E AndroidRuntime: 	... 28 more
11-14 22:03:11.451  1484  2475 W ActivityManager:   Force finishing activity com.android.settings/.SubSettings
11-14 22:03:11.453  5314  5328 D Index   : Indexing locale 'de_DE' took 9 millis
11-14 22:03:11.454  1484  2475 W ActivityManager:   Force finishing activity com.android.settings/.Settings$AccountSettingsActivity`

**Comment by Nanolx** [comment]
On a side-note: I can't use my Google account in Maps for downloading offline areas, aswell.

**Comment by mar-v-in** [comment]
Regarding Maps: check if you granted permission to use accounts to the Google Maps App (it will not ask automatically, you need to manually grant through system settings -> apps)

Regarding crash in Settings app: I was able to reproduce it on Android 7.0 as well. Fix will be in one of the next commits.

**Comment by Nanolx** [comment]
Thank you, for the quick response!


I was previously using a modified TouchWiz ROM, where Maps was working straight ahead.

Am 15. November 2016 02:34:24 MEZ schrieb Marvin W <notifications@github.com>:
>Regarding Maps: check if you granted permission to use accounts to the
>Google Maps App (it will not ask automatically, you need to manually
>grant through system settings -> apps)
>
>Regarding crash in Settings app: I was able to reproduce it on Android
>7.0 as well. Fix will be in one of the next commits.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/microg/android_packages_apps_GmsCore/issues/224#issuecomment-260520362

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
