### ISSUE TITLE
Android 7.1 - Test Notifications Never Arrived

### ISSUE THREAD

**Issue by blaiserudaz** [microg/android_packages_apps_GmsCore#226]
On the PushNotificationTeser app, I'm stuck on "Notification arrived" (screen Step 3). Notifications do not arrive. I'm using AOSP (`NDE63P / android-7.1.0_r4`) patched for "signature spoofing" on a rooted PixelXL.

The microG `0.2.4-27-g279b35b` solve the problem of the crash in "Settings -> Accounts -> Google" but it seems that there is still a small problem with CGM communication mechanisms. I didn't see something relevant in logcat during the execution of PushNotificationTeser.

**Comment by okeer** [comment]
Same here on patched cm14.1. Version 0.2.4-22 worked fine after reconnecting to mobile data/wifi AP.

**Comment by ale5000-git** [comment]
A logcat would be helpful.

**Comment by okeer** [comment]
Yeah, [if it helps](http://pastebin.com/u4APDnWP).
What is done:
1. Wake up device;
2. Request notification via PushNotificationTester;
3. Switch "google device registration" off/on;

**Comment by okeer** [comment]
I'm using 0.2.4-27 already

**Comment by mar-v-in** [comment]
GCM connections seem to be problematic on 7.0+. I guess Google changed something with broadcasts related to connectivity changes or just "battery optimized" stuff again.
Just to make sure, please check if the following is true for you (on 0.2.4-27+) when the message is not arriving:
1. In microG Settings -> Google Cloud Messaging it says "Current state: Disconnected" and in Push Notification Tester it says "Registered" in the bottom.
2. Open Dialer and call *#*#42678278#*#* (42678278 = gcmstart). The message should arrive shortly after that.

**Comment by blaiserudaz** [comment]
I have cellular connectivity limitations with my last AOSP compilation. (no 4G) (Is this important ?)
Anyway, I will try to fix the problem this week-end and check your procedure above to provide an accurate feedback.
Thank you

**Comment by okeer** [comment]
1. Yes, GCM in microg settings set to on, but displays current state: disconnected. 
2. The magic number doesn't help - no messages so far. Logcat is clear of any GCM related entries.

**Comment by blaiserudaz** [comment]
For me the dialer call to `##42678278##` produce the error message :
"Connection problem or invalid MMI code."

[logcatIssue#226.txt](https://github.com/microg/android_packages_apps_GmsCore/files/601607/04.LogcatIssue.226.txt)

and screenshots :
![01 pushnotificationteser_step1](https://cloud.githubusercontent.com/assets/11794834/20457361/e3133888-ae89-11e6-90a2-e4aa5743a745.png)
![02 pushnotificationteser_step3](https://cloud.githubusercontent.com/assets/11794834/20457363/e7c2362c-ae89-11e6-9095-b18b2d0994fb.png)
![03 connectionproblem](https://cloud.githubusercontent.com/assets/11794834/20457365/ecce95b6-ae89-11e6-9548-ddfc5ddaea68.png)

**Comment by mar-v-in** [comment]
Sorry, The markdown thing removed the stars from my previous post, the correct code is `*#*#42678278#*#*`.

**Comment by blaiserudaz** [comment]
Ok ! Great it's working with `*#*#42678278#*#*`. All notifications now arrive and I can see in microG Settings : 
"Current State : Connected since X minutes ago."
Thank you for this valuable assistance

**Comment by okeer** [comment]
Yay! This magic works 😃 Thank you!

**Comment by mar-v-in** [comment]
Since 97f4c82 (0.2.4-28) the code should no longer be required (but is still there in case it is). If you are running Android 7.0+ it would be nice if you could check from time to time if the GCM client is connected when there is network access, to ensure this is all working now.

**Comment by bytemybits** [comment]
I was having the same problem with version 0.2.4-27, where forcing the `gcmstart` did the trick. Uninstalled microG, installed -28, rebooted and it worked on the first try. I'll monitor the GCM client connection and ping if there any issues. Thanks @mar-v-in 😃

**Comment by okeer** [comment]
GCM now works without the magic code (version -28 on cm-14.1).

**Comment by be-neth** [comment]
Same for me. (version -28 on cm 14.1)

Thanks @mar-v-in for fixing that !

**Comment by mar-v-in** [comment]
I assume this fixed since -28.
