### ISSUE TITLE
New build of the APK ?

### ISSUE THREAD

**Issue by Technowix** [microg/android_packages_apps_GmsCore#227]
Hey,
I've see some fixes have been pushed to master for 7.1, and I don't managed to get a build working, someone can have a build ready to use ? ^-^' 
Thanks.

**Comment by ale5000-git** [comment]
It is here as always: https://microg.org/download.html

**Comment by Technowix** [comment]
My bad, the last one I saw few hours ago was the 0.2.4-22, sorry for bothering.
