### ISSUE TITLE
Unable to use Black VPN app

### ISSUE THREAD

**Issue by Primokorn** [microg/android_packages_apps_GmsCore#228]
Hi,

I already used 3 VPN services on my Nexus 5 but the Android app of [BlackVPN](https://play.google.com/store/apps/details?id=com.blackvpn) doesn't work. When launching the app I have an error message saying that the app can't connect the server.

My current setup is Dirty Unicorns ROM (AOSP 6.0.1) + Xposed framework (v86) for FakeGapps (v1.1)  + GmsCore.apk (v0.2.4-22 - I also tried with v0.2.4-27) + GsfProxy.apk (v0.1.0) + Google Play Store apk + Mozilla Stumbler + Mozilla UnifiedNlp Backend.
(no firewall, no app to restrict app permissions...)

With the same custom ROM, I tried with Open Gapps Pico instead of microG package and Black VPN is working.
The support of BlackVPN confirms that there's no issue with their Android app.

I have attached a log while launching the BlackVPN app.
Thank you.

[logcat_and_device_info.zip](https://github.com/microg/android_packages_apps_GmsCore/files/599360/logcat_and_device_info.zip)

**Comment by mar-v-in** [comment]
The app seems to use GCM upstream messaging (device pushes to server) which is not working, will try to fix it this weekend.

**Comment by mar-v-in** [comment]
Should be working as of 97f4c82

**Comment by Primokorn** [comment]
Just to confirm that it works, thanks.
