### ISSUE TITLE
Signature spoofing not working on Nougat 7.1

### ISSUE THREAD

**Issue by bytemybits** [microg/android_packages_apps_GmsCore#229]
I've recently updated my OPO to CM14.1 and right away the signature spoofing was unchecked in the microG app. I basically uninstalled the FakeGApps and everything microG related, and installed everything again with the latest versions.
For some reason I don't have signature spoofing enabled, and I can't figure out why. Here's the status of my Self-Check:
![screenshot_20161119-144421](https://cloud.githubusercontent.com/assets/8046519/20456161/cbf57f58-ae66-11e6-83e1-5aa0dcb5fa2e.png)
![screenshot_20161119-144436](https://cloud.githubusercontent.com/assets/8046519/20456162/cc0a3830-ae66-11e6-8f7d-892b5081de25.png)
![screenshot_20161119-144439](https://cloud.githubusercontent.com/assets/8046519/20456163/cc1bf958-ae66-11e6-8d9e-34d792513326.png)

Is there any know issue (wasn't able to find one reported previously) with these settings for Nougat 7.1?

**Comment by okeer** [comment]
Did you built cm-14.1 rom yourself or you're using an official CM nighly?

**Comment by bytemybits** [comment]
Official CM nightly. I reported this issue as well the FakeGApps repo and supposedly there isn't Xposed support Nougat just yet, maybe that's the cause of the issue.

**Comment by okeer** [comment]
Well, maybe Xposed is the culprit. I applied signature spoofing patch and built cm-14.1 from sources. Everything checked in microg Self-Check menu so far.

**Comment by metaphorex** [comment]
You can use Needle to force signature spoofing. 
https://github.com/moosd/Needle.git

**Comment by ale5000-git** [comment]
There is also [Tingle]https://github.com/ale5000-git/tingle)

**Comment by bytemybits** [comment]
I've managed to solve the signature spoofing issue with Tingle (thanks @ale5000-git). I think FakeGApps doesn't yet support Nougat, so Needle or Tingle should do it.
This is not a microG related issue, sorry for the inconvenience and thank you for your help!
