### ISSUE TITLE
Settings for push notifications not working as expected

### ISSUE THREAD

**Issue by n76** [microg/android_packages_apps_GmsCore#230]
Thanks for the new feature to view and control which applications are registered for push notifications!

I was surprised a little while ago by getting a notification from Maps.me since I thought I'd disabled that one. I am attaching a screen shot showing the control settings for it.

I had guessed that I could leave it registered for notifications but disable the wake up and "allow registration" and that the app would be happily assuming it was registered but that it just happened that nothing was being pushed to it. But it seems this is not the case.

Especially interesting to me was that Maps.me was not a recent app and should not have been in the foreground when the notification alert from it occurred. Which also implies that the wake up disable is not working too.

I know this is a new feature. And it could be that it is working as intended but that I just made incorrect assumptions about the operation of the new feature.

Any explanations?

Thanks!
![screenshot_20161119-181135](https://cloud.githubusercontent.com/assets/4681938/20459845/b53b458a-ae85-11e6-84e2-e42152678f09.png)

**Comment by mar-v-in** [comment]
1. The app is already registered for push notifications, you can see this in the very last row together with the option to unregister (touch there). As long as the app is registered it is able to receive push notifications, the option only denies future registrations, not the current one. I guess it would be a good idea to show a pop-up if you deny registrations to let you know about this (when the app is still registered).
2. The "start app on push notification" option is currently limited to certain special cases when the app is marked as closed by the package manager which is not the same as closing the app by swiping it away in recent apps. I will extend it to these apps in a future commit.

**Comment by mar-v-in** [comment]
Both should be fixed as of 97f4c82

**Comment by blastagator** [comment]
This commit seems to have broken GCM registration - http://forum.xda-developers.com/showpost.php?p=69732960&postcount=2361
