### ISSUE TITLE
Youtube wants an updated Google Play Services

### ISSUE THREAD

**Issue by hansWURSCHT10000** [microg/android_packages_apps_GmsCore#231]
Maybe increase version number?

**Comment by Primokorn** [comment]
Which version do you have? (0.2.4-28?)

**Comment by hansWURSCHT10000** [comment]
yes 0.2.4-28

I just looked at the log and it says
`GooglePlayServicesUtil: Google Play services out of date.  Requires 9683000 but found 9258259`

**Comment by mar-v-in** [comment]
[0.2.4-28](https://microg.org/fdroid/repo/com.google.android.gms-10086487.apk) is version 10086487 which is larger than 9683000 and should not cause problems. are you sure you run on 0.2.4-28?

**Comment by hansWURSCHT10000** [comment]
Yes, you are right. I  was on 0.2.4. But F-Droid said that there are no updates (strange?) and as I looked in F-Droid for the installed Version and mixed it with the newest release. Sorry...

**Comment by mar-v-in** [comment]
0.2.4-28 is an preview release, that's why it's not shown as update in f-droid (you can enable defaulting to preview releases in f-droid settings).

**Comment by hansWURSCHT10000** [comment]
Ah makes sense
