### ISSUE TITLE
Slack wants a GMS update.

### ISSUE THREAD

**Issue by artur9010** [microg/android_packages_apps_GmsCore#232]

**Comment by artur9010** [comment]
![image](https://cloud.githubusercontent.com/assets/4835677/20529777/a672a0c2-b0d1-11e6-8200-ed29554cd087.png)

**Comment by ale5000-git** [comment]
I think many people don't understand that language.
If possible translate it to English.

**Comment by mar-v-in** [comment]
@artur9010 try updating microG Services Core to 0.2.4-28.

**Comment by artur9010** [comment]
@ale5000-git something like "please update GMS"
@mar-v-in thanks

**Comment by 3ex3** [comment]
I am also getting this warning on several apps including slack, basecamp 3 and the Wells Fargo app so far. Using 0.2.4-39.
