### ISSUE TITLE
Unregister null?

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#237]
It is just a cosmetic isssue.

In case I try to unregister an app already uninstalled it cannot get the "display name" and show a message with the title "Unregister null?".
In these cases I think it is better to display the internal name "com...." instead of null.

**Comment by mar-v-in** [comment]
Should be fixed as of ef9e9b0. by the way: this should not happen very often because microG will now automatically unregister from push notifications once an app is uninstalled (this is the same behavior the original implementation has)

**Comment by ale5000-git** [comment]
I know but it happens when you update from an old version the have it already :)
