### ISSUE TITLE
Signature spoofing patch doesn't work for Android 7.1.1

### ISSUE THREAD

**Issue by uiopc** [microg/android_packages_apps_GmsCore#245]
Hi,

I want to build a custom ROM based on Android 7.1.1... Applying the signature spoofing patch from here (https://github.com/microg/android_packages_apps_GmsCore/tree/master/patches) worked fine for Android 6 and 7.0, however for 7.1.1 I receive the following error:

Prüfe Patch core/res/AndroidManifest.xml ...
Patch-Bereich #1 erfolgreich angewendet bei 1903 (249 Zeilen versetzt)
Prüfe Patch core/res/res/values/config.xml ...
Patch-Bereich #1 erfolgreich angewendet bei 1267 (-31 Zeilen versetzt)
Prüfe Patch core/res/res/values/strings.xml ...
Patch-Bereich #1 erfolgreich angewendet bei 664 (48 Zeilen versetzt)
Prüfe Patch services/core/java/com/android/server/pm/PackageManagerService.java ...
error: bei der Suche nach:
        final Set<String> permissions = permissionsState.getPermissions(userId);
        final PackageUserState state = ps.readUserState(userId);

        return PackageParser.generatePackageInfo(p, gids, flags,
                ps.firstInstallTime, ps.lastUpdateTime, permissions, state, userId);
    }

    @Override

error: Anwendung des Patches fehlgeschlagen: services/core/java/com/android/server/pm/PackageManagerService.java:2816
error: services/core/java/com/android/server/pm/PackageManagerService.java: Patch konnte nicht angewendet werden

Can you give me a hint how to fix this?
Thanks in advance and best regards.

**Comment by mar-v-in** [comment]
OmniROM has the patch active in their 7.1 branch (see [this commit](https://github.com/omnirom/android_frameworks_base/commit/591ac9a1853f717282d2d858c91500d64a6baa8d)). What ROM are you trying to patch? There might be slight modifications in the ROM that cause the patch to fail.

**Comment by uiopc** [comment]
I tried to patch CopperheadOS...

**Comment by mar-v-in** [comment]
@uiopc try the patch I just uploaded (https://github.com/microg/android_packages_apps_GmsCore/blob/master/patches/android_frameworks_base-N.patch)

**Comment by uiopc** [comment]
Thanks a lot for your quick help :) Applying the patch works fine...
