### ISSUE TITLE
Is the Map API implementation in progress？

### ISSUE THREAD

**Issue by byronwind** [microg/android_packages_apps_GmsCore#25]
I have studied a lot for map api in google play service. But, I have not sure how the MapFragment and MapView are transferred across processes. 

So, cloud you share something about the main idea in this project ? I will look forward contributing to the map api development.

Thanks.

**Comment by mar-v-in** [comment]
> I have studied a lot for map api in google play service. But, I have not sure how the MapFragment and MapView are transferred across processes.

`MapView` and `MapFragment` are not transferred across processes. The Maps API does not require any process from the `com.google.android.gms` package to be started.

The classes are loaded into the application using a package context classloader. See [this link](https://developer.android.com/reference/android/content/Context.html#CONTEXT_INCLUDE_CODE )for details on package context classloader. The entry point used to handle any request in the Maps API is an implementation of the [`ICreator`](https://github.com/microg/android_external_GmsApi/blob/master/play-services-api/src/main/aidl/com/google/android/gms/maps/internal/ICreator.aidl) interface that must use the class name `com.google.android.gms.maps.internal.CreatorImpl` - this name is hard-coded into the play-services library and used on [`loadClass()`](https://developer.android.com/reference/java/lang/ClassLoader.html#loadClass(java.lang.String, boolean)).

[MapView](https://developers.google.com/android/reference/com/google/android/gms/maps/MapView) and [MapFragment](https://developers.google.com/android/reference/com/google/android/gms/maps/MapFragment) provided when embedding the play-services library into an application are wrappers around [IMapViewDelegate](https://github.com/microg/android_external_GmsApi/blob/master/play-services-api/src/main/aidl/com/google/android/gms/maps/internal/IMapViewDelegate.aidl) and [IMapFragmentDelegate](https://github.com/microg/android_external_GmsApi/blob/master/play-services-api/src/main/aidl/com/google/android/gms/maps/internal/IMapFragmentDelegate.aidl). 
The actual View is wrapped in an [`IObjectWrapper`](https://github.com/microg/android_external_GmsApi/blob/master/play-services-api/src/main/aidl/com/google/android/gms/dynamic/IObjectWrapper.aidl). See [`ObjectWrapper`](https://github.com/microg/android_external_GmsApi/blob/master/play-services-api/src/main/java/com/google/android/gms/dynamic/ObjectWrapper.java) for details how this does work.

> So, cloud you share something about the main idea in this project ? I will look forward contributing to the map api development.

The main idea of the whole µg project is to build a free replacement for all proprietary parts by Google injected into the Android ecosystem. This is mainly two components these days, both called Play Services: the client library play-services, that is injected into applications by their developers and GmsCore, the service component used by this library. Play services includes more or less all newer proprietary Android features.

Currently I focus my development on GmsCore and only on those portions of play services used a lot. In my experience, this is GCM/C2DM (push), Google login (OAuth), Geolocation APIs and Maps API v2.

**Comment by byronwind** [comment]
@mar-v-in .Thank u very much. Your reply is very particular.
