### ISSUE TITLE
Store native libs uncompressed and zipaligned

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#265]
If the native libs are stored in the apk uncompressed and zipaligned then they can be loaded from the apk without be pre-extracted.

It won't work on all cases but it would simplify things in most cases.

Ref: https://github.com/LineageOS/android_frameworks_base/commit/ff193d642eea7128faad837d19e347cd25212c27

**Comment by mar-v-in** [comment]
I guess this is about the case when you put microG to `/system` right?

**Comment by ale5000-git** [comment]
I think it apply to both system and data, it use the libraries from the apk without extract them.

Look [here](https://medium.com/@wkalicinski/smallerapk-part-8-native-libraries-open-from-apk-fc22713861ff#.d4o7omnhd).

**Comment by ale5000-git** [comment]
Thanks :)
