### ISSUE TITLE
cyberghost 6 for android crashing on update.

### ISSUE THREAD

**Issue by cswag** [microg/android_packages_apps_GmsCore#266]
Hey, I downloaded microg from f droid, version 0.2.4, and the app cyberghost VPN 6.0.0.57 worked fine. I later updated microg to 0.2.4-39-ga53b32e, and now the app crashes as soon as its opened, I'm not sure why. Would it be possible to run some tests to see what's going wrong?

Thanks.

**Comment by cswag** [comment]
I just noticed this is a Preview Release, so thats probably why its not 100% stable yet. If it helps for future development, I've noticed the apps CyberGhost 6.0.0.57 and "ZPN Connect" crash/become unusable.

**Comment by ale5000-git** [comment]
@cswag: Is your ploblem fixed?
