### ISSUE TITLE
microG update needed for gcm client libraries 9.6.1

### ISSUE THREAD

**Issue by icasdri** [microg/android_packages_apps_GmsCore#268]
[Signal](https://github.com/WhisperSystems/Signal-Android) recently updated Google Play Services client libraries from `8.1.0` to `9.6.1` (see [Signal-Android:build.gradle#L54](https://github.com/WhisperSystems/Signal-Android/blob/master/build.gradle#L54), and the specific commit that changed it: [Signal-Android:f310dd60](https://github.com/WhisperSystems/Signal-Android/commit/f310dd60479d746645d7473d7dacbea2a1af5c72)).

Ever since this change, Signal has been unable to register itself with GCM (through microG GmsCore), asking that I update *Google Play Services* (which of course is not possible as I am using microG).

I am using microG GmsCore version 0.2.4 (latest release) and Android 5.1 (CyanogenMod 12.1).

**Comment by ArchangeGabriel** [comment]
0.2.4-1 or 0.2.4-39?

**Comment by icasdri** [comment]
0.2.4-1 (I believe), i.e. the download from here: https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.4

Wouldn't I need to manually build GmsCore to obtain 0.2.4-39 (i.e. HEAD/master)? Is this fixed in 0.2.4-39?

**Comment by n76** [comment]
0.2.4-39-ga53b32e is available via pull down at https://microg.org/download.html

I find the easiest way to install/update this is to add the repository to F-Droid using the QR Code on the same page.

**Comment by icasdri** [comment]
I had the F-Droid repo, however it seems GmsCore is missing. Is this due to the signature spoofing (maybe F-Droid doesn't think GmsCore is GmsCore)? i.e. when I search for "microG" in F-Droid with the repo added, I see `FakeStore`, `microG Services Framework Proxy`, and `ug UnifiedNlp`, but no GmsCore.

I will try 0.2.4-39 from the downloads and see if it works.

**Comment by icasdri** [comment]
It appears to work! Thanks everyone for their help. I will report back if I have any other issues. Please do still comment/reply about the F-Droid issue if you have any idea.

**Comment by ArchangeGabriel** [comment]
@icasdri For F-Droid, yes, that is because of signature spoofing. You’ll find it under `ug UnifiedNlp`.
