### ISSUE TITLE
Gsf crashed when opening Vainglory

### ISSUE THREAD

**Issue by acsway878787** [microg/android_packages_apps_GmsCore#275]
Phone: Sony Xperia TX Android 4.3.0
microG Services Core: 0.2.4-50
microG Services Framework Proxy: 0.1.0

>01-19 22:23:10.862 I/Appboy v1.15.3 .com.appboy.Appboy(8958): Google Cloud Messaging found. Setting up Google Cloud Messaging
01-19 22:23:10.902 I/ActivityManager(1169): Start proc com.google.android.gsf for service com.google.android.gsf/org.microg.gms.gcm.PushRegisterProxy: pid=9014 uid=10017 gids={50017, 1028}
01-19 22:23:11.123 W/ActivityManager(1169): Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=9014, uid=10017 requires com.google.android.c2dm.permission.RECEIVE
01-19 22:23:11.133 W/dalvikvm(9014): threadid=10: thread exiting with uncaught exception (group=0x415ba658)
01-19 22:23:11.133 E/AndroidRuntime(9014): FATAL EXCEPTION: IntentService[GsfGcmRegisterProxy]
01-19 22:23:11.133 E/AndroidRuntime(9014): java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
01-19 22:23:11.133 E/AndroidRuntime(9014): 	at android.app.ContextImpl.startServiceAsUser(ContextImpl.java:1446)
01-19 22:23:11.133 E/AndroidRuntime(9014): 	at android.app.ContextImpl.startService(ContextImpl.java:1428)
01-19 22:23:11.133 E/AndroidRuntime(9014): 	at android.content.ContextWrapper.startService(ContextWrapper.java:473)
01-19 22:23:11.133 E/AndroidRuntime(9014): 	at org.microg.gms.gcm.PushRegisterProxy.onHandleIntent(PushRegisterProxy.java:32)
01-19 22:23:11.133 E/AndroidRuntime(9014): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
01-19 22:23:11.133 E/AndroidRuntime(9014): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-19 22:23:11.133 E/AndroidRuntime(9014): 	at android.os.Looper.loop(Looper.java:213)
01-19 22:23:11.133 E/AndroidRuntime(9014): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by mar-v-in** [comment]
Try reinstalling Gsf Proxy.

**Comment by acsway878787** [comment]
It works! Thank you very much!
