### ISSUE TITLE
Unable to apply signature spoofing patch

### ISSUE THREAD

**Issue by Piesek0515** [microg/android_packages_apps_GmsCore#279]
I am trying to apply the signature spoofing patch for a CopperheadOS build from source. I put the patch file in /frameworks/base directory of the ROMs source folder. I typed git apply android_frameworks_base-N.patch and terminal outputs:

error: patch failed: core/res/AndroidManifest.xml:1654
error: core/res/AndroidManifest.xml: patch does not apply
error: patch failed: core/res/res/values/config.xml:1298
error: core/res/res/values/config.xml: patch does not apply
error: patch failed: core/res/res/values/strings.xml:616
error: core/res/res/values/strings.xml: patch does not apply
error: patch failed: services/core/java/com/android/server/pm/PackageManagerService.java:3067
error: services/core/java/com/android/server/pm/PackageManagerService.java: patch does not apply

Am I not applying the patch correctly or is something else going on here? Thank you for the help!

**Comment by mar-v-in** [comment]
The patch is for AOSP, CopperheadOS is modified from AOSP and thus the patches might not directly apply. You can try if `patch -p1 < android_frameworks_base-N.patch` works for you.

**Comment by Piesek0515** [comment]
Thanks mar-v-in! I'll give that a try and report back.

**Comment by BenBaltz** [comment]
You can also try Haystack by Lanchon, worked like a charm for me. @Piesek0515 
https://github.com/Lanchon/haystack

The instructions are sort've weird but if you follow them it works.

**Comment by Piesek0515** [comment]
@mar-v-in the patch applied cleanly following your instructions. Thank you for the support!
