### ISSUE TITLE
Package cannot be installed

### ISSUE THREAD

**Issue by motatuc** [microg/android_packages_apps_GmsCore#280]
Hello

I get an error when trying to install android_packages_apps_GmsCore built from sources today.
I already have android_packages_apps_GmsCore installed that I built three weeks ago. But It seems the recent apk cannot be installed. Is my OS making problems or is the problem that I already got a version of GmsCore installed?

Using Android 7.

Anyways, here's the error-log:

> 01-23 12:14:13.907  1423  2667 I ActivityManager: START u0 {dat=file:///storage/emulated/0/Download/play-services-core-23.01.2017.apk cmp=com.android.packageinstaller/.InstallAppProgress (has extras)} from uid 10017 on display 0
01-23 12:14:13.952 20794 20794 W InstallAppProgress: Replacing package:com.google.android.gms
01-23 12:14:13.985   269   269 I         : free_cache(2620077) avail 5069352960
01-23 12:14:14.054  1423  1520 I ActivityManager: Displayed com.android.packageinstaller/.InstallAppProgress: +135ms
01-23 12:14:14.118 20794 20808 D OpenGLRenderer: endAllActiveAnimators on 0x7f778b0400 (RippleDrawable) with handle 0x7f778a3960
01-23 12:14:14.849  1423 16972 W art     : Long monitor contention with owner Binder:1423_8 (12335) at void com.android.server.pm.PackageInstallerService$InternalCallback.onSessionSealedBlocking(com.android.server.pm.PackageInstallerSession)(PackageInstallerService.java:1278) waiters=0 in android.content.pm.PackageInstaller$SessionInfo com.android.server.pm.PackageInstallerService.getSessionInfo(int) for 227ms
01-23 12:14:15.207  1423  2254 D NativeLibraryHelper: Library 'libvtm-jni.so' is not page-aligned - will not be able to open it directly from apk.
01-23 12:14:15.207  1423  2254 W NativeHelper: Failure copying native libraries [errorCode=-2]
01-23 12:14:15.208  1423  2254 E PackageInstaller: Commit of session 904515950 failed: Failed to extract native libraries, res=-2
01-23 12:14:15.215  1423  1433 I art     : Background sticky concurrent mark sweep GC freed 47597(3MB) AllocSpace objects, 27(1272KB) LOS objects, 27% free, 12MB/17MB, paused 5.528ms total 52.589ms
01-23 12:14:15.221 20794 20794 D InstallAppProgress: Installation error code: 4
01-23 12:14:15.450  1423  2667 W art     : Long monitor contention with owner PackageInstaller (2254) at void com.android.server.pm.PackageInstallerService$InternalCallback$1.run()(PackageInstallerService.java:1253) waiters=0 in android.content.pm.PackageInstaller$SessionInfo com.android.server.pm.PackageInstallerService.getSessionInfo(int) for 237ms

**Comment by ale5000-git** [comment]
@motatuc: Does the version provided [here](https://microg.org/download.html) work?

**Comment by ale5000-git** [comment]
@motatuc: You must zipalign the apk.

**Comment by motatuc** [comment]
Hm. I don't remember doing this with the build three weeks ago. Anyways, zipalign did the trick.
Thanks.

**Comment by ale5000-git** [comment]
@motatuc: With Android Studio it is zipaligned automatically.
Since now native libs are used directly without extraction (when possible), they need to be zipaligned.

**Comment by ale5000-git** [comment]
@mar-v-in: I have never tried to compile it but doesn't the compilation script auto zipalign the file?

**Comment by mar-v-in** [comment]
The gradle build process should automatically zipalign the file, the apk from the microG F-Droid repo is just the output of that build process and works perfectly on various android versions.

@motatuc 
I guess the reason for your problem is that you signed manually and not as part of the build process. If you sign manually or resign the apk, you need to zipalign afterwards as the signing breaks previous zipalign. To sign as part of the build process, create a file `play-services-core/user.gradle` with the following content:
```
android {
    signingConfigs {
        release {
            storeFile file('path/to/keystore/file')
            storePassword 'keystore password'
            keyAlias 'key name'
            keyPassword 'key password'
        }
    }

    buildTypes {
	release {
            signingConfig signingConfigs.release
        }
    }
}
```
As this is gradle, you can also read the info from env or sth like that by using groovy code.

I will update the wiki with these build instructions later.
