### ISSUE TITLE
Signal/CyberGhost/Others crashing on version 0.2.4-55-g4c4086a [OmniRom] [7.1.1] [LogCat Inside]

### ISSUE THREAD

**Issue by cswag** [microg/android_packages_apps_GmsCore#292]
Hey, Im running a Nexus 6P with OmniRom (Android 7.1.1) and I had MicroG version 0.2.4 stable. Everything seemed to work fine, but I would always get messages from apps to "update google play services". 

I updated microG to version 0.2.4-55-g4c4086a and now the messages are gone, but some apps crash as soon as I open them. Signal, CyberGhost VPN, and a few others (Such as ZPN Connect) are unusable, and only work if I downgrade.

I have checked all permissions, Signature Spoofing permission is granted, and I even tested with "Push Notification Tester" to make sure GCM was working. This only seems to happen with microG preview releases.

Is this something I have configured wrong? 

Thanks

**Comment by JonnyTech** [comment]
You may need to reinstall the apps for them to register correctly.

**Comment by cswag** [comment]
Yeah I tried that with CyberGhost to no avail. I will try again and report back now.

**Comment by cswag** [comment]
Just updated microg to the latest again, uninstalled all the problematic apps (cyberghost, zpn, signal) rebooted and reinstalled the apps. Signal now works, ZPN and cyberghost still crash for some reason. Is this some kind of problem with the new microG?

**Comment by ale5000-git** [comment]
@cswag: It would help if you post a logcat.

**Comment by cswag** [comment]
Do I need root? I don't have root on my device at the moment

**Comment by cswag** [comment]
If anyone else is also running the latest microG, maybe try installing CyberGhost from the play store and see if it crashes too? I'm not sure if this is just me

**Comment by ale5000-git** [comment]
@cswag: No, it doesn't need root.

**Comment by cswag** [comment]
I will try to get a LogCat shortly.

**Comment by cswag** [comment]
Im not sure if this is exactly what you need. If not, please let me know: http://pastebin.com/ED6WJYGS

**Comment by cswag** [comment]
I dont understand why the old version of microG works fine, while the new one fails.

**Comment by mar-v-in** [comment]
Both apps seem to make use of the Firebase API, which is not yet supported by microG. It was "working" before, because it refused using microG and thus did not call the code that leads to crash now.

**Comment by cswag** [comment]
Thanks for the explanation. Would there be any kind of workaround other than downgrading? It would be nice if this worked.

**Comment by tomasz1986** [comment]
I have not tested it but you may want to try blocking their Firebase related components (either using an app like MyAndroidTools or manually with `pm disable`).

**Comment by cswag** [comment]
I see, thanks :)

**Comment by mar-v-in** [comment]
@cswag This should be fixed as of 0.2.4-62 preview, can you verify it?

**Comment by cswag** [comment]
Just tested, everything works great on 0.2.4-62

Thanks :)

**Comment by brdelphus** [comment]
I'm sorry to reopen this thread, but how do I get 0.2.4-62 preview version ? I've installed 0.2.4 and I'm getting the same issues described above and i gotta fix it as well. 
Thank you

**Comment by JonnyTech** [comment]
If you are using f-droid then select the option in its settings for unstable updates.

If not then you can download: from https://microg.org/download.html

The current preview build is 0.2.4-92

**Comment by ArchangeGabriel** [comment]
Or (in F-Droid case), just go the package view and select the correct version. Unstable updates can bring you unstable updates of other packages, I’ve lost messages in another app because of that.

**Comment by brdelphus** [comment]
Thank you, i've managed to install it and now Signal is working. It's not able to find any contacts on my phone even with permissions granted, but better than crashes. 
Thanks guys
