### ISSUE TITLE
Unable to unfollow someone on Google+

### ISSUE THREAD

**Issue by Primokorn** [microg/android_packages_apps_GmsCore#293]
Hi,
When I select the **Follow** button a profile I have the below popup message and I can't do anything.
Here is the log:
> 02-07 09:46:19.703 1779 2395 I ActivityManager: START u0 {cmp=com.google.android.apps.plus/com.google.android.libraries.social.circlemembership.impl.CirclesMembershipActivity (has extras)} from uid 10135 on display 0
> 02-07 09:46:19.868 1779 1887 I ActivityManager: Displayed com.google.android.apps.plus/com.google.android.libraries.social.circlemembership.impl.CirclesMembershipActivity: +142ms
> 02-07 09:46:30.438 1779 1862 E SyncManager: Couldn't find backoff values for xxxx@gmail.com/com.google.android.apps.plus.iu.EsGoogleIuProvider:u0
> 02-07 09:46:30.457 1779 1862 E SyncManager: Couldn't find backoff values for xxxx2@gmail.com/com.google.android.apps.plus.iu.EsGoogleIuProvider:u0

![screenshot_20170207-094630](https://cloud.githubusercontent.com/assets/5938828/22684058/0961fcd4-ed1b-11e6-99c3-47a35c5ccc68.png)

**Comment by MrDodojo** [comment]
Google+ is gone so this is unneeded now?

**Comment by ale5000-git** [comment]
I think this is no longer needed, in case there is another problem please report it.
