### ISSUE TITLE
microG Services Framework crashes..

### ISSUE THREAD

**Issue by darlkr** [microg/android_packages_apps_GmsCore#297]
java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1255)	at android.app.ContextImpl.startService(ContextImpl.java:1232)	at android.content.ContextWrapper.startService(ContextWrapper.java:587)	at org.microg.gms.gcm.PushRegisterProxy.onHandleIntent(PushRegisterProxy.java:32)	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)	at android.os.Handler.dispatchMessage(Handler.java:102)	at android.os.Looper.loop(Looper.java:148)	at android.os.HandlerThread.run(HandlerThread.java:61)

Crashes every couple of hours. 11 times this week, last 8h ago.

I have an app called Snoop from fdroid, which is how I got the error.

**Comment by darlkr** [comment]
I have granted all of the permission at setup, and have not changed them since

**Comment by darlkr** [comment]
The official youtube app seems to crash sometimes with a similar error:

java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1255)	at android.app.ContextImpl.startService(ContextImpl.java:1232)	at android.content.ContextWrapper.startService(ContextWrapper.java:587)	at hen.b(Unknown Source)	at hen.a(Unknown Source)	at hek.b(Unknown Source)	at hek.a(Unknown Source)	at ipi.a(SourceFile:1000)	at pgg.a(SourceFile:261)	at pgh.run(SourceFile:3029)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)	at java.lang.Thread.run(Thread.java:818)

**Comment by darlkr** [comment]
If you could point me in the right direction, would be much appreciated

**Comment by darlkr** [comment]
YouTube crashed with that error twice, last 20th January, so it doesn't seem to be effected right now, unlike the Services Framework Proxy

**Comment by darlkr** [comment]
It is indeed microG Services Framework Proxy, sorry wasnt clear in the title

**Comment by mar-v-in** [comment]
This happens when apps have been installed *before* installing GmsCore. Reinstall microG Services Framework Proxy to fix it.

**Comment by darlkr** [comment]
Thanks

/Closed
