### ISSUE TITLE
Skype for business (lync) crash

### ISSUE THREAD

**Issue by daktak** [microg/android_packages_apps_GmsCore#298]
Skype crashes when loading, unable to get c2dm permission

I/ActivityManager: START u0 {flg=0x24000000 cmp=com.microsoft.office.lync15/com.microsoft.office.sfb.activity.dashboard.DashboardActivity} from uid 10093 on display 0
W/ActivityManager: Duplicate finish request for ActivityRecord{edf31eb u0 com.microsoft.office.lync15/com.microsoft.office.sfb.activity.SplashActivity t6145 f}
W/InstanceID/Rpc: Found 10020
W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=1877, uid=10093 requires com.google.android.c2dm.permission.RECEIVE
E/AndroidRuntime: FATAL EXCEPTION: IntentService[[PNS] PushNotificationRegistrationService]
E/AndroidRuntime: Process: com.microsoft.office.lync15, PID: 1877
E/AndroidRuntime: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
E/AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1381)
E/AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1358)
E/AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:613)
E/AndroidRuntime: 	at com.google.android.gms.iid.zzc.zzb(Unknown Source)
E/AndroidRuntime: 	at com.google.android.gms.iid.zzc.zza(Unknown Source)
E/AndroidRuntime: 	at com.google.android.gms.iid.zzc.zzb(Unknown Source)
E/AndroidRuntime: 	at com.google.android.gms.iid.zzc.zza(Unknown Source)
E/AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
E/AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
E/AndroidRuntime: 	at com.microsoft.office.sfb.common.gcm.PushNotificationRegistrationService.onHandleIntent(PushNotificationRegistrationService.java:42)
E/AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
E/AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/Process : Sending signal. PID: 1877 SIG: 9
W/DropBoxManagerService: Dropping: data_app_crash (1352 > 0 bytes)
D/GraphicsStats: Buffer count: 25
I/WindowManager: WIN DEATH: Window{be27f42 u0 com.microsoft.office.lync15/com.microsoft.office.sfb.activity.SplashActivity}
I/ActivityManager: Process com.microsoft.office.lync15 (pid 1877) has died
D/ActivityManager: cleanUpApplicationRecord -- 1877
W/ActivityManager: Service crashed 2 times, stopping: ServiceRecord{7432370 u0 com.microsoft.office.lync15/com.microsoft.office.sfb.common.ui.contacts.sync.SyncService}
V/Avrcp   : MediaController session destroyed
V/Avrcp   : Active sessions changed, 0 sessions
W/ActivityManager: Scheduling restart of crashed service com.microsoft.office.lync15/com.microsoft.office.sfb.common.gcm.PushNotificationRegistrationService in 1000ms
D/Avrcp   : Exit onActiveSessionsChanged()
W/ActivityManager: Scheduling restart of crashed service com.microsoft.office.lync15/com.microsoft.office.sfb.common.ui.app.ForegroundService in 1000ms
W/ActivityManager: Service crashed 2 times, stopping: ServiceRecord{7ca00d u0 com.microsoft.office.lync15/com.microsoft.applications.telemetry.TelemetryService}
E/FrameworkListener: read() failed (Connection reset by peer)
E/FrameworkListener: read() failed (Connection reset by peer)
I/ActivityManager: Start proc 2601:com.microsoft.office.lync15/u0a93 for activity com.microsoft.office.lync15/com.microsoft.office.sfb.activity.dashboard.DashboardActivity
W/SocketClient: write error (Broken pipe)
W/DnsProxyListener: Error writing DNS result to client
I/art     : Starting a blocking GC AddRemoveAppImageSpace
I/MAMComponents: Not initializing MAM classes because the MDM package is not installed.
I/MultiDex: VM with version 2.1.0 has multidex support
I/MultiDex: install
I/MultiDex: VM has multidex support, MultiDex support library is disabled.
D/TokenSharingManager_v1.1.7: Library works in release mode
E/Conditions: Binding.to() called but implementation type already set
E/Conditions: Binding.to() called but implementation type already set
E/Conditions: Binding.to() called but implementation type already set
E/Conditions: Binding.to() called but implementation type already set
E/Conditions: Binding.to() called but implementation type already set
E/Conditions: Binding.to() called but implementation type already set
E/Conditions: Binding.to() called but implementation type already set
E/Conditions: Binding.to() called but implementation type already set
E/Conditions: Binding.to() called but implementation type already set
E/Conditions: Binding.to() called but implementation type already set

**Comment by ale5000-git** [comment]
Apps must be installed after GmsCore otherwise they won't work.
Try to reinstall Skype.

**Comment by daktak** [comment]
Right you are.
