### ISSUE TITLE
Feature request: Stop services when not usable

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#303]
I'm not sure if it is feasible but it would be nice if the LocationServiceV2 is stopped immediately if there isn't at least one backend enabled; the same for GeocodeServiceV1

**Comment by mar-v-in** [comment]
That's not possible: The services are bound by the system, stopping them will cause location/geocode to be unavailable until next reboot.

Also note there is no reason to stop services: "running" services is mostly a state, not actual code being executed and thus no harm to battery. The memory footprint of these services is also negligible.
