### ISSUE TITLE
UI Bug: Truncated text

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#305]
After the text "but the official server requires SafetyNet requests to be" all the other text is missing.

See:
![screenshot_20170212-014424](https://cloud.githubusercontent.com/assets/15793015/22858818/b3480ada-f0c8-11e6-8b35-5848d838ddc0.png)

**Comment by mar-v-in** [comment]
There seems to be a limit of 10 lines by default, which is not enough for some screen resolutions, will remove it.

**Comment by mar-v-in** [comment]
Should be fixed in latest preview.
