### ISSUE TITLE
Strange behaviour: microG Services Core inside itself

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#306]
microG Services Core appears inside microG Services Core, I'm not sure if it is normal but it is strange.

See:
![screenshot_20170212-014517](https://cloud.githubusercontent.com/assets/15793015/22858843/6c3dfc20-f0c9-11e6-87ed-9e17518f08f8.png)

**Comment by mar-v-in** [comment]
This definitely shouldn't be the case. When you touch on it, does it list any messages?

**Comment by ale5000-git** [comment]
Yes, I see `Messages 8 (4841 bytes)`.

**Comment by mar-v-in** [comment]
Do you have original Google Play Store installed on that device? It might be that Google sends out push notifications to Play Services even without them being registered if they feel that's a good idea...

**Comment by ale5000-git** [comment]
@mar-v-in: Yes, I have Google Play Store 5.1.11 installed.
Sometimes I disable push notifications and sometimes I re-enable them but other than that and update components I haven't done any changes.

Could you please add some code that store all the messages sent to microG Services Core (only the ones with microG Services Core as recipient)?
So I can send them to you when it re-happens.

**Comment by ale5000-git** [comment]
The problem seems to be disappeared, I will re-open it in case the problem will reappear.
