### ISSUE TITLE
Maps API V2

### ISSUE THREAD

**Issue by dk-zero-cool** [microg/android_packages_apps_GmsCore#318]
I have an app that crashes when trying to access/use the maps API. According to the log, location is working fine, but crashes when trying to display the map with the location. I can post a log of this, but first I just want to know if this API is even meant to work? Not sure if this project has gotten this far yet?

**Comment by mar-v-in** [comment]
It's meant to not crash, but not all features are supported. So, please attach a log of the crash.

**Comment by dk-zero-cool** [comment]
[Logcat](https://dl.dropboxusercontent.com/u/14234754/logcat.txt)  
[Screenshot](https://dl.dropboxusercontent.com/u/14234754/Screenshot.png)

Okay, I have attached a clean logcat that only contains logs from the moment that I open the app and to the point where it has just crashed. 

I also attached a screenshot of the app because it gives a better idea of what this app is trying to do. The app is a gas station app. It uses my current location to display a small map at the top that points to the closest gas station. It also has additional features, but that does not mater here. At the moment it just tries to load the map for a while and then it crashes. 

I am not sure exactly what the problem is with the map. I have just tried installing Google Maps, which I am guessing uses the Maps API and it is working just fine.

**Comment by ArchangeGabriel** [comment]
I don’t think that Google Maps uses the Maps API as a matter of fact, because I remember having it working without any GMS/PlayServices implementation. But I’m sure @mar-v-in will tell us.

**Comment by mar-v-in** [comment]
Found the bug causing the issue you described, will push a fix later today

**Comment by dk-zero-cool** [comment]
That was fast. Good thing I decided to report it then, I almost uninstalled the app instead. No way I would install gapps to get it working.
