### ISSUE TITLE
Can't build with AndroidStudio: AndroidManifest.xml not found

### ISSUE THREAD

**Issue by jensMF** [microg/android_packages_apps_GmsCore#32]
When I try to build this in AndroidStudio I get the error that the file AndroidManifest.xml can not be found. Can I create one by my own? (I am very new to java and android development and did not even coded more than a few lines... so I would need a simple option or a step by step instruction, sorry.)

**Comment by mar-v-in** [comment]
No, all needed files are already there.

Did you remember to run `git submodule update --init --recursive` before using Android Studio?

**Comment by jensMF** [comment]
yes I did but AndroidStudio gives me this error:
```
Error:Android Source Generator: [android_packages_apps_GmsCore] AndroidManifest.xml file not found
```

**Comment by mar-v-in** [comment]
Just a wild guess: you did not import the project correctly, probably as a legacy project, but this is a "modern" gradle project.
If this problem still persists, please consult other documentation as the problem seems not to be related to the project.
