### ISSUE TITLE
Freeze: SafetyNet Helper Sample freeze

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#320]
I was passing all tests in SafetyNet Helper Sample, then I have updated SafetyNet Helper Sample to the latest version and now it freeze (independently if SafetyNet is enabled or disabled in GmsCore).

Logcat: [SafetyNet freeze log.txt](https://github.com/microg/android_packages_apps_GmsCore/files/792088/SafetyNet.freeze.log.txt)

**Comment by mar-v-in** [comment]
Should be fixed as of d7fd344 in 0.2.4-76

**Comment by ArchangeGabriel** [comment]
Can confirm it fixed it.
