### ISSUE TITLE
Feature request: add "always true" option to safety net  settings 

### ISSUE THREAD

**Issue by jurek23452** [microg/android_packages_apps_GmsCore#332]
Add "always true" option to safety net  settings . I need root for signature spoofing .

**Comment by ArchangeGabriel** [comment]
What do you mean by that? Returning success on any SafetyNet request? That won’t work in most cases, because app are supposed to validate response server side.

Look at XDA for root+SafetyNet, I think they are solutions for this.

**Comment by jurek23452** [comment]
i tried magisk hide , its not working magisk closing xposed process

**Comment by mar-v-in** [comment]
This is technically not possible besides overlap with #301
