### ISSUE TITLE
Google Play services out of date.  Requires 10298000

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#335]
[ 03-03 02:08:55.886  9642:10407 W/GooglePlayServicesUtil ]
Google Play services out of date.  Requires 10298000 but found 10087438

**Comment by JERW86** [comment]
I have this in my logcat too.
20:19:29.612 GooglePlayServicesUtil(22091)
Google Play services out of date.  Requires 10298000 but found 10087438
Package Name: com.hyperionics.avar
App Link:
https://play.google.com/store/apps/details?id=com.hyperionics.avar

Thanks for your hard work.

**Comment by Nanolx** [comment]
The first app I have that actually throws a user-visible message because of the low version number is 'Tapas' (https://play.google.com/store/apps/details?id=com.tapastic&hl=de). It still works, since the message disappears after 2 or 3 seconds.

**Comment by jdeluyck** [comment]
Confirmed. Google docs also requires a newer version

**Comment by vermut** [comment]
Hey, guys. Do you have a nightly builds apk storage or something similar? Maybe Travis stashes them somewhere? How can I get latest master build apk?

**Comment by ale5000-git** [comment]
@vermut: You can get it [here](https://microg.org/download.html).

Use the drop-down menu to select the preview version.

**Comment by Awerick** [comment]
@vermut: The preview releases are also available via F-Droid – however updating microG via F-Droid has a problem… The comment [here](https://github.com/microg/android_packages_apps_GmsCore/issues/271#issuecomment-279191150) describes how to do it.

**Comment by vermut** [comment]
@Awerick Thank you. F-Droid 0.104 resolved it all. Needed "unstable updates" to start rolling.
