### ISSUE TITLE
Ingress and Nougat

### ISSUE THREAD

**Issue by JonnyTech** [microg/android_packages_apps_GmsCore#339]
I have just updated my ROM to LineageOS 14.1 (Android Nougat).

- wiped the phone
- flash the rom
- follow [installation instructions](https://github.com/microg/android_packages_apps_UnifiedNlp/blob/master/README.md)
- copy NetworkLocation.apk to /system/priv-app/
- reboot

The microg self-check is all ticked (apart from play store installed).
But Ingress displays this message
```
Google Play services
com.nianticproject.ingress.NemesisApplication relies onGoogle Play services, which is not supported by your device. Contact the manufacturer for assistance.
```
Ingress is unusable as it displays
```
Scanner disabled; Location inaccurate
```
Location is found with [SatStat](http://mvglasow.github.io/satstat/index.html) and [HereGPSLocation](https://github.com/borneq/HereGPSLocation) (both network and GPS).

Have I missed something?

**Comment by Herny64** [comment]
Hi JohnnyTech

I just downloaded the ingress App on my Phone 
Resurrection Remix (based on LineageOS 14.1) 
and i had no problems.

I had a similar problem two weeks ago...
How did you patched for signature spoofing ?

**Comment by Herny64** [comment]
Nevermind
,,The microg self-check is all ticked (apart from play store installed)."
Did you installed the FakeStore? Its a dummy App that spoofs the existance of the Play Store.
You can find it here: https://github.com/microg/android_packages_apps_GmsCore/wiki/Downloads

**Comment by JonnyTech** [comment]
I didn't see FakeStore in F-Droid so I disabled all repositories apart from https://microg.org/fdroid/repo and then it appeared.

Note that v0.0.1 is marked as release but v0.0.2 is newer, maybe @mar-v-in needs to tag it in Github.

But, thank you @Herny64, installing it and rebooting has worked. I must have done it with Marshmallow but forgotten about it as I didn't think that having a store was important..

FYI I used [Tingle](https://github.com/ale5000-git/tingle) for signature spoofing - it has never let me down.

**Comment by ale5000-git** [comment]
For reference, if you don't have Play Store or Fake Store or another app that identify as Play Store many apps won't detect Google Play services.

PS: If you use GmsCore you don't have to copy NetworkLocation.apk to /system/priv-app/ but GmsCore.apk (and if you don't have a ROM that can load native libraries directly from the apk you have to also manually extract them).
