### ISSUE TITLE
Cannot paste email or password when setting up Google account

### ISSUE THREAD

**Issue by n76** [microg/android_packages_apps_GmsCore#34]
When setting up a Google account using GmsCore, I attempted to paste account ID/email and password information from KeePassDroid but a long press in the fields did not bring up the expected "paste" contextual option. Since my passwords are all long, unique, impossible to remember and difficult to type this is a short coming for me.

**Comment by nu11point3r** [comment]
I can confirm this issue. I am unable to paste a two factor code from an authenticator app.
