### ISSUE TITLE
Broken with Play Store version 7.6.08.N-All [0] [PR] 149245622

### ISSUE THREAD

**Issue by ShapeShifter499** [microg/android_packages_apps_GmsCore#341]
I've been compiling the latest LineageOS 14.1 with the following two patches.

https://github.com/microg/android_packages_apps_GmsCore/blob/master/patches/android_frameworks_base-N.patch
https://github.com/microg/android_packages_apps_UnifiedNlp/blob/master/patches/android_frameworks_base-N.patch

Since I was having issues trying to go from a build made on 03/12/2017 I decided to build a fresh one today, 03/09/2017 and install from scratch. Naturally I downloaded the latest Google Play Store apk to install along side microG in /system/priv-app/Phonesky/Phonesky.apk  So far the Play Store does not connect and causes microG framework to crash "microG Services Framework Proxy has Stopped". The Play Store itself displays "Error retrieving information from server. [RH-01]"

What should I do at this point?

Also possibly related is my issue with UnifiedNlp here, https://github.com/microg/android_packages_apps_UnifiedNlp/issues/132

System:
Moto X Pure (Clark)
LineageOS 14.1 Built on 03/09/2017
microG Services Framework Proxy v0.1.0
UnifiedNlp (no GAPPS) v0.2.4-79-g7f13738
LocalWifiNlpBackend v1.1.6
MozillaNlpBackend v1.3.2
NominatimNlpBackend v1.2.1

**Comment by ShapeShifter499** [comment]
I found a workaround, use Google Play Store version 7.6.07.N-All [0] [PR] 148468439 or older.    The other issue microg/android_packages_apps_UnifiedNlp#132 still affects me though.

**Comment by ShapeShifter499** [comment]
Closed, no longer an issue with microG version 0.2.4-81-gb1e98ea

**Comment by ale5000-git** [comment]
You get "Error retrieving information from server. [RH-01]" when "Google device registration" is disabled in microG settings.

**Comment by ShapeShifter499** [comment]
@ale5000-git I've since switched to NanoMod, I use that patcher and the official builds from LineageOS.   I've noticed that this error occurs on the first start of Play Store even with "Google device registration" switched on before launching the Play Store.  I find I have to clear the Play Store data and settings once my device is logged in to a Google account to get it to finally load.

**Comment by ShapeShifter499** [comment]
Seems like the Play Store tries to load without first having you accept "terms and conditions". After clearing data and loading a second time I get a "terms and conditions" pop up.

**Comment by token0** [comment]
Faced this issue with 7.8.16.P-all [0] [PR] 155590935
microG version is 0.2.9.19420-5 (cfc90b4)

And how I resolved it:
Settings → Applications → Play Store 
    1. Stop
    2. Remove all data
    3. Disable application
    4. Enable application

After that, when you start it, it asks you to accept "Terms and conditions" and works after as should.
PS: without steps 3 and 4 it doesn't work.
