### ISSUE TITLE
RuneScape Companion crash on start-up

### ISSUE THREAD

**Issue by Octopusss** [microg/android_packages_apps_GmsCore#343]
Hello readers,

Since Android 7.1.1 (LineageOS 14.1) I am pushing MicroG Core (v0.2.4-79) to my System/Priv-app folder in order to receive network location.

Previously I just had installed MicroG like any other app, RuneScape Companion worked fine and I received GCM push-notifications. Now, RuneScape crashes at start-up when (I think) it wants to register itself for GCM. Other apps like Signal work with GCM with MicroG in System/priv-app folder in my case.

I tried to find out how to make a log of the crash, but I can't find a way how to. Is there anyone who can help me with my crashing app and if needed how to produce a bugrepport/logcat?

Device: OnePlus 3
OS: LineageOS 14.1 Android 7.1.1
Securitypatch: march 5
MicroG version: 0.2.4-79
RuneScape Companion version: 1.0.6

**Comment by JonnyTech** [comment]
You need to remove then reinstall your GCM app after installing MicroG.

**Comment by Octopusss** [comment]
Thank you for your answer, unfortunately after reinstalling RuneScape Companion MicroG is still crashing when I launch RuneScape Companion.

In my previous post I mentioned RuneScape crashing, this is not correct, MicroG is crashing when I launch RuneScape, sorry for the typo.

Do you have other possible solutions?

**Comment by n76** [comment]
Can you get a logcat of the crash? That would help determine what the fix should be.

**Comment by JonnyTech** [comment]
I just installed RuneScape Companion to check. It starts up correctly and takes me to a login page (I have not logged in as I do not have an account). Then went to MicroG settings and looked at Google Cloud Messaging but Runescape Companion was not listed there. Are you sure that it uses GCM?

My setup details are: Download microG Services Core from https://microg.org/download.html and copy to /system/priv-app/ then reboot and setup as normal.

**Comment by Octopusss** [comment]
I am 100% sure RS Companion uses GCM because earlier when I had MicroG installed as user app, RS Companion was listed in the MicroG Core app as using GCM. 

RS Companion makes an attemp to register itself to the GCM network right after you log in, before log in I don't experience any crash of MicroG Services Framework Proxy.

Unfortunately like I mentioned in my first post I don't know how to produce a logcat, if someone would give me a hint or link to a how-to I would gladly make one.

Could my problem exist because I don't have MicroG Services Framework Proxy installed in System/Priv-app?

**Comment by Herny64** [comment]
I found this Tutorial on xda:
https://forum.xda-developers.com/showthread.php?t=2141817
It explains how to make a logcat log. if something does not work like expected feel free to ask here for help.

**Comment by Herny64** [comment]
Oh, this is a Windows Guide. Are you on windows ?

**Comment by mar-v-in** [comment]
@Octopusss reinstall microG Services Framework Proxy (not microG Services Core that you put in `/system`)

**Comment by Octopusss** [comment]
@mar-v-in That worked! Thank you very much for all the time and effort you put into MicroG, am really loving your project!

@Herny64 Thanks for your help and thanks for the guide, I will use it for the future.
