### ISSUE TITLE
"Package x requires unavailable shared library com.google.android.maps; failing!"

### ISSUE THREAD

**Issue by darlkr** [microg/android_packages_apps_GmsCore#347]
Can't install an app

03-22 08:37:12.249 I/PackageManager.DexOptimizer(5843): Running dexopt (dex2oat) on: /data/app/vmdl1535076303.tmp/base.apk pkg=com.ombiel.campusm.angliaruskin isa=arm64 vmSafeMode=false debuggable=false oatDir = /data/app/vmdl1535076303.tmp/oat bootComplete=true
03-22 08:37:23.622 W/PackageManager(5843): Package couldn't be installed in /data/app/com.ombiel.campusm.angliaruskin-1
03-22 08:37:23.622 W/PackageManager(5843): com.android.server.pm.PackageManagerException: Package com.ombiel.campusm.angliaruskin requires unavailable shared library com.google.android.maps; failing!
03-22 08:37:23.622 W/PackageManager(5843): 	at com.android.server.pm.PackageManagerService.updateSharedLibrariesLPw(PackageManagerService.java:6709)
03-22 08:37:23.622 W/PackageManager(5843): 	at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:7074)
03-22 08:37:23.622 W/PackageManager(5843): 	at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:6801)
03-22 08:37:23.622 W/PackageManager(5843): 	at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:12850)
03-22 08:37:23.622 W/PackageManager(5843): 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:13536)
03-22 08:37:23.622 W/PackageManager(5843): 	at com.android.server.pm.PackageManagerService.-wrap28(PackageManagerService.java)
03-22 08:37:23.622 W/PackageManager(5843): 	at com.android.server.pm.PackageManagerService$9.run(PackageManagerService.java:11208)
03-22 08:37:23.622 W/PackageManager(5843): 	at android.os.Handler.handleCallback(Handler.java:739)
03-22 08:37:23.622 W/PackageManager(5843): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-22 08:37:23.622 W/PackageManager(5843): 	at android.os.Looper.loop(Looper.java:148)
03-22 08:37:23.622 W/PackageManager(5843): 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-22 08:37:23.622 W/PackageManager(5843): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)

**Comment by darlkr** [comment]
I have all ticks in Self-Check

**Comment by mar-v-in** [comment]
You need [mapsv1](https://github.com/microg/android_frameworks_mapsv1) or legacy [MapsAPI](https://github.com/mar-v-in/MapsAPI) to run apps that require deprecated maps api v1

**Comment by darlkr** [comment]
Thanks

**Comment by n76** [comment]
@mar-v-in Which of the two Maps API v1 implementations is preferred? I've run both (at different times) and both seem to have some issues.

Also, neither seem to be under further development. Do I assume correctly that the one with source on GitHub is more likely to be fixed if specific issues found?

Unfortunately, it seems that even some recently developed apps use the v1 API so issues with the microG implementation won't fade with time.
