### ISSUE TITLE
Unable to remove Google account

### ISSUE THREAD

**Issue by n76** [microg/android_packages_apps_GmsCore#35]
Once a Google account is configured it does not seem to be possible to remove it short of removing GmsCore. For some other accounts I can access settings->accounts and then long press on the account and get an option for removing, but not for the Google account presented by GmsCore.

**Comment by Tentos** [comment]
Just a question: which Android version do you use? Does your smartphone have a custom user interface like the Samsung smartphones?

**Comment by n76** [comment]
Galaxy Nexus (Maguro) running ZMoD 5.1 ROM (basically pretty close to AOSP): http://forum.xda-developers.com/galaxy-nexus/development/rom-cyanogenmod-12-beta-builds-t3060319

**Comment by mar-v-in** [comment]
@n76 the procedure to remove an account on Android 5.1 should be `Settings -> Accounts -> Google -> [email address] -> [overflow menu] -> Remove Account`, no long press is needed.

**Comment by n76** [comment]
That works, I guess it wasn't obvious to me.
