### ISSUE TITLE
Google Play Services Spoofing Failed

### ISSUE THREAD

**Issue by ev3y2** [microg/android_packages_apps_GmsCore#352]
- clean flash of TWRP 3.0.4-1 + 4.1.0 firmware+modem + latest OmniRom 7.1 for OnePlus 3 (omni-7.1.1-20170326-oneplus3-WEEKLY)
- follow [instructions](https://github.com/microg/android_packages_apps_GmsCore/wiki/Installation) while also granting all permissions possible (spoofing and standard (location, modify storage, etc)) during step 4, choosing FakeStore (yes I rebooted my phone after this)
- install and run [Push Notification Tester](https://play.google.com/store/apps/details?id=com.firstrowria.pushnotificationtester)

leads to error "Push Notification Tester relies on **Google Play services, which is not supported by your device**. Contact the manufacturer for assistance" and leaves a red x instead of a green check-mark for "Play Services installed.

- all check-boxes for signature spoofing support and installed packages are checked except "Play Store (Phonesky) has correct signature"

Without microG, my phone cannot register for push notifications nor does it recognize Play Services being installed; with microG it can register for push notifications but still doesn't recognize Play Services being installed. What is going on here?

**Comment by iRave** [comment]
Go into Settings->Apps->Gear(in top right corner)->App Permissions->Scroll down to signature spoofing->Click signature spoofing and apply it for FakeStore

The problem here is, that the FakeStore app does not request the signature spoofing permission by itself, therefore you have to grant it manually.

**Comment by ev3y2** [comment]
I did this and then it told me Play Services needed to be updated; so I redid the process in the instructions but this time with the latest release of Services Core (0.2.4-81-gb1e98ea), making sure to enable Google device registration and Google Cloud Messaging. Push Notification Tester says Play Services is installed now, but now it fails to "Register for Push Notifications".

**Comment by ev3y2** [comment]
I'll just open a new issue for this as it seems to be an unrelated problem.

**Comment by Derlafff** [comment]
You can also just `adb shell pm grant com.android.vending android.permission.FAKE_PACKAGE_SIGNATURE` (a simple solution for google lurkers with signature spoofing patches that do not allow poking this in GUI)

**Comment by derlaft** [comment]
You can also just `adb shell pm grant com.android.vending android.permission.FAKE_PACKAGE_SIGNATURE` (a simple solution for google lurkers with signature spoofing patches that do not allow poking this in GUI)
