### ISSUE TITLE
Services Core (0.2.4-81-gb1e98ea) Fails to Register for Push Notifications

### ISSUE THREAD

**Issue by ev3y2** [microg/android_packages_apps_GmsCore#353]
- clean flash of TWRP 3.0.4-1 + 4.1.0 firmware+modem + latest OmniRom 7.1 for OnePlus 3 (omni-7.1.1-20170326-oneplus3-WEEKLY)
- follow [instructions](https://github.com/microg/android_packages_apps_GmsCore/wiki/Installation) while also granting all permissions possible (spoofing and standard (location, modify storage, etc)) during step 4, choosing **Services Core Version 0.2.4-81-gb1e98ea** and FakeStore (which I manually grant signature spoofing permissions to)
- enable Google device registration and Google Cloud Messaging
- reboot phone
- all check-boxes for signature spoofing support and installed packages are checked
- install and run [Push Notification Tester](https://play.google.com/store/apps/details?id=com.firstrowria.pushnotificationtester)

push notification test completes except that **"Register for Push Notifications" fails with a red x**

note that it **does complete the register for push notifications check on Services Core Version 0.2.4 stable**; however, this version is prompted to update

_continuation of #352_

**Comment by ev3y2** [comment]
Further testing reveals that apps like Skype and Signal are able to register for push notifications and show up in the Google Cloud Messaging sub-menu of the microG Settings app. Among the three apps it is only the Push Notification Tester that fails to register or show itself in the sub-menu, which is rather peculiar. This would imply that it is the Push Notification Tester app that is failing to properly register for push notifications (its primary function - it is, of course, a Push Notification Tester app), but only with Services Core Version 0.2.4-81-gb1e98ea - it worked fine with Services Core Version 0.2.4 stable. Any idea why this would be happening?

Signal and Skype both have been updated in the last two weeks but Push Notification Tester's last update was almost six months ago. Perhaps something has changed with Google Cloud Messaging, something accounted for between Services Core Version 0.2.4 stable and Services Core Version 0.2.4-81-gb1e98ea, that Skype and Signal accounted for in recent updates but Push Notification Tester did not?

I'll update back about any other apps failing to register to push notifications.

**Comment by JonnyTech** [comment]
Did you:
- (re)install the tester *after* installing microg?
- copy the gms core app to system/priv-app?

**Comment by ev3y2** [comment]
Did I:
> (re)install the tester after installing microg?

yes

> copy the gms core app to system/priv-app?

no, what does that do? Is that the same as making the app a device administrator? Moreover, how do I do this (I installed via F-Droid)? And should I, considering I didn't do this for Services Core Version 0.2.4-81-gb1e98ea?

**Comment by JonnyTech** [comment]
If you have root then use whichever method you are comfortable with:

- use a root capable file manager to copy microg gms apk to /system/priv-app/
- for command-line follow [instructions here](https://github.com/microg/android_packages_apps_UnifiedNlp/blob/master/README.md) replacing NetworkLocation with gms

Then reboot your device and try again. It is the only way that I can get it to work in Nougat.

**Comment by ev3y2** [comment]
It seems that all other apps of mine are able to register for push notifications just fine; it's only the Push Notification Tester app that is unable to register for push notifications, which is rather ironic. It's likely a problem with the app, then, and not a problem with Services Core (0.2.4-81-gb1e98ea). Not sure if there is a way to tell, though.
Anyway, I don't see a reason to attempt making Services Core a priv-app at this point as it isn't much of an issue for me anymore.
I think I'll open a pull request to add a disclaimer to the [Helpful Information](https://github.com/microg/android_packages_apps_GmsCore/wiki/Helpful-Information) page that the app may be inaccurate and to consider testing with a more recently updated app.

**Comment by ale5000-git** [comment]
@ev3y2: Make microG Services Core a priv-app is just needed for location, for the other things there isn't any difference.

**Comment by ev3y2** [comment]
@ale5000-git ah okay, thanks for the tip. I imagine it's needed, more specifically, for network based location? Or is it needed even for deviced-based/GPS?

**Comment by ale5000-git** [comment]
@ev3y2: Just for network-based location and only on Android 7 and higher.

**Comment by ev3y2** [comment]
I opened an [issue](https://github.com/bbindreiter/PushNotificationTester_App/issues/3) in the Push Notification Tester repo and the app got updated and the issue was fixed. I'll update the [Helpful Information ](https://github.com/microg/android_packages_apps_GmsCore/wiki/Helpful-Information)page accordingly.
