### ISSUE TITLE
WIN DEATH (probably) due to error "Channel is unrecoverably broken and will be disposed!"

### ISSUE THREAD

**Issue by jejo86** [microg/android_packages_apps_GmsCore#370]
the following three applications are not working for me:

- DB Navigator (crashing immediately after starting)
- VRS Auskunft (cannot 'set a region') 
- Firefox (crashes eventually after a while [max 5min]. not really reproducible but, i think it happens when switching applications)

Device: Fairphone 2
OS: Fairphone Open 5.1 Lollipop
uG: Version 0.2.4 (see attached screenshots)
XPosed-Framework: Version 87 (Android 5.1 Lollipop, API 22, ARM v7)
XPosed Module: FakeGapps: v 1.1

log exceprts:
`DB Navigator Crash:
05-11 19:14:40.097 E/AndroidRuntime( 7688): FATAL EXCEPTION: main
05-11 19:14:40.097 E/AndroidRuntime( 7688): Process: de.hafas.android.db, PID: 7688
05-11 19:14:40.097 E/AndroidRuntime( 7688): java.lang.IllegalArgumentException: provider doesn't exist: fused
...
05-11 19:14:42.241 W/InputDispatcher(  914): channel '4a9894a de.hafas.android.db/de.hafas.main.HafasApp (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-11 19:14:42.242 E/InputDispatcher(  914): channel '4a9894a de.hafas.android.db/de.hafas.main.HafasApp (server)' ~ Channel is unrecoverably broken and will be disposed!

Firefox Crash:
05-11 19:17:43.250 W/ActivityManager(  914): Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=7400, uid=10078 requires com.google.android.c2dm.permission.RECEIVE
05-11 19:17:43.251 E/GeckoPushService( 7400): Got exception during startup; ignoring.
05-11 19:17:43.251 E/GeckoPushService( 7400): java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
05-11 19:17:43.251 E/GeckoPushService( 7400): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1716)
...
05-11 19:18:48.121 E/GeckoCrashHandler( 7400): >>> REPORTING UNCAUGHT EXCEPTION FROM THREAD 736 ("GeckoBackgroundThread")
05-11 19:18:48.121 E/GeckoCrashHandler( 7400): java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
05-11 19:18:48.121 E/GeckoCrashHandler( 7400): 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1716)
...
05-11 19:18:50.153 W/InputDispatcher(  914): channel '4d9007f org.mozilla.firefox/org.mozilla.gecko.BrowserApp (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-11 19:18:50.153 E/InputDispatcher(  914): channel '4d9007f org.mozilla.firefox/org.mozilla.gecko.BrowserApp (server)' ~ Channel is unrecoverably broken and will be disposed!
05-11 19:18:50.225 I/Zygote  (  282): Process 7400 exited cleanly (11)
05-11 19:18:50.226 I/WindowState(  914): WIN DEATH: Window{4d9007f u0 org.mozilla.firefox/org.mozilla.gecko.BrowserApp}
05-11 19:18:50.226 W/InputDispatcher(  914): Attempted to unregister already unregistered input channel '4d9007f org.mozilla.firefox/org.mozilla.gecko.BrowserApp (server)'
05-11 19:18:50.229 I/WindowState(  914): WIN DEATH: Window{13288077 u0 SurfaceView EXITING}

VRS Error:
05-11 19:17:16.561 W/InputDispatcher(  914): channel '10201177 de.vrsinfo/de.vrsinfo.ConnectionResultlist (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-11 19:17:16.561 E/InputDispatcher(  914): channel '10201177 de.vrsinfo/de.vrsinfo.ConnectionResultlist (server)' ~ Channel is unrecoverably broken and will be disposed!
05-11 19:17:16.562 I/WindowState(  914): WIN DEATH: Window{a718205 u0 de.vrsinfo/de.vrsinfo.ConnectionResult}
05-11 19:17:16.571 I/WindowState(  914): WIN DEATH: Window{369684f1 u0 de.vrsinfo/de.vrsinfo.HTDCustomActivity}
05-11 19:17:16.578 I/WindowState(  914): WIN DEATH: Window{10201177 u0 de.vrsinfo/de.vrsinfo.ConnectionResultlist}`

please see full logs (between 'Start Activity' and 'WIN DEATH' or 'has died' logs) and screenshots in the attachment. [This is actually '.zip' file. To open correctly please remove the '.png' extension!]:

![logs-and-screenshots zip](https://cloud.githubusercontent.com/assets/28619134/25968508/076a2f9e-3692-11e7-97d1-0b5ce89fe9ba.png)

any ideas what i can do, or is the needed functionality simply not yet implemented?

**Comment by ale5000-git** [comment]
The latest stable release is very old, I suggest to use the latest [preview build](https://microg.org/download.html) (currently 0.2.4-92).

**Comment by jejo86** [comment]
i just created a backup and installed the "opengapps nano" since i need those apps to work from tomorrow on during the next week on a business trip. i'll give your advice a shot in a week or so.
thanks

**Comment by jejo86** [comment]
all right, with the version 0.2.4-92 Firefox shows no problems anymore, the DB Navigator prompts to update Google Services, but everythings works, except showing the map, which is no big limitation. in the latest version 0.2.4-103 the prompt is gone and the map is shown.
only the VRS application error remains, but maybe that app is poorly programmed. i installed the "HandyTicket Deutschland" app, which replaces the VRS app without restraints.
so the latest updated closes this issue for me.
