### ISSUE TITLE
[question] SafetyNet status with microG

### ISSUE THREAD

**Issue by tumpio** [microg/android_packages_apps_GmsCore#376]
Hello, today I build first time myself LineageOS rom. I applied the signature spoofing patch provided in here. I installed the rom and microG to it with DroidGuard helper. Then enabled safetynet in microg settings but SafetyNet check fails. 

Are others here able to pass SafetyNet check using microG? Or did I do something incorrect in building the rom? The official rom passed the test using OpenGapps package. I'm wondering if my build process is the culprit. 

Device in question is Moto E (condor).

**Comment by ArchangeGabriel** [comment]
SafetyNet works for me with MicroG. You probably did something wrong. How did you install MicroG? How did you install DroidGuard? Which version for each? How do you test SafetyNet?

**Comment by tumpio** [comment]
I installed microG and DroidGuard with Fdroid from microG Fdroid repository.  I'm using SafetyNet Helper Sample from playstore for testing SafetyNet.

I'll first try if safetynet passes using OpenGapps in my build Lineage rom. Thanks @ArchangeGabriel 👍

**Comment by ale5000-git** [comment]
@tumpio: It pass SafetyNet check only if DroidGuard helper is in /system/priv-app and if you haven't installed root.

**Comment by tumpio** [comment]
Solved! Thanks @ale5000-git 

I simply moved DroidGuard helper from /data/apps to /system/priv-app and SafetyNet passes.
