### ISSUE TITLE
Bug: Cannot add a Google account on KitKat

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#379]
When there is the courtesy page where you can select if add the account or not, clicking everything do nothing.

The problem happens on KitKat instead it works correctly on Nougat.
It may seems the same of #342 but it isn't since the aforesaid bug stuck on the "Just a sec" page while this one happens before.

I get this:
```
PicturePileLayerContent => Warning: painting PicturePile without content!
webcoreglue => Should not happen: no rect-based-test nodes found
```

Full logcat is here: [Google-account-log.txt](https://github.com/microg/android_packages_apps_GmsCore/files/1017369/Google-account-log.txt)

**Comment by Mynacol** [comment]
I have encountered the exactly same problem, but on this setup:
Device: Samsung Galaxy S3 mini   GT-i8190   golden
ROM: Maclaws' CM10.2   Android 4.3.1
MicroG: 0.2.4-103-xxxxx

**Comment by mar-v-in** [comment]
dup of #368
