### ISSUE TITLE
Upgrade GMS version?

### ISSUE THREAD

**Issue by n76** [microg/android_packages_apps_GmsCore#38]
Using BlankStore I updated Skype today (apparently a mistake to do that). This new version of Skype is saying my Play Services needs updating and that it won't work properly until I do that. Looking at logcat I see:

    I/Xposed  ( 2142): faked signature
    I/Xposed  ( 2142): faked signature
    W/GooglePlayServicesUtil(18725): Google Play services out of date.  Requires 7895000 but found 7887001
    V/NlpLocationProvider(18695): onSetRequest: ProviderRequest[ON interval=+10m0s0ms] by WorkSource{10147 com.skype.raider}
    V/NlpLocationProvider(18695): using autoUpdate=true autoTime=600000

Is this something simple like just updating a version number in the code?

**Comment by bonanza123** [comment]
I just changed the numbers in the AndroidManifest.xml, here is the APK: http://d-h.st/EyAL
does it work?

**Comment by n76** [comment]
That seems to have worked. In the build I was using before the message and logcat warning would not occur all the time so I don't know how to force it for sure. But I tried the same types of operations as before with your build and I don't see the dialog box nor the logcat warning.

The main thing I see in logcat, unrelated to this issue, is this

    W/ActivityManager( 2142): Unable to start service Intent { act=com.google.android.gms.ads.identifier.service.START pkg=com.google.android.gms } U=0: not found

My guess is that this is for an ad server/service (which I am happy not to have) but it might be nice to have a dummy handler for that intent. But, as noted, that has nothing to do with this "outdated Play Services" issue.

**Comment by n76** [comment]
Opps, probably should not have closed this until the change is merged.

**Comment by barturblits** [comment]
bonanza123: your new version gives me problems in maps, location does not work anymore. The current gmscore probably does not comply to the new google gms standards so it seems best to keep the old compatibility definition.
Also google seems to have changed something again. At the moment, when using the original apk there are no more update messages.
