### ISSUE TITLE
How to update ROM with microG?

### ISSUE THREAD

**Issue by gabm** [microg/android_packages_apps_GmsCore#397]
I would like to update my ROM (LineageOS) that has microG installed. I used NanoMod flashable zip to install microG. Last time I updated the ROM I lost microG upon reboot, so I had to reinstall it which lead to losing my GCM subscriptions.

What is the recommended process to do a ROM upgrade? Flash the update and microG followed by the spoof-signature pathc before booting? Or is there some "secret"?

Thanks for building microG, it works very well

**Comment by codebam** [comment]
If you don't reboot before flashing nanomod you shouldn't lose your gcm subscriptions

**Comment by gabm** [comment]
thanks for your answer, I'll try that in one go, without reboot:

- install lineage
- patch for sig spoofing
- install magisk + nanomod

**Comment by ale5000-git** [comment]
[microG unofficial installer](https://forum.xda-developers.com/showthread.php?t=3432360) contain a script that preserve GmsCore through ROM updates.

**Comment by gabm** [comment]
didn't know about the installer.. nice work!

I did as suggested above and all gcm subscriptons have been kept.. thank you both for ur support!

**Comment by gabm** [comment]
didn't know about the installer.. nice work!

I did as suggested above and all gcm subscriptons have been kept.. thank you both for ur support!
