### ISSUE TITLE
unable to patch

### ISSUE THREAD

**Issue by NONOman** [microg/android_packages_apps_GmsCore#399]
Im trying right now to build lineageos with signature spoofing but so far i failed to apply the android_frameworks_base-N.patch file via git. Is there any other way to patch this file?

**Comment by dzizi** [comment]
you can use tingle from ale5000 to patch for signature spoofing

**Comment by NONOman** [comment]
i will give it a try. thank you

**Comment by ale5000-git** [comment]
Tingle is [here](https://github.com/ale5000-git/tingle).

**Comment by NONOman** [comment]
its working. thank you very much!

**Comment by bam80** [comment]
@NONOman, what was your error in patching?
Maybe the patch needs to be updated?
