### ISSUE TITLE
Wishlist: add support for Blackberry 10

### ISSUE THREAD

**Issue by pavelschon** [microg/android_packages_apps_GmsCore#40]
It will be nice to have support for Blackberry 10.

**Comment by mar-v-in** [comment]
It should be possible to install this on BlackBerry 10. What will not work is the signature faking part (which requires patching of the Android system on "normal" Android as well). But you can also patch the applications instead to not check signature. This is not a nice solution, but I know that there are tools in the crackberry community to do this.
