### ISSUE TITLE
Help with RO system

### ISSUE THREAD

**Issue by JonnyTech** [microg/android_packages_apps_GmsCore#409]
Sorry if this is not the best place to post this. There are a lot of clever people here and I need help getting microG onto my updated ROM.

The only stable ROM for my phone is the official manufacturers one. I keep trying others but end up going back to it. It is fairly stock AOSP Marshmallow running on an ext4 system partition.

The long awaited Nougat OTA update finally arrived and I heard lots of good things about it, many long-standing bugs fixed and performance improvements.

Installing it converts the system partition from ext4 to squashfs. That means read only access. I cannot root it, install SU, patch it for signature spoofing or copy GMS Core to priv-app.

I extracted all files to a freshly formatted ext4 system partition but it does not boot. Maybe I am missing something to do with permissions or similar but searching online has been no help.

So I am asking here if anyone knows of a way to convert a squashfs system partition to something with rw access. Any tips are appreciated.

**Comment by ale5000-git** [comment]
You will probably be more lucky by rooting with Magisk since it doesn't touch the system partition.

**Comment by JonnyTech** [comment]
OK, I believe that it just modifies the kernel in boot.img to create an overlay. Can I still add signature spoofing with Magisk? What about removing the preinstalled apps like GMS that will clash with microG?

**Comment by ale5000-git** [comment]
A Magisk module can do everything (almost).
In the future I will make my installer be able to operate also as Magisk module, but it require time.

There is also NanoMod by Setialpha that is already ready.

**Comment by JonnyTech** [comment]
Great, I shall look at it in the next few days - thank you!

(Although my preferred solution would be to make the system writable so suggestions are still welcome)

**Comment by JonnyTech** [comment]
FYI, steps to make it work:
- extract boot.img
- edit fstab to indicate that the system partition is ext4
- repack and flash boot.img
- format system to ext4
- extract the contents of the squashfs image to new ext4 partition

The squashfs image was compressed and once uncompressed all of the files did not fit in the system. I deleted all the system apps that I did not want - and there were many!
