### ISSUE TITLE
GCM never connects

### ISSUE THREAD

**Issue by nExXxuS** [microg/android_packages_apps_GmsCore#415]
GCM is enabled and i'm using "com.firstrowia.pushnotificationtester" to verify push notifications are working.

In fact it never receive push notification, while microG settings show: "Aktueller Zustand: Nicht verbunden/Not connected".

ROM: AOSP Extended
https://forum.xda-developers.com/redmi-note-4/xiaomi-redmi-note-4-snapdragon-roms-kernels-recoveries--other-development/rom-aospextended-rom-v3-3-t3578477

Logcat:
<pre>08-15 21:39:32.463: D/GmsGcmMcsSvc(2323): Activated SSL with mtalk.google.com:5228
08-15 21:39:42.080: W/GmsGcmMcsSvc(2323): javax.net.ssl.SSLHandshakeException: Connection closed by peer
08-15 21:39:42.080: W/GmsGcmMcsSvc(2323): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
08-15 21:39:42.080: W/GmsGcmMcsSvc(2323): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
08-15 21:39:42.080: W/GmsGcmMcsSvc(2323): 	at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:682)
08-15 21:39:42.080: W/GmsGcmMcsSvc(2323): 	at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:644)
08-15 21:39:42.080: W/GmsGcmMcsSvc(2323): 	at org.microg.gms.gcm.McsService.connect(McsService.java:381)
08-15 21:39:42.080: W/GmsGcmMcsSvc(2323): 	at org.microg.gms.gcm.McsService.handleMessage(McsService.java:535)
08-15 21:39:42.080: W/GmsGcmMcsSvc(2323): 	at android.os.Handler.dispatchMessage(Handler.java:98)
08-15 21:39:42.080: W/GmsGcmMcsSvc(2323): 	at org.microg.gms.gcm.McsService$HandlerThread.run(McsService.java:152)
08-15 21:39:42.081: D/GmsGcmMcsSvc(2323): Teardown initiated, reason: javax.net.ssl.SSLHandshakeException: Connection closed by peer</pre>

I guess its related right? What else do you need to debug?

Best

**Comment by mar-v-in** [comment]
Are you using any AdBlocker / Firewall like AdAway? Some of them block access to `mtalk.google.com` server.

**Comment by nExXxuS** [comment]
Nope. No firewalls.

**Comment by nExXxuS** [comment]
You were right, this was due to a wrongly configured APN.
