### ISSUE TITLE
F-Droid Repository - Certificate from Lets Encrypt expired

### ISSUE THREAD

**Issue by Catfriend1** [microg/android_packages_apps_GmsCore#419]
Untrusted Website
While trying to retrieve the URL:
https://microg.org/fdroid.html
Status
certificate has expired
Subject
/CN=microg.org
Issuer
/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
SHA1 Fingerprint
60:BE:2E:87:B3:B5:67:15:9B:78:39:EE:45:FD:91:D8:B3:8D:9A:F7
MD5 Fingerprint
01:43:F0:B6:FD:15:61:25:FE:1D:F0:41:BC:EF:CA:7D
Valid from
May 31 21:02:00 2017 GMT
Valid until
Aug 29 21:02:00 2017 GMT

**Comment by Primokorn** [comment]
Can be closed since it's now valid until 11-29.

**Comment by Catfriend1** [comment]
Thank you very much. :-)

**Comment by ghost** [comment]
please delete issue
