### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by Catfriend1** [microg/android_packages_apps_GmsCore#420]
Hi,

according to
https://github.com/microg/android_packages_apps_GmsCore/commits/master
there were no recent updates for a longer time span.

What is the reason? Do you need more funds to continue work on the open tickets?

**Comment by ale5000-git** [comment]
It is how open source applications are.

There may be one day or one year between updates, the time doesn't matter since no one is paid.

**Comment by pomarec** [comment]
@Catfriend1 probably means that he/she can help with the funding if it can help development of the project. Am I right ?

**Comment by cstich** [comment]
Would it make sense to setup a patreon or something like that? I would happily donate a few bucks every month to the project, but I actually don't know how.

**Comment by ale5000-git** [comment]
There is [this](https://www.bountysource.com/teams/microg).

**Comment by Catfriend1** [comment]
Pretty cool, count me in :-).

**Comment by ghost** [comment]
please delete issue
