### ISSUE TITLE
Google Opinion Rewards

### ISSUE THREAD

**Issue by JonnyTech** [microg/android_packages_apps_GmsCore#421]
Any suggestions on how to get "Google Opinion Rewards" working? I am asked to choose my Google account then it gets no further. If needed then I can get a logcat later when I am at a computer.

**Comment by utack** [comment]
Why not use the proprietary Google Service, when you want to have your every step tracked?

**Comment by JonnyTech** [comment]
The aim is to get freebies without any tracking :)

**Comment by utack** [comment]
You do realize that opinion rewards works only when you send your location to Google 24/7?

**Comment by JonnyTech** [comment]
They can see me sitting at the North Pole 24/7 if need be...

**Comment by utack** [comment]
Opinion rewards works by tracking your location, and asking about places you go.  
So even if you get it running, you will get no questions at all, because you are always at the north pole

**Comment by JonnyTech** [comment]
Doesn't Google want to know how Father Christmas is faring???
