### ISSUE TITLE
... won't run unless you update Google Play services. . .

### ISSUE THREAD

**Issue by n76** [microg/android_packages_apps_GmsCore#422]
Installed a new version of an app today and am now getting a notification about play services being out of date.

I have microG v0.2.4-103-gd9e86d9 installed which I believe is the most current release. At least it is the most recent shown in your repository by my F-Droid client.

**Comment by ale5000-git** [comment]
@n76: I think it would be better if you look in the logcat for a lin like `Google Play services out of date. Requires 10298000 but found 10087438` and post it so he can know the exact needed version.

**Comment by n76** [comment]
@ale5000-git You are correct, but I was away from my computer when it came up and by the time I could plug the phone in and get a logcat that message was no longer visible.

Oddly, in this case, the app still appears (actually a weather widget) seems to run just fine despite issuing this notification. Hmm, wrote too soon. I uninstalled the app then reinstalled it so I could get the message you referred to and now I can't place the widget on my home screen. :(

Oh, well. The message is 

> GooglePlayServicesUtil: Google Play services out of date.  Requires 11200000 but found 11059462

**Comment by ale5000-git** [comment]
It should be fixed.

**Comment by n76** [comment]
@ale5000-git - Yes, it is. Noticed the update in F-Droid and applied it and then upgraded the offending app and there is no complaint now.

**Comment by maracuja-juice** [comment]
I ran into this issue today when trying out these apps:
- YouTube
- Evernote
- The Guardian

**Comment by ale5000-git** [comment]
@maracuja-juice: Did you update microG GmsCore to 0.2.4-**108**?

**Comment by maracuja-juice** [comment]
You're right. The update helped, the warnings disappeared. 
In the YouTube app nothing loads though but that is probably a different issue.

**Comment by maracuja-juice** [comment]
That issue is resolved now aswell.

**Comment by eDeviser** [comment]
Hey there.
Its now for me the same. 

@ale5000-git:
Logcat says: "07-19 09:10:00.046 W/GooglePlayServicesUtil(11155): Google Play services out of date.  Requires 12451000 but found 12221403"

**Comment by Lama02** [comment]
Hi all,

I just installed microg (the last build) and I have the same issue for BlablaCars and BlablaLines apps.
Others apps that used play services seems to be ok.
Is the microg app still maintained?

Thanks in advance.

**Comment by sm4rk0** [comment]
Yes: https://github.com/microg/android_packages_apps_GmsCore/pull/553#issuecomment-405063562

**Comment by eDeviser** [comment]
Seems to be fixed since the last update. :)
