### ISSUE TITLE
Permission already defined

### ISSUE THREAD

**Issue by theScrabi** [microg/android_packages_apps_GmsCore#430]
Hi I've tried to install microG on my Linage (Android 7.1) smarthphone.
fdroid gives me this error if I try to install core:
![screenshot_20171011-080359](https://user-images.githubusercontent.com/1891273/31510514-12d73f9a-af85-11e7-9618-d216e21c52cf.png)
However if installed extended privileges of fdroid, so maybe this is clashing with microG core, but I'm not sure.

**Comment by ale5000-git** [comment]
@theScrabi: Is it possible that you have GApps installed?

**Comment by theScrabi** [comment]
No, it's a freshly installed linage.

**Comment by theScrabi** [comment]
Ok never mind, I had the wrong Unified NLP installed (headpalm).
