### ISSUE TITLE
Youtube and Gboard asks for a newer version of Google Play Services

### ISSUE THREAD

**Issue by koso00** [microg/android_packages_apps_GmsCore#433]
I've updated youtube and gboard and they asks for a google play services update, there's a way to mock the microg version?

**Comment by ale5000-git** [comment]
Hi,
it would be nice if you look in the logcat for a line like this: `Google Play services out of date. Requires 10298000 but found 10087438`
and post it here.

**Comment by t0ma5** [comment]
I have the same issue with a few apps: Revolut, N26, and PushNotification Tester.
I have the latest versions of Service Core (GmsCore) / Services Framework Proxy (GsfProxy) / FakeStore

`11-01 20:28:29.439 W/GooglePlayServicesUtil(3456): Google Play services out of date. Requires 10298000 but found 9258259`

**Comment by ArchangeGabriel** [comment]
@t0ma5 You need to update μG to its latest version (0.2.4-105 I believe).

**Comment by t0ma5** [comment]
@ArchangeGabriel thanks for your reply. I am up to date with F-droid repository running `MicroG 0.2.4 (9258259)` is there a newer version? Where to find it?

**Comment by brevilo** [comment]
For all others: at the time of writing the **default** F-Droid version isn't the latest. You have to select the latest version manually.

**Comment by t0ma5** [comment]
that was the solution, thanks @ArchangeGabriel @brevilo

**Comment by chuckwagoncomputing** [comment]
I've got the same issue with Pushbullet.
`W GooglePlayServicesUtil: Google Play services out of date.  Requires 11020000 but found 10548448
`

**Comment by ale5000-git** [comment]
@chuckwagoncomputing: The message prove that you haven't installed the latest version.

**Comment by chuckwagoncomputing** [comment]
OK I got it sorted out. I hadn't wiped the system partition and the real Google Play Services was interfering.

**Comment by x86dev** [comment]
ccccccccccccccccc

**Comment by x86dev** [comment]
Can you please point to the most recent version of what needs to be installed to get YouTube working? After searching the repositories it's still unclear to me where to get the latest version. Thanks!

**Comment by ale5000-git** [comment]
If you can't find it on F-Droid just open [this link](https://microg.org/download.html) in a normal browser, select the drop down menu under "Services Core" and select the latest preview release.

**Comment by x86dev** [comment]
Cheers!

**Comment by ale5000-git** [comment]
@koso00: Have you tried to update microG GmsCore to 0.2.4-108?

If the problem is fixed close the ticket please :)
