### ISSUE TITLE
Unable to use GPS

### ISSUE THREAD

**Issue by metiis** [microg/android_packages_apps_GmsCore#435]
Hi,
When I try to use any app using Location services, only the proximate network-based location shows. If I set the location setting to "device only", no app using location works. 
I'm using LineageOS 14.1 and a Samsung Galaxy S5 (klte).
This is being spammed in logcat:
10-28 23:36:44.499   717  1156 W GnssLocationProvider: Invalid size of GpsSvStatus found: 0.
I have granted android.permission.ACCESS_FINE_LOCATION to my navigation app and to com.google.android.gms via adb shell.
I'm not sure if this occurs for microG only, as I have not tested it with Gapps yet. I will update it once I flashed gapps and tested it.

**Comment by n76** [comment]
Sounds like you have an issue with the GPS on your phone.

As far as I know, microG does nothing that should affect that.

GPS does work with LineageOS on other devices, though it only seems to use the US GPS system and to ignore others like GLONASS even if the hardware/stock ROM support them. On my phone there is a hardware issue with the GPS antenna which means a poor signal to noise ratio, by ignoring the GLONASS satellites LineageOS makes the situation worse. Part of the price of using a custom ROM. . .

**Comment by metiis** [comment]
Apparently I killed my GPS a while ago, closing
