### ISSUE TITLE
Google Connectivity Services asks for a newer version of Google Play Services after updade

### ISSUE THREAD

**Issue by MartinX3** [microg/android_packages_apps_GmsCore#440]
I use "Google Connectivity Services" version "E.2.1.40 (4333558)"

When I upgrade to version "E.2.3.04 (4400698)" the APP stops working and is telling me, that I need to upgrade the Google Play Services to a new version.

I installed Lineage MicroG Edition from the MicroG Homepage.
Everything fresh and wiped.
No old LineageOS migration.

**Comment by ale5000-git** [comment]
@MartinX3: Have you tried to update microG GmsCore to 0.2.4-108 using F-Droid?

**Comment by MartinX3** [comment]
Thank you, that worked fine! :)

But why die F-Droid not tell me, that there are are updates in the micro-g repo?
I installed them by Hand (clicking in every APP in f-droid and opened the "Version"-tab)
Fdroid has admin rights with its heller module.

**Comment by ale5000-git** [comment]
@MartinX3
Because all these microG updates are marked as preview and they don't get notified if you don't enable the option to show unstable updates in F-Droid.

**Comment by MartinX3** [comment]
Thank you!
I didn't saw that clearly in the APP.
But poor to see, that I can only global activate the unstable updates and not per repo/app
