### ISSUE TITLE
Crash App Call a Bike

### ISSUE THREAD

**Issue by coxtor** [microg/android_packages_apps_GmsCore#451]
Hi, the German bike rental service "Call a bike" crashes on start.
 Here a logcat: [bahnCrash.txt](https://github.com/microg/android_packages_apps_GmsCore/files/1524748/bahnCrash.txt)

**Comment by eggercomputerchaos** [comment]
It is the same crash as described in issue #449

**Comment by coxtor** [comment]
Fixed at least in version 0.2.6.15180-dirty-241
