### ISSUE TITLE
Google Maps complains "Maps won't run unless you update Google Play Services"

### ISSUE THREAD

**Issue by haunma** [microg/android_packages_apps_GmsCore#452]
I am running the latest microG components from F-Droid on a Nexus 10 tablet with a Marshmallow ROM (OmniROM).  All self-checks pass in the settings app, and microG appears to be working normally, with the exception of not being able to add a google account to the device (see my comment on issue #342).  I also went into F-Droid and ticked expert settings / unstable versions to make sure there wasn't a microG preview in there, but there doesn't seem to be.

Contrary to the dire claims in the notification, Maps appears to be working just fine.  However, every time I launch it this warning notification is displayed.  The notification also appears at boot up.  I attempted to capture the version info with alogcat by clearing the notification, starting the log, and launching Maps.  For some reason I cannot see errors or warnings in the log which would be related to play-services versioning.  Any suggestions for capturing more info would be welcome.

**Comment by LoRDxRaVeN** [comment]
Because several people including myself had the problem, that the default F-droid Version _isn't_ the newest one, please double check if you really have version 0.2.4-**105**. Just to make sure.

**Comment by haunma** [comment]
Where do you find a minor version #?  All I know to do is to select "About microG Services Core" in the settings app.  There it only says "Version 0.2.4" (and GmsApi 0.2.3, SafeParcel 1.3.3-4-g6e2e63b, UI Tools 0.1.6-2-g3532954, UnifiedNlp 1.6.7, UnifiedNlp Api 1.5.5).

**Comment by ale5000-git** [comment]
@haunma: If you don't see it probably you have the stable version that is old.

**Comment by ArchangeGabriel** [comment]
@haunma If you go to F-Droid, and then to the `microG Services Core` app, you can look at the available versions.

**Comment by haunma** [comment]
Thanks.  That was indeed the problem.  I thought I was safe by selecting Expert Mode, and Unstable Updates in the F-Droid settings.  But it looks like that is not enough, if you have already installed the "stable" version.  F-Droid says "no versions with compatible signature" so it is necessary to first uninstall the stable version, then the unstable versions appear.
