### ISSUE TITLE
"Pulse won't run unless you update Google Play Services" 

### ISSUE THREAD

**Issue by olhybrius** [microg/android_packages_apps_GmsCore#453]
Hi !

First of all, thank you for the great work !

Most of my apps work well with microG, but Pulse sms give me warnings about how it needs Google Play Services to be updated. 

The application works perfectly fine, but the warnings are annoying and they keep coming back even if I swipe them, so if there's something I can do about those...

Looking at adb logcat, I found this message : `GooglePlayServicesUtil: Google Play services out of date.  Requires 11717000 but found 11675464`

Pretty sure I run the latest Services Core package though, since I'm on 0.2.4-105. Is there another version planned any soon ? Or is there another solution ?

On a side note, but maybe related, I am unable to start Fake Store or Gmail (which came as the pre-installed app on my phone). When I try to start them, I get a popup saying "Install core GMS packages to use google play store". 
I do not need any of these two apps (I use Yalp Store as a frontend for the Play Store, I didn't really understand the purpose of the fake store in the first place), but I thought I'd mention it.

Thanks for taking the time to read and answer me and another big thanks again for the great work !

**Comment by ArchangeGabriel** [comment]
Maybe this time the Play Services version is really outdated… Updating it and rebuilding μG wouldn’t be complicated, but on the more long term the lack of updates from @mar-v-in does not sound good.

**Comment by ale5000-git** [comment]
I have found on a forum a quote of a message from MaR-V-iN:
[QUOTE=MaR-V-iN]I am pretty busy these days and I won't be able to deliver v0.3 in 2017[/QUOTE]

My interpretation is that we have to wait 2018.

**Comment by olhybrius** [comment]
At least there is still hope.

**Comment by AnyoeDove** [comment]
so maybe just need to modify the versionCode like this commit? https://github.com/microg/android_packages_apps_GmsCore/commit/f289a13a7f32a9c4f1e5b0127a155bfe26a1c07e

**Comment by ArchangeGabriel** [comment]
Yes, first and third files of this commit.

**Comment by olhybrius** [comment]
Is it possible to do this ourselves ?

**Comment by ale5000-git** [comment]
@olhybrius
FakeStore is an app that do nothing but identify as PlayStore (needed only if you don't have the real PlayStore); you need it otherwise many app won't detect Google Play Services.

To fix yout problem install FakeStore 0.0.2 and update microG Service Core to 0.2.4-**107**.

**Comment by olhybrius** [comment]
@ale5000-git 
That did it, no more annoying warnings ! Thanks a lot ! :)
Also, thank you for making Fakestore's purpose clearer.

**Comment by pr-delta** [comment]
@olhybrius How did you get to sign into pulse. When I try to sign in I just get a generic error message.
