### ISSUE TITLE
Cannot find the SafetyNet options any more after reinstalling

### ISSUE THREAD

**Issue by luutifa** [microg/android_packages_apps_GmsCore#454]
Sorry for a question which feels pretty stupid but I've done everything multiple times including trying "your" https://lineage.microg.org/ version of Lineage _and_ trying the proven good method of vanilla Lineage + tingle patching... And the option for SafetyNet just is no longer there in the microG settings. Self check is 100% fine and I've (re)installed DroidGuard helper and everything.

Was it a mistake to format (from TWRP) the phone before flashing Lineage? Was something vital to SafetyNet on some partition which the LOS zip doesn't provide? Also most of my Play Store apps are now saying "Update Google Play services" on startup...?

**Comment by ale5000-git** [comment]
Maybe you are using the stable version instead of the latest preview version of microG GmsCore.
Try updating to 0.2.4-105.

**Comment by luutifa** [comment]
Aha! Sounds like an idiotically simple solution. I'll try that when the phone finishes restoring. Huge thanks for working on these wonderful software, BTW.

**Comment by ale5000-git** [comment]
I'm not working on it, I just help sometime.

**Comment by luutifa** [comment]
Sure, but Tingle

**Comment by luutifa** [comment]
Yeah, that was it, I feel really stupid. I'll stick to tingle for now instead of https://lineage.microg.org/ as the latter failed SafetyNet for some reason.
