### ISSUE TITLE
ASB Bank mobile app complains about out of date Google services

### ISSUE THREAD

**Issue by kozross** [microg/android_packages_apps_GmsCore#456]
The app in question is [here][1]. When I start it, I can go through all the setup steps, but then at first login, it complains that it can't run unless I update Google Play services.

I'm running the lastest GmsCore, using the Mozilla UnifiedNlp backend, and have activated everything.

[1]: https://play.google.com/store/apps/details?id=nz.co.asb.asbmobile&hl=en

**Comment by ArchangeGabriel** [comment]
Latest = 0.2.4-107?

**Comment by n76** [comment]
Are you running the latest "alpha" version of microG? If not, then try it. If you are using the latest alpha version then there should be a line in the logcat indicating what version microG needs to be claiming.

**Comment by kozross** [comment]
@ArchangeGabriel @n76 I have the version available [here][1], which microG Settings reports as 'Version 0.2.4'. I assume that this isn't the latest alpha - if it isn't,how do I obtain it? Also, how do I view the logcat?

[1]: https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.4

**Comment by ArchangeGabriel** [comment]
It’s not the lastest indeed. You can get newer version from here: https://microg.org/download.html. Either use the F-Droid repo, or use the dropdown menu to select latest version.

**Comment by n76** [comment]
@kozross from your computer, run the command `adb logcat` to get a logcat. However your problem is almost certainly that you are not using the latest alpha release and @ArchangeGabriel has already given you pointers to that.

**Comment by kozross** [comment]
@ArchangeGabriel I have the F-Droid repo enabled, but it doesn't seem to carry alphas. I'll get mine direct.

**Comment by ArchangeGabriel** [comment]
It does (I use it), but you have to manually select the version among the available ones.

**Comment by kozross** [comment]
@ArchangeGabriel Wow, you've taught me something about both microG and F-Droid today! Can confirm it works now.
