### ISSUE TITLE
No microg settings app on fresh install

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [microg/android_packages_apps_GmsCore#465]
Hi,
I just installed lineage os + microg on klte (samsung S5) for the first time and I don't find anywhere the the `microg settings app` described there : https://lineage.microg.org/
Is it hidden somewhere unexpected ?

I didn't get any peculiar error message on install, the zip I flashed is this one : `lineage-14.1-20180101-microG-klte.zip` with this sudo zip `addonsu-14.1-arm-signed.zip`

I'll try to find an apk somewhere but it's really odd...

**Comment by n76** [comment]
This is not a microG issue. . .

It might be a Lineage with microG issue (microG not properly installed as part of the ROM). But I doubt it as other devices seem to to work okay (including the `lineage-14.1-20180101-microG-harpia.zip` ROM I installed today on my phone).

When you tap on the icon for all apps at the bottom of the launcher window and scroll down do you see a "microG Settings" app and icon? (I notice that when I change the default language on my phone the order that apps are show changes based on the translated name).

**Comment by thiswillbeyourgithub** [comment]
Thanks for the quick reply :)

Do you suggest I flash a zip from another day ?

I looked at every single app like 5 times to be sure and there is no microg settings app in there, I tried severall langage just in case too..

I looked at the application list from the settings menu too but it's nowhere...

**Comment by n76** [comment]
Do you have adb setup? If so then:

```
$ adb shell
harpia:/ $ ls /system/priv-app/
```

And see if "GmsCore" exists in that directory. If it does then microG is installed.

**Comment by thiswillbeyourgithub** [comment]
`ls /system/priv-app|grep Gms` returns `GmsCoreSetupPrebuilt` and `PrebuiltGmsCore`. Is that okay ?

**Comment by n76** [comment]
Hmmm. That is not what I'm getting:

$ adb shell
harpia:/ $ ls /system/priv-app|grep Gms
GmsCore
harpia:/ $ 

If worse comes to worse, download either the -107 or -108 version of "Services Core" from https://microg.org/download.html then:

```
adb root
adb remount
adb push com.google.android.gms-11951417.apk /system/priv-app/
adb reboot

```
File name may vary depending on which "preview release" you use. 107 appears to be the one that the Lineage with microG uses for my phone. 108 has fixes on the maps API v2 but breaks some of the handling (no op actually I think) of ads.

I've not noticed `GmsCoreSetupPrebuilt` and `PrebuiltGmsCore` before. . . I wonder if they are from Google's gapps. Are you sure that gapps has not been installed at some time.

**Comment by thiswillbeyourgithub** [comment]
Just done flashing the second zip from my previous message and it doesn't change a thing.

Before trying what you told me, can you tell me wether I should wipe `System` with TWRP when doing the factory reset ? I had indeed the Gapps installed with lineageOS before trying out microg and maybe this has something to do with my problem ?

**Comment by n76** [comment]
Bingo! You must wipe /system using TWRP before flashing Lineage with microG. Otherwise the old gapps stuff is still there and interfering with everything.

A "factory reset" does not reset the /system area (i.e. the "ROM"), it only clears the user data.

**Comment by thiswillbeyourgithub** [comment]
Bingo indeed ! Just found the apk when flashing with the first zip but while wiping system.

1 - Thank YOU a lot, you were really responsive and helpfull, much love
2 - I'm starting to wonder wether it's the right github for this issue, should I have gone somewhere else ?
3 - The tutorial I was following was at this page : `https://lineage.microg.org/`, and it says `
Clean install (wipe data and installed apps)

If you don't care about losing your current data just reboot into recovery, **wipe Data, Cache and Dalvik (perform a "Factory reset")** and, without rebooting, install LineageOS for microG.` so it's apparently missing the "System" wipe don't you think ? Actually the reason might be found there : `https://twrp.me/faq/whattowipe.html`, it says `The vast majority of ROMs wipe system as part of the zip install. This means that in most cases you do not need to wipe system... ever.` So I think someone that packaged the ROM might have missed something. Do you know where I should report this ?

**Comment by n76** [comment]
My guess is that it should be reported on either the [XDA thread for Lineage with microG](https://forum.xda-developers.com/android/software/lineageos-microg-t3700997). Or on [the GitHub page for that project](https://github.com/lineageos4microg).

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot :)

**Comment by ale5000-git** [comment]
Actually you generally don't need to wipe /system (although it is a good thing to do when changing ROM), in your case probably you were having a script in /system/addon.d/ that preserved GApps.

**Comment by thiswillbeyourgithub** [comment]
Well okay but my install of lineageOS+Gapps was very conventional : I can't be the only one with that script and issue ^^

**Comment by ale5000-git** [comment]
Sure, in fact it is the Open GApps zip that add this file.
