### ISSUE TITLE
E JavaBinder: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by Der-Schubi** [microg/android_packages_apps_GmsCore#466]
Hi!
I'm trying to run microG on AICP (o 8.1) which is based on LineageOS 15.1.
I added patches for signature spoofing and location providers outside of /system.

The Self-Check is ok except of "UnifiedNlp has no last known location".
Location itself (e.g. Google Maps) works fine, but Ingress keeps showing "Scanner Disabled: Location Inaccurate".

Logcat:
`D GmsLocManagerSvcImpl: getLastLocationWithPackage: com.nianticproject.ingress
E JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
E JavaBinder: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
E JavaBinder:    at android.widget.Toast$TN.<init>(Toast.java:393)
E JavaBinder:    at android.widget.Toast.<init>(Toast.java:117)
E JavaBinder:    at android.widget.Toast.makeText(Toast.java:280)
E JavaBinder:    at android.widget.Toast.makeText(Toast.java:270)
E JavaBinder:    at org.microg.gms.common.Utils.hasSelfPermissionOrNotify(Utils.java:57)
E JavaBinder:    at org.microg.gms.location.GoogleLocationManager.<init>(GoogleLocationManager.java:58)
E JavaBinder:    at org.microg.gms.location.GoogleLocationManagerServiceImpl.getLocationManager(GoogleLocationManagerServiceImpl.java:70)
E JavaBinder:    at org.microg.gms.location.GoogleLocationManagerServiceImpl.getLastLocationWithPackage(GoogleLocationManagerServiceImpl.java:235)
E JavaBinder:    at com.google.android.gms.location.internal.IGoogleLocationManagerService$Stub.onTransact(IGoogleLocationManagerService.java:440)
E JavaBinder:    at org.microg.gms.location.GoogleLocationManagerServiceImpl.onTransact(GoogleLocationManagerServiceImpl.java:341)
E JavaBinder:    at android.os.Binder.execTransact(Binder.java:696)`

Any ideas?

Regards,
Schubi

**Comment by Der-Schubi** [comment]
Btw, the same exception is thrown when starting maps, but maps is working so far.

**Comment by mar-v-in** [comment]
Did you grant GPS location access to microG Services Core?

**Comment by Der-Schubi** [comment]
Yes, app info says all permissions are granted. But hasSelfPermissionOrNotify seems to have a different opinion...

**Comment by Der-Schubi** [comment]
Well, ok... I ran `adb shell pm grant com.google.android.gms android.permission.ACCESS_FINE_LOCATION` and Irgress is working now. ¯\_(ツ)_/¯
But the Self-Check still says "UnifiedNlp has no last known location".

**Comment by Der-Schubi** [comment]
The last known location prolem was solved by updating the database of GSM Location Service.
Thaks a lot for your help!
