### ISSUE TITLE
wishlist: make heartbeat interval adjustable

### ISSUE THREAD

**Issue by bonanza123** [microg/android_packages_apps_GmsCore#47]
I'm not sure about the energy consumption of the current (1min ?) heartbeat interval, but I would guess that it would be nice for many users to have an option to adjust this interval.

**Comment by pejakm** [comment]
Any progress on this one? :)

**Comment by zoff99** [comment]
i don't understand. does that mean it's already implemented?
or, can you please specify where in the code the value is set, then we can compile it a with different value for now.

**Comment by pejakm** [comment]
@zoff99 https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/gcm/McsService.java#L78
