### ISSUE TITLE
Latest WhatsApp has serious issues with microG

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#471]
Latest version of WhatsApp has serious issues.
Likely related to #322, #404, #439 and #450 but a lot more serious.

It cause slowdown and freeze.

> [ 01-18 23:33:05.303 19287:19323 I/WhatsApp ]
> LL_I D [698:pool-3-thread-4]:229102 ProcessMediaQueue/attemptDequeueRequest no requests available
> 
> [ 01-18 23:33:05.313 19287:19287 I/WhatsApp ]
> LL_I D [1:main]:243682 PAY: PaymentsManager:isPaymentsEnabled: false for country code: 39 with server props: false
> 
> [ 01-18 23:33:05.320 19287:19287 I/WhatsApp ]
> LL_I D [1:main]:166701 ContactsSyncAdapter/created
> 
> [ 01-18 23:33:05.340 19287:19287 D/FirebaseApp ]
> com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
> 
> [ 01-18 23:33:05.354 19287:19287 D/FirebaseApp ]
> com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
> 
> [ 01-18 23:33:05.367 19287:19287 I/FA       ]
> App measurement is starting up, version: 11020
> 
> [ 01-18 23:33:05.367 19287:19287 I/FA       ]
> To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
> 
> [ 01-18 23:33:05.379 19287:19287 I/FA       ]
> To enable faster debug mode event logging run:
>   adb shell setprop debug.firebase.analytics.app com.whatsapp
> 
> [ 01-18 23:33:05.388 19287:19287 I/FirebaseInitProvider ]
> FirebaseApp initialization successful
> 
> [ 01-18 23:33:05.424  2366: 2378 W/ActivityManager ]
> Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms } U=0: not found
> 
> [ 01-18 23:33:05.429  2366: 2377 W/ActivityManager ]
> Unbind failed: could not find connection for android.os.BinderProxy@ee55705
> 
> [ 01-18 23:33:05.429 19287:19331 E/GmsClient ]
> unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
> 
> [ 01-18 23:33:05.464 19287:19333 I/WhatsAppJni ]
> EnsureThreadAttached: attached current thread to JVM
> 
> [ 01-18 23:33:05.821 19287:19331 I/FA       ]
> Tag Manager is not found and thus will not be used
> 
> [ 01-18 23:33:05.845 19287:19287 W/FA       ]
> Service connection failed: a{statusCode=API_UNAVAILABLE, resolution=null, message=null}
> 
> [ 01-18 23:33:05.851  2366:13859 W/AppOps   ]
> Finishing op nesting under-run: uid 10087 pkg com.whatsapp code 40 time=1515936680873 duration=3008 nesting=0

**Comment by ale5000-git** [comment]
> [ 01-18 23:33:06.239  2366: 2779 W/AppOps   ]
> Finishing op nesting under-run: uid 10087 pkg com.whatsapp code 40 time=1515936680873 duration=3008 nesting=0
> 
> [ 01-18 23:33:06.263  2366: 4648 W/ActivityManager ]
> Unable to start service Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms } U=0: not found
> 
> [ 01-18 23:33:06.265  2366:17987 W/ActivityManager ]
> Unbind failed: could not find connection for android.os.BinderProxy@e7b34d1
> 
> [ 01-18 23:33:06.267 19287:19331 E/GmsClient ]
> unable to connect to service: com.google.android.gms.measurement.START on com.google.android.gms
> 
> [ 01-18 23:33:06.277 19287:19331 E/FA       ]
> Discarding data. Failed to send app launch
> 
> [ 01-18 23:33:06.282 19287:19331 E/FA       ]
> Failed to get app instance id
> 
> [ 01-18 23:33:06.282 19287:19331 E/FA       ]
> Failed to send current screen to service
> 
> [ 01-18 23:33:06.282 19287:19331 E/FA       ]
> Discarding data. Failed to send event to service
> 
> [ 01-18 23:33:06.289  2366:14054 W/AppOps   ]
> Finishing op nesting under-run: uid 10087 pkg com.whatsapp code 40 time=1515936680873 duration=3008 nesting=0
> 
> [ 01-18 23:33:06.409 19287:19287 I/AppCompatViewInflater ]
> app:theme is now deprecated. Please move to using android:theme instead.

**Comment by ale5000-git** [comment]
> [ 01-18 23:33:07.327  2366: 2387 I/ActivityManager ]
> Displayed com.whatsapp/.HomeActivity: +1s197ms (total +2s774ms)
> 
> [ 01-18 23:33:07.550 19287:19287 D/Event    ]
> No subscribers registered for event class com.whatsapp.k.e
> 
> [ 01-18 23:33:07.551 19287:19287 D/Event    ]
> No subscribers registered for event class b.a.a.g

**Comment by Catfriend1** [comment]
Yeah, it would be nice if we could trigger the fallback mode of Whatsapp according to https://github.com/microg/android_packages_apps_GmsCore/issues/338#issuecomment-360977425 where it doesnt rely in Google services and/or firebase messaging that much.

**Comment by MOVZX** [comment]
It's the Firebase.

**Comment by ale5000-git** [comment]
Just to be clear, beside the errors WhatsApp is registered correctly for GCM and I receive messages, but it freeze while seeing status many times.

**Comment by Catfriend1** [comment]
I used disableservice app to work around it and set fcm services to disabled. WhatsApp feels better now, but I would appreciate a fcm merge from you with the official repo. Btw did you build your own microg with fcm support so there would be anything to test available?

**Comment by Lanchon** [comment]
what is the status on this? are you guys able to run whatsapp acceptably well with a workaround?

**Comment by Catfriend1** [comment]
After reinstalling whatsapp from whatsapp.com/android freshly and importing my chat backup notifications (push via gcm/microg) work again. No problems anymore.

**Comment by Lanchon** [comment]
too bad, i cannot really reverify my current whatsapp, i can only backup and restore the working installation. (this is a different story of stupidity on the part of whatsapp.)

**Comment by bocekm** [comment]
For me, the current WhatsApp works with no issues. And it's registered to GCM.
WhatsApp 2.18.142
MicroG 0.2.4-111
LineageOS 14.1

**Comment by kjjjnob** [comment]
After some minutes on deep sleep, i cant recive push notification for WhatsApp.

WhatsApp version 2.18.156
MicroG 0.2.4-111
aosIp 8.1 (Moto G5s Plus)

**Comment by godoftech** [comment]
Possible workaround:
https://github.com/microg/android_packages_apps_GmsCore/issues/631#issuecomment-429013399

**Comment by ale5000-git** [comment]
With the latest version of microG GmsCore it seems to work well enough.
I will open new issues if there will be other problems.
