### ISSUE TITLE
Unable to connect to Google account regulated by Okta

### ISSUE THREAD

**Issue by nezorflame** [microg/android_packages_apps_GmsCore#472]
OnePlus 3, OmniROM stable 8.1.
I have a Google work account which is connected to Okta system.
In usual scenario (with OpenGApps) when you log into the account, Google page redirects you to Okta, you log into Okta account and then it redirects you back to Google.
When you try to log into it with microG, after successfully logging into Okta, microG Services Core redirects you back to setup page for a split second, and then goes to blank white page with yellow progress bar on top, doing nothing, so setup never finishes.

Account is not created, although nothing seems to be the problem.

Any log I could get to debug this?

**Comment by ale5000-git** [comment]
The problem should be fixed in recent versions of microG GmsCore, I'm closing this for now.
Please try it and report back.
