### ISSUE TITLE
Unable to add Google account

### ISSUE THREAD

**Issue by zilti** [microg/android_packages_apps_GmsCore#474]
I'm on LineageOS 14.1. I can log in to a Google account, but then it is eternally stuck at "Your device is connecting to Google to store information in your account. This could take a few minutes". But it doesn't take a few minutes, it never finishes. microG 0.2.4.

**Comment by zilti** [comment]
I might have to add that the exact version I have is `0.2.4-108-g464d45d`. All microG packages are installed as root packages using the "inofficial microg installer" via TWRP.

**Comment by Hattshire** [comment]
There is an _**android.view.ViewRootImpl$CalledFromWrongThreadException**_ on https://github.com/microg/android_packages_apps_GmsCore/blob/464d45d552eb7bf075fd19ea1a5e9d8b8e7078b4/play-services-core/src/main/java/org/microg/gms/auth/login/LoginActivity.java#L294

Funny fact, the first time I tried to login it didn't except.

**Comment by Hattshire** [comment]
So I got it, more or less.
accountManager.addAccountExplicitly was returning false apparently (I can't use the android studio to debug due to my crappy computer), but showError(R.string.auth_general_error_desc); is not getting executed due to the thread restriction.
I guess there is also a bug on android, because my account was not on the Settings>Accounts section.
https://imgur.com/a/w9FZj

**Comment by Hattshire** [comment]
I was trying to remove my account using _**accountmanager.removeAccountExplicitly()**_, without results, then I printed out the accounts with _**getAccounts()**_, and my account was not there. Finally I searched for the _accounts.db_ file and I found 3 system folders on _/data_, 2 of them contained an _accounts.db_ file, and one of them was storing my account while the other stored what was shown on the _System>Accounts_ screen. I will submit a pull request later with a couple of fixes to display the error screen, to at least fix the _"eternally stuck"_ screen.

**Comment by nezorflame** [comment]
Seems that my issue https://github.com/microg/android_packages_apps_GmsCore/issues/472 is somewhat same here.

**Comment by Hattshire** [comment]
So, no life signals from @mar-v-in ?( •̥́ ˍ •̀ू )

**Comment by soredake** [comment]
Same problem for me.

**Comment by mar-v-in** [comment]
@Hattshire sorry for not merging your PR yet. I am currently super-busy with private and work stuff and thus my time to work on microG is very limited.

As many of my other projects conclude the next weeks, I hope to have spare time again in April.

**Comment by ale5000-git** [comment]
@mar-v-in: I (and I think most users) appreciate your work a lot.
It is just that users that come to github just draw conclusions from the apparent quiet of the github page.

**Comment by ale5000-git** [comment]
The problem should be fixed in recent versions of microG GmsCore, I'm closing this for now.
Please try it and report back.
