### ISSUE TITLE
Unable to add Google account on Kitkat

### ISSUE THREAD

**Issue by booti386** [microg/android_packages_apps_GmsCore#483]
microG Services Core 0.2.4-108 (latest)
When I try to add a Google account inside the settings app (or Play Store or anywhere), it shows the Sign-in view, but clicking on the Cancel or Sign in buttons does absolutely nothing.

**Comment by ildar** [comment]
https://github.com/microg/android_packages_apps_GmsCore/issues/368

**Comment by booti386** [comment]
Thanks, closing as duplicate.
