### ISSUE TITLE
Paella Calendar Issue

### ISSUE THREAD

**Issue by baba18** [microg/android_packages_apps_GmsCore#487]
Hi guys, 
I recently installed the latest lineage on my paella (BQ X5) with the latest (108) microG core included. While chromium will sync happily, the aosp calender and google calendar always try to add a new account instead of using my synced one. I granted all permissions manually and readded my google account but this did not help. Is there anything else I can do or might have missed ?

**Comment by n76** [comment]
microG does not include a Google sync adaptor. To synchronize your contacts and/or calendar you will need to install a sync adaptor. You can grab the Google sync adaptor out of a gapps package or use something like DavDroid to sync to a generic calendar server.

**Comment by baba18** [comment]
Wow thank you, with the guide of shadow 53 I managed to sync.
