### ISSUE TITLE
Unable to add Google account

### ISSUE THREAD

**Issue by ClayMaster** [microg/android_packages_apps_GmsCore#491]
MicroG Services Core is 0.2.4-108.
Wher I try to add Google account:

![screenshot_2018-02-27-21-46-05](https://user-images.githubusercontent.com/36898345/36748355-add7a9b8-1c08-11e8-9e2b-6df2b872a33d.png)

Both buttons "Cancel" and "Sign in" are inactive and cannot be pressed.
Tried on some custom ROMs 4.2.1 and 4.4.2 with same result.

**Comment by ale5000-git** [comment]
Duplicate of #368

**Comment by ale5000-git** [comment]
It should be fixed in the latest code (it isn't yet released).
Ref: https://github.com/microg/android_packages_apps_GmsCore/commit/ceb7e721b1882b21814cb4333f77f93c0c13ed51

**Comment by ale5000-git** [comment]
Bugs is fixed.
New version is out now.
