### ISSUE TITLE
[Bug?] Apps do not wake up on push notification

### ISSUE THREAD

**Issue by githtz** [microg/android_packages_apps_GmsCore#494]
I am using the LineageOS-microg-ROM on a LG-G3-D855 Smartphone and the Signal messenger. Signal has registered for push notifications.
When I receive push notifications and the battery optimizations for the signal messenger is enabled (default) Signal does not wake up when a push notification was received. After changing the battery optimizations for the signal messenger everything seems to be working correctly.
In the push notification settings wake up on push notification is enabled for the Signal app and I can see when (and that) the last notification arrived.

This also happened with a few other apps on my phone, for example Battle.net and NINA.

MicroG self-check states everything is okay.

Any help is very much appreciated!

**Comment by dk-zero-cool** [comment]
Yes this has always been a problem for me as well on any apps using push notifications like SnapChat, Facebook Messenger etc. It can take between 20 minutes and up to more than an hour some times, before the apps respond. Some times they don't respond until the device i woken from deep sleeep by turning on the screen.

**Comment by andschwa** [comment]
I'm using LineageOS 15.1-20180507-microG-dumpling on my OnePlus 5T with Signal, and have the same issue. It's registered correctly, it receives notifications, but it is not woken up to receive the notification. It only works if I disable battery optimization for Signal (note that it was already disabled for microG).

**Comment by ale5000-git** [comment]
It isn't a bug but it is a not yet implemented feature, duplicate of #338

**Comment by andschwa** [comment]
Ah, thanks @ale5000-git! Good to know.

**Comment by githtz** [comment]
I guess this can be closed then. Thanks for clarification @ale5000-git !

**Comment by ale5000-git** [comment]
The problem should be fixed in the new version of microG GmsCore released yesterday.
