### ISSUE TITLE
Lineage OS 15.1 support?

### ISSUE THREAD

**Issue by DissCent** [microg/android_packages_apps_GmsCore#495]
(Sorry if this doesn't belong here - I wasn't sure where to put the question)

Hi,

since 1 or 2 weeks, Lineage OS has released version 15.1 with Android 8.1 for my phone (OnePlus 3).
Currently I use the microg builds from download.lineage.microg.org - but since 15.1 arrived, the builds aren't updated anymore.

Will the new builds be supported?

**Comment by ArchangeGabriel** [comment]
https://github.com/lineageos4microg/l4m_website/issues/13
