### ISSUE TITLE
GCM - future?

### ISSUE THREAD

**Issue by thermatk** [microg/android_packages_apps_GmsCore#5]
Hello!
I saw you have started adding GCM to the project. Does it mean there is a possibility to finally have a free version of google's push client? Are you using the sources from Chromium's push implementation? GCM is a true killer-feature

**Comment by mar-v-in** [comment]
Currently, only the gcm registration request is handled, but complete gcm is a feature I'd like to add soon.

**Comment by mar-v-in** [comment]
GCM is now usable with µg GmsCore (although the connection seems to get lost sometimes)
