### ISSUE TITLE
UnifiedNLP not supported in LineageOS for microG 15.1 (OnePlus 3T)

### ISSUE THREAD

**Issue by deesnook** [microg/android_packages_apps_GmsCore#501]
I've recently flashed the newest version of LineageOS for microG. The self-test in the microG settings tells me that UnifiedNLP is not supported. I've tried to manually install the newest version from F-Droid (v1.6.8), but cannot install it (error 112: The system failed to install the package because it is attempting to define a permission that is already defined by some existing package)

Anyone else who has experienced this?

PS I previously had flashed OxygenOS 5.0.1 so it shouldn't be a firmware issue (?)

**Comment by ildar** [comment]
What exact package you're installing from F-Droid? Obviously the wrong one.

**Comment by deesnook** [comment]
yeah probably. The package is UnifiedNlp (GAPPS), but I don't have GAPPS installed. Just the microG version of Lineage 15.1. With the microG version of Lineage 14.1 everything worked out of the box

**Comment by deesnook** [comment]
Problem solved after updating to LOS 2018-03-19. Looks like the update got withdrawn though, cannot find it anyware on the LOS websites
