### ISSUE TITLE
Could you implement ProviderInstaller

### ISSUE THREAD

**Issue by KOLANICH** [microg/android_packages_apps_GmsCore#504]
I see that there is no ProviderInstaller at all in MicroG.
https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/com/google/android/gms/common/security/ProviderInstallerImpl.java#L24

Could you implement this?

Here is a google library for it:
https://github.com/google/conscrypt

And some implementation which may be useful https://github.com/maks/MGit/blob/a5f0b5d73b35a73eaa2c8870a7cb62efa32e2060/app/src/main/java/com/manichord/mgit/transport/SSLProviderInstaller.java

**Comment by voidstarstar** [comment]
This issue should probably get more attention for a couple of reasons:
1. This is a security issue.
2. As servers and apps are updated (including official Google apps), they will deprecate old insecure protocols causing apps to simply stop working without this fix (including older versions of the app).

(For example, many servers are disallowing TLS 1.0 and requiring TLS 1.2+, yet this is unsupported on older versions of Android.)

It looks like there are already some Google apps that try to update the providers as seen in the logcats reported in #72 and #86.

Details can be found here: https://developer.android.com/training/articles/security-gms-provider

If conscrypt is included as a dependency, would something as simple as this be enough to fix the issue?

```
Security.insertProviderAt(Conscrypt.newProvider(), 1);
```

**Comment by voidstarstar** [comment]
This may be of use: https://pastebin.com/NaisKQTb

(This was obtained by using the Jadx decompiler on `classes2.dex` in `PrebuiltGmsCore.apk` in the stock variant of Open GApps.)
