### ISSUE TITLE
Threema can't register for GCM on LOS 15.1

### ISSUE THREAD

**Issue by GitteHuber** [microg/android_packages_apps_GmsCore#509]
Device: Nexus 5x
ROM: Lineage 15.1 for microg (latest build)
App: Threema 3.41 (Webshop-Version)

Switched over from _LOS 14.1 for microg_ to _LOS 15.1 for microg_ yesterday. Push via microg GCM worked like a charm for Threema (3.41) on LOS 14.1, it doesn't on LOS 15.1.
On LOS 15.1 the logs are showing a timeout when Threema is trying to register for GCM (java.io.IOException: TIMEOUT).

See the attached logs for details. The error messages seem to be the same in case of the initial registration intent and when hitting the "Reset Push Token" button in Threema config options.

This is a newly installed LOS 15.1, before installation I did a full wipe. Threema (Threema Webshop APK-Version) was installed from SDCARD.

Logcat Threema: [logcat_threema_gcm_bug.txt](https://github.com/microg/android_packages_apps_GmsCore/files/1845611/logcat_threema_gcm_bug.txt)
Threema Log: [threema_message_log.txt](https://github.com/microg/android_packages_apps_GmsCore/files/1845613/threema_message_log.txt)

I`ve seen #439 and #502 but don't think this is a duplicate. The  other reports are describing different phenomena, this is meant as a specific report for Threema on LOS 15.1.

**Comment by conrad-heimbold** [comment]
Until the issue is fixed, maybe go back to LOS 14.1?

**Comment by ximmox** [comment]
Exactly the same issue with GCM connections after switching from LOS 14.1 to 15.1 yesterday.
Only difference: My device is a Motorola Moto Z (griffin).

My logs show exactly the same errors, App is also 3.41 from the Threema Shop.

**Comment by brevilo** [comment]
Same here, yet on AOSP 8.1 (OmniROM).

Cheers

**Comment by chris42** [comment]
After the newest patch Threema still would not register. 
Marvin knows of it: https://github.com/microg/android_packages_apps_GmsCore/issues/439#issuecomment-417241385
We'll need to wait till a patch comes around

**Comment by neolovich** [comment]
Same here with Fairphone 2.

**Comment by GitteHuber** [comment]
0.2.6.13280 seems to fix this on my phone.

**Comment by GitteHuber** [comment]
After reading #439 I guess this can be closed, too.
