### ISSUE TITLE
Update Google Play services issue

### ISSUE THREAD

**Issue by hbers** [microg/android_packages_apps_GmsCore#511]
I'm using the last beta version of Microg on F-Droid right now. After Telegram's last update this issue emerged

**Comment by conrad-heimbold** [comment]
Error message in logcat: 
``Google Play Services out of date. Requires 12210000 but found 11951417``

Please change the version.

**Comment by conrad-heimbold** [comment]
Hellooooo?!? Anybody listening? This is very easy to fix!

**Comment by fabian-marquardt** [comment]
Same issue here.

**Comment by conrad-heimbold** [comment]
Finally I found the place: 
/play-services-core/build.gradle , line 68 has to be changed, from ```versionCode(11951400 + x % 100 + ((int) (x / 100)) * 100 ``` to ``` versionCode(12210000 + x % 100 + ((int) (x / 100)) * 100```

**Comment by mar-v-in** [comment]
Fixed with 908c20ccc25f5e16bfc14f6b1267910dbd2dc964

**Comment by julienschmidt** [comment]
It's present but you have to manually select the latest preview version.
By default it links to an outdated "stable" version.
Direct link: https://microg.org/fdroid/repo/com.google.android.gms-12221403.apk

**Comment by aktivkohle** [comment]
Thankyou that worked!

**Comment by smigima** [comment]
Well it's not working with Opera Touch - it shows message that I need to update Google PLay Services and shut down.
I've found mods of microg with changed version of Play Service to 9999999 on some russian forums but aren't available to download anymore.
I've also found out that I can change manually version in Manifest.xml but can't find accurate line, maybe something changed.

**Comment by ps-r** [comment]
Installing [Fakestore](https://github.com/microg/android_packages_apps_FakeStore/releases) solved the issue for me (incl. Telegram).

**Comment by BrandonGL** [comment]
@conrad-heimbold How and where do you edit that line? Is "/play-services-core/build.gradle" a location in the File Manager or something else?
