### ISSUE TITLE
0.2.4-111. Broken registration of push messages applications.

### ISSUE THREAD

**Issue by RealVaVa** [microg/android_packages_apps_GmsCore#517]
Hi and sorry for owful English.
It does not matter  - clean install on pure noGapps firmware or update previous build (108). New applications are not registered in microG Google Cloud Messaging.  It can be Viber,  Telegram, VK etc.

**Comment by ArchangeGabriel** [comment]
This is quite expected, see #510.

**Comment by ale5000-git** [comment]
I think it has nothing to do with version 0.2.4-111 since there are only minor changes, and none related to push messages.

**Comment by Vavun** [comment]
Strange thing, but yesterday I made an experiment.
I installed microg 108 and 111 version on clean firmware 4.4.4, 5.1 and 7.1.
I tested vk app, Kate mobile and telegram.
On 108 everything is OK, on 111 no one app is registered to receive push.
Every time I did a clean firmware and microg install. I use zip from Nano droid project.
Sorry for bad English.

**Comment by Vavun** [comment]
Is was coincidence ?

**Comment by ArchangeGabriel** [comment]
On what hour did you run which attempt? Problems with SafetyNet/Certification started y-day precisely.

**Comment by chris42** [comment]
Check #439 
Try to install an older version of the app that is not registering and then updating. Microg is not yet prepared for the new messaging FCM registration, hence needs to use old GCM methods.

**Comment by godoftech** [comment]
Possible workaround:
https://github.com/microg/android_packages_apps_GmsCore/issues/631#issuecomment-429013399

**Comment by ale5000-git** [comment]
The problem should be fixed in recent versions of microG GmsCore, I'm closing this for now.
Please try it and report back.
