### ISSUE TITLE
Various android.* packages does not exist while trying to build UnifiedNlp

### ISSUE THREAD

**Issue by pundirsumit** [microg/android_packages_apps_GmsCore#522]
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/internal/location/ProviderProperties.java:19: error: package android.os does not exist
import android.os.Parcel;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/internal/location/ProviderProperties.java:20: error: package android.os does not exist
import android.os.Parcelable;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/internal/location/ProviderProperties.java:28: error: cannot find symbol
public final class ProviderProperties implements Parcelable {
                                                 ^
  symbol: class Parcelable
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/internal/location/ProviderProperties.java:113: error: package Parcelable does not exist
    public static final Parcelable.Creator<ProviderProperties> CREATOR =
                                  ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/internal/location/ProviderProperties.java:132: error: cannot find symbol
    public void writeToParcel(Parcel parcel, int flags) {
                              ^
  symbol:   class Parcel
  location: class ProviderProperties
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/internal/location/ProviderRequest.java:20: error: package android.os does not exist
import android.os.Parcel;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/internal/location/ProviderRequest.java:21: error: package android.os does not exist
import android.os.Parcelable;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/internal/location/ProviderRequest.java:28: error: cannot find symbol
public final class ProviderRequest implements Parcelable {
                                              ^
  symbol: class Parcelable
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationRequest.java:19: error: package android.os does not exist
import android.os.Parcel;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationRequest.java:20: error: package android.os does not exist
import android.os.Parcelable;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationRequest.java:21: error: package android.os does not exist
import android.os.SystemClock;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationRequest.java:22: error: package android.os does not exist
import android.os.WorkSource;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationRequest.java:85: error: cannot find symbol
public final class LocationRequest implements Parcelable {
                                              ^
  symbol: class Parcelable
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/internal/location/ProviderRequest.java:51: error: package Parcelable does not exist
    public static final Parcelable.Creator<ProviderRequest> CREATOR =
                                  ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/internal/location/ProviderRequest.java:70: error: cannot find symbol
    public void writeToParcel(Parcel parcel, int flags) {
                              ^
  symbol:   class Parcel
  location: class ProviderRequest
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationRequest.java:159: error: cannot find symbol
    public static LocationRequest createFromDeprecatedCriteria(Criteria criteria, long minTime,
                                                               ^
  symbol:   class Criteria
  location: class LocationRequest
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationRequest.java:420: error: cannot find symbol
    public void setWorkSource(WorkSource workSource) {
                              ^
  symbol:   class WorkSource
  location: class LocationRequest
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationRequest.java:426: error: cannot find symbol
    public WorkSource getWorkSource() {
           ^
  symbol:   class WorkSource
  location: class LocationRequest
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationRequest.java:454: error: package Parcelable does not exist
    public static final Parcelable.Creator<LocationRequest> CREATOR =
                                  ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationRequest.java:473: error: cannot find symbol
    public void writeToParcel(Parcel parcel, int flags) {
                              ^
  symbol:   class Parcel
  location: class LocationRequest
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/LocationProviderBase.java:21: error: package android.os does not exist
import android.os.Bundle;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/LocationProviderBase.java:22: error: package android.os does not exist
import android.os.IBinder;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/LocationProviderBase.java:23: error: package android.os does not exist
import android.os.WorkSource;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/LocationProviderBase.java:65: error: cannot find symbol
    public IBinder getBinder() {
           ^
  symbol:   class IBinder
  location: class LocationProviderBase
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/Location.java:19: error: package android.os does not exist
import android.os.Bundle;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/Location.java:20: error: package android.os does not exist
import android.os.Parcel;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/Location.java:21: error: package android.os does not exist
import android.os.Parcelable;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/Location.java:22: error: package android.util does not exist
import android.util.Printer;
                   ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/Location.java:35: error: cannot find symbol
public class Location implements Parcelable {
                                 ^
  symbol: class Parcelable
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/LocationProviderBase.java:100: error: cannot find symbol
    public abstract void onSetRequest(ProviderRequestUnbundled request, WorkSource source);
                                                                        ^
  symbol:   class WorkSource
  location: class LocationProviderBase
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/LocationProviderBase.java:120: error: cannot find symbol
    public abstract int onGetStatus(Bundle extras);
                                    ^
  symbol:   class Bundle
  location: class LocationProviderBase
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/LocationProviderBase.java:142: error: cannot find symbol
    public boolean onSendExtraCommand(String command, Bundle extras) {
                                                      ^
  symbol:   class Bundle
  location: class LocationProviderBase
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/Location.java:490: error: cannot find symbol
    public Bundle getExtras() {
           ^
  symbol:   class Bundle
  location: class Location
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/Location.java:498: error: cannot find symbol
    public void setExtras(Bundle extras) {
                          ^
  symbol:   class Bundle
  location: class Location
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/Location.java:501: error: cannot find symbol
    public void dump(Printer pw, String prefix) {
                     ^
  symbol:   class Printer
  location: class Location
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/Location.java:504: error: package Parcelable does not exist
    public static final Parcelable.Creator<Location> CREATOR =
                                  ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/Location.java:523: error: cannot find symbol
    public void writeToParcel(Parcel parcel, int flags) {
                              ^
  symbol:   class Parcel
  location: class Location
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/GeocodeProvider.java:19: error: cannot find symbol
import android.location.Address;
                       ^
  symbol:   class Address
  location: package android.location
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/GeocodeProvider.java:21: error: package android.os does not exist
import android.os.IBinder;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/GeocoderParams.java:19: error: package android.content does not exist
import android.content.Context;
                      ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/GeocoderParams.java:20: error: package android.os does not exist
import android.os.Parcel;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/GeocoderParams.java:21: error: package android.os does not exist
import android.os.Parcelable;
                 ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/GeocoderParams.java:35: error: cannot find symbol
public class GeocoderParams implements Parcelable {
                                       ^
  symbol: class Parcelable
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/GeocodeProvider.java:42: error: cannot find symbol
            GeocoderParams params, List<Address> addrs);
                                        ^
  symbol:   class Address
  location: class GeocodeProvider
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/GeocodeProvider.java:52: error: cannot find symbol
            GeocoderParams params, List<Address> addrs);
                                        ^
  symbol:   class Address
  location: class GeocodeProvider
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/com/android/location/provider/GeocodeProvider.java:61: error: cannot find symbol
    public IBinder getBinder() {
           ^
  symbol:   class IBinder
  location: class GeocodeProvider
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/GeocoderParams.java:41: error: cannot find symbol
    public GeocoderParams(Context context, Locale locale) {
                          ^
  symbol:   class Context
  location: class GeocoderParams
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/GeocoderParams.java:58: error: package Parcelable does not exist
    public static final Parcelable.Creator<GeocoderParams> CREATOR =
                                  ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/GeocoderParams.java:73: error: cannot find symbol
    public void writeToParcel(Parcel parcel, int flags) {
                              ^
  symbol:   class Parcel
  location: class GeocoderParams
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationManager.java:19: error: package android.app does not exist
import android.app.PendingIntent;
                  ^
/home/pundirsumit/android_packages_apps_GmsCore/extern/UnifiedNlp/unifiednlp-compat/src/current/java/android/location/LocationManager.java:20: error: package android.content does not exist
import android.content.Context;

Does anyone know what could be the problem? I have set my directories properly as well.

**Comment by pundirsumit** [comment]
Okey i've fixed the issue by changing the line in build.gradle file present at extern/UnifiedNlp/unifiednlp-compat/build.gradle:

compileClasspath += project.rootProject.files("$sdkDir/platforms/android-25/android.jar")  to 
compileClasspath += project.rootProject.files("$sdkDir/platforms/android-27/android.jar").

**Comment by voidstarstar** [comment]
For reference, this appears to have been fixed in https://github.com/microg/android_packages_apps_UnifiedNlp/pull/159.

It seems that this fix is not being applied because the git submodule was never updated when the above PR was merged in.  I have opened the PR https://github.com/microg/android_packages_apps_GmsCore/pull/568 to fix this.
