### ISSUE TITLE
No new builds for Mido

### ISSUE THREAD

**Issue by marlid91** [microg/android_packages_apps_GmsCore#523]
I downloaded microg for Lineage OS at lineage.microg.com for Xiaomi Redmi Note 4. The latest update that I've gotten is from March 31st. There have been 2-3 updates for my phone since then, but I haven't received any. 

What's causing this problem?

**Comment by ArchangeGabriel** [comment]
1. Wrong place to ask. Ask [here](https://github.com/lineageos4microg/l4m_website/issues).

2. There are indeed two new updates upstream, but not at https://download.lineage.microg.org/mido/. So the issue is likely build failure or something like that.
