### ISSUE TITLE
SafetyNet failing

### ISSUE THREAD

**Issue by nguyen4514** [microg/android_packages_apps_GmsCore#526]
I've been using Lineage OS with microg for several months and recently noticed that I cannot pass safetynet.

I noticed this a couple of weeks ago. At first, I thought it was because of the current build for Lineage, so I downgraded to the last previous build I remember that passed safetynet. Unfortunately, my device is still failing safetynet.

Droidguard helper has been moved to /system/priv-app/.

**Comment by ale5000-git** [comment]
Google has updated its code, so there is no way to pass until DroidGuard Helper is fixed.

**Comment by nguyen4514** [comment]
Thanks for the update.

**Comment by jamestrot19992** [comment]
SafetyNet is passing for me on latest MicroG
[SafetyNet Attest](https://i.ibb.co/YB8mXVz/Capture.png)
[microG Settings](https://i.ibb.co/dGPnfPt/Capture.png)

**Comment by aaron-sonin** [comment]
Seconded. Getting "response payload validation failed" when checking safetynet with latest lineageos-microg, droidguard helper in priv-apps, and unrooted.

**Comment by kYc0o** [comment]
@jamestrot19992 which servers are you using? I'm with the official ones and still have the `ApiException[14] 14:`

**Comment by Riamse** [comment]
@Happyfeet01  @kYc0o  @aaron-sonin  https://github.com/microg/android_packages_apps_GmsCore/issues/638#issuecomment-428640487 might be the droidguard helper apk you're looking for

**Comment by Nanolx** [comment]
@ale5000-git could you close this issue? It's about the old bug fixed by https://github.com/microg/android_packages_apps_RemoteDroidGuard/pull/19
