### ISSUE TITLE
Telegram 4.8.6, Google Play Services issue

### ISSUE THREAD

**Issue by 0x264f** [microg/android_packages_apps_GmsCore#527]
After today's update of the Telegram (4.8.6), sometimes I began to receive a notification about the need to update Google Play Services. For version 4.8.5, this issue has been fixed in version 0.2.4-111-gf1cdb48, but now this again requires fix.

**Comment by ildar** [comment]
You may want to switch to FOSS "Телеграм"
https://f-droid.org/app/org.telegram.messenger
It doesn't need GCM at all

**Comment by Torvin** [comment]
Relevant log line:
`GooglePlayServicesUtil: Google Play services out of date.  Requires 12451000 but found 12221403`

@mar-v-in please patch

**Comment by Torvin** [comment]
I wonder if apps would complain if we set it to something like 9999xxxx...

**Comment by hbers** [comment]
If there was an option to set it manually within the gui this issue wouldn't come up every month or so. Any users out there who can come up with a solution for this it would be much appreciated.

**Comment by firstamendment** [comment]
My current understanding is that the manual changing is impossible without xposed or the like.

I also believe that @mar-v-in doesn't want to set it too a really high number so that things don't break with no indication.

**Comment by ArchangeGabriel** [comment]
Yes, @mar-v-in already said that manual changing is not possible, and that setting an high number is not a good idea.

**Comment by bocekm** [comment]
@sudofail, I can see in the Telegram settings, that you're able to set Proxy with which you may bypass the Russian ban. As a workaround, I'd suggest you to use VPN (e.g. https://nordvpn.com/blog/russia-wants-ban-telegram/) instead of Proxy together with the FOSS Telegram version from F-droid.

**Comment by Dr-Cool** [comment]
Unfortunately the FOSS version uses too much battery compared to the GCM version. Waiting for a new microG, and meanwhile I have an Automate task killing Google's notification nag, since the GCM version seems to work fine except for the nag.

**Comment by maracuja-juice** [comment]
@Dr-Cool Can you share that task with me?

**Comment by Dr-Cool** [comment]
@maracuja-juice, I tried it myself after posting but unfortunately APK Icon Editor refuses to recompile the app once you change its version codes, it appears to only allow to make changes to simpler apps. Dead end.

**Comment by maracuja-juice** [comment]
@Dr-Cool I mean that Automate task you're talking about.

**Comment by Dr-Cool** [comment]
Oh, OK, you can get it here: [https://forum.fairphone.com/t/battery-heat-control-flow-for-automate-needs-root/40656](https://forum.fairphone.com/t/battery-heat-control-flow-for-automate-needs-root/40656)

**Comment by Dr-Cool** [comment]
Oh, thanks me for reminding me of that one, fortunately I still had a copy of that flow around, you can get it here: [https://forum.fairphone.com/t/kill-update-google-play-services-notification-nag-flow-for-automate/40679](https://forum.fairphone.com/t/kill-update-google-play-services-notification-nag-flow-for-automate/40679)

**Comment by maracuja-juice** [comment]
@Dr-Cool Thanks. I tried it out but it does nothing when I get such a notification.

**Comment by Dr-Cool** [comment]
You have to make sure that Automate has all the permissions that are necessary, there are quite a few including accessibility (it needs to read your screen to know that notification has been issued and to "touch" it).

**Comment by benwaffle** [comment]
same error with slack

**Comment by benwaffle** [comment]
isn't this fixed?

**Comment by chris42** [comment]
It should be fixed with the latest version from microg.org.
Of course it will reoccur with every google framework update
