### ISSUE TITLE
MediaMonkey wants Google Play Services

### ISSUE THREAD

**Issue by DocMAX** [microg/android_packages_apps_GmsCore#532]
I installed latest microG with all status checks checked green. But still Mediamonkey wants Google Play Services. What can i do?

Error:
This version of MediaMonkey for Android requires Google Play Services 11.9.1 or higher. Please update to latest version.

**Comment by ale5000-git** [comment]
Update microG GmsCore to the latest version [here](https://microg.org/download.html) (using the drop-down menu).

**Comment by DocMAX** [comment]
thanks, looks like its working.

**Comment by Roboe** [comment]
Please close this issue if it's solved
