### ISSUE TITLE
Safetynet fails

### ISSUE THREAD

**Issue by JohnGLFour** [microg/android_packages_apps_GmsCore#543]
Hi, I wanna say that Safetynet fails all the time even with the SU hide (Magisk)
I've done the following steps:
1. Switch to Lineage for MicroG
2. SUHide all of the MicroG apps
3. Register my device
4. Login to Google Play
5. MOVED DROIDGUARD HELPER TO /system/priv-app AND SETTED RIGHT PERMISSIONS
I guess is the server problem or something, I got Response payload validation failed (According to Safety net test)

**Comment by ale5000-git** [comment]
Duplicate.

See #526

**Comment by Nanolx** [comment]
@ale5000-git could you close this issue? It's about the old bug fixed by https://github.com/microg/android_packages_apps_RemoteDroidGuard/pull/19
