### ISSUE TITLE
Whatsapp Backup broken

### ISSUE THREAD

**Issue by Sirtz** [microg/android_packages_apps_GmsCore#547]
Hi,

When I start whatsapp, I log in using the sms code. After that it asks me to recover a backup from my google drive. Now when I want to give whatsapp access to my google drive, it just gives me the option to add a new google account. My current one (where my google drive backup is uploaded) is not in the list. When I add it by using the whatsapp prompt, it says that the account already is on my device. When I remove the account in the settings app, and add it as a new one in whatsapp, it just loads forever.

I would really appreciate your help, as this is kinda a dealbreaker for me :D

**Comment by Catfriend1** [comment]
Probably related https://github.com/microg/android_packages_apps_GmsCore/issues/548

**Comment by Sirtz** [comment]
Workaround is to do a local backup on stock rom, and copy it over to your new install until the accounts are fixed.

**Comment by maracuja-juice** [comment]
Security wise you shouldn't do Google Drive Backups for WhatsApp anyway.
