### ISSUE TITLE
Any.do won't run unless you update GPlay Services

### ISSUE THREAD

**Issue by maracuja-juice** [microg/android_packages_apps_GmsCore#549]
I'm on the newest version of Any.Do and microg but the message in the title shows in my notifications.
What can I do?

**Comment by tjallingran** [comment]
This is the same issue as #541 and #527. I ran into the issue with the Alarmy alarm clock app. It looks like we'll have to wait for a new microG release.

**Comment by maracuja-juice** [comment]
Okay thanks. Patiently waiting for that.

**Comment by k3lt** [comment]
Same with Google Pay.. says to update Google Play Services.

**Comment by kenogo** [comment]
I don't think we need to open a new issue for every other app that needs a version bump, because they're all really the same issue and spamming the issues is doing noone a favor.

**Comment by k3lt** [comment]
The version is still not bumped or i'm doing something wrong?

**Comment by k3lt** [comment]
Thanks but i switched back to standard gapps.. i can't afford to have my apps that require latest gplay services not working for 10 days..

**Comment by tjallingran** [comment]
@pejakm That's not an "official" version from this Github repository, but bases on a fork (https://github.com/NoGooLag/android_packages_apps_GmsCore). The commits over there do look OK from what I've seen, but I'd rather wait for an "official" version bump here.

**Comment by maracuja-juice** [comment]
That's correct. We could also submit a PR for this based on the commits of @MVXZ

**Comment by maracuja-juice** [comment]
You need to update to the newest preview version through F-Droid!

**Comment by tjallingran** [comment]
It's not fixed. Wel ok, maybe it is for Any.do, in which case closing this issue makes sense. The latest microg preview version is from April 4th, which still uses a Play Services version number that is too low for a lot of apps.

**Comment by maracuja-juice** [comment]
Yes that's correct. For any.do it's fixed but there is a different app that complains.

**Comment by xenithorb** [comment]
Still not bumped :| 

@mar-v-in Have you thought about passing along some release management and merge responsibilities to trusted contributors? 

There's enough people to go around and community support (especially with the lineage fork) to get things done in a relatively timely manner. Can we find a way for you to not be the only gate-keeper? Please?

**Comment by ale5000-git** [comment]
To all: update to the latest version of microG GmsCore (currently 0.2.5.12879).
