### ISSUE TITLE
Can NewPipe be part of a YouTube API implementation?

### ISSUE THREAD

**Issue by timofonic** [microg/android_packages_apps_GmsCore#57]
Hello.

Can NewPipe work as a YouTube API replacement? In order to remove Google stuff and make other apps depending on it to still work as should.

It can be part of MicroG package, that aims to replace Google Services API and such.

https://developers.google.com/youtube/android/player/
https://github.com/theScrabi/NewPipe

NewPipe is in initial development stage. It aims to support YouTube first and support other services later too. The roadmap is described out there.

This could not only replace the proprietary YouTube API implementation, but also the base to make it a service-agnostic API too.

Kind regards.

**Comment by breversa** [comment]
I've discovered NewPipe a few weeks ago and been using it since, as a replacement for the privacy-invasive YouTube app.

IMO too, it perfectly fits the scope of the μg project. :-)

**Comment by n76** [comment]
microG doesn't even package all of its own needed little bits and pieces in one package so I am not sure why packaging up an app available on F-Froid would be high on the priority list.

https://f-droid.org/repository/browse/?fdfilter=NewPipe&fdid=org.schabi.newpipe

**Comment by breversa** [comment]
It's true that a single μg package would be a much more useful thing. Adding options (à la [Open GApps](http://opengapps.org/) could always come later.

**Comment by binaricode** [comment]
Google Play services does not provide a YouTube API, therefore it should not be included in this app specifically. However, including it in an "Open Source GAPPS" package in the future would be good.

**Comment by mar-v-in** [comment]
YouTube API seems not to be relevant right now and I am not even sure that it belongs to GmsCore or is actually implemented by the YouTube app. I will close this issue for now, we maybe want to reconsider it in a year ;)

**Comment by breversa** [comment]
WebTube (https://fossdroid.com/a/webtube.html) actually (currently) does a
better job than NewPipe. :-)

2016-01-26 15:00 GMT+01:00 Marvin W <notifications@github.com>:
