### ISSUE TITLE
Your system does not support this UnifiedNlP Package

### ISSUE THREAD

**Issue by 0pLuS0** [microg/android_packages_apps_GmsCore#575]
Hello

I'm running an Mi A1 Stock Oreo. I used the Terminal Debloater and removed as much of Google as I understand...

```Apps Installed```
Xposed - version 90-beta 3
FakeGapps - 2.0
Magisk 16.0
Services Core - com.google.android.gms-9258259.apk
Services Framework Proxy - com.google.android.gsf-8.apk
Store (FakeStore release) - com.android.vending-16.apk
DroidGuard Helper - org.microg.gms.droidguard-4.apk

From the above apps I installed, I didn't install any UnifiedNlP package. These are the same apps I install in Custom Roms, and I don't see this message in Custom Roms, but for some reason running Stock Oreo with only these packages installed, it is not working. instead in the microg settings I see this section;

```System supports location provider```
Your system does not support this UnifiedNlP 
package. Either install a matching package or a 
compatibility Xposed module.

Should I also install ```UnifiedNlp.apk``` & ```NetworkLocation.apk```?

I'm attaching two screen shots showing the microg settings.

![settings2](https://user-images.githubusercontent.com/36190223/42608695-90548bf2-8578-11e8-9337-3b4bd0386929.jpg)

**Comment by 0pLuS0** [comment]
Sorry if I have found a correct solution? After reading around, I installed the ```XposedGmsCoreUnifiedNlP``` 

And now I have ```System supports location provider``` Checked

**Comment by 0pLuS0** [comment]
Since I posted this, I am now using a OnePlus 5T with Oxygen OS 5.1.5 and I'm running into the same thing using the latest microg v0.2.6.13280.

UNifiedNLP that comes in microg doesn't seem to work in stock Android, or does it, and can someone please help, I've been trying to figure this out for the past 3-4 months with no success... :(

Thanks

**Comment by Nanolx** [comment]
It removes all location providers as per the link posted above.

**Comment by 0pLuS0** [comment]
I found out, even with ```XposedGmsCoreUnifiedNlP``` installed, ```UnifiedNlP do not have Location to test Geocoder``` is still not checked.

What I ran across is that I now have to add in these two permissions and then it's checked.

pm grant com.google.android.gms android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.gms android.permission.ACCESS_COARSE_LOCATION

Now in Self-Check it shows up as;

```Geocoder provides address resolution from location``` and it's checked.

Do you know anything about these permissions?

So this is what I'm installing manually in this exact order;

XposedInstaller_3.1.5-Magisk
XposedGmsCoreUnifiedNlP
Magisk 17.1
microG Services Core
microG Services Framework Proxy
FakeStore microG Store
microG DroidGuard Helper

After installing these apps, do these permissions seems like something that does need to be done?

Thanks

**Comment by 0pLuS0** [comment]
@Nanolx thanks for sharing this with me. It also made me think to install DejaVu just to be on the safe side for it's benefits....

So I guess to be safe I'll run all these permissions;

pm grant com.google.android.gms android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.gms android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.gms android.permission.GET_ACCOUNTS
pm grant com.google.android.gms android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.gms android.permission.READ_PHONE_STATE
pm grant com.google.android.gms android.permission.WRITE_EXTERNAL_STORAGE

pm grant com.android.vending android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.vending android.permission.ACCESS_FINE_LOCATION
pm grant com.android.vending android.permission.GET_ACCOUNTS
pm grant com.android.vending android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.vending android.permission.READ_PHONE_STATE
pm grant com.android.vending android.permission.WRITE_EXTERNAL_STORAGE

pm grant org.microg.nlp.backend.ichnaea android.permission.ACCESS_COARSE_LOCATION
pm grant org.microg.nlp.backend.ichnaea android.permission.ACCESS_FINE_LOCATION
pm grant org.microg.nlp.backend.ichnaea android.permission.READ_PHONE_STATE

pm grant org.fitchfamily.android.dejavu android.permission.ACCESS_COARSE_LOCATION
pm grant org.fitchfamily.android.dejavu android.permission.ACCESS_FINE_LOCATION

```Look good?```

THANKS

**Comment by Nanolx** [comment]
You don't have to grant all of them manually, only those that are missing

But yes, technically that would be correct.

**Comment by 0pLuS0** [comment]
Ok, on perms, and getting back to the original problem;

```System supports location provider```
Your system does not support this UnifiedNlP
package. Either install a matching package or a
compatibility Xposed module

How can this be done on Stock Android to avoid Xposed? Doing Xposed, then SafetyNet problems...

I assumed when I started messing with microG, that Stock Android was taken into consideration for making all of this work? Not just a project for Custom Roms only...

@Nanolx are you working/helping on microg project?

Thanks

**Comment by Nanolx** [comment]
You said you installed everything from F-Droid? Starting with Android 7 microG needs to be a system app (in /system/priv-app) in first place for unifiednlp to work. So you need to move them there.

**Comment by 0pLuS0** [comment]
Ok, well on my phone evrything is in a directory in /priv-app

GmsCore-v0.2.6.13280.apk I renamed to GmsCore.apk and it lives under /system/priv-app/GmsCore

What about the other packages, does this work?

https://github.com/microg/android_packages_apps_GsfProxy/releases
Services Framework Proxy - /system/priv-app/GsfProxy/GsfProxy.apk

https://github.com/microg/android_packages_apps_FakeStore/releases
Store (FakeStore release) - /system/priv-app/FakeStore/FakeStore.apk

https://microg.org/fdroid/repo/org.microg.gms.droidguard-4.apk
DroidGuard Helper - /system/priv-app/GmsDroidGuard/GmsDroidGuard.apk

https://github.com/microg/android_packages_apps_UnifiedNlp/releases
UnifiedNlp - /system/priv-app/UnifiedNlp/UnifiedNlp.apk

Now if I place UnifiedNlp.apk in the /path /system/priv-app/UnifiedNlp/UnifiedNlp.apk it shows up in the App Drawer, and I didn't think this is what we want happening?

Thanks

**Comment by 0pLuS0** [comment]
Ok, well on my phone everything is in a directory in /priv-app

GmsCore-v0.2.6.13280.apk I renamed to GmsCore.apk and it lives under /system/priv-app/GmsCore

What about the other packages, does this work?

https://github.com/microg/android_packages_apps_GsfProxy/releases
Services Framework Proxy - /system/priv-app/GsfProxy/GsfProxy.apk

https://github.com/microg/android_packages_apps_FakeStore/releases
Store (FakeStore release) - /system/priv-app/FakeStore/FakeStore.apk

https://microg.org/fdroid/repo/org.microg.gms.droidguard-4.apk
DroidGuard Helper - /system/priv-app/GmsDroidGuard/GmsDroidGuard.apk

https://github.com/microg/android_packages_apps_UnifiedNlp/releases
UnifiedNlp - /system/priv-app/UnifiedNlp/UnifiedNlp.apk

Now if I place UnifiedNlp.apk in the /path /system/priv-app/UnifiedNlp/UnifiedNlp.apk it shows up in the App Drawer, and I didn't think this is what we want happening?

Thanks

**Comment by 0pLuS0** [comment]
Ok, well on my phone everything is in a directory in /priv-app

GmsCore-v0.2.6.13280.apk I renamed to GmsCore.apk and it lives under /system/priv-app/GmsCore/GmsCore.apk

What about the other packages, does this work?

https://github.com/microg/android_packages_apps_GsfProxy/releases
Services Framework Proxy - /system/priv-app/GsfProxy/GsfProxy.apk

https://github.com/microg/android_packages_apps_FakeStore/releases
Store (FakeStore release) - /system/priv-app/FakeStore/FakeStore.apk

https://microg.org/fdroid/repo/org.microg.gms.droidguard-4.apk
DroidGuard Helper - /system/priv-app/GmsDroidGuard/GmsDroidGuard.apk

https://github.com/microg/android_packages_apps_UnifiedNlp/releases
UnifiedNlp - /system/priv-app/UnifiedNlp/UnifiedNlp.apk

Now if I place UnifiedNlp.apk in the /path /system/priv-app/UnifiedNlp/UnifiedNlp.apk it shows up in the App Drawer, and I didn't think this is what we want happening?

Thanks

**Comment by 0pLuS0** [comment]
Ok, well on my phone everything is in a directory in /priv-app

GmsCore-v0.2.6.13280.apk I renamed to GmsCore.apk and it lives under /system/priv-app/GmsCore/GmsCore.apk

What about the other packages, does this work?

https://github.com/microg/android_packages_apps_GsfProxy/releases
Services Framework Proxy - ```/system/priv-app/GsfProxy/GsfProxy.apk```

https://github.com/microg/android_packages_apps_FakeStore/releases
Store (FakeStore release) - ```/system/priv-app/FakeStore/FakeStore.apk```

https://microg.org/fdroid/repo/org.microg.gms.droidguard-4.apk
DroidGuard Helper - ```/system/priv-app/GmsDroidGuard/GmsDroidGuard.apk```

https://github.com/microg/android_packages_apps_UnifiedNlp/releases
UnifiedNlp - ```/system/priv-app/UnifiedNlp/UnifiedNlp.apk```

Now if I place ```UnifiedNlp.apk``` in the /path ```/system/priv-app/UnifiedNlp/UnifiedNlp.apk``` it shows up in the ```App Drawer```, and I didn't think this is what we want happening?

Thanks

**Comment by 0pLuS0** [comment]
Ok, well on my phone everything is in a directory in /priv-app

The Wiki;
https://github.com/microg/android_packages_apps_GmsCore/wiki/Installation

Only talks about installing GmsCore...

GmsCore-v0.2.6.13280.apk I renamed to GmsCore.apk and it lives under /system/priv-app/GmsCore/GmsCore.apk

Do the other packages need to also be installed like below?

https://github.com/microg/android_packages_apps_GsfProxy/releases
Services Framework Proxy - ```/system/priv-app/GsfProxy/GsfProxy.apk```

https://github.com/microg/android_packages_apps_FakeStore/releases
Store (FakeStore release) - ```/system/priv-app/FakeStore/FakeStore.apk```

https://microg.org/fdroid/repo/org.microg.gms.droidguard-4.apk
DroidGuard Helper - ```/system/priv-app/GmsDroidGuard/GmsDroidGuard.apk```

https://github.com/microg/android_packages_apps_UnifiedNlp/releases
UnifiedNlp - ```/system/priv-app/UnifiedNlp/UnifiedNlp.apk```

Now if I place ```UnifiedNlp.apk``` in the /path ```/system/priv-app/UnifiedNlp/UnifiedNlp.apk``` it shows up in the ```App Drawer```, and I didn't think this is what we want happening?

Thanks

**Comment by 0pLuS0** [comment]
Ok, well on my phone everything is in a directory in /priv-app

The Wiki only talks about installing GmsCore...

https://github.com/microg/android_packages_apps_GmsCore/wiki/Installation

GmsCore-v0.2.6.13280.apk I renamed to GmsCore.apk and it lives under /system/priv-app/GmsCore/GmsCore.apk

```I followed the Wiki with just GmsCore and this is still not checked.```

Do the other packages need to also be installed like below?

https://github.com/microg/android_packages_apps_GsfProxy/releases
Services Framework Proxy - ```/system/priv-app/GsfProxy/GsfProxy.apk```

https://github.com/microg/android_packages_apps_FakeStore/releases
Store (FakeStore release) - ```/system/priv-app/FakeStore/FakeStore.apk```

https://microg.org/fdroid/repo/org.microg.gms.droidguard-4.apk
DroidGuard Helper - ```/system/priv-app/GmsDroidGuard/GmsDroidGuard.apk```

https://github.com/microg/android_packages_apps_UnifiedNlp/releases
UnifiedNlp - ```/system/priv-app/UnifiedNlp/UnifiedNlp.apk```

Now if I place ```UnifiedNlp.apk``` in the /path ```/system/priv-app/UnifiedNlp/UnifiedNlp.apk``` it shows up in the ```App Drawer```, and I didn't think this is what we want happening?

Thanks

**Comment by 0pLuS0** [comment]
@Nanolx I had a look through the NanoDroid-microg and is this all you remove, which includes the Locations?

for app in ${GOOGLE_DATA}; do
		rm -rf /data/data/${app}
		rm -rf /data/user/*/${app}
		rm -rf /data/user_de/*/${app}
		rm -rf /data/app/${app}-*
	done
	
	
	for app in com.google.android.gms \
					com.google.android.gsf \
					com.android.vending; do
				rm -rf /data/data/${app}
				rm -rf /data/user/*/${app}
				rm -rf /data/user_de/*/${app}
				rm -rf /data/app/${app}-*
			done
			
			if [ "${NANODROID_UPGRADE}" -eq 0 ]; then
			rm -rf /data/data/com.android.vending
			rm -rf /data/user/*/com.android.vending
			rm -rf /data/user_de/*/com.android.vending
			rm -rf /data/app/com.android.vending-*


Also I see this is what you place in ```priv-app```

/NanoDroid-microG-18.3.1.20180921/system/priv-app >ls
DroidGuard  FakeStore  GmsCore  GsfProxy  Phonesky  YalpStore

Besides YalpStore I'm assuming I should all these to priv-app too?

**Comment by 0pLuS0** [comment]
@Nanolx I had a look through the NanoDroid-microg and is this all you remove, which includes the Locations?

for app in ${GOOGLE_DATA}; do
		rm -rf /data/data/${app}
		rm -rf /data/user/*/${app}
		rm -rf /data/user_de/*/${app}
		rm -rf /data/app/${app}-*
	done
	
	for app in com.google.android.gms \
					com.google.android.gsf \
					com.android.vending; do
				rm -rf /data/data/${app}
				rm -rf /data/user/*/${app}
				rm -rf /data/user_de/*/${app}
				rm -rf /data/app/${app}-*
			done
			
			if [ "${NANODROID_UPGRADE}" -eq 0 ]; then
			rm -rf /data/data/com.android.vending
			rm -rf /data/user/*/com.android.vending
			rm -rf /data/user_de/*/com.android.vending
			rm -rf /data/app/com.android.vending-*


Also I see this is what you place in ```priv-app```

/NanoDroid-microG-18.3.1.20180921/system/priv-app >ls
DroidGuard  FakeStore  GmsCore  GsfProxy  Phonesky  YalpStore

So I'm assuming for microG I should do?

/system/priv-app/DroidGuard
/system/priv-app/GmsCore
/system/priv-app/GsfProxy

But on the Wiki it only talks about GmsCore for priv-app;
https://github.com/microg/android_packages_apps_GmsCore/wiki/Installation

So I would of thought if these were all needed, it would be mentioned on the Wiki?

**Comment by 0pLuS0** [comment]
@Nanolx I had a look through the NanoDroid-microg and is this all you remove, which includes the Locations?

for app in ${GOOGLE_DATA}; do
		rm -rf /data/data/${app}
		rm -rf /data/user/*/${app}
		rm -rf /data/user_de/*/${app}
		rm -rf /data/app/${app}-*
	done
	
	for app in com.google.android.gms \
					com.google.android.gsf \
					com.android.vending; do
				rm -rf /data/data/${app}
				rm -rf /data/user/*/${app}
				rm -rf /data/user_de/*/${app}
				rm -rf /data/app/${app}-*
			done
			
			if [ "${NANODROID_UPGRADE}" -eq 0 ]; then
			rm -rf /data/data/com.android.vending
			rm -rf /data/user/*/com.android.vending
			rm -rf /data/user_de/*/com.android.vending
			rm -rf /data/app/com.android.vending-*


Also I see this is what you place in ```priv-app```

/NanoDroid-microG-18.3.1.20180921/system/priv-app >ls
DroidGuard  FakeStore  GmsCore  GsfProxy  Phonesky  YalpStore

So I'm assuming for microG I should do?

/system/priv-app/DroidGuard
/system/priv-app/GmsCore
/system/priv-app/GsfProxy

But on the Wiki it only talks about GmsCore for priv-app;
https://github.com/microg/android_packages_apps_GmsCore/wiki/Installation

So I would of thought if these were all needed, it would be mentioned on the Wiki?

**Comment by 0pLuS0** [comment]
I went through all these /paths you mentioned in the scripts for removal and couldn't find anything that needed removing.

I then placed in priv-app;

/system/priv-app/DroidGuard/DroidGuard.apk
/system/priv-app/GmsCore/GmsCore.apk
/system/priv-app/GsfProxy/GsfProxy.apk

But ```System supports location provider``` is still unchecked.

I'm wondering if this has to do with the ```frameworks-res.apk``` and this may never work in Oxygen...

**Comment by 0pLuS0** [comment]
@Nanolx I had a look through the NanoDroid-microg and what it's removing, but I didn't have anything extra that needed removing in these paths

Also I see this is what you place in ```priv-app```

/NanoDroid-microG-18.3.1.20180921/system/priv-app >ls
DroidGuard  FakeStore  GmsCore  GsfProxy  Phonesky  YalpStore

So for microG I'll add in these paths too;

/system/priv-app/DroidGuard
/system/priv-app/GmsCore
/system/priv-app/GsfProxy

But on the Wiki it only talks about GmsCore for priv-app;
https://github.com/microg/android_packages_apps_GmsCore/wiki/Installation

So I would of thought if these were all needed, it would be mentioned on the Wiki...

System supports location provider is still unchecked.

I wonder if decompiling and changing the framework-res.apk this might work? I don't have java or the tools on my box, if it's not to much trouble maybe you can have a look at this framework-res.apk off the OnePlus 5T? 


[framework-res.apk.zip](https://github.com/microg/android_packages_apps_GmsCore/files/2459456/framework-res.apk.zip)

THANKS

**Comment by Nanolx** [comment]
As in regard of your previous question: I'm not part of the microG project, I'm just using it myself and try to help others.

About /system/app Vs. /system/priv-app: for GmsCore this is required, for the others it shouldn't make a difference in the end.

As for framework-res, I in fact never had a look at it for modifying one regarding unlp, as I always use Aftermarket ROMs. The problem with this approach is, that it will be defeated by each ROM update.

Could you post what stuff is inside /system/app and /system/priv-app, aswell as a logcat? It should contain information about why unlp fails to register in the system.

**Comment by 0pLuS0** [comment]
I know who you are, just wasn't sure if you did anything on microG project. Your work on NanoDroid is greatly appreciated!

I've attached a find.txt run from this cmd;
find /system /data/{app,data,misc*,system*} > /sdcard/find.txt

And a logcat

[find.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2462580/find.txt)


[logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2462581/logcat.txt)


Thank you very much for your help!

**Comment by 0pLuS0** [comment]
Ok last one, this time I wiped and installed all microG from F-Droid. So for now it shows two items unchecked, I'm attaching a screen shot. Also new logcat and find.txt

```find.txt```
[find.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2462935/find.txt)


```logcat```
[logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2462938/logcat.txt)


![microg](https://user-images.githubusercontent.com/36190223/46710442-5a985380-cc37-11e8-863e-df0b3876f239.jpg)


THANKS!

**Comment by Nanolx** [comment]
I'll have a look at it during the next days.

**Comment by 0pLuS0** [comment]
@Nanolx

Thank you

**Comment by 0pLuS0** [comment]
@Nanolx hi, by chance any luck?

Thanks

**Comment by bam80** [comment]
@Nanolx, any luck?

**Comment by 0pLuS0** [comment]
I've since moved on and with the latest changes in NanoDroid-microG, it all works now...

No need to reply on my behalf...

Thanks

**Comment by bam80** [comment]
@0pLuS0 I was replying for my behalf. If you had success since then you could report about it.
Sorry for that.

**Comment by 0pLuS0** [comment]
I just installed the Xposed module I mentioned in the second reply, made sure it had all the correct permisions and everything works, there's nothing else I can tell you.

**Comment by Nanolx** [comment]
The NanoDroid-Patcher (again) includes the unified_nlp patch, which *might* fix the issue.

But what I noticed is that on some devices com.qualcomm.location *must be installed* for uNlp to work, while on most/older ROMs you need to remove that package for uNlp to work. The OnePlus 5T is one of the affected devices.

**Comment by bam80** [comment]
@Nanolx do you know the reason of such different behavior?

**Comment by Nanolx** [comment]
It's just the way the location provider is technicall implemented. oF2pks has posted a link (in the NanoDroid XDA-Thread) to a git commit by OnePlus which shows that change.

**Comment by Iey4iej3** [comment]
> The NanoDroid-Patcher (again) includes the unified_nlp patch, which _might_ fix the issue.
> 
> But what I noticed is that on some devices com.qualcomm.location _must be installed_ for uNlp to work, while on most/older ROMs you need to remove that package for uNlp to work. The OnePlus 5T is one of the affected devices.

I wonder whether `com.qualcomm.location` is the proprietary blob [described](https://www.qualcomm.com/site/privacy/services) in their official site as

> Qualcomm Location periodically sends us a unique software ID, the location of your device (longitude, latitude and altitude, and its uncertainty) and nearby cellular towers and Wi-Fi hotspots, signal strength, and time (collectively, “Location Data”). As with any Internet communication, we also receive the IP address your device uses. We use Location Data, software IDs and IP addresses, and the other data we collect to help us protect, evaluate, and improve the performance of our systems.

that is to say, even if we use UnifiedNlp, the presence of `com.qualcomm.location` means that users will upload these privacy data `periodically`? I searched in the repo of LineageOS and found that the maintainers repeatedly re-added it into blobs, even disabling location overlays so that UnifiedNlp won't work any longer. I don't understand what is the difficulty there, but LineageOS is at least advertised to be free and open-source, if there is no difficulty to remove `com.qualcomm.location`, I don't understand why they include it and make it exclusive.
