### ISSUE TITLE
Making a chat group for MicroG?

### ISSUE THREAD

**Issue by Pneumaticat** [microg/android_packages_apps_GmsCore#581]
I didn't see that MicroG had any chat room to organize development/discuss the project, and I thought that perhaps with @mar-v-in being busy, having one might stimulate some community support.

I took the liberty of creating one on Matrix at [#microg:potatofrom.space](https://matrix.to/#/#microg:potatofrom.space), and I can add @mar-v-in as admin if you think that having the room is a good idea. (Or we could use another chat service if you prefer as well.)

**Comment by dimqua** [comment]
https://t.me/joinchat/FyFlS0X2D7f6YNvdxhEsfw

**Comment by Pneumaticat** [comment]
Yeah, didn't mean to start a chat service debate, sorry about that ;) The telegram group looks like just what I was picturing, so I think this issue is solved.
