### ISSUE TITLE
Android 4.2.2 not supported?

### ISSUE THREAD

**Issue by pejakm** [microg/android_packages_apps_GmsCore#59]
I've tried to install GmsCore on my old Prestigio with (nearly AOSP) 4.2.2 Android, but installation failed. I didn't looked at logcat cause I remembered that UnifiedNlp isn't officially supported for old platforms anymore, and figured this might be the reason of installation failure. So, is there a way for a user to build GmsCore for old Android versions?

**Comment by Tentos** [comment]
I am using GmsCore on an Android 4.2.2 device without any problem. Have you downloaded the file from http://files.brnmod.rocks/apps/GmsCore/Latest/ ? If yes, have you chosen play-services-core-debug.apk?

**Comment by pejakm** [comment]
No, I used apk I've compiled myself. But will try this one later today, thanks for the hint.

**Comment by pejakm** [comment]
Debug version installs. Apparently, there's an issue with the apk I signed using my signing certificate. Thanks Tentos!
