### ISSUE TITLE
"$app_name won't run properly until you update Google Play Services"

### ISSUE THREAD

**Issue by DPTJKKVH** [microg/android_packages_apps_GmsCore#596]
An increasing number of apps start to ask for an updated version of Google Play Services, after they received an update themselves.

The most recent ones where Discord and Protonmail. Discord seems to use ReCaptcha now that fails to show so the app is unusable. Protonmail seems to work so far but I need to do more testing before I can be sure.

How can I assist you in finding the issue with this? You probably need a logcat but of what app(s) or service(s) in particular?

I will then try to provide you with those logs.

Both apps are free btw so you could try to reproduce it.

https://play.google.com/store/apps/details?id=ch.protonmail.android

https://play.google.com/store/apps/details?id=com.discord

**Comment by Tyler-2** [comment]
Same:

`08-27 11:36:53.555   525  1510 D audio_hw_primary: select_devices for use case (low-latency-playback)
08-27 11:36:53.555   525  1510 D audio_hw_extn: audio_extn_set_anc_parameters: anc_enabled:0
08-27 11:36:53.557   549   549 D QCOM PowerHAL: Activity launch hint handled
08-27 11:36:53.560   622   666 E ANDR-PERF-OPTSHANDLER: Sched boost lock is already acquired, concurrency is not supported for this resource
08-27 11:36:53.560   622   666 E ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 3, 0]
08-27 11:36:53.697 14473 18102 W ContextImpl: Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
08-27 11:36:53.713 14473 18102 W GooglePlayServicesUtil: Google Play services out of date.  Requires 12451000 but found 12221403
08-27 11:36:54.001 17601 17601 W GeckoApplication: STARTUP PERFORMANCE WARNING: un-official build: purging the startup (JavaScript) caches.
08-27 11:36:54.136  1042  1169 I ActivityManager: Displayed com.Slack/.ui.NotificationSettingsActivity: +539ms
`

This is with Slack's "troubleshoot notifications" feature on a MicroG build of LineageOS.

**Comment by Tyler-2** [comment]
#590 looks like a more app-specific dupe.

**Comment by Tyler-2** [comment]
Turns out this is absolutely nothing new... In the past the GMS version would just get bumped, but now there are functional differences that must also be built in. PR #553 shows some of the discussion around this. And the sole maintainer of this software is over burdened to handle it on his or her own. :-(

**Comment by mar-v-in** [comment]
Fixed in v0.2.5.12879 / 4040e3df85db5dd59ed3028978a33eb92d7f4e46.

**Comment by Tyler-2** [comment]
See the update for MicroG Services Core to version 0.2.5.12879. Appears to have done the trick. Thanks Mar-V-In!

**Comment by DPTJKKVH** [comment]
@mar-v-in Thanks Marvin. I'll send some money your way soon!

I assume those will be included with the next LineageOS for microG ROMs as well as released as an update to F-Droid, right?

**Comment by cRaZy-bisCuiT** [comment]
Thank you very much. Hopefully the next LineageOS for MicroG whyred build will pull these changes.
