### ISSUE TITLE
Fdroid repo error with new update

### ISSUE THREAD

**Issue by churchthecat** [microg/android_packages_apps_GmsCore#599]
Something wrong with the repo. I get ..."repo failed to verify" . Tried to remove and add repo again but same error. Linage Oreo, Magisk and Xposed

**Comment by Miwer** [comment]
Repo is working fine for me. I just upgraded microg using F-Droid 1.3.1.
URL: https://microg.org/fdroid/repo
Fingerprint: 9B D0 67 27 E6 27 96 C0 13 0E B6 DA B3 9B 73 15 74 51 58 2C BD 13 8E 86 C4 68 AC C3 95 D1 41 65

**Comment by projectgus** [comment]
For anyone else who bumps into this trying to update the official APK via FDroid, check in FDroid client if the "Address" field of the MicroG repo is just the URL https://microg.org/fdroid/repo and not the "with fingerprint" URL https://microg.org/fdroid/repo?fingerprint=9BD06727E62796C0130EB6DAB39B73157451582CBD138E86C468ACC395D14165

(Have reported the full details over here: https://gitlab.com/fdroid/fdroidclient/-/issues/2078 )
