### ISSUE TITLE
[victorops] Google Play Store signature invalid

### ISSUE THREAD

**Issue by jeekajoo** [microg/android_packages_apps_GmsCore#60]
Hi @mar-v-in,

I'm using [Victorops](https://play.google.com/store/apps/details?id=com.victorops.androidclient) (current version: 6.1.118) as a pager application on Omnirom 5.1.1.20151103 with gmscore 8.1.15 (microG v0.01) and blankstore 0.7.4 and no google apps at all.

GCM is not working properly (even if the app was installed after gmscore.)
I'm getting this when I launch the app.
```
W/GooglePlayServicesUtil(31124): Google Play Store signature invalid.
E/GooglePlayServicesUtil(31124): Google Play services is invalid. Cannot recover.
```
I'm getting the same when I hit the button `reset push notification ID` inside the app.

Let me know if you need more information.

Thanks
J.

PS: GCM generally works on my phone. Tested with "Push Notification Tester".

**Comment by bonanza123** [comment]
I guess I have seen something similar like that before with another app. When I read this log, I installed the fakeGapps xposed package (despite I'm also running omnirom) and that log disappeared. But still it was not working for me. Have you tried using fakeGapps additionally?

**Comment by haffenloher** [comment]
Did you enable signature spoofing in your phone's developer settings?

**Comment by jeekajoo** [comment]
Well, I was not aware of this setting and I thought it was activated by default.
Thanks to both of you! It works. Closing.
