### ISSUE TITLE
MicroG Wakelock cause no Deep Sleep

### ISSUE THREAD

**Issue by leewp14** [microg/android_packages_apps_GmsCore#604]
MicroG cause phone not entering deep sleep (although battery consumption is not affected, can refer to screenshot attached). 
Clean install of LOS11 with MicroG installed before first boot, runtime is Dalvik. 
Tried *#*#CHECKIN#*#* as stated in previous similar gh issue but not working. 
Using latest MicroG apps. GCM apps are Play Store, Telegram X, WhatsApp, Ebay. 
Using Contact Sync. Don't know if sync is related, as sync always say syncing although alreafy synced. 

![screenshot_2018-09-03-00-28-58](https://user-images.githubusercontent.com/17796518/44958314-3a2afa00-af11-11e8-8f3a-5df327dee6d9.png)
![screenshot_2018-09-03-00-28-50](https://user-images.githubusercontent.com/17796518/44958315-3ac39080-af11-11e8-9844-943d2063cd63.png)

![screenshot_2018-09-03-00-37-17](https://user-images.githubusercontent.com/17796518/44958392-2338d780-af12-11e8-8aba-28be575b28ac.png)
![screenshot_2018-09-03-00-37-25](https://user-images.githubusercontent.com/17796518/44958403-65621900-af12-11e8-879c-8c317746ca2f.png)

**Comment by tomasz1986** [comment]
> Using Contact Sync. Don't know if sync is related, as sync always say syncing although alreafy synced.

You are saying that you are using Google Sync, but there is no Contacts listed under Sync on the screen shot above. Do you have the correct sync adapter APK placed in the /system/app folder?

I think I actually had the same issue in KitKat but I am not sure what exactly fixed it. I think the sync adapter APK from OpenGapps for KitKat was the one that worked fine eventually.

**Comment by leewp14** [comment]
> You are saying that you are using Google Contacts Sync, but there is no Contacts listed under Sync on the screen shot above. Do you have the correct sync adapter APK placed in the /system/app folder?

Opps, turns out that I forget to update the sync adapters too after update gmscore to latest (contacts entry is there before I update gmscore). I will try and report back soon. 

> I think I actually had the same issue in KitKat but I am not sure what exactly fixed it. I think that the sync adapter APK from OpenGapps for KitKat was the one that worked fine eventually.

So you using microg with sync adapters from opengapps before on KitKat?
Sorry for my relatively basic English :sweat_smile:

**Comment by leewp14** [comment]
@tomasz1986 I think I know what happened. The Google contact sync in my phone somehow won't work properly with the latest gmscore. Revert gmscore to earlier version fix the problem but sync won't work well (apps show that play service is outdated)

**Comment by bam80** [comment]
@leewp14 Sorry to interrupt you, I just wonder why are you trying to use Google contact sync at all? What function you lack in DAVDroid?

**Comment by leewp14** [comment]
@bam80 I'm not using DAVDroid. I'm using packages from [here](https://forum.xda-developers.com/android/development/microg-unofficial-installer-t3432360) . Btw is this the right place to report problems like this?

**Comment by ildar** [comment]
пн, 3 сент. 2018 г., 14:12 bam80 <notifications@github.com>:

> @leewp14 <https://github.com/leewp14> Sorry to interrupt you, I just
> wonder why are you trying to use Google contact sync at all? What function
> you lack in DAVDroid?
>
That's because MicroG sites do not mention this alternative. Users have
basically nowhere to know it from

**Comment by tomasz1986** [comment]
> So you using microg with sync adapters from opengapps before on KitKat?

Actually, I have tested again and the result is that all versions of the GoogleContatsSyncAdapter.apk available in OpenGapps or APKMirror force close and fail to sync. I have managed to get it to work with very old files from https://forum.xda-developers.com/showthread.php?t=2256212. The sync does work but I would not suggest this method. If possible, try to use DAVDroid, as already suggested above.

**Comment by leewp14** [comment]
@tomasz1986 no problem. I also thinks that maybe this is kind of out of microg's scope. 
Just fyi, none of them crash on my phone. The adapters just works fine for me. 
But anyways it's ok, I'm using the previous microg now and just chrome sync not working just like earlier, as stated earlier due to outdated microg version, but at least every other thing works. Deep sleep also not present when using that earlier version. 
@ildar yes, I didn't see that before. I might try it one day. 

Thanks anyone for looking into this issue!

**Comment by tomasz1986** [comment]
After more testing, I can say that this issue is unrelated to the actual GoogleSyncAdapter apk. Just installing microG and logging in to your Google account will cause the wakelock, and setting DAVDroid up to sync Contacts does not make any difference. To reiterate, microG is stuck in Google Contacs sync wakelock even if no Contacts sync has been actually set up on the device.

The problem only happens in KitKat (and probably below too, but I have not tested that).

**Comment by leewp14** [comment]
@tomasz1986 yes, it did stuck, similarly to what I said [earlier](https://github.com/microg/android_packages_apps_GmsCore/issues/604#issuecomment-418035414) before which I realized after performing a clean install of system. 
My workaround is reverting to earlier microg, which I said before, which works just well, with an exception that apps sync won't work well (prompts to update play services) which is understandable as that version is released before the gmscore version bump. 
Thank you for spending time in testing out too!
