### ISSUE TITLE
Contacts Has Stopped - I Thought GmsCore Supports It?

### ISSUE THREAD

**Issue by 0pLuS0** [microg/android_packages_apps_GmsCore#606]
Hello,

My Specs:
--------------
Essential - Stock Oreo 8.1.0 - Deodex
Magisk 17.1 - Modules - Debloater (Terminal Emulator) - F-Droid Privileged Extension
Services Core - com.google.android.gms-12879000.apk
Services Framework Proxy - com.google.android.gsf-8.apk
Store (FakeStore release) - com.android.vending-16.apk
DroidGuard Helper - org.microg.gms.droidguard-4.apk - stable

Following Debloated:
---------------------------
Calendar
Chrome
Essential Services
Gmail
Google
Google Play Services
Google Play Store
Maps
Photos
YouTube

I thought/assumed that with the microg Services Core installed the Google Contacts would work ok?

Every time I try to start it, I get a popup saying ```Contacts has stopped```.

I also thought there's a AOSP Contacts version, and Google's version? Because I don't understand how in Custom Roms with no Gapps installed Contacts works, but in this Stock Oreo I am running that I debloated and manually installed microg it's not?

Any help here and understanding would be appreciated, especially if Contacts is not supported to work, so I'm not running trying to solve something that can't...

I've attached a logcat, I hope that helps.

[logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2352196/logcat.txt)

Thanks

**Comment by voidstarstar** [comment]
The signature probably just needs to be added to [`KNKOWN_GOOGLE_PACKAGES`](https://github.com/microg/android_packages_apps_GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/common/PackageUtils.java#L59).

Maybe someone can confirm if this is correct/works:

`KNOWN_GOOGLE_PACKAGES.put("com.google.android.contacts", "ee3e2b5d95365c5a1ccc2d8dfe48d94eb33b3ebe");`

**Comment by 0pLuS0** [comment]
NanoDroid just made this change in their microg package, so I'm seeing it work from it.

https://downloads.nanolx.org/NanoDroid/Stable/

Thanks
