### ISSUE TITLE
Transit app is crashing and don't show Map

### ISSUE THREAD

**Issue by wedza** [microg/android_packages_apps_GmsCore#608]
Hello,

It seems like the Transit app can't pick up the Maps API. When the apps start, the map doesn't show up, and the app crashes after a few seconds.

![screenshot_action_launcher_20180905-220832](https://user-images.githubusercontent.com/20335741/45131255-7903be80-b162-11e8-9fb1-6ddc32005c74.png)

![screenshot_action_launcher_20180905-220848](https://user-images.githubusercontent.com/20335741/45131272-8caf2500-b162-11e8-83fa-4292bb7277ae.png)

Nexus 6P with Lineage 15.1-20180827-microG-angler

MicroG version 0.2.5.12879

Transit 5.0.3

Thanks for making possible to use all of those great APIs without giving all our life to Google!

**Comment by Riamse** [comment]
An update to this thread, it seems that the map problems remain but now without Transit App crashing. It seems to me that there is something chronically wrong with every app that has a map embedded, with the only exception being Google Maps itself which works flawlessly.

**Comment by wedza** [comment]
Yeah, your alright @Riamse, Transit now seems to work with his latest version (with the same map glitches than there are in any other app).

I think the maps problems should be treaded in a separated issues to keep things clean.

Closing#608
