### ISSUE TITLE
Unable to tap login or cancel

### ISSUE THREAD

**Issue by HemanthJabalpuri** [microg/android_packages_apps_GmsCore#619]
I am running on stock touchwiz 4.4.2 rom..
I flashed Nanodroid microG..
But I am not able to tap Login or Cancel in microG login setup wizard...
here is the logcat taken with SysLog app https://drive.google.com/file/d/1k8SIHMkr0f1gy18fB5qR4lEm5JjghXBV/view?usp=drivesdk ..

Thanks..

**Comment by tomasz1986** [comment]
It is a known issue. Either use an old version of microG (e.g. v2.4) and update it later, or connect an external keyboard and navigate the buttons with TAB key.

**Comment by HemanthJabalpuri** [comment]
> It is a known issue. Either use an old version of microG (e.g. v2.4) and update it later, or connect an external keyboard and navigate the buttons with TAB key.

Sir...thanka for reply...
I use Nanodroid package for microG...
when I replaced the gmscore with 0.2.4 , It cant spoof correctly... Maybe @Setialpha of Nanodroid is making some changes to GmsCore... 
Can you please modify the 0.2.4 version of GmsCore to spoof correctly?....
with v0.2.4, I can login but it cant spoof correctly ....

**Comment by tomasz1986** [comment]
You can use v0.2.4 only to log-in first and then update it to the newest release which can be downloaded directly from this GitHub repository. Of course, you will not be able to use the NanoDroid package afterwards because that one uses their own versions of microG.

**Comment by HemanthJabalpuri** [comment]
> You can use v0.2.4 only to log-in first and then update it to the newest release which can be downloaded directly from this GitHub repository. Of course, you will not be able to use the NanoDroid package afterwards because that one uses their own versions of microG.

With official microG latest version also not spoofing correctly since when I install Inbox by Gmail app , it warns to update google play services... but with Nanodroid microG it is not the case...

**Comment by tomasz1986** [comment]
> With official microG latest version also not spoofing correctly since when I install Inbox by Gmail app , it warns to update google play services... but with Nanodroid microG it is not the case...

My guess would be that you probably do not have the Play Store app installed.

> edit:- sir Since i am new to microG .... Can you please suggeat a flashable package that has all apps required for microG like in NanoDroid ...

I do not use any all-in-one packages, but for a minimalist setup I would recommend to download Services Core and Services Framework Proxy from https://microg.org/download.html, download PlayStore from https://www.apkmirror.com/apk/google-inc/google-play-store/ (and rename the file to something short with no spaces), and then copy the three files to /system/priv-app/. I usually do this using the file manager in TWRP, or with `adb push`.

Of course, you will also need to have signature spoofing support in your ROM, either built in or patched. I like to use the NanoDroid patcher, but if it does not work (and I had this often happen with older versions of Android), then try to use Tingle (https://github.com/ale5000-git/tingle).

If you need location backends, etc., then you can just download and install them later from FDroid. There are also ways to work around without the official Play Store app, but I have had too many issues with apps which simply need it to work.

**Comment by HemanthJabalpuri** [comment]
> > With official microG latest version also not spoofing correctly since when I install Inbox by Gmail app , it warns to update google play services... but with Nanodroid microG it is not the case...
> 
> My guess would be that you probably do not have the Play Store app installed.
> 
> > edit:- sir Since i am new to microG .... Can you please suggeat a flashable package that has all apps required for microG like in NanoDroid ...
> 
> I do not use any all-in-one packages, but for a minimalist setup I would recommend to download Services Core and Services Framework Proxy from https://microg.org/download.html, download PlayStore from https://www.apkmirror.com/apk/google-inc/google-play-store/ (and rename the file to something short with no spaces), and then copy the three files to /system/priv-app/. I usually do this using the file manager in TWRP, or with `adb push`.
> 
> Of course, you will also need to have signature spoofing support in your ROM, either built in or patched. I like to use the NanoDroid patcher, but if it does not work (and I had this often happen with older versions of Android), then try to use Tingle (https://github.com/ale5000-git/tingle).
> 
> If you need location backends, etc., then you can just download and install them later from FDroid. There are also ways to work around without the official Play Store app, but I have had too many issues with apps which simply need it to work.

Finally with your suggesstion, microG is working sir.....
Thanks.. Can you please give your XDA user name..

**Comment by tomasz1986** [comment]
> Finally with your suggesstion, microG is working sir.....
> Thanks.. Can you please give your XDA user name..

It is good to hear that :relaxed:.

My username on XDA is [tomasz86](https://forum.xda-developers.com/member.php?u=5038522), but I am not a very active user (read: I visit the forums once or twice per week). If you need urgent help, you will be better opening an issue here (or asking others on XDA).

**Comment by tomasz1986** [comment]
> DroidGuard

[https://github.com/microg/android_packages_apps_GmsCore/issues/214 ](https://github.com/microg/android_packages_apps_GmsCore/issues/214)

I do not use any apps that need it, so I also do not install the DroidGuard app. I would recommend installing it only if you absolutely have to.

> FakeStore, BlankStore

https://android.stackexchange.com/questions/174635/fakestore-blankstore-gms-microg-unifiednlp-whats-best-for-android-without

Blank Store is deprecated, and FakeStore is only to appear as if you had the Play Store installed in your system (but you actually do not). None of them is needed if you use the official Play Store app.

> Is Maps api files are needed?

I cannot really help with this one because I do not use Google Maps.

**Comment by HemanthJabalpuri** [comment]
> > DroidGuard
> 
> [https://github.com/microg/android_packages_apps_GmsCore/issues/214 ](https://github.com/microg/android_packages_apps_GmsCore/issues/214)
> 
> I do not use any apps that need it, so I also do not install the DroidGuard app. I would recommend installing it only if you absolutely have to.
> 
> > FakeStore, BlankStore
> 
> https://android.stackexchange.com/questions/174635/fakestore-blankstore-gms-microg-unifiednlp-whats-best-for-android-without
> 
> Blank Store is deprecated, and Fake Store is only to appear as if you had the Play Store installed in your system (but you actually do not). None of them is needed if you use the official Play Store app.
> 
> > Is Maps api files are needed?
> 
> I cannot really help with this one. Where I live Google Maps is useless and I have to use other map providers anyway, so I have never needed these.

Thanks for clarification...
Is it necessary to put those GmsCore, GsfProxy, Phonesky to /system/priv-app?
Since in microG xda page, Ma-R-Vin said to install as normal apps....
My device is running on 4.4.2 KitKat....

Thanks

**Comment by HemanthJabalpuri** [comment]
> > Is it necessary to put those GmsCore, GsfProxy, Phonesky to /system/priv-app?
> 
> GmsCore has to be in /system/priv-app in Android 7+ in order to use location backends. In older versions of Android it should not matter. GsfProxy can probably go to /system/app. Phonesky (the Play Store) has to be in /system/priv-app, unless the OS is Android 4.3 or older, where everything goes to /system/app. I just put all three in /system/priv-app for the same of simplicity and to avoid any potential system permissions related issues.

I have a doubt..
How GmsCore of microG and GooglePlayStore use its libraries if they are in /system/priv-app?
Since in Nanodroid and OpenGapps there are separate libs are placing in /system/lib.....
Thanks
