### ISSUE TITLE
Services Core v0.2.6.13280 - Won't Install

### ISSUE THREAD

**Issue by 0pLuS0** [microg/android_packages_apps_GmsCore#620]
Hello,

Phone Specs:

OnePlus 5T Oxygen OS 5.1.5
Magisk 17.1
Debloater Terminal Emulator 13.8

I've done the same exact steps on two other devices with success, Xiaomi Mi A1 and Essential PH-1. So I assumed on the OnePlus 5T it's going to work the same.

I even checked the Wiki Prerequisites and I also removed some additional Gapps;

https://github.com/microg/android_packages_apps_GmsCore/wiki/Prerequisites

When I try to install v0.2.6.13280 it won't install, I click on it, and it shows ```App not installed```.

I really don't understand this, since I've had this working perfectly on the other devices.

Hopefully the logcat I've attached will shed some light.

Thanks

[logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2422625/logcat.txt)

P.S. After posting this, I went back and manually did over debloating the system with the Debloater Terminal Emulator 13.8, and I noticed that the Play Store was still sitting in the App Drawer. So I'm not sure why it's not getting uninstalled.

**Comment by Vavun** [comment]
Remove prebuild gmscore and **its updates from /data/app** correctly

**Comment by 0pLuS0** [comment]
I was thinking the exact thing, about Updates.

But here's another thing, this was a fresh install of Oxygen OS, not Google accounts added to the phone, and no actual updates to the phone. I only rooted it, and went online for not even 40 seconds just to update Magsik. Now at that point in time I noticed Google was trying to do an update, but I canceled it.

So my questions are...

1. Can a factory ROM, from like OnePlus already have updates placed in it, and this caused the problem?

2. Or, just because I was only online for 1 minute and cancelled the update is was trying to perform, it was enough to cause the problem?

As far as number 2 is concerned, I did the same exact thing on two other devices, let them online for like a minute to update magisk and I never had these problems, which brings me back to #1...

Hmm

**Comment by 0pLuS0** [comment]
@Vavun 

I was thinking the exact thing, about Updates.

```I also removed gmscore from /data/app and it didn't help...``` I'll go back and start this all over clean and try again, and see...

But here's another thing, this was a fresh install of Oxygen OS, not Google accounts added to the phone, and no actual updates to the phone. I only rooted it, and went online for not even 40 seconds just to update Magsik. Now at that point in time I noticed Google was trying to do an update, but I canceled it.

So my questions are...

1. Can a factory ROM, from like OnePlus already have updates placed in it, and this caused the problem?

2. Or, just because I was only online for 1 minute and cancelled the update is was trying to perform, it was enough to cause the problem?

As far as number 2 is concerned, I did the same exact thing on two other devices, let them online for like a minute to update magisk and I never had these problems, which brings me back to #1...

Hmm

**Comment by 0pLuS0** [comment]
@Vavun 

I was thinking the exact thing, about Updates before you replied and,  ```I also removed gmscore from /data/app and it didn't help...``` I'll go back and start this all over clean and try again, and see...

But here's another thing, this was a fresh install of Oxygen OS, not Google accounts added to the phone, and no actual updates to the phone. I only rooted it, and went online for not even 40 seconds just to update Magsik. Now at that point in time I noticed Google was trying to do an update, but I canceled it.

So my questions are...

1. Can a factory ROM, from like OnePlus already have updates placed in it, and this caused the problem?

2. Or, just because I was only online for 1 minute and cancelled the update is was trying to perform, it was enough to cause the problem?

As far as number 2 is concerned, I did the same exact thing on two other devices, let them online for like a minute to update magisk and I never had these problems, which brings me back to #1...

Hmm

**Comment by 0pLuS0** [comment]
@Vavun 

I was thinking the exact thing, about Updates before you replied and this the only thing gms I could find in /data/app and I removed it and it didn't help;

```com.google.android.gms-0q9u1F3qiXjcrHqtqJvKEw==```

But here's another thing, this was a fresh install of Oxygen OS, not Google accounts added to the phone, and no actual updates to the phone. I only rooted it, and went online for not even 40 seconds just to update Magsik. Now at that point in time I noticed Google was trying to do an update, but I canceled it.

So my questions are...

1. Can a factory ROM, from like OnePlus already have updates placed in it, and this caused the problem?

2. Or, just because I was only online for 1 minute and cancelled the update is was trying to perform, it was enough to cause the problem?

As far as number 2 is concerned, I did the same exact thing on two other devices, let them online for like a minute to update magisk and I never had these problems, which brings me back to #1...

Hmm

**Comment by 0pLuS0** [comment]
@Vavun 

I was thinking the exact thing, about Updates before you replied and this the only thing gms I could find in /data/app and I removed it and it didn't help;

```com.google.android.gms-0q9u1F3qiXjcrHqtqJvKEw==```

But here's another thing, this was a fresh install of Oxygen OS, no Google accounts added to the phone, and no actual updates to the phone. I only rooted it, and went online for 1 minute just to update Magsik. Now at that point in time I noticed Google was trying to do an update, but I canceled it.

So my questions are...

1. Can a factory ROM, from like OnePlus already have updates placed in it, and this caused the problem?

2. Or, just because I was only online for 1 minute and cancelled the update is was trying to perform, it was enough to cause the problem?

As far as number 2 is concerned, I did the same exact thing on two other devices, let them online for like a minute to update magisk and I never had these problems, which brings me back to #1...

Hmm

**Comment by 0pLuS0** [comment]
@Vavun I went back and wiped and put back a clean install and tried this over.

This time I only wanted to Debloat/Remove the Play Store, because it's icon still appears in the App Drawer and it shouldn't

I've attached a find log showing the entire system /paths, maybe you could be so kind as to look it over and see if you can find why the Play Store is not being removed? Maybe this is the problem here... hmm

Of course I understand more Gapps have to be removed, I'm just saying that the Play Store is not being properly removed and maybe this is the factor/problem I'm running in to?

[find.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2426173/find.txt)


THANKS

**Comment by 0pLuS0** [comment]
@Vavun I went back and wiped and put back a clean install and tried this over.

I used the Magisk module ```Debloater (Terminal Emulator)``` to remove all the Google, that I've removed in the past and had microg install.

I've come to see that for some reason the Debloater is not properly removing the Google Services and some things are left over somewhere in the system. I had to manually uninstall the Play Store after I ran the Debloater and I also had to remove a /data/app directory for the Google Services. But I still can't get the microg core services installed.

I've attached a find log showing the entire system /paths, maybe you could be so kind as to look it over and see if you can find where there are other Play Services or anything else Google that needs to be taken out?

I really appreciate this, and sorry it looks like the Debloater as I mentioned isn't working properly.

THANKS


[find.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2426828/find.txt)

**Comment by 0pLuS0** [comment]
@Vavun I went back and wiped and put back a clean install and tried this over.

I used the Magisk module ```Debloater (Terminal Emulator)``` to remove all the Google, that I've removed in the past and had microg install.

I've come to see that for some reason the Debloater is not properly removing the Google Services and some things are left over somewhere in the system. I had to manually uninstall the Play Store after I ran the Debloater and I also had to remove a /data/app directory for the Google Services. But I still can't get the microg core services installed.

I've attached a find log for this cmd I ran;

find /system /data/{app,data,misc*,system*} > /sdcard/find.txt

If you could be so kind as to look it over and see if you can find where there are other Play Services or anything else Google that needs to be taken out?


I really appreciate this, and sorry it looks like the Debloater as I mentioned isn't working properly.

THANKS


[find.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2426828/find.txt)

**Comment by 0pLuS0** [comment]
@Vavun I went back and wiped and put back a clean install and tried this over.

I used the Magisk module ```Debloater (Terminal Emulator)``` to remove all the Google, that I've removed in the past and had microg install.

I've come to see that for some reason the Debloater is not properly removing the Google Services and some things are left over somewhere in the system. I had to manually uninstall the Play Store after I ran the Debloater and I also had to remove a /data/app directory for the Google Services. But I still can't get the microg core services installed.

I've attached a find log for this cmd I ran;

find /system /data/{app,data,misc*,system*} > /sdcard/find.txt

If you could be so kind as to look it over and see if you can find where there are other Play Services or anything else Google that needs to be taken out and the logcat?

I really appreciate this, and sorry it looks like the Debloater as I mentioned isn't working properly.

After I tried installing microg and I noticed some things from line 456 down... hmm


THANKS


[find.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2426828/find.txt)

[logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/2426899/logcat.txt)

**Comment by 0pLuS0** [comment]
Sorry, I've deleted and removed my last comments several times, I hope that doesn't send you notifications everytime that's done? So I wanted to make a reply here, rather then messing with the last one.

Here's the bottom line; 

I've followed the wiki and instructions, but the problem is, saying as example, how I'm looking at this, where the wiki instructions say, remove "Google Services". The problem I'm encountering is, how much of and where, like remove every possible trace of it in the system, or is this just removing like only the .apk if there was one associated to it?

I've been trying to do this with the Debloater (Terminal Emulator) and do this Systemlessly, but this doesn't seem to be working.

Maybe when someone gets the time, hopefully in the near future the wiki can be edited to include /paths to remove data from, so that the end-users will get a better idea of where to remove, because for me, just removing, for a lack of better words I can think of, just the "Basics" of Google Services & Framework, isn't working for me. It's as if it's really intertwinded deeper into the ROM that I need to do digging around ripping it out, which I've been doing for 2 days still with no success.

So there has to be better simpler way, this is why I humbly ask to please get some more detailed information on the wiki how to better go about this.

Thank you very much!

**Comment by 0pLuS0** [comment]
I finally got this working, I believe that some google updates got in, while I wasn't paying attention, which I thought I was doing.

SORRY FOR THIS POST!

All is good now!

**Comment by diman82** [comment]
Download microg from here, it works: https://vanced.app/APKs?type=NONROOT

**Comment by Vavun** [comment]
@diman82 are you really sure in what you are offering?

**Comment by diman82** [comment]
@Vavun I'm not offering anything, just posting a possible solution (that doesn't require recompilation and adb procedures) that worked for me.
