### ISSUE TITLE
Firebase subscription for riot.im

### ISSUE THREAD

**Issue by symphorien** [microg/android_packages_apps_GmsCore#625]
With a fresh install of lineageOS 14.1 for microg (0.2.5-12879) the google play version of riot is not able to register. Same behavior with 0.2.6.13280.
When changing the gcm settings in the app, it tries to force register and fails. I get this toaster: https://github.com/vector-im/riot-android/blob/05b9532a29b420411d7674172608b8ae3c488fc8/vector/src/main/java/im/vector/gcm/GcmRegistrationManager.java#L609
Logcat gives:
```
09-29 22:53:49.484  3506  3506 D GmsGcmRegisterSvc: onBind: Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
09-29 22:53:49.502  3506  5021 D GmsHttpFormClient: -- Request --
09-29 22:53:49.502  3506  5021 D GmsHttpFormClient: X-GOOG.USER_AID=0&device=0&app=im.vector.alpha&cert=xxxxxx&app_ver=81500&sender=xxxx
09-29 22:53:49.543  3506  5021 D GmsHttpFormClient: -- Response --
09-29 22:53:49.543  3506  5021 D GmsHttpFormClient: Error=PHONE_REGISTRATION_ERROR
09-29 22:53:49.544  3506  5021 D GmsGcmRegisterSvc: received response: RegisterResponse{token='null', retryAfter='null', deleted='null'}
09-29 22:53:49.549  4829  5019 W FirebaseInstanceId: Unexpected response: Bundle[{registration_id=null}]
09-29 22:53:49.549  4829  5019 W FirebaseInstanceId: java.lang.Throwable
09-29 22:53:49.549  4829  5019 W FirebaseInstanceId: 	at com.google.firebase.iid.zzq.zza(Unknown Source)
09-29 22:53:49.549  4829  5019 W FirebaseInstanceId: 	at com.google.firebase.iid.zzq.zza(Unknown Source)
09-29 22:53:49.549  4829  5019 W FirebaseInstanceId: 	at com.google.firebase.iid.zzt.then(Unknown Source)
09-29 22:53:49.549  4829  5019 W FirebaseInstanceId: 	at com.google.android.gms.tasks.zzd.run(Unknown Source)
09-29 22:53:49.549  4829  5019 W FirebaseInstanceId: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-29 22:53:49.549  4829  5019 W FirebaseInstanceId: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-29 22:53:49.549  4829  5019 W FirebaseInstanceId: 	at java.lang.Thread.run(Thread.java:761)
09-29 22:53:49.550  4829  4848 E FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
```
Microg settings say 0 apps are registered with gcm. Riot does not receive call any notifications when polling is disable and the app is not in the foreground.
I have no fire-walling app or so, microg self-test is all green.

This is a copy of https://github.com/microg/android_packages_apps_GmsCore/issues/439#issuecomment-425675512

**Comment by mar-v-in** [comment]
As you can see in the log (PHONE_REGISTRATION_ERROR), the device is not properly registered for push notifications. Did you enable device registration? If you did, try dialing (in the phone app) *#*#2432546#*#* (2432546=checkin), wait a few seconds and try again.

**Comment by symphorien** [comment]
I had enabled registration. Setting it off, and on again, rebooting could not make it work. But the code `*#*#2432546#*#*` you mentioned let the app access gcm. Thanks for mentioning this.
