### ISSUE TITLE
Orbot

### ISSUE THREAD

**Issue by sxml** [microg/android_packages_apps_GmsCore#633]
Sorry for Google English
China blocked google 
Current State: Disconnected
Invalid installation of Orbot 
Requires Orbot to be installed Not yet supported 

Increase support for other proxy settings? 
Telegram has built-in Mtproto proxy option 

Start app on push message 
Wechat push can't start up

**Comment by sxml** [comment]
microG Settings
How to open Orbot? I have installed Orbot or gray. Can I use socks5 proxy?

**Comment by ale5000-git** [comment]
Duplicate of #173
