### ISSUE TITLE
Marshmallow permissions support

### ISSUE THREAD

**Issue by ibleedbinari** [microg/android_packages_apps_GmsCore#64]
Push notifications are currently broken on Android 6. The new permissions system is not granting the CD2M permission to apps correctly. Reinstalling the package does not grant the permissions either. Permission for apps compiled with the Android 6 SDK can be manually granted in settings, but I cannot confirm at the moment whether push messaging actually starts working after this. Android 5 and lower apps cannot be granted the permission at all, creating messages like:

901  3472 W ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.gms/org.microg.gms.gcm.PushRegisterService} from pid=9822, uid=10085 requires com.google.android.c2dm.permission.RECEIVE

 9822  9893 E AndroidRuntime: Caused by: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.UNREGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE

I also read on the XDA thread that UnifiedNLP/Network Location has some permission issues as well

**Comment by binaricode** [comment]
It looks like Google account sign in within Google apps is also failing

**Comment by okias** [comment]
Not sure, maybe this could help:
OmniRom:
- https://gerrit.omnirom.org/#/c/16079/2 this revert previous solution
- https://gerrit.omnirom.org/#/c/16080/3 new solution based on 6.0 access rights

CM13: http://review.cyanogenmod.org/#/c/125637/

**Comment by mar-v-in** [comment]
On Android 6 you currently need to grant receive c2dm permission in settings. This will be adjusted soon.

**Comment by ibleedbinari** [comment]
I can no longer see the permission in the list to be able to grant it in the latest version. Has this been fixed, or is that a bug?

**Comment by mar-v-in** [comment]
C2DM / GCM does not require permission granting anymore since 7b74722c3d2ffd89bb4ac719e34290279de6c357

Regarding Google app sign in: You need to grant "Contacts" permission to Google apps manually if you want them to use your Google account. Third-party applications will ask for this permission before using the account so this does only apply to Google apps.
