### ISSUE TITLE
updating play support libraries...

### ISSUE THREAD

**Issue by martobg10** [microg/android_packages_apps_GmsCore#657]
Every time when i restart my phone and i open "google play" it downloading "play support libraries".
Why every phone restart google play download the same ? This to me is a large consumption of the Internet. With google play services i don't have this problem, but with microG services i have.
What do I do to fix this issue ?
(sorry for my english)

![screenshot-20181111-105554](https://user-images.githubusercontent.com/44940748/48311365-59947200-e5a7-11e8-851e-c3b41fda3fb9.png)

**Comment by dawidd6** [comment]
Can confirm this. It happens since a couple of days, i think.

**Comment by Nanolx** [comment]
Because the spoofed version is outdated, see #646

**Comment by patrickdrd** [comment]
> Because the spoofed version is outdated, see #646

yes, but what about a solution?
why does this problem remains for such a long time?

I mean there are solutions:
here's two I can think of quickly:
1) release a weekly update with only version updated or
2) release a version with 99.99.99 version (so that it would always be higher) as it is posted on russian forums etc

**Comment by chris42** [comment]
The version change in android is not only a number, but the framework is further developed. Hence 2. won't work at all, as new features and changes to old ones would break microg at some unknown point.
Regarding 1. you will need someone to test it every week for this new changes and adapt microg. So far I can't see Marvin having time for this, hence other developers would be needed.
