### ISSUE TITLE
Play Store Won't Appear In App Drawer

### ISSUE THREAD

**Issue by 0pLuS0** [microg/android_packages_apps_GmsCore#661]
I'm using a OnePlus 5T with Oxygen OS 5.1.5 that I debloated out google to run microG instead.

I'm not sure what's going on, I've had this working in the past with an older version of microG, 0.2.5 or 0.2.4.

I debloated out all these apps with the Debloater Terminal Emulator

Android Setup
Calendar
Chrome
Drive
Duo
Gboard
Gmail
Google
Google Backup Transport
Google One Time Init
Google Partner Setup
Google Pay
Google Play Movies
Google Play Music
Google Play Services
Google Play Store
Google Services Framework
Market Feedback Agent
Maps
Photos

In the past I was using a patched version of Phonesky.apk from Nanodroid that I'd copy to /priv-app, now if I either copy it again, or put back the official Play Store from the Debloater, after I reboot, just the first time, the Play Store will appear in the App Drawer, if I reboot a second time, it will never reappear again, and this has me confused as to why it won't stay in the App Drawer?

I thought with microG it's suppose to work to use the Play Store...

Thanks

**Comment by Nanolx** [comment]
```
 Google Play Store
```

You should remove that from Terminal Debloater, as your manullay installed Play Store will also be removed due to that.

But this sounds pretty familiar to me, doesn't it? :)

**Comment by 0pLuS0** [comment]
I figured it out, it was because I still had ```Fakestore``` installed, and Play Store won't go back with it installed...

So all good now...

Thanks
