### ISSUE TITLE
CarGuru: markers are shown but not "clickable"

### ISSUE THREAD

**Issue by rfvermut** [microg/android_packages_apps_GmsCore#675]
Version: v0.2.6.13280

https://play.google.com/store/apps/details?id=lv.slyfox.carguru is a car rental app. 
It displays a map (correctly) with a bunch of markers depicting free cars (correctly).

When the person clicks the car marker it opens registration window, but not under microG. No errors are shown, clicks are simply ignored.

Here a link to android log from startup to click attempts: https://gist.github.com/rfvermut/1fdf304bdc330b0204d54d5fd19b42d3

Potential error might be:
```
I/n       ( 6141): Making Creator dynamically
D/GmsChimeraSpoof( 6167): query: content://com.google.android.gms.chimera/api_force_staging/com.google.android.gms.maps_dynamite
W/DynamiteModule( 6141): Failed to retrieve remote module version.
D/GmsDynamiteLoaderImpl( 6141): unimplemented Method: getModuleVersion for com.google.android.gms.maps_dynamite
W/DynamiteModule( 6141): Local module descriptor class for com.google.android.gms.maps_dynamite not found.
I/DynamiteModule( 6141): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:0
E/n       ( 6141): Failed to load maps module, use legacy
E/n       ( 6141): com.google.android.gms.dynamite.DynamiteModule$a: No acceptable module found. Local version is 0 and remote version is 0.
E/n       ( 6141):   at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source)
E/n       ( 6141):   at com.google.android.gms.maps.a.n.c(Unknown Source)
E/n       ( 6141):   at com.google.android.gms.maps.a.n.b(Unknown Source)
E/n       ( 6141):   at com.google.android.gms.maps.a.n.a(Unknown Source)
E/n       ( 6141):   at com.google.android.gms.maps.d.a(Unknown Source)
E/n       ( 6141):   at com.google.android.gms.maps.SupportMapFragment$b.i(Unknown Source)
E/n       ( 6141):   at com.google.android.gms.maps.SupportMapFragment$b.a(Unknown Source)
E/n       ( 6141):   at com.google.android.gms.b.a.a(Unknown Source)
E/n       ( 6141):   at com.google.android.gms.b.a.a(Unknown Source)
E/n       ( 6141):   at com.google.android.gms.maps.SupportMapFragment.a(Unknown Source)```

**Comment by sm4rk0** [comment]
Duplicate of #287?

**Comment by weechoochter** [comment]
I have this same problem on the following app:
park4night: https://play.google.com/store/apps/details?id=fr.tramb.park4night
Pins are shown on the map but are not clickable. Have tried two different installs of microg.

Also on this app:
POI Pocket: https://play.google.com/store/apps/details?id=com.las.poipocket
Adding a POI and choosing the map option opens up the map and shows the pin in the middle. You are supposed to long tap to select the location. You can move the map but tapping does nothing.

**Comment by rfvermut** [comment]
This is no longer applicable to CarGuru as they updated it and it's not working at all now :)
