### ISSUE TITLE
Casting from official Youtube app doesn't working

### ISSUE THREAD

**Issue by the4anoni** [microg/android_packages_apps_GmsCore#692]
Hello
Can't cast from official youtube app and microG.
With Google Play Services all works fine.

**Comment by sjdrc** [comment]
https://github.com/microg/android_packages_apps_GmsCore/wiki/Implementation-Status
Cast isn't yet implemented

**Comment by ibleedbinari** [comment]
You can subscribe to issue #79 for this. I would recommend closing this issue as a duplicate.
