### ISSUE TITLE
Nearby Support - Oura ring app not pairing [$100]

### ISSUE THREAD

**Issue by ocwa1** [microg/android_packages_apps_GmsCore#707]
App starts up fine, but when app scans for the device, it never finds it.  (ring is detected in bluetooth settings, unfortunately you have to pair via the app)  Works with gapps installed.  Same error on Lineage for Microg (15.1) (20190204)
Device: Nexus 6P (aka angler)
OS: RR 7.0.0 (Pie) (20190210)
Microg: 0.2.6.13280 (installed as system app)
App: Oura (2.4.1)

[logcat.log](https://github.com/microg/android_packages_apps_GmsCore/files/2872764/logcat.log)
[2019-02-17_00.36-oura.zip](https://github.com/microg/android_packages_apps_GmsCore/files/2872765/2019-02-17_00.36-oura.zip)

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=70184055)](https://www.bountysource.com/issues/70184055-nearby-support-oura-ring-app-not-pairing)

**Comment by ocwa1** [comment]
Looks like this is a part of support for the nearby API, which handles searching for bluetooth devices. Going to post a bounty

**Comment by ocwa1** [comment]
bounty posted

**Comment by bricewge** [comment]
It fully works on my side, synchronization, data analysis and even firmware update. There is just the "Moment" feature which fails with "Something went wrong" but it isn't essential at all, to me at least.

My setup is:
- Device: Samsung Galaxy S7 (herolte)
- ROM: LineageOS 16.0
- Services: MicroG 0.2.9.19420-5 (cfc90b4) ROM built-in
- App: 2.8.0
- Firmware: 1.47.1

**Comment by ocwa1** [comment]
I installed the latest oura app (same version, 2.8.0) and I'm not able to login.


    Device: Google Pixel 3 (blueline)
    ROM: CalyxOS 1.0.0-beta2 (QQ1A.200105.002.2020.01.07.13)
    Services: MicroG 0.2.10.19420-vtm (ab8c2cc)
    App: 2.8.0
    Firmware: 1.47.1

**Comment by bricewge** [comment]
I wasn't able to reproduce your issue. I wiped the app data and disassociated the ring from my phone and started the app again. I logged in (successfully) answered the 3 questions about notifications and Google Fit, then on the connection ring page I gave the app the permission to locate me and scanning started but ended with a popup "No ring found", I just waited a little more and got greeted with the welcome page, after it I got another popup "Something went wrong". After this initialization of the app all is working fine.

If it fail at ring the connection page it may be you doesn't have a working localization service. I don't think I can help you further than that.

**Comment by apraile** [comment]
It works for me too. My setup:

* Device: Wileyfox Swift (crackling)
* ROM: [LineageOS for microG](https://lineage.microg.org/) (16.0-20200325-microG-crackling)
* Services: GmsCore-v0.2.9.19420-5-cfc90b4
* App: 2.9.0
* Firmware: 2.5.1

microG Settings:

* `Google Services`: all disabled
* `UnifiedNlp Settings`:
    * `Network-based Geolocation > Mozilla Location Service` (enabled)
    * `Address lookup > Nominatim` (enabled)

_I haven't tried to update the firmware yet._
