### ISSUE TITLE
LG G4 Stock Android 6 with Root/twrp

### ISSUE THREAD

**Issue by Catfriend1** [microg/android_packages_apps_GmsCore#71]
hi, 

do I habe chances to run microg with that Rom? when i delete Google services and gms out of priv app, i am stuck on Boot loop. will i habe Vetter compat with cm 13 and xposed?

**Comment by mar-v-in** [comment]
Can you provide logcat of the bootlooping system? I strongly suggest not using microG on stock systems but it should be possible.

**Comment by Catfriend1** [comment]
how can I access logcat when stuck in Boot loop? i have twrp installed. after restoring the whole partitions, my logs are gone. will try checking to get logs later this week when I continue working with g4.

**Comment by julienschmidt** [comment]
Try to connect the phone to an ADB authorized device via USB and then use `adb logcat`

**Comment by Catfriend1** [comment]
Ok, problem occurs before installing MicroG GmsCore. For testing purposes, I removed GmsCore (Google Play Services) App from /data/app and /system/priv-app. On CM12.1 that was no problem at all, phone booted correctly after that. On LG G4 with Android 6 KDZ 20b version, the following behaviour was encountered:

- Rebooted phone
- LG Bootloader logo appeared
- LG Animation (from kernel?) appeared
- blue LED started to flash (LG animation goes on)
- 4 seconds later (LG animation goes on) phone vibrated (it did never do this before during boot animation!)
- Last time, I though it was endless hanging - while I opened logcat on PC, phone came back after ca. 2 minutes waiting time (I entered adb shell, adb stop at the beginning)
- Display told me to "Start apps" (this is androids "optimizer") but only 12 apps instead of usually more.
- When optimizing phase was complete, the phone did not go to lock screen - it rebooted itself automatically. LG animation appeared again. This went on two times while I took the capture.
- I removed adb connection and restored it from endless looping via TWRP backup.

Any ideas?



[2016-01-07_logcat_bootbloop.zip](https://github.com/microg/android_packages_apps_GmsCore/files/81348/2016-01-07_logcat_bootbloop.zip)

**Comment by Catfriend1** [comment]
Is this the correct answer to my problem: ROM without DeOdex won't work?

https://github.com/rovo89/Xposed/issues/100

**Comment by mar-v-in** [comment]
Atleast the problem is clearly about Xposed and has nothing to do with microG. You can try if [Needle](https://github.com/moosd/Needle) works for you.

**Comment by Catfriend1** [comment]
Update. I am now up and running with fake signatures under my H815-V20B Stock ROM. XPosed is no longer a problem because I flashed deodexed stock apps via TWRP. 

Now its again MicroG. I cant install MicroG  GSFProxy and MicroG GMS Core. Error 25 is given in logcat. I seems the system would like to install MicroG as an update. Steps I have taken so far:

- Installed TitaniumBackup Pro (Root)
- Used TitaniumBackup Pro to uninstall Google GMSCore and GSF.

It is still giving me the error 25. Any ideas at this point?

**Comment by mar-v-in** [comment]
@Catfriend1 as you wrote about a different issue, I assume this problem no longer exists. As stock ROMs especially those by LG, Samsung and HTC tend to use non standard methods for several things, microG cannot afford to actively support those. You can still try your luck in the device specific XDA-developers forums or similar locations.

**Comment by ghost** [comment]
please delete issue
