### ISSUE TITLE
MDM / Android for Work: Any chance?

### ISSUE THREAD

**Issue by andyboeh** [microg/android_packages_apps_GmsCore#712]
I'm running microg for years now and I've always been very satisfied with the implementation and what's possible.
Recently, I started evaluating free as well as FOSS MDM solutions for my company. I stumbled upon ManageEngine MDM and gave it a go. I could start the enrollment process and a work profile was created on my device, however ManageEngine MDM is complaining about not being able to connect to FCM (GCM).

Is there anything that can/needs to be done on microg side to support Android for Work / MDM?

I have yet to give flyve a try, the downside is, though, that the app needs to be compiled from source due to FCM.

Testing environment: LineageOS 16.0 with latest NanoDroid microg.

**Comment by marlid91** [comment]
You've to copy microg over to the work environment.

**Comment by andyboeh** [comment]
Thanks, on the third try, microg was copied over by the enrollment process. However, now I hit another problem, in the logs I get:
```
com.google.android.gms.common.api.ApiException: 17: API: WorkAccount.API is not available on this device
```
Does that mean microg has not implemented this API?

**Comment by marlid91** [comment]
I've a work environment running with microg just fine. I use Shelter though (search for it here on Github or fdroid) to manage the work space. 

Did you spoof the device yourself or did you download from lineageos.microg.com?

**Comment by andyboeh** [comment]
I did spoof it myself (NanoDroid), because the lineageos port for my device became official just a few days ago.

I'll give Shelter a try, I wasn't aware of that app, but it looks really promising. ManageEngine would have had the advantage of being able to manage the device over a web console, but I can live without that.

**Comment by andyboeh** [comment]
Thanks for pointing me to Shelter, that's actually exactly what I needed and it works perfectly fine!
