### ISSUE TITLE
Could not get connect to google server, what's wrong?

### ISSUE THREAD

**Issue by JadeVane** [microg/android_packages_apps_GmsCore#721]
## I have enable GCM, and some of applications has registered, that is what the Self-Check shows:
![2323232322](https://user-images.githubusercontent.com/34258753/53713816-2d1ea180-3e87-11e9-9cd9-52be6ebd9cc9.png)
## but what I am meeting now is that the registered apps receives no message through GCM:
![1216116667](https://user-images.githubusercontent.com/34258753/53713894-6ce58900-3e87-11e9-9e19-91b07781d3bc.jpg)
## and what the `More` under the `Google Services` shows, looks so bad:
![1807837858](https://user-images.githubusercontent.com/34258753/53713974-b1712480-3e87-11e9-9364-6d67823753ae.jpg)
## this is the result of the `push notification tester`:
![screenshot_20190304-140537](https://user-images.githubusercontent.com/34258753/53714032-e7160d80-3e87-11e9-8cb5-fa3f0dbe4ad5.png)
## How can i do with that?

**Comment by Tentos** [comment]
Just to be sure: Do you have activated not only Google Cloud Messaging (GCM), but also the Google log-in? (The corresponding menu entry can be found in the microG main screen, just above the GCM option.) Moreover, you can try to dial *#*#2432546#*#* (i.e., *#*#CHECKIN#*#*) in you phone app to let microG properly re-connect to the Google servers.

**Comment by JadeVane** [comment]
@Tentos Thanks for reply. Do you mean `Google device registration` option? It is enabled, and i have signed in a google account in my phone. BTW, everything goes well without gmail, I just can't find any account on the account list when i lanuch gmail, and i can't add my google account because it already exist, delete and retry to sign in the account doesn't work for gmail, i'll meet the same solution. Hope this will bring some clues.

It seems that nothing happens after I dial `##24324546##`.

**Comment by Tentos** [comment]
My bad, it should be `*#*#24324546#*#*`. I have updated the corresponding comment.
Yes, I meant Google Device Registration.
Unfortunately, I do not use Gmail and do not have a Google account on my phone, so I cannot try to reproduce your problem for now.
Has anyone else some experience regarding microG, Gmail and a Google account?

**Comment by JadeVane** [comment]
`*#*#24324546#*#*` returns nothing too, it disappered when i typed the last symbol.

**Comment by Vavun** [comment]
Check your VPN

**Comment by JadeVane** [comment]
@Vavun It is working well now, thanks!
