### ISSUE TITLE
"Unifiednlp do not have location to test geocoder" will not pass

### ISSUE THREAD

**Issue by UHSL-Marcus** [microg/android_packages_apps_GmsCore#733]
I have installed MicroG with all the backends with nanodroid. It has all the permissions, full internet access and all backends are enabled. 

Yet I cannot get "Unifiednlp do not have location to test geocoder" to pass. What else can I try to investigate to find out why it is failing?

Just to note, I have no sim card in this phone yet, but that shouldn't cause an issue should it?

**Comment by JohnGLFour** [comment]
I have same problem with my device too. But it got fixed by removing the magisk module and reinstall it. Might take a while but it would work.

But problems still exists some random time all modules disabled on reboot. After another reboot the problem of unitednlp still exists. Maybe don't use nanodroid for now.

**Comment by Nanolx** [comment]
I can't reproduce the issue. Where's the log?

Also duplicate of https://gitlab.com/Nanolx/NanoDroid/issues/47

Am 23. März 2019 00:32:45 MEZ schrieb JohnGLFour <notifications@github.com>:
>I have same problem with my device too. But it got fixed by removing
>the magisk module, restart and reinstall it. (Repeat if problem still
>exists) Might take a while but it would work.
>
>But problems still exists some random time all modules disabled on
>reboot. After another reboot the modules re-enabled, modules reseted
>and the problem of unitednlp still exists. Maybe don't use nanodroid
>for now.
>@Nanolx please fix it.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/microg/android_packages_apps_GmsCore/issues/733#issuecomment-475811566

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by UHSL-Marcus** [comment]
I could only fix this but removing NanoDroid and installing MicroG using the APK's from their website and moving them to priv-app. I then installed the back-ends via fdroid. 

It works perfectly after doing that
