### ISSUE TITLE
zip signature verification failed in TWRP

### ISSUE THREAD

**Issue by TjrGithub** [microg/android_packages_apps_GmsCore#746]
I copied  https://download.lineage.microg.org/mido/lineage-15.1-20190320-microG-mido.zip to the external SD card, installed TWRP according to LineageOS instructions, and then tried to install the lineageos-microg zip file. But I had to disable zip signature verification.

**Comment by ale5000-git** [comment]
@TjrGithub
This has nothing to do with microG itself, you should report it [here](https://github.com/lineageos4microg/docker-lineage-cicd/issues).
