### ISSUE TITLE
LOS16: GCM not connecting in Work profile

### ISSUE THREAD

**Issue by heinhuiz** [microg/android_packages_apps_GmsCore#747]
In LineageOS 16 + microG, GCM is not connecting in the work profile.

I've tried dirty flashing of 16.0 over 15.1 as well as a clean install. While in the personal profile GCM is connected, I installed Shelter. In the work profile, after turning on Google Cloud Messaging, the Current State remains Disconnected. 

I've tried calling `*#*#CHECKIN#*#*` both in the main as in the work profile (with cloned Phone app) to no avail. Rebooting doesn't solve it either.

Exact same applies using the Island app.

Note: In LOS15.1 + microG GCM did connect, both in the personal and in the work profile.

**Comment by miquecg** [comment]
I've noticed that besides status in work profile still continues to be disconnected, I actually get notifications from time to time. Not sure though, if these are real push notifications or they happen because apps are waking up at regular intervals.

**Comment by heinhuiz** [comment]
Since last OTA (April 9, 2019 build) GCM in the work profile is connected.

**Comment by miquecg** [comment]
Not for me. I've also tried dialing the registration code again after update with no change in device connection status.

- LOS 16 build 20190415
- microG Core 0.2.6.13280

@heinhuiz Are you running LOS for microG or you build it yourself?

**Comment by rugk** [comment]
What is this strange registration code? And how can one enter it?

**Comment by heinhuiz** [comment]
@miquecg, I use LOS for microG.

Today, I notice strange behavior with WhatsApp in the work profile: it only works with the default notification tone. Changing it to another one makes the app crash when a message is received.

**Comment by miquecg** [comment]
> What is this strange registration code? And how can one enter it?

https://github.com/microg/android_packages_apps_GmsCore/issues/439#issuecomment-433018720

You can use it to force your device registration into GCM to get push notifications. Sadly, for me it just worked in the main profile, not in the work one.

@heinhuiz Have you done anything special or just simply OTA upgrading fixed this issue? I don't know what to do... Maybe I could try to remove GCM settings from the work profile and add it again afterwards.

**Comment by heinhuiz** [comment]
@miquecg indeed I did nothing special, just the OTA. In fact, because of another problem one week later I restored my phone to the older version where GCM did not connect and performed OTA to the latest version now, and immedialtely GCM connected again. 

AFAIK, you can just dirty flash LOS/microG over your official version. Just make sure  you have a proper TWRP backup in case anything goes wrong.
