### ISSUE TITLE
Google Photos crash: "Not a url"

### ISSUE THREAD

**Issue by sm4rk0** [microg/android_packages_apps_GmsCore#749]
Trying to open hamburger menu caused a fatal exception since the last (or the penultimate) Google Photos update. I also recently did a manual checkin via `*#*#CHECKIN#*#*`.

After locating the URL from the exception in this line:
```xml
<string name="0.profile_photo_url">~6/-EkucOnIjliM/AAAAAAAAAAI/AAAAAAAABUw/QwLUBUejiGw/photo.jpg</string>
```
at `/data/data/com.google.android.apps.photos/shared_prefs/accounts.xml` and replacing the string with a full URL: `https://lh3.googleusercontent.com/-EkucOnIjliM/AAAAAAAAAAI/AAAAAAAABUw/QwLUBUejiGw/photo.jpg` the issue is gone.

Seems related to #444 #598 #611

microG 0.2.6.13280 (from microG f-droid repo)
Photos 4.13.0.240385459

Below's the stack trace:
```
04-08 16:18:08.034  5316  5316 E AndroidRuntime: FATAL EXCEPTION: main
04-08 16:18:08.034  5316  5316 E AndroidRuntime: Process: com.google.android.apps.photos, PID: 5316
04-08 16:18:08.034  5316  5316 E AndroidRuntime: Theme: themes:{org.adw.launcher=overlay:org.cyanogenmod.hexolibre}
04-08 16:18:08.034  5316  5316 E AndroidRuntime: java.lang.IllegalArgumentException: Not a url: ~6/-EkucOnIjliM/AAAAAAAAAAI/AAAAAAAABUw/QwLUBUejiGw/photo.jpg
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at alcl.a(PG:6)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at nvp.<init>(PG:4)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at gbv.a(PG:22)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at gbv.a(PG:11)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at jzs.d(PG:142)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at jzs.a(PG:91)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at ng.b(PG:282)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at nz.a(PG:325)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at nz.d(PG:613)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at nz.a(PG:680)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at na.g(PG:160)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at nz.b(PG:892)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at nz.b(PG:875)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at nz.k(PG:836)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at nz.b(PG:34)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at eww.run(PG:14)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at lzf.f(PG:35)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at mbg.b(PG:6)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at chb.b(PG:36)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at cgg.a(PG:165)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at akzz.a(PG:82)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at albk.onOptionsItemSelected(PG:77)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at android.app.Activity.onMenuItemSelected(Activity.java:2914)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at np.onMenuItemSelected(PG:63)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at acq.onMenuItemSelected(PG:29)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at ake.onMenuItemSelected(PG:14)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at ake.onMenuItemSelected(PG:14)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at atl.onClick(PG:4)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at android.view.View.performClick(View.java:5204)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:21158)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5461)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-08 16:18:08.034  5316  5316 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

**Comment by voidstarstar** [comment]
Thanks for the detailed report.  I just tried installing the Photos app, but I can't even reach the hamburger menu - it just crashes on launch, but with a different stack trace.  I then checked in the `accounts.xml` file, but I see the full URL.

#611 was merged in the latest version 0.2.6.13280.  Did you upgrade from an earlier version to 0.2.6.13280 and if so, do you remember if you uninstalled and reinstalled the Photos app after upgrading microG?

When 0.2.6.13280 was released, I think it only would fix this for newly generated `account.xml` files.  I think anyone with an older "corrupted" `accounts.xml` file would need to either manually edit it or regenerate it by uninstalling and reinstalling the app (which I expected people to do anyway when upgrading microG).

**Comment by sm4rk0** [comment]
Thank you for quick reply and effort in improving and maintaining microG!
I've updated it to the latest version as soon as it became available via f-droid (2018-09-27). I didn't reinstall Photos recently (Titanium Backup says install date is 2017-10-27), just cleared its data few times while trying to make backup work (but not this year).

**Comment by sm4rk0** [comment]
I didn't use Titanium Backup (or any other backup app) for Photos before this crash. I've created a backup before modifying accounts.xml. There shouldn't be any risk of losing photos, just local settings and one big database (224MB for ~33k photos and videos) that can be recreated.

Just cleared app data, but there was no crash on first startup.
Maybe it depends on microG account data.

`accounts.xml` now contains this line ('lh3' changed to 'lh6'):
```xml
<string name="0.profile_photo_url">https://lh6.googleusercontent.com/-EkucOnIjliM/AAAAAAAAAAI/AAAAAAAABUw/QwLUBUejiGw/photo.jpg</string>
```

**Comment by voidstarstar** [comment]
Great!  So it sounds like just clearing the app data is enough to fix the issue?  If so, I think this can be considered resolved.

#611 should fix the issue for any apps installed after upgrading to microG 0.2.6.13280.  Unfortunately, I don't think there's much we can do in microG to fix any already corrupted `accounts.xml` files.  For currently installed apps, I think clearing the app data is the best and easiest option for most users.  This seems to me like a reasonable solution since it's often recommended to clear app data (or reinstall apps) anyway to fix GCM issues.

Also, FYI Google uses lh3, lh4, lh5, and lh6 as subdomains dating back to the original picasaweb project.  It looks like after clearing the data, your `~6/` prefix is correctly being expanded to `https://lh6.`.  `lh3` would have worked too, but it's just not what happens to be returned by the API for your account.  I don't know how they pick which subdomain is issued, but I assume it's used for load balancing.

(The crash on startup I get is probably just because I'm running an older version of Android that the Photos app doesn't support, so it's unrelated.)

**Comment by sm4rk0** [comment]
OK, closing.
I've opened it for other users and microG developers, so they/you are aware of this behavior and a possible solution(s).
Thanks for support!
