### ISSUE TITLE
Let the user set the faked GSF version.

### ISSUE THREAD

**Issue by pthfdr-42** [microg/android_packages_apps_GmsCore#750]
Lots of GSF-enabled apps will check the version of the GSF and refuse to launch if it is too old.
Constantly updating MicroG is not a solution since in most cases MicroG is integeated in the ROM package and hard to replace.
So you should let the user to specify faked GSF version.

**Comment by chris42** [comment]
This is not a good idea. With each GSF Version, there comes a certain functionality. Just resetting the Version number would pretend to provide this functionality whilst not having the functionality. Leading to not traceable errors and misbehaving Apps.
This is a fundamental thing with microg, as it always mimics a specific functionality at a certain time. The better idea is to only update your GSF dependant apps when you are being able to go back to the a working version.

**Comment by pthfdr-42** [comment]
Another setting does not hurt, though.

**Comment by chris42** [comment]
This actually was discussed in several other Issues. It appears, that it is not as easy as a setting a string, as the version number is set with the compile. Hence I understood that microg would need to be sort of recompiled during runtime or changed somehow. This seemed very complicated.
Don't get me wrong, feel free to request this. But know, that this might not be a priority of the developer to do something complicated that will increase people requesting support for undefined errors.

**Comment by ale5000-git** [comment]
It isn't possible from the app level, but I think it could be possible at ROM level (specially for ROMs that integrate microG).
Like signature spoofing someone can add version spoofing.

**Comment by mar-v-in** [comment]
While this might be a good idea for a custom ROM, it is definitely out of scope for microG GmsCore itself.
