### ISSUE TITLE
How many people are working on this?

### ISSUE THREAD

**Issue by ahkuma** [microg/android_packages_apps_GmsCore#752]
Seems like the original author have not been active for a bit of time. Just curious, how many people are working on this?

**Comment by Nanolx** [comment]
There's only @mar-v-in as project member (likely due the nature of it being a re-implementation of Play Services, thus requiring more or less reverse-engineering skills, also it's a niche-product), along several contributors, translators, testers, community volunteers (other at XDA) and die-hard fan(atic)s who don't want it to die (lol), including, but not limited to @voidstarstar @armills @ale5000-git @Vavun @chris42 @lanchon Oswald Boelke and me.

@mar-v-in currently works on microG part-time (20h a week via funding), but usually often "behind the scenes" and then pulls a surprise batch of commits and new release when it's ready™. So just wait and see.

**Comment by ahkuma** [comment]
That's good @Nanolx I thought the project died last year.
