### ISSUE TITLE
Custom Maps implementations?

### ISSUE THREAD

**Issue by Riamse** [microg/android_packages_apps_GmsCore#755]
Is it possible for ride share apps, etc. to be able to use Open Street Map instead of Google?

**Comment by ale5000-git** [comment]
microG is already not using Google, implementation isn't completely functional but @mar-v-in is working on it.

**Comment by Vavun** [comment]
@ale5000-git Hi.

Some offtopic

Are you able to add labels to issues ?

**Comment by ale5000-git** [comment]
@Vavun 
Hi,
yes :)

**Comment by Vavun** [comment]
@ale5000-git oh, it can be very useful =)
Lot of issues should have labels. 

PS
And lot of should be closed also =)

**Comment by ale5000-git** [comment]
I don't have much time today but I will look at it in a couple of day.
