### ISSUE TITLE
GmsCore official update?

### ISSUE THREAD

**Issue by patrickdrd** [microg/android_packages_apps_GmsCore#769]
so, is @mar-v-in pushing his commits in Nanolx repo?
when will those of us running the official microg get a GmsCore update?
we can't update from nanolx repo because the signatures are different.
I think we should expect an update from this page https://microg.org/download.html,
but it's been a while since there was an update there

also, is there any way to get notified for play store updates @Nanolx?
I'm tracking both this page:
https://github.com/Nanolx/NanoDroid/blob/master/doc/Phonesky.diff
and the gitlab repo and they aren't consistent and I have to check each time,
since I have disabled automatic checking from f-droid app, I don't want it constantly checking

**Comment by incognico** [comment]
Or maybe beta releases (you can flag packages as beta/experimental in F-Droid). +1 for a bit more frequent releases.

**Comment by Nanolx** [comment]
Nope, I've re-structured my fork nanolx/master is now equal to microg/master. My builds are based on nanolx/nanolx-new. But the differences are becoming less. mar-v-in will push a release once it's ready, he's currently busy with working on the Maps API.

In regard to the patched Play Store: nope, there isn't. I also only do manual repo updates in F-Droid, btw.

**Comment by MrDodojo** [comment]
What about the cast api? Armills thing still needs to be merged xD

**Comment by ahkuma** [comment]
@Nanolx That sounds great to be honest. I was thinking of working on the maps api but never got around to it.

**Comment by julienschmidt** [comment]
It's great that marvin is working on the maps API. But why can't it be released in another beta release when it's done?
We have important fixes merged in the master branch for about a week. Why isn't there a beta release in such a case?

**Comment by Gigadoc2** [comment]
Is there a way to switch to a self-built version without everything breaking due to changed signatures?

**Comment by Nanolx** [comment]
@Gigadoc2 well, yes, but not easily. Boot into TWRP. Replace the original GmsCore system apk with your own, unpack the libraries, set the files owner and permission (preferably also the selinux context). Then delete /data/app/com.google.android.gms-* folder and reboot into ROM.

**Comment by ale5000-git** [comment]
Most important changes are now included and most problems are fixed, I'm closing this.
New version of official microG GmsCore was released yesterday.
