### ISSUE TITLE
Question: Use microG for google api

### ISSUE THREAD

**Issue by AnonymusRaccoon** [microg/android_packages_apps_GmsCore#771]
Hello, I'm creating an android app where i need google sign-in in order to use the youtube api. Since I'm not following the youtube ToS, I can't use the google play service. So, is it possible to use microG instead of the googles API for only this app (like youtube vanced do). Or is it possible to allow a user to sign in and return an access token witch will allow me to use the youtube API (an access token with the Youtube scope).

Thanks for reading.
Great project btw.

**Comment by MrDodojo** [comment]
I think you can't since Newpipe isn't doing that

**Comment by AnonymusRaccoon** [comment]
I don't know if they don't do that because it's not possible or because it's hard to do. Youtube Vanced is using that but they use the original youtube source code so that may behave differently. So I know that it's possible to use microG for an app only but it may be impossible to use it with google APIs.  
I would love if someone could confirm that. Or if somebody know how could I modify playlists owned by users or thinks like that without having to register in the google console, please tell me.

**Comment by ahkuma** [comment]
I think you should read the source code and the official documentation for that since this project needs to mirror the official API.

**Comment by AnonymusRaccoon** [comment]
The google sign-in is a proprietary software, the source code is not available. And for the youtube API, they just use a normalized access token given by the google sign-in. I have already read the official doc for google sign-in but I don't know if I can use the microG for that and if I can, how should I use microG for that but allowing users to have google services everywhere else like they normally do.

**Comment by ahkuma** [comment]
@AnonymusRaccoon I was asking you to read the source code for MicroG not Google's, and since MicroG needs to mirror the Google API, the usage should be the same.

**Comment by AnonymusRaccoon** [comment]
Oh, I see. Sorry. I should do that , you're right. I'm too used to bad codes that are unreadable. I think I found the good part (https://github.com/microg/android_packages_apps_GmsCore/tree/master/play-services-core/src/main/java/org/microg/gms/auth) just by going random. Thank you for the idea.

I'll close the issue but if anyone has more information please send it.

**Comment by Omar-D** [comment]
> Oh, I see. Sorry. I should do that , you're right. I'm too used to bad codes that are unreadable. I think I found the good part (https://github.com/microg/android_packages_apps_GmsCore/tree/master/play-services-core/src/main/java/org/microg/gms/auth) just by going random. Thank you for the idea.
> 
> I'll close the issue but if anyone has more information please send it.

have you used it?
or have you made your login using microG in your app?
