### ISSUE TITLE
microG Sign-in on JellyBean

### ISSUE THREAD

**Issue by neutrobox** [microg/android_packages_apps_GmsCore#773]
Hi, is there any fix yet fo this issue? It's the same image from here #757. I can't sign-in atm.

EDIT: Landscape doesn't work either.

![56324190-7f353100-616e-11e9-9097-4d1733146b1c](https://user-images.githubusercontent.com/6561643/57183186-40de8800-6e77-11e9-860a-ac1a084ba0c8.png)

**Comment by ale5000-git** [comment]
Don't create duplicate issues please, but instead comment on existing ones.
