### ISSUE TITLE
PocketCasts misbehaving app

### ISSUE THREAD

**Issue by alex-eyre** [microg/android_packages_apps_GmsCore#777]
Just reporting a misbehaving app, (potentially) for the wiki list.
PocketCasts v7 crashes on startup with a cryptic error message (https://del.dog/iyebegipom).
If there's a fix avaliable I'm sorry I missed it, and I am __not__ expecting a fix for this from MicroG because that's unreasonable and I have no clue what `d.d.a.b.d.a.I d.d.a.b.d.a.E.r()` does as a method.

**Comment by der-Daniel** [comment]
The app is working again for me.
Check out if it's working for you too. :v::raised_hands:

**Comment by alex-eyre** [comment]
Yep, seems to have sorted itself!
