### ISSUE TITLE
The importance of having the webview bug fixed

### ISSUE THREAD

**Issue by lostycho** [microg/android_packages_apps_GmsCore#781]
Microg Broke with webview v74 as found out in issue #770. People get stuck at an infinite loading screen after clicking agree, that was easily fixable just by disabling the v74(or v75) webview. Now the latest android Pie (security) update webview v75 is pre-installed without chrome webview(Not sure about that).
That means one workaround(disabling chrome) won't work anymore and lot more people will get effected not being able to login without having to use another workaround.

**Comment by Nanolx** [comment]
If your ROM supports `com.android.webview` you may use my Bromite WebView (`Nanodroid-BromiteWebView`) installer  to remove the pre-installed WebView and replace it with Bromite WebView v73, as a work-around.

* [Repository/Documentation](https://gitlab.com/Nanolx/NanoDroid)
* [Support Thread](https://forum.xda-developers.com/apps/magisk/module-nanomod-5-0-20170405-microg-t3584928)
* [Download](https://downloads.nanolx.org/NanoDroid/Stable/)

**Comment by mar-v-in** [comment]
Close as duplicate.
