### ISSUE TITLE
GCM removed soon, does MicroG have FCM?

### ISSUE THREAD

**Issue by MrDodojo** [microg/android_packages_apps_GmsCore#783]
As soon as in 8 days now(9 yesterday) Google Cloud Messaging will be removed.(May 29th 2019)
![image](https://user-images.githubusercontent.com/47711280/58037240-43a2d380-7b2d-11e9-9c38-2e5c7488c39d.png)

{Disclaimer: this is all speculation/logical thinking of problems that might occur if GCM is removed}
Does MicroG support firebase Cloud Messaging? YouTube already stepped to FCM first notification registering since April 2018 and FCM ONLY with a server side update later that year. 
It still supports notifications if already registered/logged in with GCM on a YouTube Version before 10 April 2018. On a version that supports both GCM and FCM notification registering

When GCM will be removed(and if MicroG doesn't support FCM) in just a little over a week you will not be able to register/activate notifications anymore and it might even break notifications for every MicroG user there is.

This kinda needs fixing asap

https://developers.google.com/cloud-messaging/

**Comment by Mafus1** [comment]
As far as I know, microg already supports FCM.

**Comment by MrDodojo** [comment]
> As far as I know, microg already supports FCM.

I don't see it in the code or referenced anywhere,
Even my YouTube with the latest MicroG doesn't give notifications

**Comment by Mafus1** [comment]
> > As far as I know, microg already supports FCM.
> 
> I don't see it in the code or referenced anywhere,
> Even my YouTube with the latest MicroG doesn't give notifications

There was a bounty for this problem, and it was closed and paid out, so I have to assume its fixed. Link to the bounty: https://www.bountysource.com/issues/51518216-gcm-fcm-update-needed-for-push-messaging

**Comment by chris42** [comment]
Guys, please use the search function!
Most was discussed here: https://github.com/microg/android_packages_apps_GmsCore/issues/439

**Comment by MrDodojo** [comment]
> Guys, please use the search function!
> Most was discussed here: #439

I did, and it's broken for me.. is gsfproxy needed or something.

**Comment by chris42** [comment]
Good, then the question of FCM should be answered: It is somewhat implemented. Some functions are missing hence apps, that rely heavily on FCM special functions, might not work.
To see if your app is one of them, you can check your logs for errors.

So I guess you have them after reading/trying:
https://github.com/microg/android_packages_apps_GmsCore/issues/439#issuecomment-419052102 (now with version 13280)
and
https://github.com/microg/android_packages_apps_GmsCore/issues/439#issuecomment-433018720

If you found an error, please check if there is an issue existing for it or create a new one with the logs. This will allow Marvin and others to take a look into it.

**Comment by ale5000-git** [comment]
Please all of you try the new version released today to see if it works fine with FCM apps.
