### ISSUE TITLE
[SUGGESTION] Optimize battery for microg 

### ISSUE THREAD

**Issue by RoiArthurB** [microg/android_packages_apps_GmsCore#787]
Will optimizing microg will generate any particular bug? 

I know that, with some modules on Magisk, it's possible to optimize GApps and GSM (like any other app on the smartphone). Isn't it possible to do it with MicroG, UnifiedNlp, etc ?

**Comment by Nanolx** [comment]
microG doesn't consume nearly as much battery as GApps, so you wouldn't see much difference.

Anyway, yes, it would prevent you from getting push notifiations in time.

**Comment by RoiArthurB** [comment]
> Anyway, yes, it would prevent you from getting push notifiations in time.

But freezing "classical" GApps and/or "classical" GSM doesn't prevent from getting push notification (I've optimised full Google set before switching on MicroG and I didn't notice any problem)... 🤔🤔🤔

**Comment by Nanolx** [comment]
So? microG isn't GApps. And again: microG consumes very low battery, you wouldn't notice any significant difference.

Am 24. Mai 2019 04:06:24 MESZ schrieb Arthur Brugiere <notifications@github.com>:
>> Anyway, yes, it would prevent you from getting push notifiations in
>time.>
>>
>But freezing "classical" GApps and/or "classical" GSM doesn't prevent
>from getting push notification (I've optimised full Google set before
>switching on MicroG and I didn't notice any problem)... 🤔🤔🤔 >
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/microg/android_packages_apps_GmsCore/issues/787#issuecomment-495446499

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by RoiArthurB** [comment]
I don't know, I'm just asking why we have to avoid the battery optimization with microg ^^'

**Comment by n76** [comment]
Optimizing battery use on an app (and microG is an app) will mean that it can be put in to deep sleep. If microG is in deep sleep then any push notifications that are trying to get to your phone won't happen until you wake the phone up which could delay the notifications for quite some time.
