### ISSUE TITLE
No updates since 5/13-15

### ISSUE THREAD

**Issue by kendallgreen** [microg/android_packages_apps_GmsCore#788]
I haven't seen any updates since 5/13-15/19.  I am interested in the nash fork which usually happen once a week.

**Comment by MrDodojo** [comment]
Nash fork? Whats that

**Comment by wombatch** [comment]
Hello, I am also wondering if there is a planned date for a new fdroid release. I see lots of new things/fixes going into the code however I prefer not to compile my own version but let people who really know what they are doing do that. 
The last Fdroid release was 0.2.6.13280 as far as I know. I understand the software is early (even though it works really well for me) but it would be nice to have an idea of when there might (if ever) be another Fdroid release.

**Comment by caneleex** [comment]
Any eta of new update?

**Comment by ale5000-git** [comment]
New version of microG GmsCore (app only) is released today.

If you are looking for the ROM you should ask [here](https://github.com/lineageos4microg).
