### ISSUE TITLE
The app does not install in my mobile phone

### ISSUE THREAD

**Issue by XAMIR555** [microg/android_packages_apps_GmsCore#789]
#### Project Information

* Repository--------------:[Here](https://github.com/microg/android_packages_apps_GmsCore)
* Project Name-----------:  [android_packages_apps_GmsCore](https://github.com/microg/android_packages_apps_GmsCore/releases)
* Publisher-----------------: [microG Project ](https://github.com/microg)
* My GitHub account------:  [Here](https://github.com/XAMIR555)

#### Expected behavior
The application should be installed when I try to install the application

#### Actual behavior

The application is not being installed

#### How to reproduce
* [Download ](https://github.com/microg/android_packages_apps_GmsCore/releases)the application
* try to install the application
* Note the Bug

* Browser/App version-: v0.2.6.13280
* Operating system----: 9.0.0

#### Recording Of The Bug
![20190528_015626](https://user-images.githubusercontent.com/49812927/58439145-6bdb8680-8087-11e9-9ae4-f1825a25af35.gif)

**Comment by JonnyTech** [comment]
You must uninstall Google play services first.

**Comment by XAMIR555** [comment]
I have tried many times but still the applications are not installed

i have uninstalled the google play service

**Comment by JonnyTech** [comment]
The system asks if you want to install an update to an existing application so obviously you have not. Is the devices rooted and have you debloated and performed the [prerequisites](https://github.com/microg/android_packages_apps_GmsCore/wiki/Prerequisites)?

**Comment by XAMIR555** [comment]
ok sir  itry

**Comment by XAMIR555** [comment]
I have tried a lot but the application is not installed
I do not understand what the problem is, I have made everything possible

**Comment by JonnyTech** [comment]
Use a root file manager and remove `/system/priv-app/GoogleLoginService.apk` and `/system/priv-app/GoogleServicesFramework.apk`, else you can try [microG unofficial installer](https://forum.xda-developers.com/android/development/microg-unofficial-installer-t3432360)

**Comment by XAMIR555** [comment]
The problem is not resolved yet

**Comment by oldosfan** [comment]
You can't. You'll need NanoDroid after debloating.


Your ROM doesn't support signature spoofing. µG will not work.

**Comment by XAMIR555** [comment]
ok sir
