### ISSUE TITLE
microg.org down?

### ISSUE THREAD

**Issue by patrickdrd** [microg/android_packages_apps_GmsCore#793]
what happened to microg.org?

is it abandoned?

**Comment by sm4rk0** [comment]
microg.com is not related to this project:

> MicroGraphics is a manufacturers' rep company incorporated in 1980.

But https://microg.org is and it really is down at the moment.

**Comment by patrickdrd** [comment]
oops, sorry, I corrected my message, I meant microg.org of course

**Comment by mar-v-in** [comment]
A temporary downtime due to issue in datacenter. Hopefully won't last for long.

**Comment by patrickdrd** [comment]
ok it's up again

**Comment by sm4rk0** [comment]
great!
@patrickdrd, you can close this issue now
