### ISSUE TITLE
MicroG LineageOS 16.0 (dumpling) + GmsCore 13280 receiving but not displaying incoming notifications

### ISSUE THREAD

**Issue by rarecoil** [microg/android_packages_apps_GmsCore#794]
I'm currently running an official MicroG + LineageOS 16.0 build for `dumpling` (OnePlus 5T) and while most things work, GCM/FCM notifications are not working as expected. 

I can't tell if this is a Lineage bug or a MicroG bug at this point. The device:

The device: 
* passes self-check
* is registered with GCM
* has apps registered to GCM
* Push notifications tester works
* All app notifications are enabled in settings

I am seeing MicroG show that notifications are being received, and logcat also displays that the notifications are working in some way. `GmsGcmMcsInput` shows the incoming data object, but this is never surfaced to the UI. There are a few more FCM/GMS related things in the logs thereafter:

````
GmsGcmMcsSvc: ResolveInfo {<hex> <redacted app>/com.google.firebase.iid.FirebaseInstanceIdReceiver}
FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
ContextImpl: Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
FirebasePerformance: HTTP Method is null or invalid: null
FirebasePerformance: Unable to process an HTTP request/response due to missing or invalid values. See earlier log statements for additional information on the specific invalid/missing values.
````

I know that microG has limited FCM support, but literally nothing on the phone is displaying push notifications (including SMS messaging, Signal, et al.) Should I report this upstream to Lineage? Seems like a pretty obvious break for those running Gapps so I'm assuming this is microG related.

**Comment by rarecoil** [comment]
Got another crash now regarding FCM, from Google Voice:

````
FATAL EXCEPTION: Firebase-FcmListenerService
Process: com.google.android.apps.googlevoice, PID: 19819
java.lang.NullPointerException: Null messageId 
at bxx.a(PG:3) 
at com.google.android.apps.voice.backends.cloudmessaging.fcm.receiver.FcmListenerService.a(PG:35)
at com.google.firebase.messaging.FirebaseMessagingService.a(PG:191)
at oii.run(PG:4)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at ior.run(PG:4)
at java.lang.Thread.run(Thread.java:764)
````

**Comment by MrDodojo** [comment]
Same issue but on normal MicroG and only 1 of my multiple brand accounte

**Comment by voidstarstar** [comment]
I can confirm the Google Voice crash.  Older versions of the app have started telling the user to update to continue using the app, but the latest version causes this crash.  I'm not sure if there are any versions that neither crash nor show the upgrade prompt.

Regarding the lack of notifications, that could be a Doze related issue that was patched in #732.

**Comment by rarecoil** [comment]
@voidstarstar Would that PR be in the current stable build, or should I build from `master` and try it?

**Comment by voidstarstar** [comment]
@rarecoil Yes it is in v0.2.7.17455.  It will probably only fix the notification issue.

**Comment by rarecoil** [comment]
The notification issue has resolved, but Voice is still broken for me. Since this is about notifications, I'll close the issue.

**Comment by voidstarstar** [comment]
There are two separate issues here.
1. The notification issue.  This was fixed.
2. The crashing issue.  Is this still occurring?  If so, it is probably better to reopen this issue or create a new issue.  This is possibly due to a bug or missing feature in the GCM/FCM implementation.

**Comment by voidstarstar** [comment]
The crash issue is a duplicate of #762.

I haven't been able to consistently reproduce the crash.  I sometimes can encounter it, but not always.  Any info on how to reliably reproduce it might be helpful.

(This couldn't be caused by `GServices` giving a `null` value for `android_id`, could it?)

> Should I report this upstream to Lineage?

Nope, you reported it in the right place.  (Sorry I didn't say that earlier.)
