### ISSUE TITLE
MicroG-GMS - Android 6 - Stock LG - Sygic App does not start

### ISSUE THREAD

**Issue by Catfriend1** [microg/android_packages_apps_GmsCore#81]
Hello,

I got my uG GMS Core running under Stock Android 6 with Xposed and FakeGApps. I noticed on installation, that the package installer showed "No permissions required" when installing the debug.apk by clicking it in Root Explorer. MicroG worked (tested with Play Store and Google Account), but seems to fail to supply a valid GPS service from user-perspective.

E.g. I cannot run Sygic Navigation App.
Link: https://play.google.com/store/apps/details?id=com.sygic.aura&hl=de

Also tried to manually enable permissions for MicroG and dependent APKs under Settings->Apps->Permissions.

My logcat is attached. Phone is still LG-G4 H815. Using rovo89 XPosed sdk 23 version 80test2.

I think this part of the Logcat is important:
[2016-01-20-00-45-54.txt](https://github.com/microg/android_packages_apps_GmsCore/files/102394/2016-01-20-00-45-54.txt)

01-20 00:46:13.058 E/Fabric  (18736): Failed to execute task.
01-20 00:46:13.058 E/Fabric  (18736): java.util.concurrent.TimeoutException
01-20 00:46:13.058 E/Fabric  (18736): 	at java.util.concurrent.FutureTask.get(FutureTask.java:177)
01-20 00:46:13.058 E/Fabric  (18736): 	at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44)
01-20 00:46:13.058 E/Fabric  (18736): 	at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:275)
01-20 00:46:13.058 E/Fabric  (18736): 	at com.flurry.sdk.li.b(SourceFile:96)
01-20 00:46:13.058 E/Fabric  (18736): 	at com.flurry.sdk.li.b(SourceFile:19)
01-20 00:46:13.058 E/Fabric  (18736): 	at com.flurry.sdk.li$a.uncaughtException(SourceFile:107)
01-20 00:46:13.058 E/Fabric  (18736): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
01-20 00:46:13.058 E/Fabric  (18736): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
01-20 00:46:13.059 E/AndroidRuntime(18736): FATAL EXCEPTION: main
01-20 00:46:13.059 E/AndroidRuntime(18736): Process: com.sygic.aura, PID: 18736
01-20 00:46:13.059 E/AndroidRuntime(18736): java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at android.os.Parcel.readException(Parcel.java:1599)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at android.os.Parcel.readException(Parcel.java:1552)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.location.internal.zzg$zza$zza.zza(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.location.internal.zzi.zza(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.location.internal.zzj.zza(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.api.zzc$zza.zzb(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.api.zzf.zza(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.api.zzf.zzb(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.api.zzi.zzb(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.sygic.aura.feature.gps.LowGpsFeatureBase$PlayServiceLocationManager.onConnected(LowGpsFeature.java:119)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.internal.zzk.zzh(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.api.zzg.zznt(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.api.zzg.onConnected(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.api.zzi$2.onConnected(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.internal.zzj$zzg.zzoD(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.internal.zzj$zza.zzc(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.internal.zzj$zza.zzs(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.internal.zzj$zzc.zzoF(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.google.android.gms.common.internal.zzj$zzb.handleMessage(Unknown Source)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at android.os.Looper.loop(Looper.java:148)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at android.app.ActivityThread.main(ActivityThread.java:5525)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at java.lang.reflect.Method.invoke(Native Method)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
01-20 00:46:13.059 E/AndroidRuntime(18736): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
01-20 00:46:13.074 W/ActivityManager( 1264):   Force finishing activity com.sygic.aura/.activity.NaviNativeActivity

**Comment by ibleedbinari** [comment]
Run this command in the shell

pm grant com.google.android.gms android.permission.ACCESS_FINE_LOCATION

**Comment by ibleedbinari** [comment]
@mar-v-in This looks like the same issue as #68

**Comment by lbdroid** [comment]
Would I be right in guessing that this issue should *ONLY* be present in "High accuracy" location mode where it is trying to give you a hybrid between network and GPS location..? Use of hardware GPS doesn't depend on any google blobs and should work on any AOSP build.

**Comment by mar-v-in** [comment]
@lbdroid Use of network location does not depend on any google blobs, there are implementations by Amazon and Nokia as well and microG UnifiedNlp.
However there are two APIs for locating, one using google blobs and one that does not. See [this post](https://github.com/microg/android_packages_apps_UnifiedNlp/issues/36#issuecomment-86744484) for details.

**Comment by Catfriend1** [comment]
I added the command
pm grant com.google.android.gms android.permission.ACCESS_FINE_LOCATION
to my Tasker startup with a root shell task and it works fine.
Issue solved.

**Comment by ibleedbinari** [comment]
You don't need to run it every startup. It should be one time

**Comment by lbdroid** [comment]
@Catfriend1 : You should NOT close the issue for figuring out a hackaround. The problem still exists and ultimately needs to be handled by GmsCore automatically, without manual intervention.

**Comment by ghost** [comment]
please delete issue
