### ISSUE TITLE
Emulator image won't start

### ISSUE THREAD

**Issue by Bubu** [microg/android_packages_apps_GmsCore#815]
I can't start the emulator image as explained here: https://github.com/microg/android_packages_apps_GmsCore/wiki/Development-Tools

```
11:33	Emulator: emulator: ERROR: This AVD's configuration is missing a kernel file! Please ensure the file "kernel-ranchu" is in the same location as your system image.

11:33	Emulator: emulator: ERROR: ANDROID_SDK_ROOT is undefined

11:33	Emulator: Process finished with exit code 1
```

Anything I'm doing wrong?

*Edit:* The emulator works fine with other images.

**Comment by mar-v-in** [comment]
Google apparently dropped support for qemu in emulator 29 in favor of their newer engine ranchu. The microG image doesn't support ranchu (yet). You can however downgrade your emulator to version 28.0.25 by downloading it manually from http://dl.google.com/android/repository/emulator-linux-5395263.zip (assuming linux).

**Comment by Kamalnrf** [comment]
I've downgraded the emulator, but still I have few blockers 

- Emulator is taking forever to start (RAM size it is 4gb)
- Not able to complete HAX installation for the downgraded emulator

**Comment by mar-v-in** [comment]
There is a new emulator image using Android 10.0 / x86_64 which should also run fine with ranchu emulator.
