### ISSUE TITLE
YouTube Vanced: "Please check your network connection" even though it is running

### ISSUE THREAD

**Issue by Sv443** [microg/android_packages_apps_GmsCore#819]
I have a Xiaomi Mi A2 Lite with Android 8.1.0
I've installed MicroG 2.6 and YouTube Vanced but as I log in, it keeps telling me to check my internet connection even though it's working fine. A restart, reinstall and even a lower version all didn't work.
If you need more information or if I am in the wrong repository, please tell me and I'll correct it.

Screenshot:
![grafik](https://user-images.githubusercontent.com/38158426/58982587-16188400-87d5-11e9-8d3f-2437419119f9.png)

**Comment by Nanolx** [comment]
YouTube Vanced doesn't work with upstream microG, because it's looking for com.**m**google.android.gms, which is the Vanced microG fork (which they don't release the source for AFAIK), so please post your issue over at the Vanced Thread.

**Comment by Sv443** [comment]
Yeah sorry, I just noticed, went over there and discovered that I downloaded the wrong one. Now it works fine.
But thank you for responding and have a great day :)

**Comment by beg1nner** [comment]
Since I have exactly the same problem and google didn't deliver any results to fix this, it would be great if you could link your question. Thanks a lot in advance 😊

**Comment by Sv443** [comment]
@beg1nner I downloaded MicroG from the [YouTube Vanced](https://vanced.app) page: https://vanced.app/APKs?type=NONROOT

![image](https://user-images.githubusercontent.com/38158426/64003788-45f1d200-cb0d-11e9-8ab6-63312a4df918.png)

**Comment by aritraroy24** [comment]
> Yeah sorry, I just noticed, went over there and discovered that I downloaded the wrong one. Now it works fine. But thank you for responding and have a great day :)

Hey @Sv443 , I'm having the same issue...even also I have downloaded the vanced microG from their website. But it is showing same as yours...any suggestion to fix it?

**Comment by aritraroy24** [comment]
@Sv443 Thanks. But actually, I have downloaded it from [vancedapp.com](https://vancedapp.com/)...and no issue I'm posting this in the main repo.

**Comment by noahUKUK** [comment]
In a person's thinking, the answer to this [YouTube Vanced](https://youtubvanced.com/) issue reflects frustration and a desire for clarity, prompting a need to troubleshoot or seek solutions.
