### ISSUE TITLE
None of the sig faking patches apply on Marshmallow / CM13

### ISSUE THREAD

**Issue by bugrepor** [microg/android_packages_apps_GmsCore#83]
I can't find a sig faking patch that applies to current Android sources, neither the one in the GmsCore repo nor the ones in OmniROM's Gerrit work.

Is there a more recent one?

**Comment by Primokorn** [comment]
If your ROM does not support signature faking, but you use Xposed, you can grab this [module](https://github.com/thermatk/FakeGApps/releases).

**Comment by lbdroid** [comment]
Primokorn; that is probably not true. Reason being that if the code being patched has changed sufficiently that the patch doesn't apply, the same problem could be encountered by the xposed module.

@bugrepor : code changes. If the patch doesn't apply, then you will need to understand what the patch does, and adjust it according to the new code.

**Comment by ibleedbinari** [comment]
@bugrepor The one in CM13's Gerrit (from issue #63) should work
http://review.cyanogenmod.org/#/c/125637/

**Comment by lbdroid** [comment]
lol @ their arguments against accepting the patch. As if there is ANY element of CM that is actually secure or even works correctly. They're just fundamentally opposed to anything that makes sense.

**Comment by Catfriend1** [comment]
I think this can be considered as "solution found". Other tickets say, Needle or XPosed + FakeGApps are a good alternative to accomplish this.
