### ISSUE TITLE
Google Apps crashing [microG v0.2.7.17455]

### ISSUE THREAD

**Issue by SchwartzWare** [microg/android_packages_apps_GmsCore#836]
I currently installed microG because Google Play Services did make my Tegra Note 7 temporarily unusable every time I connected with a Wifi.

Now the problem: Google Maps and Calendar are crashing with microG v0.2.7.17455 installed under Android KitKat 4.4. With the previous version of microG (v0.2.6.13280) installed, the apps aren't crashing but I can not login with my Google Account because the 'Sign in' button is unclickable.

**Comment by mar-v-in** [comment]
Can you please provide a log as I can't reproduce these crashes.

**Comment by ale5000-git** [comment]
@SchwartzWare: There are 2 variants of 0.2.7.17455, which one do you have installed?

**Comment by SchwartzWare** [comment]
I tried both version of 0.2.7.17455. Both have the same result. When I install very old versions of Calendar and Maps they don't crash.

Here is the log of the Calendar App crash:
[microG_Google Calendar Crash_Logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3288176/microG_Google.Calendar.Crash_Logcat.txt)

**Comment by oldosfan** [comment]
can't reproduce - latest Maps & Calendar work perfectly

**Comment by SchwartzWare** [comment]
Okay, so it seems I made a mistake in the installation process or I should consider resetting my messed up tablet.
