### ISSUE TITLE
Don't report mapbox in the vtm version

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_GmsCore#837]
Also in the vtm version mapbox appears inside the list of libraries.
It should appears only in the mapbox version to avoid confusion.

**Comment by mar-v-in** [comment]
As was already discussed in another issue, I'd like to split the maps implementation out of the GmsCore apk, this issue can be easily done afterwards :)

**Comment by ale5000-git** [comment]
My idea was to simplify error reporting until the maps split.
But since now there is "-vtm" text in the vtm version, it should be enough for now.
