### ISSUE TITLE
No notifications with Matrix Android Console app and microg

### ISSUE THREAD

**Issue by jfrederickson** [microg/android_packages_apps_GmsCore#84]
I use the Android app for Matrix, and I don't seem to get push notifications from events that should notify me. I can see that I do receive a message from GCM:

`01-28 15:21:00.065  1311 21352 D GmsGcmMcsInput: Incoming message: DataMessageStanza{id=861D34EB, from=546327642826, category=org.matrix.androidsdk.alpha, token=do_not_collapse, app_data=[AppData{key=room_id, value=!WRIhDDWHvpnipvwyHe:terracrypt.net}, AppData{key=unread, value=1}, AppData{key=body, value=Jon: test}, AppData{key=type, value=m.room.message}, AppData{key=content, value={"body":"Jon: test","msgtype":"m.text"}}, AppData{key=room_name, value=pushtest}, AppData{key=sender, value=@jfred:matrix.org}, AppData{key=id, value=$145401245744735aaGVV:matrix.org}, AppData{key=msgtype, value=m.text}], from_trusted_server=false, persistent_id=0:1454012460499237%869bf29ef9fd7ecd, sent=1454012460496}`

However, it seems that this does not wake the Matrix app, and therefore I don't see the notification.

I'm running Android 6.0.1 (a CyanogenMod nightly build) but was experiencing the same issue on 5.1.1. I've verified that other users of 5.1.1 (using Play Services) do correctly receive the notification. I am using the version of microG from the F-Droid repo mentioned on this page:

https://o9i.de/2015/10/23/howto-gmscore.html

The GCM-related source code of the application can be found here:

https://github.com/matrix-org/matrix-android-console/tree/master/console/src/main/java/org/matrix/console/gcm

**Comment by jfrederickson** [comment]
This may be related to #75 but it didn't look quite the same (I don't see the error message shown in that report) so I opened this as a new report.

**Comment by pvagner** [comment]
I am also facing this.
Unfortunatelly it's the same with v0.2.0 update.

Here is a full catlog coresponding with this "not happening"...

D/GmsGcmMcsInput( 2695): Incoming message: HeartbeatAck{last_stream_id_received=49}
D/GmsGcmMcsSvc( 2695): Heartbeat initiated, reason: Intent { act=org.microg.gms.gcm.mcs.HEARTBEAT flg=0x4 cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }
D/GmsGcmMcsSvc( 2695): Scheduling heartbeat in 60 seconds...
D/GmsGcmMcsOutput( 2695): Outgoing message: HeartbeatPing{last_stream_id_received=57}
D/GmsGcmMcsInput( 2695): Incoming message: HeartbeatAck{last_stream_id_received=50}
D/GmsGcmMcsInput( 2695): Incoming message: DataMessageStanza{id=A922DF31, from=546327642826, category=org.matrix.androidsdk.alpha, token=do_not_collapse, app_data=[AppData{key=room_id, value=!vUTMcLppFTGnXuZGmy:matrix.org}, AppData{key=unread, value=1}, AppData{key=body, value=this is another test}, AppData{key=type, value=m.room.message}, AppData{key=content, value={"body":"this is another test","msgtype":"m.text"}}, AppData{key=sender, value=@pvagner:matrix.org}, AppData{key=sender_display_name, value=Peter Vágner}, AppData{key=id, value=$1454697459137255RTCfE:matrix.org}, AppData{key=msgtype, value=m.text}], from_trusted_server=false, persistent_id=0:1454697459682516%869bf29ef9fd7ecd, sent=1454697459676}
D/GmsGcmMcsSvc( 2695): No target for message, wut?

**Comment by mar-v-in** [comment]
Can you verify that this does actually work on original play services? The app uses a the category `org.matrix.console.gcm` for receiving messages (see [here](https://github.com/matrix-org/matrix-android-console/blob/master/console/src/main/AndroidManifest.xml#L176)), but according to [Google documentation](https://developers.google.com/android/reference/com/google/android/gms/gcm/GcmReceiver) it should be the package name (which would be `org.matrix.androidsdk.alpha`). So either the app is broken or Google documentation is crap.

**Comment by pvagner** [comment]
With gapps this app does really work and push notifications.
When I look into the source files @jfrederickson linked in the first post they have package org.matrix.gms there at the top. So what would be a proper fix should they change it to they real package or is there a way on how to address this within MicroG GCM implementation? I think matrix guys have grabbed some sample from google SDK to base their GCM implementation on. Might other apps be doing similar things? e.g. I am also getting no notifications from Viber heh but I don't care about that.

**Comment by pvagner** [comment]
Okay, looking more at this.
Matrix guys have initially published an alpha app with packagename org.matrix.androidsdk.alpha [via Google play](https://play.google.com/store/apps/details?id=org.matrix.androidsdk.alpha).
Looking into the source files there are package declarations such as these:
package org.matrix.console;
and within the gcm folder
package org.matrix.console.gcm;
When looking at activities listed in their manifest there are activities named such as org.matrix.console.activity.LoginActivity .
So using different valid package name than the app package name is apparently possible as they are doing all over their manifest.
I don't know what a proper fix might be. Is it really necessary to relocate all the gcm stuff into the org.matrix.androidsdk.alpha?

**Comment by mar-v-in** [comment]
This is not about the java package but the category announced in [AndroidManifest.xml](https://github.com/matrix-org/matrix-android-console/blob/master/console/src/main/AndroidManifest.xml#L176) that (as far as I can tell) should match the package name. I did not try, but I think that setting category name to `${applicationId}` in AndroidManifest.xml will fix this issue.

However if this does work perfectly with original play services, this should be fixed in microG for compatibility reasons.

**Comment by pvagner** [comment]
unfortunatelly that is not just cosmetic thingy as I understand from your comments.
If I changed the matrix android console app as you have suggested then MicroG GCM_core is happy but activity manager can't find associated activity as it is not found in the given package....
D/GmsGcmMcsInput( 2695): Incoming message: DataMessageStanza{id=AD441CF2, from=546327642826, category=org.matrix.androidsdk.alpha, token=do_not_collapse, app_data=[AppData{key=room_id, value=!vUTMcLppFTGnXuZGmy:matrix.org}, AppData{key=unread, value=117}, AppData{key=body, value=more test}, AppData{key=type, value=m.room.message}, AppData{key=content, value={"body":"more test","msgtype":"m.text"}}, AppData{key=sender, value=@pvagner:matrix.org}, AppData{key=sender_display_name, value=Peter Vágner}, AppData{key=id, value=$14547722008318PKrRf:matrix.org}, AppData{key=msgtype, value=m.text}], from_trusted_server=false, persistent_id=0:1454772200342787%869bf29ef9fd7ecd, sent=1454772200340}
D/GmsGcmMcsSvc( 2695): Target: ResolveInfo{296e85ba org.matrix.androidsdk.alpha/com.google.android.gms.gcm.GcmReceiver m=0x108000}
W/ActivityManager( 2275): Unable to start service Intent { act=com.google.android.c2dm.intent.RECEIVE cat=[org.matrix.androidsdk.alpha] flg=0x30 pkg=org.matrix.androidsdk.alpha (has extras) } U=0: not found
D/GmsGcmMcsSvc( 2695): Heartbeat initiated, reason: Intent { act=org.microg.gms.gcm.mcs.HEARTBEAT flg=0x4 cmp=com.google.android.gms/org.microg.gms.gcm.McsService (has extras) }
D/GmsGcmMcsSvc( 2695): Scheduling heartbeat in 60 seconds...
D/GmsGcmMcsOutput( 2695): Outgoing message: HeartbeatPing{last_stream_id_received=384}

**Comment by pvagner** [comment]
Heh, lesson learned. I can now build MicroG GCM Core.
At the other hand looking at a method handleAppMessage(DataMessageStanza msg) I can now understand seeing the error 
D/GmsGcmMcsSvc( 2695): No target for message, wut?
does not mean broadcast receiver is not sent.
It is adding the category from the message to the intent. So this might really be closely related to #75 I guess. Or I am missunderstanding all the time. I can't figure it out.

**Comment by pvagner** [comment]
Some more things and assumptions.
I have discovered when the app is in foreground notifications are shown.
Then I have found a similar query [on sending broadcasts to closed apps](http://stackoverflow.com/questions/28842043/unable-to-send-broadcast-to-closed-app).
If we were about to add a component to our intent what should hopefully help in this case, we would assume package from the msg.category field and class com.google.android.gms.gcm.GcmReceiver by default.
However people can implement [their own receivers](http://stackoverflow.com/questions/12089428/gcm-with-custom-broadcastreceiver#14424539) so we need to somehow come up with a way on how to resolve a proper broadcast to send even if the app is not running. It appears I am thinking of more issues rather than being close to solve something.

**Comment by jfrederickson** [comment]
I don't think the notifications being shown while the app is in the foreground is related. The Matrix app only relies on GCM while in the background - while in the foreground, it receives messages directly through the event stream, bypassing GCM altogether.

**Comment by pvagner** [comment]
Yes I've just verified this. Still I assume our issue is that we somehow need to wake the app as matrix goes asleep intentionally when it is not in the foreground. I'm still trying to figure it out.

**Comment by pvagner** [comment]
I've tested with gapps and this is what I'm getting when such message arrives.
I/GCM     ( 2841): GCM message org.matrix.androidsdk.alpha 0:1454873836587114%869bf29ef9fd7ecd
That suggests I am looking at it all wrong.

**Comment by pvagner** [comment]
Okay last little thing for today. When testing with v0.2.0 release, I can see the message in the catlog. With latest master it even does not display there.

**Comment by pvagner** [comment]
Running self-made build from the master branch I can see no apps except of push notification tester registering. It might be why Imay get no messages from matrix android console since 67b1ac7 should help with that a bit.

**Comment by mar-v-in** [comment]
@pvagner you should not see a lot of push notification registrations as these are only done once - push notification tester is the only app that re-registers every time. 

When you clear data of GmsCore you destroy the device registration at Google servers and thus will not receive messages for registrations done before. That's why some applications have an option in settings to re-register.

Can you try if removing all data from Matrix app causes a new registration? Additionally with latest master it should be possible to use the official Matrix builds again, so it would be awesome if you can try that as well.

**Comment by pvagner** [comment]
I apologize for a lot of incomplete messages. Now I've reinstalled it all including MicroG GCM Core and Matrix Android Console and push notifications are working after the commit which has supposed to address this.

Thank you!

This is all with official builds.

D/GmsGcmMcsInput( 2692): Incoming message: HeartbeatAck{last_stream_id_received=37}
D/GmsGcmMcsInput( 2692): Incoming message: DataMessageStanza{id=B7EDC1D5, from=546327642826, category=org.matrix.androidsdk.alpha, token=do_not_collapse, app_data=[AppData{key=room_id, value=!vUTMcLppFTGnXuZGmy:matrix.org}, AppData{key=unread, value=694}, AppData{key=body, value=test!}, AppData{key=type, value=m.room.message}, AppData{key=content, value={"body":"test!","msgtype":"m.text"}}, AppData{key=sender, value=@pvagner:matrix.org}, AppData{key=sender_display_name, value=Peter Vágner}, AppData{key=id, value=$145526580518469QbcgR:matrix.org}, AppData{key=msgtype, value=m.text}], from_trusted_server=false, persistent_id=0:1455265806078902%869bf29ef9fd7ecd, sent=1455265806071}
D/GmsGcmMcsSvc( 2692): Target: ResolveInfo{59fb850 org.matrix.androidsdk.alpha/com.google.android.gms.gcm.GcmReceiver m=0x108000}
D/GcmListenerService( 6021):  onMessageReceived 
E/GcmListenerService( 6021):  >>> sender_display_name : Peter Vágner

**Comment by zeorin** [comment]
+1 I have this same error with Cerberus. When I send a command from Cerberus console to my phone, logcat shows the following:

```
D/GmsGcmMcsInput( 2979): Incoming message: DataMessageStanza{id=BAE019E5, from=999803017449, category=com.lsdroid.cerberuss, token=do_not_collapse, app_data=[AppData{key=param, value=}, AppData{key=message, value=START_TRACKING}], from_trusted_server=false, persistent_id=0:1455465177551995%6bc75e70f9fd7ecd, sent=1455465177547}
D/GmsGcmMcsSvc( 2979): No target for message, wut?
```

**Comment by zeorin** [comment]
I also reinstalled microG and Cerberus, and now it's working.

**Comment by mar-v-in** [comment]
This seems to be no longer a problem, closing.
