### ISSUE TITLE
(logcat) GmsCheckinClient: CheckinRequest{<is this sent to Google?>}

### ISSUE THREAD

**Issue by infozsoda** [microg/android_packages_apps_GmsCore#85]
Is there some documentation about what kind of data is sent to Google? For example, I interpreted the menu description under "Enable device checkin" as saying that none of this data (MAC address, device model/features etc.) is ever sent to Google, but now I'm wondering if that's true -- because why would there be code to display it in the first place? (Not meant as a criticism or anything, I just don't understand it.)

**Comment by mar-v-in** [comment]
No proper documentation yet, but basically no identifying bits are sent. Device model is not considered identifying in this context (it's not unique, there are tons of them out there), whereas mac address is not sent (instead a fake mac is sent). The basic principle used to determine what is "identifying" and what not, is whether it requires permission to gather it. For compatibility reasons, the "device description" (model, processor type, screen size, etc) are real data. This is needed, e.g. to download the version of an app that is actually compatible with the device.

The CheckinRequest written to logcat is exactly what is sent to Google in decoded form.

**Comment by infozsoda** [comment]
Thanks for clarifying, I very much appreciate that you're trying to anonymize the data to some extent. And for many users, the stuff that's sent is probably not unique, as you said. But for example -- say for people on an old device with a small user base, running an unoffical ROM port, that maybe they've built themselves, or even patched to remove problematic features, the air gets pretty thin pretty quickly...

I see a couple of things in my checkin request that seem unnecessary in any case, e.g. my bootloader version. Probably a few others.

More interestingly though, would you in principle consider a toggle that removes or standardizes _absolutely everything_ about the hardware or ROM, for users who download their .apks independently anyway? Do push notifications need more than some opaque id?

**Comment by mar-v-in** [comment]
To allow the user to spoof a certain device configuration will certainly be a feature some time. I just created #90 for that.

Push notifications should work fine with all data, this mostly affects Play Store
