### ISSUE TITLE
Cannot install self-signed build / signatures do not match previously installed version

### ISSUE THREAD

**Issue by geigertom** [microg/android_packages_apps_GmsCore#857]
Hi, 

I managed to build com.google.android.gms.apk from the latest sources. However, I cannot install it, because of a signature error:
`
adb: failed to install outputs/com.google.android.gms.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.google.android.gms signatures do not match previously installed version; ignoring!]
`
Is there a way of completey removing an old version of microg so that I can install my self-signed apk? Or else, is it possible to get a signed build of the apk containing all the latest commits and fixes? The last stable release v0.2.7.17455 does not contain the "Calling package detection in KK+" fix, so many of my apps keep crashing.

Thanks!
tom

**Comment by mar-v-in** [comment]
You need to fully uninstall GmsCore first. If your ROM comes shipped with GmsCore or you manually installed it to `/system` partition, you need to manually remove it from there.

**Comment by geigertom** [comment]
I had trouble to fully uninstall the previous version, tried to delete it in recovery mode from /system/priv-app/ but still got the `signatures do not match` error when i tried to reinstall. I may have copied it to multiple locations before and overlooked the correct file. Anyway, good to hear a new release is on the way, I'll just wait until it's available, many thanks for your effort!

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I am having the exact same problem. How did you remove it ? I have removed completely official gms fom the /system partition, but I still have the error and I can't find any solution.

**Comment by ale5000-git** [comment]
See my reply: #2864
