### ISSUE TITLE
App crashes on Xiaomi Redmi Note 6 Pro

### ISSUE THREAD

**Issue by YusufHussein** [microg/android_packages_apps_GmsCore#866]
![Screenshot_2019-07-04-20-40-45-564_com miui bugreport](https://user-images.githubusercontent.com/12372274/60692558-2ab36f00-9e9c-11e9-9e45-541261c978ea.png)

When I try to run Youtube vanced on my phone it crashes

**Comment by paulbauriegel** [comment]
I have the same problem with multiple apps, that where registered by the last version and after the update they are crashing with the same error. Try to reinstall, did always solve the problem for me. But still seems to be a bug.

**Comment by Vavun** [comment]
Your problem is not related to microG. Look at the package name in log.

You should either install microG vanced or use root variant of youtube vanced.

**Comment by Nanolx** [comment]
@ale5000-git can be closed as issue coming from different project.

@YusufHussein @paulbauriegel as @Vavun pointed out it says: `com.mgoogle.android.gms` which is Vanced's private microG fork, as oposed to `com.google.android.gms` which is the official microG.

If the issue persists, report it over to the Vanced developers. They should also tell people that their microG build is a fork and bugs should not be reported upstream.

**Comment by paulbauriegel** [comment]
@Nanolx @Vavun I'm having the same issues with the official microG. A lot of of apps crashed with the same error:
```
[07-08 13:10:32.969 30173:30196 E/AndroidRuntime]
FATAL EXCEPTION: firebase-iid-executor
Process: com.duolingo, PID: 30173
java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
	at d.i.b.b.d.g.a.b(SourceFile:8)
	at d.i.c.e.g.a(SourceFile:20)
	at d.i.c.e.e.a(SourceFile:12)
	at d.i.c.e.v.a(SourceFile:61)
	at d.i.c.e.S.run(SourceFile:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```
[logcat_07-08-2019_13-10-42.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3367853/logcat_07-08-2019_13-10-42.txt)

**Comment by Nanolx** [comment]
Do you have GsfProxy installed? Is GmsCore a system app? Did you try device checkin, see: https://github.com/microg/android_packages_apps_GmsCore/wiki/Helpful-Information

**Comment by paulbauriegel** [comment]
Yes, and my device is registered to gcm aswell. Works for all the apps I installed after the update. The weird thing is, if I reinstall the apps crashing with the exception above everything works as expected.
