### ISSUE TITLE
Can't login in google play games

### ISSUE THREAD

**Issue by Relwi** [microg/android_packages_apps_GmsCore#874]
I have a Leeco Le Max 2 with LienageOS 16 with microg, I have installed all microg apps installed as system apps, and in microg settings, I have al checks activated in Self-Check option, but when I open play games, it says "Play Games is having trouble with Google Play Services. Please try again". [https://imgur.com/gallery/LEIOHAm](url)

**Comment by Eerovil** [comment]
#163 Duplicate.

Known issue, play games is not yet supported.

**Comment by Relwi** [comment]
And there is another way to login with Google account in Pokemon go, ingress and wizard? Google photos for example is working fine, but in this games I can't login
