### ISSUE TITLE
Safetynet false with magisk root

### ISSUE THREAD

**Issue by Relwi** [microg/android_packages_apps_GmsCore#879]
Is possible to pass safetynet with a root device? I have DroidGuard in system/priv-app and I have enabled in magis hide, but safetynet still in false

**Comment by Nanolx** [comment]
Not currently, the issue is known and open in the respective repository, see: https://github.com/microg/android_packages_apps_RemoteDroidGuard/issues/24

**Comment by Relwi** [comment]
Okay, thank you
