### ISSUE TITLE
Play Store: IAP fails with java.lang.SecurityException

### ISSUE THREAD

**Issue by ibleedbinari** [microg/android_packages_apps_GmsCore#88]
Using IAP force closes the Play Store and the calling app. I have successfully made an IAP with the Play Store and microG in the past, so something may have changed permission-wise that broke it.

Using: Play Store 6.1.12 installed in /system/priv-app
Version: GmsCore Nightly 0.2.0
Tested with: Awesome Pop-Up Video, Battery Shutdown Manager, and Forest

Steps to reproduce:
1) Open an app with IAB
2) Initiate purchase
3) Play Store pops up and asks for payment method
4) Click "Buy"
5) Play Store and calling app force close with UID 10074 security exception. UID 10074 on my device is com.android.vending/Play Store according to /data/system/packages.list

[2016-02-06-23-35-22.txt](https://github.com/microg/android_packages_apps_GmsCore/files/120574/2016-02-06-23-35-22.txt)
[2016-02-06-23-38-43.txt](https://github.com/microg/android_packages_apps_GmsCore/files/120575/2016-02-06-23-38-43.txt)
##

**Comment by mar-v-in** [comment]
The error message suggests that Play Store is trying to access account information that is not accessible for it as it does not share microG's signature (this has nothing to do with signature spoofing, as this is a security restriction). This is not something that can be "fixed" directly and as you mentioned it worked for you before, this is probably due to the Play Store update 6.1.12. Can you try if downgrading Play Store fixes this issue again (as a temporary solution).

**Comment by ibleedbinari** [comment]
Downgrading to 6.0.5, which was the previously working version, did not fix the issue

**Comment by Diapolo** [comment]
So is there way to use Play Store without the official Play Store app currently?

**Comment by Catfriend1** [comment]
Play Store 6.4.12 and 6.5.8 still throw "java.lang.SecurityException" Error mentioned above when trying to buy an app from in-app purchase. Has anyone found a workaround in the meantime? Perhaps a PlayNeedle?

**Comment by budulinek** [comment]
It seems than Play Store 6.0 and above is affected by this issue (I have 6.0.5 and it still throws the same error).

The only solution is to install Play Store 5.x and disable automatic self-update of Google Play. This is very tricky...

SOLUTION

Probably the easiest solution is to install older version of Google Play which is modified to prevent self-update, for example this black themed Play Store:
[http://forum.xda-developers.com/showthread.php?t=2287493](url)
I can confirm that the black Play Store 5.1.11 from this xda thread does not self-update and does not suffer from the "java.lang.SecurityException" error. I am on Lollipop.

**Comment by Catfriend1** [comment]
The following raw extract from my Tasker Task "on-Boot" will disable nagging services, for the play store, only "disable com.android.vending" lines are relevant.

[Tasker-Setup-Services_extract.txt](https://github.com/microg/android_packages_apps_GmsCore/files/310989/Tasker-Setup-Services_extract.txt)

**Comment by budulinek** [comment]
The last working Google Play is 5.4.12. I can confirm that your trick with disabling Play store services responsible for auto-update does work. But I prefer to use DisableService for disabling services. It is safer than Tasker.

**Comment by Catfriend1** [comment]
Cool, thanks for verifying. So we finally have two good methods solving the play store problems with newest updates.
P.S. My tasker script was generated from DisableService root commands so DisableService is also a good working solution.

**Comment by tristan-k** [comment]
@Catfriend1 @budulinek [cn.wq.disableservice](https://play.google.com/store/apps/details?id=cn.wq.disableservice) doesnt seem to be very trustworthy. Is there a open source alternative available?

**Comment by budulinek** [comment]
As far as I know, there is no alternative to Disable Service.

But the newest version of Google Play works with  microg without any 
problems, so you do not need to disable self update services in Google Play.


Dne 27. listopadu 2016 2:27:17 PM  ǝʞɔoʃʞ uɐʇsıɹʇ 
<notifications@github.com> napsal:

**Comment by tristan-k** [comment]
Not for me. I tried `Google_Play_Store_7.2.13.J-all_0_PR_138561921.apk` but it crashed immediately after trying to purchase the full version of Solid Explorer.

**Comment by budulinek** [comment]
That is strange. I have the same version of Google Play and everything 
is working fine, including purchases. I have MicroG with FakeGapps 
xposed module. Xiaomi Miui 8 Stable.

Dne 27.11.2016 v 18:11 ǝʞɔoʃʞ uɐʇsıɹʇ napsal(a):

**Comment by Catfriend1** [comment]
So by the meantime, GPlay Store 8.4.18 works well purchasing on the mobile device also running MicroG GMSCore.

**Comment by ale5000-git** [comment]
@ibleedbinari: Does the problem still happen with the latest Play Store and latest microG?

**Comment by ibleedbinari** [comment]
@ale5000-git I'm not using microG actively at the moment, so I do not know

**Comment by ibleedbinari** [comment]
#309 has more details on this issue and PR #767 has a working solution. Closing this issue as duplicate.
