### ISSUE TITLE
Mapbox work on Grab, not on GO Jek

### ISSUE THREAD

**Issue by benyaminl** [microg/android_packages_apps_GmsCore#890]
Hello, I'm using microg on my ASUS Pegasus X005, the 0.28.775,but the mapbox only works for Grab, but Go Jek it's broken and not working, is there anything arround to make it work? Thanks

**Comment by benyaminl** [comment]
![Screenshot_2019-07-15-00-38-12](https://user-images.githubusercontent.com/2817332/61191360-b8c8fa00-a6d3-11e9-8c7b-b2e9fa49bfae.png)ut
Working for Grab but stuck with Go Jek when go to reservations activity.

![Screenshot_2019-07-15-07-43-03](https://user-images.githubusercontent.com/2817332/61191393-4f95b680-a6d4-11e9-8a52-8ee303d851d5.png)

**Comment by CircuitSerialKiller** [comment]
Mapbox in microG is new in still a WIP -  need more dev support!

**Comment by benyaminl** [comment]
> Mapbox in microG is new in still a WIP - need more dev support!

Hello thank you for looking at this issue. It's happen even before mapbox, so I post it hoping maybe there's a solution

**Comment by chris42** [comment]
Probably would help if you would post a log of the app not working. Some issues have been solved, others not yet.

**Comment by benyaminl** [comment]
> Probably would help if you would post a log of the app not working. Some issues have been solved, others not yet.

Nah is there any guide for it? I never posted one before. I tried to use log at but no error found for gojek. Hmm

**Comment by chris42** [comment]
You have two main options. If you connect your device via USB in debug mode, you can use `adb logcat`. Otherwise there are apps, that can read the logs, e.g. matlog.
Without logs, I doubt, that anyone can help you, as there can be many reasons for an app not to work.

Also you should check your microg version. "0.28.775" seems not to be a valid microg version number? latest is [0.2.8.17785-4-06c8b76](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk).

**Comment by benyaminl** [comment]
> You have two main options. If you connect your device via USB in debug mode, you can use `adb logcat`. Otherwise there are apps, that can read the logs, e.g. matlog.
> Without logs, I doubt, that anyone can help you, as there can be many reasons for an app not to work.
> 
> Also you should check your microg version. "0.28.775" seems not to be a valid microg version number? latest is [0.2.8.17785-4-06c8b76](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk).

Maybe I not being clear enough about the version. 
![Screenshot_2019-07-20-14-27-41](https://user-images.githubusercontent.com/2817332/61575804-9d5a5680-aafa-11e9-9e4a-366aef795e22.png)

I'll try to provide it but last time I run log cat it doesn't catch any error :'(

**Comment by benyaminl** [comment]
Seems @mar-v-in accidentally fix it by implementation on ver 0.2.9. Now Gojek Work flawlessly. Thanks!
