### ISSUE TITLE
Does not compile with Gradle

### ISSUE THREAD

**Issue by matyasf** [microg/android_packages_apps_GmsCore#9]
when trying to compile it fails with  "Cannot evaluate module play-services-api : Configuration with name 'default' not found"
As I understand this is because Gradle cannot find a sub project's location. The solution would be to rearrange the projects in a way that Gradle understands them.  
This is happening on Windows, using the latest Gradle or the wrapper supplied in the repo.

```
C:\CODE\android_packages_apps_GmsCore>gradle tasks --info
Starting Build
Settings evaluated using settings file 'C:\CODE\android_packages_apps_GmsCore\settings.gradle'.
Projects loaded. Root project using empty build file.
Included projects: [root project 'android_packages_apps_GmsCore', project ':play-services-api', project ':play-services-core', project ':safe-parcel',
 project ':unifiednlp-api', project ':unifiednlp-base', project ':unifiednlp-compat']
Evaluating root project 'android_packages_apps_GmsCore' using empty build file.
Evaluating project ':play-services-api' using empty build file.
Evaluating project ':play-services-core' using build file 'C:\CODE\android_packages_apps_GmsCore\play-services-core\build.gradle'.
Creating configuration compile.
Creating configuration apk.
Creating configuration provided.
Creating configuration wearApp.
Creating configuration androidTestCompile.
Creating configuration androidTestApk.
Creating configuration androidTestProvided.
Creating configuration androidTestWearApp.
Creating configuration testCompile.
Creating configuration testApk.
Creating configuration testProvided.
Creating configuration testWearApp.
Creating configuration debugCompile.
Creating configuration debugApk.
Creating configuration debugProvided.
Creating configuration debugWearApp.
Creating configuration testDebugCompile.
Creating configuration testDebugApk.
Creating configuration testDebugProvided.
Creating configuration testDebugWearApp.
Creating configuration releaseCompile.
Creating configuration releaseApk.
Creating configuration releaseProvided.
Creating configuration releaseWearApp.
Creating configuration testReleaseCompile.
Creating configuration testReleaseApk.
Creating configuration testReleaseProvided.
Creating configuration testReleaseWearApp.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':play-services-core'.
> Cannot evaluate module play-services-api : Configuration with name 'default' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 4.617 secs
Stopped 0 compiler daemon(s).
```

**Comment by thermatk** [comment]
Same here

**Comment by thermatk** [comment]
Everything ok, @matyasf go with 
https://github.com/microg/android_packages_apps_GmsCore/wiki/Build-and-Install

**Comment by mar-v-in** [comment]
@matyasf note that we use symbolic links which might not be fully supported by Windows. Build is only tested on Unix systems

**Comment by matyasf** [comment]
Yep, symlinks must be the cause. The error message means that the folder is empty. This is happening because Windows can not interpret the Unix symlink files.  
Are you planning to fix it? I could submit a PR that fixes it but while its a simple change it will move lots of files around. 

-----Original Message-----

**Comment by mar-v-in** [comment]
To be honest I don't really care about operating systems not supporting symlinks. I do not plan to add files from the submodules to this repo to have it working. If you now a good solution that does not break the repository + submodule structure I'll be fine with it, but I guess there is none?

**Comment by SWW13** [comment]
Windows support symlinks, but I think they can't be checked in using git.
So you could recreate the symlinks under Windows to build, see https://en.wikipedia.org/wiki/Symbolic_link#Microsoft_Windows

Maybe a script for creating them on Windows would be a acceptable workaround.

**Comment by mar-v-in** [comment]
Please read [this stackoverflow question](http://stackoverflow.com/questions/5917249/git-symlinks-in-windows) including its answers. Its important to note that while symlinks are supported windows, they require administrator privileges for creation, which is not feasible. 

If one wants to write a batch or powershell script that does the work i'll happily accept it as a pull request, but I'm not going to write or test it myself.
