### ISSUE TITLE
ConcurrentModificationException in mapbox

### ISSUE THREAD

**Issue by rfvermut** [microg/android_packages_apps_GmsCore#900]
I tested it on current f-droid version which was `0.2.8.17785-mapbox`

```

07-22 14:21:15.408 E/AndroidRuntime(24452): FATAL EXCEPTION: main
07-22 14:21:15.408 E/AndroidRuntime(24452): Process: ee.mtakso.client, PID: 24452
07-22 14:21:15.408 E/AndroidRuntime(24452): java.util.ConcurrentModificationException
07-22 14:21:15.408 E/AndroidRuntime(24452):     at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at org.microg.gms.maps.mapbox.GoogleMapImpl.initMap(GoogleMap.kt:540)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at org.microg.gms.maps.mapbox.GoogleMapImpl.access$initMap(GoogleMap.kt:61)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at org.microg.gms.maps.mapbox.GoogleMapImpl$onCreate$1.invoke(GoogleMap.kt:459)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at org.microg.gms.maps.mapbox.GoogleMapImpl$onCreate$1.invoke(GoogleMap.kt:61)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at org.microg.gms.maps.mapbox.GoogleMapKt$sam$com_mapbox_mapboxsdk_maps_OnMapReadyCallback$0.onMapReady(GoogleMap.kt)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1154)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1140)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:205)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:62)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:320)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at android.os.Handler.handleCallback(Handler.java:733)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at android.os.Handler.dispatchMessage(Handler.java:95)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at android.os.Looper.loop(Looper.java:136)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at android.app.ActivityThread.main(ActivityThread.java:5001)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at java.lang.reflect.Method.invokeNative(Native Method)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at java.lang.reflect.Method.invoke(Method.java:515)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613)
07-22 14:21:15.408 E/AndroidRuntime(24452):     at dalvik.system.NativeStart.main(Native Method)
07-22 14:21:15.408 W/ActivityManager(21329):   Force finishing activity ee.mtakso.client/.view.orderflow.OrderFlowActivity
```

**Comment by lbll** [comment]
Hi
I've got the same issue with the garmin connect app:

08-26 21:09:49.049  6293  6479 I Mbgl    : {GLThread 986}[General]: GPU Identifier: Adreno (TM) 330
08-26 21:09:49.050  6293  6479 W Mbgl    : {GLThread 986}[OpenGL]: Not using Vertex Array Objects
08-26 21:09:49.081  5543 14744 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@62a5a7b, 16
08-26 21:09:49.092  5543  6932 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@91f420a, 16
08-26 21:09:49.093  5543  5908 D GmsMeasureSvcImpl: onTransact [unknown]: 1, android.os.Parcel@62a5a7b, 16
08-26 21:09:49.094  5543  5575 D GmsMeasureSvcImpl: onTransact [unknown]: 10, android.os.Parcel@91f420a, 16
08-26 21:09:49.107  5543  5570 D GmsMeasureSvcImpl: onTransact [unknown]: 10, android.os.Parcel@62a5a7b, 16
08-26 21:09:49.115  5543  6932 D GmsLocManagerSvcImpl: getLastLocationWithPackage: com.garmin.android.apps.connectmobile
08-26 21:09:49.122  5543  5908 D SafeParcel: Unknown field num 9 in com.google.android.gms.location.internal.LocationRequestInternal, skipping.
08-26 21:09:49.123  5543  5908 D GmsLocManagerSvcImpl: updateLocationRequest: LocationRequestUpdateData{opCode=1, request=LocationRequestInternal{request=LocationRequest{priority=100, interval=3600000, fastestInterval=600000, explicitFastestInterval=false, expirationTime=9223372036854775807, numUpdates=2147483647, smallestDesplacement=0.0, maxWaitTime=0}, requestNlpDebugInfo=false, restorePendingIntentListeners=false, triggerUpdate=false, clients=[], tag='null', hideFromAppOps=false, forceCoarseLocation=false}, listener=com.google.android.gms.location.ILocationListener$Stub$Proxy@c52f0db, pendingIntent=null, callback=null, fusedLocationProviderCallback=com.google.android.gms.location.internal.IFusedLocationProviderCallback$Stub$Proxy@9157778}
08-26 21:09:49.139  6293  6293 D GmsMapBitmap: registerMap
08-26 21:09:49.140  6293  6293 D GmsMap  : Invoking 11 callbacks delayed, as map is initialized
08-26 21:09:49.144  6293  6293 D GmsMap  : Delay callback invocation, as map is not yet initialized
08-26 21:09:49.147  6293  6293 I chatty  : uid=10120(com.garmin.android.apps.connectmobile) identical 8 lines
08-26 21:09:49.147  6293  6293 D GmsMap  : Delay callback invocation, as map is not yet initialized
08-26 21:09:49.148  6293  6293 D AndroidRuntime: Shutting down VM
08-26 21:09:49.149  6293  6293 E AndroidRuntime: FATAL EXCEPTION: main
08-26 21:09:49.149  6293  6293 E AndroidRuntime: Process: com.garmin.android.apps.connectmobile, PID: 6293
08-26 21:09:49.149  6293  6293 E AndroidRuntime: java.util.ConcurrentModificationException
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at org.microg.gms.maps.mapbox.GoogleMapImpl.initMap(GoogleMap.kt:540)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at org.microg.gms.maps.mapbox.GoogleMapImpl.access$initMap(GoogleMap.kt:61)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at org.microg.gms.maps.mapbox.GoogleMapImpl$onCreate$1.invoke(GoogleMap.kt:459)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at org.microg.gms.maps.mapbox.GoogleMapImpl$onCreate$1.invoke(GoogleMap.kt:61)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at org.microg.gms.maps.mapbox.GoogleMapKt$sam$com_mapbox_mapboxsdk_maps_OnMapReadyCallback$0.onMapReady(Unknown Source:7)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1154)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1140)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:205)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:62)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:320)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-26 21:09:49.149  6293  6293 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-26 21:09:49.277  1352  1792 W ActivityManager:   Force finishing activity com.garmin.android.apps.connectmobile/.courses.create.custom.CreateCustomCourseActivity
08-26 21:09:49.286  1352  1792 W ActivityManager:   Force finishing activity com.garmin.android.apps.connectmobile/.courses.create.CourseDrawingMethodActivity

**Comment by rfvermut** [comment]
Gone in latest release. At least "Bolt" app works now.
