### ISSUE TITLE
Question: upgrading microG in a no longer supported LineageOS for microG

### ISSUE THREAD

**Issue by tuxayo** [microg/android_packages_apps_GmsCore#904]
Hi, I have LineageOS for microG 14.1
Support ended earlier this year, so my version of microG is v0.2.6.13280

After some reading I would like some confirmation to not risk breaking FCM/GCM registrations for example.

Should I just add the F-Droid repo and upgrade microG Services Core?
https://github.com/microg/android_packages_apps_GmsCore/wiki/Downloads

Will all the components be up to date? Or are there other steps to do when having a longer supported LineageOS for microG installation.

**Comment by ale5000-git** [comment]
You should report it here: https://github.com/lineageos4microg/docker-lineage-cicd

**Comment by voidstarstar** [comment]
Doesn't the F-Droid version use a different signature and would therefore require an uninstall (and a loss of the app registrations)?  Would pushing a new apk from github into `/system/priv-app/GmsCore/GmsCore.apk` overwrite the old one and work just fine?

**Comment by tuxayo** [comment]
@ale5000-git , thanks, I'll use the F-Droid repo.

> For the other issue you should report it here: https://github.com/lineageos4microg/docker-lineage-cicd

Thanks, moved:

https://github.com/lineageos4microg/docker-lineage-cicd/issues/46

**Comment by tuxayo** [comment]
@voidstarstar 

> Doesn't the F-Droid version use a different signature and would therefore require an uninstall (and a loss of the app registrations)?

No, it's the same, after all, they are both build by microG

**Comment by tuxayo** [comment]
Thanks for the answers

**Comment by ale5000-git** [comment]
The things that are in the default F-Droid repository may have a different signature but since microG GmsCore is in a custom repository provided by the author of microG himself then the signature is the same.

**Comment by voidstarstar** [comment]
Yea, sorry I forgot that microG maintains its own repo, so it's a non issue.
