### ISSUE TITLE
AOSP Email does not connect with GCM for push notifications

### ISSUE THREAD

**Issue by derhagen** [microg/android_packages_apps_GmsCore#908]
LOS 16.0-20199024-microG

Hi everyone,
I just managed to activate GCM on LOS 16.0 with help of [this comment](https://github.com/microg/android_packages_apps_GmsCore/issues/439#issuecomment-433018720). All apps could then be registered with GCM by reinstalling them. Great so far! Unfortunately I can not get the preinstalled AOSP E-Mail app to register with GCM, since it can not be completely removed. I tried deactivating/activating the app and erasing Cache and app data, without succcess. Any Ideas?

**Comment by chris42** [comment]
@derhagen 
Does it actually try to use GCM/FCM? 
My AOSP E-Mail App offers POP3 and IMAP. This should be quite different and independent from GCM/FCM. As POP3 is checking based on time interval and IMAP push is a different concept.

If you are sure that GCM/FCM is used, could you please provide logs from time of registering?!

**Comment by derhagen** [comment]
Oh I didn't know "IMAP push" is a thing. I guess that's what they actually mean by "Push". I'm going to check the logs later and reopen the issue if it tries and fails to use GCM.
