### ISSUE TITLE
Need help applying fake signature switch to CM 12.1

### ISSUE THREAD

**Issue by vuyibiran** [microg/android_packages_apps_GmsCore#91]
First of all: Thanks for your great work!

I tried to port your two patches [1,2] to cyanogenmod 12.1. While the core patch was easy to apply to the cyanogenmod source I run into problems with the patch that provides the switch to enable and disable the fake function.

Because Cyanogenmod guys do not want to help and I thought maybe some other people would like to have fake signature support on CM it might be a good idea to have these patches for CM as well.

So far I got to a stage where DevelopmentSettings.java makes problems.

This is the error I get when building the rom:
-----
>packages/apps/Settings/src/com/android/settings/DevelopmentSettings.java:1436: error: cannot find symbol
                getActivity().getContentResolver(), Settings.Secure.ALLOW_SIGNATURE_FAKE_KEY, 0) != 0);
                                                                   ^
  symbol:   variable ALLOW_SIGNATURE_FAKE_KEY
  location: class Secure
packages/apps/Settings/src/com/android/settings/DevelopmentSettings.java:1789: error: cannot find symbol
                        Settings.Secure.ALLOW_SIGNATURE_FAKE_KEY, 0);
                                       ^
  symbol:   variable ALLOW_SIGNATURE_FAKE_KEY
  location: class Secure
packages/apps/Settings/src/com/android/settings/DevelopmentSettings.java:2027: error: cannot find symbol
            if (which == DialogInterface.BUTTON_POSITIVE) {
                ^
  symbol:   variable which
  location: class DevelopmentSettings
packages/apps/Settings/src/com/android/settings/deviceinfo/Status.java:734: warning: non-varargs call of varargs method with inexact argument type for last parameter;
                TextUtils.split(res.getString(R.string.sar_head_level), ",")));
                               ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
packages/apps/Settings/src/com/android/settings/deviceinfo/Status.java:736: warning: non-varargs call of varargs method with inexact argument type for last parameter;
                TextUtils.split(res.getString(R.string.sar_body_level), ",")));
                               ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
2 warnings
<

Any idea how to solve this? Attached you will find the DevelopmentSettings.java file.
Any help in this case would much appreciated.

[1] https://gerrit.omnirom.org/#/c/14898/
[2] https://gerrit.omnirom.org/#/c/14899/

**Comment by ibleedbinari** [comment]
This port have already been done in #63 about 6 comments down. There are links to the CM12.1 Gerrit.

**Comment by vuyibiran** [comment]
Yes, indeed. I did not see this. Thanks for pointing it out. With the commits I got it to work with my rom.
