### ISSUE TITLE
Upgrade full package 21.0 --> 22.2 MicroG App missing

### ISSUE THREAD

**Issue by frank-github** [microg/android_packages_apps_GmsCore#910]
After upgrade NanoDroid full package 21.0 to 22.1 I can not find MicroG App in the launcher anymore ?!?

Do I have to install it separately? 
I want to check the Push-Settings of the applications with this app
And check if device connected to Google Push server, I had problem with this, that is why I updated NanoDroid

**Comment by ale5000-git** [comment]
This repository has nothing to do with NanoDroid, ask [here](https://forum.xda-developers.com/apps/magisk/module-nanomod-5-0-20170405-microg-t3584928) or [here](https://gitlab.com/Nanolx/NanoDroid).

**Comment by frank-github** [comment]
sorry for the wrong place
