### ISSUE TITLE
HANDY Parken App / Fatal Error / Support claims it's microG's fault

### ISSUE THREAD

**Issue by TeslaBargain** [microg/android_packages_apps_GmsCore#939]
We have a OnePlus 5 and OnePlus 6 phone in use, both equipped with the latest LineageOS 16 for microG and Magisk. The devices have correctly (manually) been registered for GCM and all apps (including otherwise problematical ones like banking and pushTAN apps) are working properly, except that one app called HANDY Parken (https://play.google.com/store/apps/details?id=at.mobilkom.android.handyparken).

That one app simply crashes each time I try to start it, the Logcat Reader shows the following fatal error:

    [09-09 16:37:53.425 12069:12111 E/AndroidRuntime]
    FATAL EXCEPTION: firebase-iid-executor
    Process: at.mobilkom.android.handyparken, PID: 12069
    java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
    	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1677)
    	at android.app.ContextImpl.bindService(ContextImpl.java:1612)
    	at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
    	at com.google.android.gms.common.stats.a.a(Unknown Source:27)
    	at com.google.android.gms.common.stats.a.a(Unknown Source:13)
    	at com.google.firebase.iid.g.a(Unknown Source:119)
    	at com.google.firebase.iid.e.a(Unknown Source:48)
    	at com.google.firebase.iid.e.a(Unknown Source:10)
    	at com.google.firebase.iid.u.a(Unknown Source:18)
    	at com.google.firebase.iid.ap.a(Unknown Source:2)
    	at com.google.firebase.iid.ao.run(Unknown Source:6)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    	at java.lang.Thread.run(Thread.java:764)

Their tech support claims it is a known problem of Lineage + microG in connection with push notifications over Firebase and they have referred issues [#740](https://github.com/microg/android_packages_apps_GmsCore/issues/740) and [#439](https://github.com/microg/android_packages_apps_GmsCore/issues/439) here with manual device registration (by dialing *#*#2432546#*#*) to be the likely solution, but of course that was not the issue and not the solution because our devices are already correctly registered for GCM use.

Since they replied that they can not help me any further if that wasn't the solution, I was hoping that someone else here may be able to analyze the problem further.

Please let me know if you need a more detailed logfile (and which filter settings to apply).

**Comment by ArchangeGabriel** [comment]
Have you try reinstalling that application? This issue is typical of an app installed before μG (see e.g. #924).

**Comment by TeslaBargain** [comment]
@ArchangeGabriel yes, multiple times, but this did not change anything and could not have been the issue, because all apps were installed after microG and manual GCM registration (since microG came already installed with LineageOS for microG and registering for GCM by dialing `*#*#2432546#*#*` was done before any apps were installed).

As said, everything else is working just fine, only that one app simply crashes when trying to start it. 

Deleting the apps storage & cache + uninstalling + reinstalling + checking if GCM is still registered + restarting the app just made the app crash again instantly.

**Comment by TeslaBargain** [comment]
From what it seems, the support team of the app creator does not want to pursue this issue any further, because nobody else (with Google Play Services installed) is experiencing this issue, so that stick to the opinion that it must be microG's fault.

I am not a programmer, but from what it seems, the app registration to GCM by firebase fails due to missing permissions, though I have disabled the option "Confirm new apps: Ask before registering a new app to receive push notifications" in microG settings and no notification about missing permissions appears and the app just crashes.

What's needed now is a skilled Android programmer, who can tell what they possibly can do wrong with that GCM registration by firebase that leads to the crash, because all the other apps could register to the GCM service just fine and can receive push notifications without problems. Maybe I can get them to have another look and fix the issue if I had more information for forward.
