### ISSUE TITLE
Hangouts Meet exiting with "selecting an account is required"

### ISSUE THREAD

**Issue by MrDrMcCoy** [microg/android_packages_apps_GmsCore#943]
## Description of problem:

With microg, Hangouts Meet is refusing to launch. It pops up a brief message on launch stating `Selecting an account is required` and then exits. I have, in fact, gone in to microg settings, logged in to the relevant account, and verified that the self-check is all good.

[Screenshot](https://i.imgur.com/KoJH4O7.png)

## Testing environment

This behavior has been reproduced on the following device/OS combinations:

- Sony Xperia XA2 with /e/ 0.7 nightly
- Sony Xperia XA2 with Lineage microg 16
- Sony Xperia XA2 with Sailfish 3.1
- OnePlus 5t with /e/ 0.7 nightly
- OnePlus 5t with Lineage microg 16
- Nexus 5x with /e/ 0.7 nightly
- Nexus 5x with Lineage microg 16

**Comment by mar-v-in** [comment]
This should be fixed through 9d0bb96 and cb5fe55

**Comment by MrDrMcCoy** [comment]
Sorry for the delayed response. I can confirm that the issue is resolved for me with the latest Lineage with MicroG on the Xperia XA2. Thank you for your help, and keep up the excellent work!
