### ISSUE TITLE
Team MicroG should team up with Team Vanced

### ISSUE THREAD

**Issue by wssopinion** [microg/android_packages_apps_GmsCore#944]
Hey, MicroG and Vanced have some issues together, like notifications, they can be done but need a MicroG app interaction to work. If Team Vanced and the MicroG team team up it would make Vanced a better app too.

**Comment by rugk** [comment]
Looking this up I find https://youtubevanced.com/. This is a usual YouTube app. Nothing special here.

Just install it by yourself.
I also have no idea for what it (optionally) needs root.

And it is proprietary, given it somehow uses the official YouTube app. (which may also be not be really legal) So shipping it in microG would not be good, as it's not FLOSS.
Personally, I'd just suggest using [NewPipe](https://f-droid.org/de/packages/org.schabi.newpipe/). That's simple enough for YouTube and FLOSS, and also blocks the ads there.

**Comment by dimqua** [comment]
YT Vanced is yet another Google spyware app.

**Comment by smnthermes** [comment]
YouTube Vanced sucks. What's so special about it?

**Comment by MrDodojo** [comment]
YT Vanced doesn't SUCK imo and https://Vanced.app is the only official domain, others have multiple mallware injection reports.

**Comment by NettoHikari** [comment]
I used YouTube Vanced for a while. That was a couple months ago. But guys, just buy YouTube premium... Support your creators. Or use [NewPipe](https://newpipe.schabi.org/) instead. That would follow the MicroG philosophy more anyways.

**Comment by ArchangeGabriel** [comment]
Can we close this? μG does not care about implementing Google Apps themselves, only the PlayServices.

And as other people said, if you want a good FOSS YouTube app replacement, go for NewPipe.

**Comment by mar-v-in** [comment]
Everything was said here. Closing.
