### ISSUE TITLE
provide builds for oneplus 7 pro

### ISSUE THREAD

**Issue by ethael** [microg/android_packages_apps_GmsCore#949]
Hello,

lineageos supports oneplus 7 pro (guacamole). 
can you add it to your supported device build list please? thanks a lot.

https://wiki.lineageos.org/devices/guacamole

**Comment by Nanolx** [comment]
Wrong project, post your request here: https://github.com/lineageos4microg

**Comment by ethael** [comment]
Thanks a lot
