### ISSUE TITLE
Crash with 0.2.9

### ISSUE THREAD

**Issue by DocSniper** [microg/android_packages_apps_GmsCore#964]
I use (standard / offical) LOS 16 without GApps.
With _GmsCore-v0.2.8.17785-mapbox.apk_ I have location (even if it claims _no know location_).
But after updating to GmsCore-v0.2.9.19420.apk MicroG crashes at start.
I tested it on system (replacing 0.2.8) and on data (with 0.2.8 on system).

I attached a logcat with filter set to _gms_.
[gms-log.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3763764/gms-log.txt)

Edit: here a second crash log, I had 0.2.8 on system and updated to 0.2.9 (data).
[gms-log-2.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3766285/gms-log-2.txt)

**Comment by Iey4iej3** [comment]
This filtration is not good enough. At the first log, there is a line:
> 10-23 19:35:02.680 E/AndroidRuntime(12738): Process: com.google.android.gms, PID: 12738
Could you please catch another log and study the context of this? (By the way, you can also try `adb logcat crash`.

You can compare the log with https://github.com/microg/android_packages_apps_GmsCore/issues/961#issuecomment-545055531, if it is similar, then seemingly @mar-v-in did not build the package correctly, see https://github.com/microg/android_packages_apps_GmsCore/issues/961#issuecomment-545483240.

Let's discuss the crash issue here instead of there.

**Comment by mar-v-in** [comment]
I guess this is caused by updating the build stack to SDK 29. I have to check the details, but my guess is that proguard is removing code that should not be removed :/

**Comment by chris42** [comment]
Could it also be a subproject Problem? Already in the Version before, I felt there was a mismatch in the submodules: See [#15](https://github.com/microg/android_external_GmsLib/issues/15) in GmsLib

**Comment by qoheniac** [comment]
I have the same problem on Fairphone Open 19.08.1 (Android 7.1.2 without GApps) + Xposed module FakeGapps 2.0. Everything is working properly again after downgrading to 0.2.8.17785-mapbox.

**Comment by nift4** [comment]
Same issue

**Comment by ploink** [comment]
Same here

GmsCore-v0.2.8.17785-mapbox.apk: collected all checkmarks in self-check and works.

GmsCore-v0.2.9.19420.apk: Crashes on boot. Fails to register UnifiedNlp in system.
When I disable GPS it stops crashing, maybe because it does not attempt to register UnifiedNlp?
It crashes again the moment I try to enable GPS.

**Comment by mar-v-in** [comment]
Anyone with this problem and related issues (crash on boot, GCM not connecting after boot), please try https://microg.org/dl/GmsCore-v0.2.9.19420-5-cfc90b4.apk and report back.

**Comment by ploink** [comment]
Just tried it, no crash, got all checkmarks in self-test. Thanks!

**Comment by Vavun** [comment]
@mar-v-in everything seems works fine now.
ROM: LineageOS for microG 16.0

no /data encryption and password protection

gmscore installed in /data as update - OK
+ after reboot - OK

gmscore updated directly in /system/priv-app - OK

**Comment by DocSniper** [comment]
The crash problem seems to be fixed, thanks. I get location and it seems to work well.
But even if I get a position, the self-test doesn't pass here:
![mg029](https://user-images.githubusercontent.com/3104188/67599510-c45e9f00-f75f-11e9-9da6-6a3e51e238c8.png)

**Comment by chris42** [comment]
Just tested it by installing it to /data and it seems to work fine. I get a location and no crashes so far. Logs seem to be fine (no errors).
Only had to re-set the UnifiedNlp backends.
Thanks a lot for that quick update!

**Comment by schiessle** [comment]
I had the exact same issue with LineageOS16-microg and the package from @mar-v-in fixed it. No more crash on startup and the all checkboxes are checked in the self-test. 😄 Thanks!

**Comment by k3lt** [comment]
> Anyone with this problem and related issues (crash on boot, GCM not connecting after boot, no location functionality) in 0.2.9, please try https://microg.org/dl/GmsCore-v0.2.9.19420-5-cfc90b4.apk and report back.

I can also confirm this fixed the UnifiedNlp backend not recognized by MicroG, i didn't have crash issues tho.

**Comment by nicheosala** [comment]
No more issues on LineageOS for MicroG 16.0.
Thanks @mar-v-in!

**Comment by DPTJKKVH** [comment]
I can confirm that the test apk fixes not only GCM but also location.

**Comment by DocSniper** [comment]
To substantiate my previous post, failing the self-check doesn't seem to be a permission problem in my case:

> runtime permissions:
> 
> - android.permission.ACCESS_FINE_LOCATION: granted=true, flags=[ SYSTEM_FIXED GRANTED_BY_DEFAULT ]
> - android.permission.READ_EXTERNAL_STORAGE: granted=true, flags=[ GRANTED_BY_DEFAULT ]
> - android.permission.ACCESS_COARSE_LOCATION: granted=true, flags=[ SYSTEM_FIXED GRANTED_BY_DEFAULT ]
> - android.permission.READ_PHONE_STATE: granted=true, flags=[ GRANTED_BY_DEFAULT ]
> - android.permission.GET_ACCOUNTS: granted=true, flags=[ GRANTED_BY_DEFAULT ]
> - android.permission.WRITE_EXTERNAL_STORAGE: granted=true, flags=[ GRANTED_BY_DEFAULT ]

**Comment by Iey4iej3** [comment]
> The crash problem seems to be fixed, thanks. I get location and it seems to work well.
> But even if I get a position, the self-test doesn't pass here:
> ![mg029](https://user-images.githubusercontent.com/3104188/67599510-c45e9f00-f75f-11e9-9da6-6a3e51e238c8.png)

@DocSniper Please open another issue and close this issue, since it is an issue different from crashing. By the way, you need to test other NLP Backends.

**Comment by Iey4iej3** [comment]
> Anyone with this problem and related issues (crash on boot, GCM not connecting after boot, no location functionality) in 0.2.9, please try https://microg.org/dl/GmsCore-v0.2.9.19420-5-cfc90b4.apk and report back.

@mar-v-in Could you pleas push this build to *releases* here and in the F-Droid repo? Thanks.

**Comment by DocSniper** [comment]
Problem seems to be fixed ...

**Comment by Iey4iej3** [comment]
> Anyone with this problem and related issues (crash on boot, GCM not connecting after boot, no location functionality) in 0.2.9, please try https://microg.org/dl/GmsCore-v0.2.9.19420-5-cfc90b4.apk and report back.

@mar-v-in I think that it is better to push the build to F-Droid repo and release the .apk here, since the build 0.2.9.19240 broken and there is no reason not to replace it by the corrected version.

**Comment by mar-v-in** [comment]
@ley4iej3 agree, will do probably tomorrow

**Comment by ale5000-git** [comment]
Also the vtm build with the latest fixes will be nice :)

**Comment by ildar** [comment]
and update f-droid repo plz ))

**Comment by mar-v-in** [comment]
@ale5000-git @ildar @Iey4iej3 0.2.10 is published on F-Droid and here.
