### ISSUE TITLE
0.2.9.109420 disconnects GCM with every reboot

### ISSUE THREAD

**Issue by DPTJKKVH** [microg/android_packages_apps_GmsCore#965]
Sine upgrading to 0.2.9.109420 the GCM connection stays disconnected until you manually connect it with *#*#2432546#*#* in the dialer.

With the previous version this had to be donr once and then the GCM connection survived reboots. Now on 0.2.9.109420 the GCM connection is lost and stays disconnected after every reboot until again the dialer code is used.

**Comment by Iey4iej3** [comment]
See https://github.com/microg/android_packages_apps_GmsCore/issues/964#issuecomment-546473162 for a temporary build to test.

**Comment by DPTJKKVH** [comment]
@Iey4iej3 Thanks. Unfortunately microg.org gives me a bad gateway error right now. Will test later.

**Comment by JonnyTech** [comment]
> microg.org gives me a bad gateway error

Confirmed - same here

**Comment by Iey4iej3** [comment]
Inform @mar-v-in of that.

**Comment by mar-v-in** [comment]
Bad Gateway should be fixed

**Comment by JonnyTech** [comment]
> Bad Gateway should be fixed

Confirmed - all good now

**Comment by DPTJKKVH** [comment]
The test apk fixed all my issues. i will also confirm in the main thread. Thanks!
