### ISSUE TITLE
Todoist crashes when continuing with E-Mail

### ISSUE THREAD

**Issue by Nesaijn** [microg/android_packages_apps_GmsCore#967]
After a fresh install of Todoist you are welcomed with three choices to login.
One is with Google, which does nothing. The second is with Facebook, which does open a Facebook login. But my choice would be with E-Mail, which on press just crashes the app.

microG Services Core Version 0.2.9.19420

[logcat-todoist.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3782805/logcat-todoist.txt)

**Comment by ale5000-git** [comment]
The version 0.2.9 is bugged, update to 0.2.10

**Comment by Nesaijn** [comment]
Yep, seems to be solved. Thanks.
