### ISSUE TITLE
com.android.vending keeps crashing

### ISSUE THREAD

**Issue by farfromrefug** [microg/android_packages_apps_GmsCore#970]
I am running:
* LOS 16 without signature spoofing
* Magisk
* Riru to get XPosed
* FakeGApps xposed module to get signature spoofing
* install MicroG, Google play store modified from F-droid (using microg repo and nanodroid)
* use Magisk App Systemizer module to have MicroG and the play store moved to priv-app
* ensure the play store have android.permission.FAKE_PACKAGE_SIGNATURE

Now the Play Store keep on crashing  with this error:
```
10-30 12:05:29.550 26672 26672 E AndroidRuntime: FATAL EXCEPTION: main
10-30 12:05:29.550 26672 26672 E AndroidRuntime: Process: com.android.vending, PID: 26672
10-30 12:05:29.550 26672 26672 E AndroidRuntime: java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query users
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1950)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1918)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1868)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at android.os.IUserManager$Stub$Proxy.getUsers(IUserManager.java:1092)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at android.os.UserManager.getSerialNumbersOfUsers(UserManager.java:2183)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at ygg.c(PG:3)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at ygh.d(Unknown Source:2)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at mlr.a(PG:193)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at mld.a(PG:4)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at ambf.run(PG:4)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-30 12:05:29.550 26672 26672 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

I remember having this one once but i dont remember how to fix this :s 
 
As anyone any idea?

**Comment by ploink** [comment]
Looks like you need to give playstore app some permissions.

**Comment by Nanolx** [comment]
It's not enough to move priviledged apps (priv-app) into /system. You also need to do priv-app permission whitelisting, see:

> https://source.android.com/devices/tech/config/perms-whitelist

**Comment by farfromrefug** [comment]
@Nanolx Thanks for the explanations! permissions whitelisting cant be done with magisk?

**Comment by Nanolx** [comment]
If you write the correct XML file on your own and place it into the module, then yes.

The problem is, that all those systemizers don't do priv-app permission whitelisting, so they don't actually work for priv-apps.

**Comment by farfromrefug** [comment]
@Nanolx actually it seems like they do!
https://github.com/Magisk-Modules-Repo/terminal_systemizer/blob/fe224bde603ce2584783da4e3cb6d182a5a3c643/system/xbin/systemize#L221

Will check those file on my system. Thanks!

**Comment by nift4** [comment]
You can try also https://github.com/nift4/microG_installer

**Comment by selurvedu** [comment]
@Nanolx this solution works: https://github.com/Magisk-Modules-Repo/microG_installer
Big thanks to @nift4 :+1:
