### ISSUE TITLE
Registration stuck at "I agree"

### ISSUE THREAD

**Issue by alex9434** [microg/android_packages_apps_GmsCore#978]
Dear all,
I am on Lineage OS 14.1 with microG 0.2.6.13280. When I try to register with my google account I am stuck after "I agree". The registration does not move forward. What went wrong?
Thank you,
alex

**Comment by drrossum** [comment]
Update to the latest version.  If the problem persists it will be useful to open an issue.

**Comment by alex9434** [comment]
OK, thank you. Will do. I close this issue then.
