### ISSUE TITLE
Installation KO for Vianavigo

### ISSUE THREAD

**Issue by wwark** [microg/android_packages_apps_GmsCore#98]
Hello,

I had this issue. I use Android 6.0.1 (OmniRom) with GmsCore 0.2.0. A friend with android 4.4 have no issue to install this apk and GmsCore 0.2.0 (OmniRom). Could you please tell me what to do ?

02-24 22:43:14.164   645   712 W PackageManager: Package couldn't be installed in /data/app/com.applidium.vianavigo-1
02-24 22:43:14.164   645   712 W PackageManager: com.android.server.pm.PackageManagerException: Package com.applidium.vianavigo requires unavailable shared library com.google.android.maps; failing!
02-24 22:43:14.164   645   712 W PackageManager:        at com.android.server.pm.PackageManagerService.updateSharedLibrariesLPw(PackageManagerService.java:6397)
02-24 22:43:14.164   645   712 W PackageManager:        at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:6738)
02-24 22:43:14.164   645   712 W PackageManager:        at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:6489)
02-24 22:43:14.164   645   712 W PackageManager:        at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:11805)
02-24 22:43:14.164   645   712 W PackageManager:        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:12491)
02-24 22:43:14.164   645   712 W PackageManager:        at com.android.server.pm.PackageManagerService.-wrap25(PackageManagerService.java)
02-24 22:43:14.164   645   712 W PackageManager:        at com.android.server.pm.PackageManagerService$9.run(PackageManagerService.java:10189)
02-24 22:43:14.164   645   712 W PackageManager:        at android.os.Handler.handleCallback(Handler.java:739)
02-24 22:43:14.164   645   712 W PackageManager:        at android.os.Handler.dispatchMessage(Handler.java:95)
02-24 22:43:14.164   645   712 W PackageManager:        at android.os.Looper.loop(Looper.java:148)
02-24 22:43:14.164   645   712 W PackageManager:        at android.os.HandlerThread.run(HandlerThread.java:61)
02-24 22:43:14.164   645   712 W PackageManager:        at com.android.server.ServiceThread.run(ServiceThread.java:46)

Regards,
Wark

**Comment by mar-v-in** [comment]
The app requires maps v1 which is not covered by this project. You can grab a flashable zip for it here: https://github.com/mar-v-in/MapsAPI/releases

**Comment by wwark** [comment]
Thanks !!! The installation is OK. Wark
