### ISSUE TITLE
Some apps crash with microG

### ISSUE THREAD

**Issue by xxxxme** [microg/android_packages_apps_GmsCore#984]
When installing GmsCore (version 0.2.10.19420) from fdroid, a couple of my apps immediately stop working:
Nova Launcher Settings crashes when opened (Nova Launcher itself is fine)
Band crashes when opened
Immediately upon uninstalling GmsCore (without a reboot), the apps work again.

https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher
https://play.google.com/store/apps/details?id=com.nhn.android.band

**Comment by chris42** [comment]
I have Novalauncher and settings are working fine.
Can you provide some logs?
What does the microg self check say?
Was any previous google framework removed?

**Comment by xxxxme** [comment]
Where do I find logs?
MicroG self check's info depends on whether I install it through f-droid (in which case, it reports everything working, but the signatures are wrong) or whether I install it through NanoDroid (in which case, it reports everything working, including the signatures).  However, NanoDroid causes other issues: https://gitlab.com/Nanolx/NanoDroid/issues/105
I'm not sure whether previous Google framework was removed, nor whether it was present.  How do I find out?

**Comment by chris42** [comment]
I never thought about a technical way, I guess if you find a gmscore already on the device before installing Microg. Normally I just know, if I installed gapps during setup of the device.
For logs you can use tools like catlog, matlog or connect directly via adb log.

**Comment by xxxxme** [comment]
I assume gapps are not installed on this custom ROM because certain apps ask for google play services when microG isn't installed.
I've restored a backup from before I started messing with microG, patched with haystack to enable signature spoofing, and installed microG through F-droid.
MicroG's self-check reports everything good except for UnifiedNLP not being installed (this is a separate issue).
As for the logs, I'm not sure what's useful out of this >1k line file I have after rebooting, opening several apps which crashed, and immediately saving the log.  If I search for the crashing apps' names, I see things like:
[quote]12-28 13:45:06.153 E/AndroidRuntime(6212): FATAL EXCEPTION: firebase-iid-executor
12-28 13:45:06.153 E/AndroidRuntime(6212): Process: com.nhn.android.band, PID: 6212
12-28 13:45:06.153 E/AndroidRuntime(6212): java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }[/quote]

**Comment by xxxxme** [comment]
Full logcat(expiration June 2020): https://pastebin.com/eMq9bxvm

**Comment by chris42** [comment]
This seems to be like #742 . Did you install GsfProxy as well and then reinstalled the crashing apps afterwards?

**Comment by xxxxme** [comment]
I already had GsfProxy installed.  Reinstalling the crashing apps seemed to do the trick for all but one of them.

**Comment by projectgus** [comment]
Had the same just now after updating GmsCore to v0.2.11.202414 release (on LineageOS 17.1), updated . Fatal exceptions were all `java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }` Reinstalling the crashing apps has worked for all of them.

Does anyone know what the technical step that fixes the apps is? Might be possible to trigger via adb or another method without having to restore app data?
