### ISSUE TITLE
FakeStore / BlankStore spoofing no longer working

### ISSUE THREAD

**Issue by 0x47** [microg/android_packages_apps_GmsCore#99]
After following the installation guidelines from the Wiki (using both FakeStore and BlankStore) the microG Settings won't accept or spoof the signature of the installed Play Store. However, the "System spoofs signature" box is ticked and everything else seems to be working smoothly, too (OmniROM). This happens using the APKs from the FDroid repo, except the FakeStore/BlankStore ones, as they are not in there. Instead, I downloaded them from the locations linked to in the installation instructions.

As a side note: I'm not sure if the non-working Play Store is the reason but I cannot get Signal to work right now. It complains about Google Play Services not being supported by my device (Nexus 4).

**Comment by mar-v-in** [comment]
On OmniROM, try to open Settings -> Apps -> [gear icon in toolbar] -> App permissions -> Spoof signature and enable for FakeStore / Market

**Comment by 0x47** [comment]
That works, thanks! So it seems the real issue is the Store not requesting that permission by itself. I suppose that would have happened if I opened the BlankStore (which I didn't because I just wanted to see if the spoofing worked for it). But how would the FakeStore, which has no app-icon, have requested that permission? It this even possible?

BTW, Signal started working after the spoofing was enabled. Unfortunately, outgoing encrypted calls won't work because the phone-icon does not have the lock (incoming working fine). Not sure if that's related to MicroG though.

**Comment by mar-v-in** [comment]
Currently asking for permission is not added to BlankStore and FakeStore. This ability to do so might be added some day - once everything is more stable a setup assistant will be added to guide through setup (the self-check is only an intermediate step so that early adopters can still use it).

**Comment by 0x47** [comment]
I see, thanks. Going to close this issue as the real problem turned out to be unrelated.

**Comment by dalb8** [comment]
The wiki should be updated with this info and the bit about Developer Options removed

**Comment by ibleedbinari** [comment]
Fixed the wiki issue in #101
