### ISSUE TITLE
Failure installing app because of missing Maps library

### ISSUE THREAD

**Issue by ocwa1** [microg/android_packages_apps_GmsCore#993]
Trying to install Kaiser Permanente's mobile app failed, so I tried with adb install, adding extra flags did not change the result.  From what I can tell it has to do with com.google.android.maps being required in the app's manifest file.  Is there any way to add a stub com.google.android.maps library to microg so that installation of apps like this don't fail?  The app doesn't require Google Maps for most functionality.

The test was performed on a Pixel 3 running CalyxOS, a microg fork of GrapheneOS.
microg version: 0.2.10.19420-1-vtm (ab8c2cc)

`$ ./adb install ./org.kp.m_42900006.apk
Performing Streamed Install
adb: failed to install ./org.kp.m_42900006.apk: Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY: Reconciliation failed...: Reconcile failed: Package org.kp.m requires unavailable shared library com.google.android.maps; failing!]`

**Comment by ale5000-git** [comment]
What about installing the maps library? :-)
https://github.com/microg/android_frameworks_mapsv1

**Comment by ocwa1** [comment]
Thanks, I'll take it up with the CalyxOS team.

**Comment by ale5000-git** [comment]
You can flash with TWRP recovery even without root.

**Comment by ocwa1** [comment]
It's a locked bootloader OS, unlocking/locking the bootloader wipes the phone, and leaving it unlocked has poor security implications, and would allow the phone to be wiped and used by anyone who finds it, decreasing the likelyhood of it being returned.
